load("@rules_go//go:def.bzl", "go_library")

package(default_package_metadata = ["//pkg/dyninst/testprogs/progs:go_package_metadata"])

go_library(
    name = "lib_v2",
    srcs = ["lib.go"],
    importpath = "github.com/DataDog/datadog-agent/pkg/dyninst/testprogs/progs/sample/lib.v2",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/dyninst/testprogs/progs/sample/lib",
    ],
)
