services:
  oracle:
    platform: linux/amd64
    image: "registry.ddbuild.io/images/mirror/oracle:${DBMS_VERSION:-21.3.0-xe}"
    ports:
      - "1521:1521"
    healthcheck:
      test:
        - CMD-SHELL
        - >-
          printf 'whenever oserror exit failure\nwhenever sqlerror exit failure\nselect 1 from dual;\nexit success\n'
          | sqlplus -L -s 'sys/datad0g@localhost:1521/XE as sysdba' > /dev/null
      interval: 5s
      start_period: 15s
      timeout: 5s
      retries: 120
    # We could just mount init.db but we mimic Gitlab's limitations
    # and rely on TestMain to run the relevant sql
    environment:
      ORACLE_PWD: datad0g
