load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

dd_agent_go_test(
    name = "tests_test",
    srcs = [
        "ddot_install_test.go",
        "flags_test.go",
        "install_script_test.go",
        "macos_install_test.go",
        "package_signing_test.go",
        "persisting_integrations_test.go",
        "rpm_test.go",
        "step_by_step_test.go",
        "upgrade_test.go",
    ],
    data = ["//cmd/agent:macos/uninstall_mac_os.sh"],
    deps = [
        "//test/e2e-framework/components/os",
        "//test/e2e-framework/scenarios/aws/ec2",
        "//test/e2e-framework/testing/components",
        "//test/e2e-framework/testing/e2e",
        "//test/e2e-framework/testing/environments",
        "//test/e2e-framework/testing/provisioners/aws/host",
        "//test/e2e-framework/testing/runner",
        "//test/e2e-framework/testing/runner/parameters",
        "//test/e2e-framework/testing/utils/e2e/client",
        "//test/e2e-framework/testing/utils/e2e/client/agentclient",
        "//test/fakeintake/aggregator",
        "//test/fakeintake/client",
        "//test/new-e2e/tests/agent-platform/common",
        "//test/new-e2e/tests/agent-platform/common/file-manager",
        "//test/new-e2e/tests/agent-platform/common/helper",
        "//test/new-e2e/tests/agent-platform/install",
        "//test/new-e2e/tests/agent-platform/install/installparams",
        "//test/new-e2e/tests/agent-platform/platforms",
        "//test/new-e2e/tests/installer/host",
        "@com_github_cenkalti_backoff_v7//:backoff",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
