load("//bazel/rules/selinux:selinux.bzl", "compile_selinux_policy")

# Compiles the system-probe policy source (.te) into a packaged module (.pp)
compile_selinux_policy(
    name = "system_probe_policy",
    src = "system_probe_policy.te",
    out = "system_probe_policy.pp",
    target_compatible_with = ["@platforms//os:linux"],
    visibility = ["//visibility:public"],
)
