load("@rules_go//go:def.bzl", "go_library")

package(default_package_metadata = ["//comp/serializer/logscompression:go_package_metadata"])

go_library(
    name = "fx",
    srcs = ["fx.go"],
    importpath = "github.com/DataDog/datadog-agent/comp/serializer/logscompression/fx",
    visibility = ["//visibility:public"],
    deps = [
        "//comp/serializer/logscompression/impl",
        "//pkg/util/fxutil",
    ],
)
