// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Http = newAsset("http.c", "37651e4d28067898a7b788a2d5ce1f99c44900c2354a9542bb62a80299c6dbb8")
