// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Http = NewRuntimeAsset("http.c", "2dcb3eb31afe649fa0ef5e5df9ecf1556cac88e12925c30dfe33baad3b78b7da")
