// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Kafka = NewAsset("kafka.c", "151f053eb5166acad6a4dd150f97c7a87f080e111dec70871e64d8e924afdff3")
