// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf

package runtime

//var OffsetguessTest = newAsset("offsetguess-test.c", "23e137d962c7984648d1282dba2d2a995fc2a85b609d9e123b0d698a4c607b79")
