// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "1ec870140fde7368ff80c5c698846d03d5882013dada2e1879e75032095b73ce")
