// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "878f687b3f2f0222cf1144bebc9f672008eae9c54e2ef49978086b5a435a0c3e")
