// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Tracer = newAsset("tracer.c", "932ba3a745ed41b6cfe62162a116dbbc461032c4a53b89745d7d50783bbce9b9")
