// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Tracer = newAsset("tracer.c", "6d03882db0e714d518882ef9450e8c40a59188d6c3198057db8e569e457401fe")
