// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Tracer = newAsset("tracer.c", "829abf5f6ffcc45e15faa8cf2156738b2261b1dadaf52717f274b45dea8fb62e")
