load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

dd_agent_go_test(
    name = "benchmarks_test",
    srcs = [
        "benchmark_test.go",
        "primitive_test.go",
    ],
    gotags_sets = [[
        "cel",
        "clusterchecks",
        "kubeapiserver",
        "kubelet",
        "orchestrator",
    ]],
    include_default = False,
    deps = [
        "//cmd/cluster-agent/admission",
        "//comp/core/config",
        "//pkg/clusteragent/admission/mutate/agent_sidecar",
        "//pkg/clusteragent/admission/mutate/autoinstrumentation",
        "//pkg/clusteragent/admission/mutate/common",
        "//pkg/clusteragent/admission/mutate/config",
        "//pkg/clusteragent/admission/patch",
        "//pkg/util/log",
        "@io_k8s_api//core/v1:core",
        "@io_k8s_apimachinery//pkg/api/resource",
        "@io_k8s_client_go//dynamic",
    ],
)
