---
fixes:
  - |
    The Agent no longer shows the content of check config files on its local expvar page.
    This includes the configuration of JMX checks. The content is still sent to Datadog and
    still included in the flare.
