# Each section from every release note are combined when the
# CHANGELOG.rst is rendered. So the text needs to be worded so that
# it does not depend on any information only available in another
# section. This may mean repeating some details, but each section
# must be readable independently of the other.
#
# Each section note must be formatted as reStructuredText.
---
fixes:
  - |
    Fixes a bug in the Network Configuration Management (NCM) module where the SSH Timeout settings were parsed as
    nanoseconds instead of seconds. This issue caused SSH sessions to time out prematurely, leading to errors like:
      ```
      Error running check: failed to connect to 192.168.0.1:22: dial tcp 192.168.0.1:22: i/o timeout
      ```
