load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "os",
    srcs = [
        "aliases.go",
        "generic_packagemanager.go",
        "linux.go",
        "linux_packagemanagers.go",
        "linux_servicemanagers.go",
        "linux_zypper_packagemanager.go",
        "macos.go",
        "macos_packagemanagers.go",
        "macos_servicemanagers.go",
        "os.go",
        "windows.go",
        "windows_servicemanagers.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/test/e2e-framework/components/os",
    visibility = ["//visibility:public"],
    deps = [
        "//test/e2e-framework/common",
        "//test/e2e-framework/common/config",
        "//test/e2e-framework/common/namer",
        "//test/e2e-framework/common/utils",
        "//test/e2e-framework/components/command",
        "//test/e2e-framework/components/os/types",
        "@com_github_pulumi_pulumi_sdk_v3//go/pulumi",
    ],
)
