load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

go_library(
    name = "impl",
    srcs = [
        "connectivity_endpoint.go",
        "dto.go",
        "newcomponent.go",
        "scan.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/comp/ndmconnectivitycheck/impl",
    visibility = ["//visibility:public"],
    deps = [
        "//comp/api/api/def",
        "//comp/api/api/utils",
        "//comp/core/config",
        "//comp/core/log/def",
        "//comp/def",
        "//comp/ndmconnectivitycheck/def",
        "//pkg/networkdevice/probe",
        "//pkg/networkdevice/probe/pingprobe",
        "//pkg/networkdevice/probe/snmpprobe",
        "//pkg/networkdevices/connectivity",
        "//pkg/util/http",
        "@org_golang_x_sync//semaphore",
    ],
)

dd_agent_go_test(
    name = "impl_test",
    srcs = [
        "connectivity_endpoint_test.go",
        "dto_test.go",
    ],
    embed = [":impl"],
    deps = [
        "//comp/core/log/mock",
        "//pkg/networkdevice/probe",
        "//pkg/networkdevice/probe/failure",
        "//pkg/networkdevice/probe/pingprobe",
        "//pkg/networkdevice/probe/snmpprobe",
        "//pkg/networkdevices/connectivity",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
