load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

go_library(
    name = "client",
    srcs = [
        "client.go",
        "tuf_proof.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/pkg/config/remote/client",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/config/remote/meta",
        "//pkg/proto/pbgo/core",
        "//pkg/remoteconfig/state",
        "//pkg/util/backoff",
        "//pkg/util/grpc",
        "//pkg/util/log",
        "@org_golang_google_grpc//:grpc",
        "@org_golang_google_grpc//codes",
        "@org_golang_google_grpc//metadata",
        "@org_golang_google_grpc//status",
        "@org_uber_go_atomic//:atomic",
    ],
)

dd_agent_go_test(
    name = "client_test",
    srcs = ["tuf_proof_test.go"],
    embed = [":client"],
    deps = [
        "//pkg/proto/pbgo/core",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
