load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

# gazelle:dd_agent_go_test on

go_library(
    name = "capture",
    srcs = [
        "inventory.go",
        "normalize.go",
        "software.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/cmd/eudm-simulator/internal/capture",
    visibility = ["//cmd/eudm-simulator:__subpackages__"],
    deps = [
        "//cmd/eudm-simulator/internal/telemetry",
        "//pkg/inventory/software",
        "//pkg/metrics",
        "//pkg/serializer/marshaler",
        "//pkg/tagset",
        "//pkg/telemetrycapture",
        "@com_github_datadog_agent_payload_v5//process",
        "@com_github_gogo_protobuf//proto",
    ],
)

dd_agent_go_test(
    name = "capture_test",
    srcs = [
        "inventory_test.go",
        "normalize_test.go",
        "software_test.go",
    ],
    embed = [":capture"],
    deps = [
        "//pkg/inventory/software",
        "//pkg/metrics",
        "//pkg/tagset",
        "//pkg/telemetrycapture",
        "@com_github_datadog_agent_payload_v5//process",
        "@com_github_gogo_protobuf//proto",
    ],
)
