// Code generated by genpost.go; DO NOT EDIT.

package http2

import (
	"testing"

	"github.com/DataDog/datadog-agent/pkg/ebpf/ebpftest"
)

func TestCgoAlignment_HTTP2DynamicTableIndex(t *testing.T) {
	ebpftest.TestCgoAlignment[HTTP2DynamicTableIndex](t)
}

func TestCgoAlignment_HTTP2DynamicTableEntry(t *testing.T) {
	ebpftest.TestCgoAlignment[HTTP2DynamicTableEntry](t)
}

func TestCgoAlignment_HTTP2StreamKey(t *testing.T) {
	ebpftest.TestCgoAlignment[HTTP2StreamKey](t)
}

func TestCgoAlignment_http2StatusCode(t *testing.T) {
	ebpftest.TestCgoAlignment[http2StatusCode](t)
}

func TestCgoAlignment_http2requestMethod(t *testing.T) {
	ebpftest.TestCgoAlignment[http2requestMethod](t)
}

func TestCgoAlignment_http2Path(t *testing.T) {
	ebpftest.TestCgoAlignment[http2Path](t)
}

func TestCgoAlignment_HTTP2Stream(t *testing.T) {
	ebpftest.TestCgoAlignment[HTTP2Stream](t)
}

func TestCgoAlignment_EbpfTx(t *testing.T) {
	ebpftest.TestCgoAlignment[EbpfTx](t)
}

func TestCgoAlignment_HTTP2Telemetry(t *testing.T) {
	ebpftest.TestCgoAlignment[HTTP2Telemetry](t)
}

func TestCgoAlignment_HTTP2IncompleteFrameEntry(t *testing.T) {
	ebpftest.TestCgoAlignment[HTTP2IncompleteFrameEntry](t)
}
