load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")
load("//bazel/rules/go_package_metadata:defs.bzl", "go_package_metadata")

package(default_package_metadata = [":go_package_metadata"])

go_package_metadata(
    name = "go_package_metadata",
    module = "github.com/DataDog/datadog-agent/comp/core/tagger/types",
)

go_library(
    name = "types",
    srcs = [
        "entity_id.go",
        "filter_builder.go",
        "filters.go",
        "types.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/comp/core/tagger/types",
    visibility = ["//visibility:public"],
    deps = [
        "//comp/core/tagger/origindetection",
        "//comp/core/tagger/utils",
    ],
)

dd_agent_go_test(
    name = "types_test",
    srcs = [
        "entity_id_test.go",
        "filter_builder_test.go",
        "filters_test.go",
    ],
    embed = [":types"],
    deps = ["@com_github_stretchr_testify//assert"],
)
