load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

go_library(
    name = "identity",
    srcs = ["identity.go"],
    importpath = "github.com/DataDog/datadog-agent/cmd/eudm-simulator/internal/identity",
    visibility = ["//cmd/eudm-simulator:__subpackages__"],
    deps = [
        "//cmd/eudm-simulator/internal/schema",
        "//cmd/eudm-simulator/internal/telemetry",
        "//pkg/tagset",
    ],
)

dd_agent_go_test(
    name = "identity_test",
    srcs = ["identity_test.go"],
    embed = [":identity"],
    deps = [
        "//cmd/eudm-simulator/internal/schema",
        "//cmd/eudm-simulator/internal/telemetry",
        "//comp/softwareinventory/impl",
        "//pkg/inventory/software",
        "//pkg/metrics",
        "//pkg/tagset",
        "@com_github_datadog_agent_payload_v5//process",
    ],
)
