load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

go_library(
    name = "driver",
    srcs = [
        "driver.go",
        "registry.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/test/e2e-framework/cmd/e2ectl/internal/driver",
    visibility = ["//test/e2e-framework/cmd/e2ectl:__subpackages__"],
    deps = [
        "//test/e2e-framework/cmd/e2ectl/internal/config",
        "//test/e2e-framework/cmd/e2ectl/internal/drivers/ec2host",
        "//test/e2e-framework/cmd/e2ectl/internal/drivers/kind",
        "//test/e2e-framework/cmd/e2ectl/internal/envstore",
        "//test/e2e-framework/cmd/e2ectl/internal/installer",
    ],
)

dd_agent_go_test(
    name = "driver_test",
    srcs = ["driver_test.go"],
    embed = [":driver"],
    deps = ["//test/e2e-framework/cmd/e2ectl/internal/config"],
)
