load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "signingkeys",
    srcs = ["signingkeys.go"],
    importpath = "github.com/DataDog/datadog-agent/pkg/privateactionrunner/signingkeys",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/privateactionrunner/types",
        "//pkg/remoteconfig/state",
    ],
)
