load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "def",
    srcs = ["component.go"],
    importpath = "github.com/DataDog/datadog-agent/comp/privateactionrunner/signingkeys/def",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/privateactionrunner/signingkeys",
        "//pkg/proto/pbgo/core",
    ],
)
