load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

go_library(
    name = "configschema",
    srcs = [
        "context.go",
        "format.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/comp/healthplatform/issues/internal/configschema",
    visibility = ["//comp/healthplatform/issues:__subpackages__"],
    deps = [
        "//pkg/config/model",
        "//pkg/config/schema",
        "//pkg/util/scrubber",
        "@com_github_dustin_go_humanize//english",
        "@com_github_qri_io_jsonpointer//:jsonpointer",
    ],
)

dd_agent_go_test(
    name = "configschema_test",
    srcs = ["context_test.go"],
    embed = [":configschema"],
    deps = [
        "//comp/core/config",
        "@com_github_stretchr_testify//assert",
    ],
)
