load("@bazel_skylib//:bzl_library.bzl", "bzl_library")

bzl_library(
    name = "purl",
    srcs = ["purl.bzl"],
)

bzl_library(
    name = "ship_source_offer",
    srcs = ["ship_source_offer.bzl"],
)
