load("@rules_go//go:def.bzl", "go_library")

package(default_package_metadata = ["//test/e2e-framework:go_package_metadata"])

go_library(
    name = "helm",
    srcs = ["helm.go"],
    importpath = "github.com/DataDog/datadog-agent/test/e2e-framework/resources/helm",
    visibility = ["//visibility:public"],
    deps = [
        "//test/e2e-framework/common/config",
        "@com_github_pulumi_pulumi_kubernetes_sdk_v4//go/kubernetes/helm/v3:helm",
        "@com_github_pulumi_pulumi_sdk_v3//go/pulumi",
    ],
)
