load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "ddot",
    srcs = [
        "procmgr.go",
        "procmgr_windows_host.go",
        "telemetry.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/test/new-e2e/tests/ddot",
    visibility = ["//visibility:public"],
    deps = [
        "//test/e2e-framework/components/os",
        "//test/e2e-framework/testing/components",
        "//test/new-e2e/tests/windows/common/agent",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
