load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "fdhandoff",
    srcs = [
        "fdhandoff.go",
        "fdhandoff_nix.go",
        "fdhandoff_nonix.go",
        "passcred_darwin.go",
        "passcred_linux.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/pkg/dogstatsd/fdhandoff",
    visibility = ["//visibility:public"],
    deps = select({
        "@rules_go//go/platform:android": [
            "@org_golang_x_sys//unix",
        ],
        "@rules_go//go/platform:darwin": [
            "@org_golang_x_sys//unix",
        ],
        "@rules_go//go/platform:ios": [
            "@org_golang_x_sys//unix",
        ],
        "@rules_go//go/platform:linux": [
            "@org_golang_x_sys//unix",
        ],
        "//conditions:default": [],
    }),
)

go_test(
    name = "fdhandoff_test",
    srcs = ["fdhandoff_nix_test.go"],
    embed = [":fdhandoff"],
    gotags = ["test"],
    deps = select({
        "@rules_go//go/platform:android": [
            "@com_github_stretchr_testify//assert",
            "@com_github_stretchr_testify//require",
            "@org_golang_x_sys//unix",
        ],
        "@rules_go//go/platform:darwin": [
            "@com_github_stretchr_testify//assert",
            "@com_github_stretchr_testify//require",
            "@org_golang_x_sys//unix",
        ],
        "@rules_go//go/platform:ios": [
            "@com_github_stretchr_testify//assert",
            "@com_github_stretchr_testify//require",
            "@org_golang_x_sys//unix",
        ],
        "@rules_go//go/platform:linux": [
            "@com_github_stretchr_testify//assert",
            "@com_github_stretchr_testify//require",
            "@org_golang_x_sys//unix",
        ],
        "//conditions:default": [],
    }),
)
