#!/bin/sh
#
# Perform necessary datadog-updater removal steps after package is uninstalled
# or during the removal of the previous version after an upgrade
#

PACKAGES_DIR=/opt/datadog-packages
INSTALL_DIR=/opt/datadog-installer
LOG_DIR=/var/log/datadog
PACKAGES_LOCK_DIR=/var/run/datadog-packages

set -e

if [ "$1" -ne 0 ]; then
    # This is an upgrade, there is nothing to do now
    exit 0
fi

echo "Deleting dd-agent user"
userdel dd-agent
userdel dd-installer
echo "Deleting dd-agent group"
(getent group dd-agent >/dev/null && groupdel dd-agent) || true
(getent group dd-installer >/dev/null && groupdel dd-installer) || true
echo "Force-deleting $INSTALL_DIR $PACKAGES_DIR $LOG_DIR"
rm -rf $LOG_DIR
rm -rf $PACKAGES_DIR
rm -rf $PACKAGES_LOCK_DIR
rm -rf $INSTALL_DIR

exit 0

