load("@bazel_skylib//rules:write_file.bzl", "write_file")
load("@rules_python//python:py_binary.bzl", "py_binary")
load(":test2json_merge.bzl", "test2json_merge_from_bep")

exports_files(glob(["bazel-bep.json"], allow_empty = True))

py_binary(
    name = "generate_module_bazel",
    srcs = ["generate_module_bazel.py"],
    visibility = ["//deps:__subpackages__"],
)

# @llvm_toolchain_llvm//:install-name-tool is only defined for macos and linux.
# This acts as a replacement to avoid analysis-time failures on windows.
write_file(
    name = "_empty_install_name_tool",
    out = "empty_install_name_tool",
    is_executable = True,
)

alias(
    name = "install_name_tool",
    actual = select({
        "@platforms//os:linux": "@llvm_toolchain_llvm//:install-name-tool",
        "@platforms//os:macos": "@llvm_toolchain_llvm//:install-name-tool",
        "//conditions:default": ":_empty_install_name_tool",
    }),
    visibility = ["//visibility:public"],
)

# Merges aspect test2json fragments after bazel test using the CI BEP file at //:bazel-bep.json.
test2json_merge_from_bep(
    name = "test2json_merge",
    bep = ":bazel-bep.json",
    visibility = ["//visibility:public"],
)
