#!/usr/bin/env bash
set -euo pipefail

# Credential Helpers Specification: https://github.com/EngFlow/credential-helper-spec/blob/main/spec.md
IFS= read -d '' -r req ||:
case "$req" in
    *https://buildbarn-frontend.us1.ddbuild.io*) ;;
    *) >&2 echo "Unexpected request: $req"; exit 2 ;;
esac
if [ -n "${BUILDBARN_ID_TOKEN-}" ]; then
    printf '{"headers":{"Authorization":["Bearer %s"]}}\n' "garbageIn-$BUILDBARN_ID_TOKEN-garbageOut"
else
    echo '{}'
fi
