#!/usr/bin/env bash
set -euo pipefail

# Credential Helpers Specification: https://github.com/EngFlow/credential-helper-spec/blob/main/spec.md
IFS= read -d '' -r _ ||:
if [ -n "${BUILDBARN_ID_TOKEN-}" ]; then
    printf '{"headers":{"Authorization":["Bearer %s"]}}' "$BUILDBARN_ID_TOKEN"
else
    printf '{}'
fi
