#!/usr/bin/env bash
set -euo pipefail

# Credential Helpers Specification: https://github.com/EngFlow/credential-helper-spec/blob/main/spec.md
IFS= read -d '' -r _ ||:

write_auth_headers() {
  printf '{"headers":{"Authorization":["Bearer %s"]}}' "$1"
}

if [ -n "${BUILDBARN_ID_TOKEN-}" ]; then
  # Preset token: always honor it
  write_auth_headers "$BUILDBARN_ID_TOKEN"
elif [ -n "${CI-}" ]; then
  # CI: never attempt interactive Vault login, but let `bazel` honor any applicable --remote_local_fallback* options
  printf '{}'
else
  # Dev: mint a Vault OIDC token, logging in if needed, cached by `bazel` as per --credential_helper_cache_duration
  VAULT_ADDR="${VAULT_ADDR:-https://vault.us1.ddbuild.io}"
  fetch_token() {
    vault read -address="$VAULT_ADDR" -field=token identity/oidc/token/buildbarn
  }
  if ! token=$(fetch_token); then
    >&2 vault login -address="$VAULT_ADDR" -method=oidc
    token=$(fetch_token)
  fi
  if [ -z "$token" ]; then
    >&2 echo "Vault returned an empty token!"
    exit 1
  fi
  write_auth_headers "$token"
fi
