load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

go_library(
    name = "remoteconfig",
    srcs = ["remote_config.go"],
    importpath = "github.com/DataDog/datadog-agent/pkg/fleet/catalog/remoteconfig",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/fleet/catalog",
        "//pkg/remoteconfig/state",
        "//pkg/util/log",
    ],
)

dd_agent_go_test(
    name = "remoteconfig_test",
    srcs = ["remote_config_test.go"],
    embed = [":remoteconfig"],
    deps = [
        "//pkg/fleet/catalog",
        "//pkg/remoteconfig/state",
    ],
)
