# gazelle:ignore

load("@bazel_skylib//rules:copy_file.bzl", "copy_file")
load("@rules_go//go:def.bzl", "go_binary")

copy_file(
    name = "ebpf_probe_o",
    src = "//pkg/security/tests/syscall_tester/c:ebpf_probe",
    out = "ebpf_probe.o",
)

go_binary(
    name = "syscall_go_tester",
    srcs = ["syscall_go_tester.go"],
    embedsrcs = ["ebpf_probe.o"],
    gotags = [
        "netgo",
        "osusergo",
        "syscalltesters",
    ],
    static = "on",
    target_compatible_with = ["@platforms//os:linux"],
    visibility = ["//visibility:public"],
    deps = select({
        "@rules_go//go/platform:android": [
            "//cmd/cws-instrumentation/subcommands/injectcmd",
            "//pkg/security/tests/testutils",
            "//pkg/security/utils/k8sutils",
            "@com_github_datadog_ebpf_manager//:ebpf-manager",
            "@com_github_syndtr_gocapability//capability",
            "@com_github_vishvananda_netlink//:netlink",
            "@io_k8s_api//authentication/v1:authentication",
        ],
        "@rules_go//go/platform:linux": [
            "//cmd/cws-instrumentation/subcommands/injectcmd",
            "//pkg/security/tests/testutils",
            "//pkg/security/utils/k8sutils",
            "@com_github_datadog_ebpf_manager//:ebpf-manager",
            "@com_github_syndtr_gocapability//capability",
            "@com_github_vishvananda_netlink//:netlink",
            "@io_k8s_api//authentication/v1:authentication",
        ],
        "//conditions:default": [],
    }),
)
