load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

go_library(
    name = "custommetrics",
    srcs = ["server.go"],
    importpath = "github.com/DataDog/datadog-agent/cmd/cluster-agent/custommetrics",
    visibility = ["//visibility:public"],
    deps = [
        "//comp/autoscaling/datadogclient/def",
        "//pkg/clusteragent/autoscaling/custommetrics",
        "//pkg/clusteragent/autoscaling/externalmetrics",
        "//pkg/config/setup",
        "//pkg/util/kubernetes/apiserver",
        "//pkg/util/kubernetes/apiserver/common/namespace",
        "//pkg/util/kubernetes/autoscalers",
        "//pkg/util/log",
        "//pkg/util/option",
        "@com_github_spf13_pflag//:pflag",
        "@io_k8s_apimachinery//pkg/api/meta",
        "@io_k8s_apimachinery//pkg/runtime/schema",
        "@io_k8s_apimachinery//pkg/util/wait",
        "@io_k8s_client_go//dynamic",
        "@io_k8s_sigs_custom_metrics_apiserver//pkg/apiserver",
        "@io_k8s_sigs_custom_metrics_apiserver//pkg/cmd",
        "@io_k8s_sigs_custom_metrics_apiserver//pkg/provider",
    ],
)

dd_agent_go_test(
    name = "custommetrics_test",
    srcs = ["server_test.go"],
    embed = [":custommetrics"],
    gotags_sets = [[
        "cel",
        "clusterchecks",
        "kubeapiserver",
        "kubelet",
        "orchestrator",
    ]],
    include_default = False,
    deps = [
        "@io_k8s_apimachinery//pkg/util/wait",
    ],
)
