// Unless explicitly stated otherwise all files in this repository are licensed
// under the Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2016-present Datadog, Inc.

//go:build linux_bpf

package diconfig

import "github.com/DataDog/datadog-agent/pkg/dynamicinstrumentation/ditypes"

var remoteConfigCallbackTypeMapEntry = []*ditypes.Parameter{
	{
		Name:      "runtimeID",
		ID:        "",
		Type:      "string",
		TotalSize: 16,
		Kind:      0x18,
		LocationExpressions: []ditypes.LocationExpression{
			{
				Opcode:               ditypes.OpReadUserRegister,
				Arg1:                 0x0,
				Arg2:                 0x8,
				Arg3:                 0x0,
				CollectionIdentifier: "",
				Label:                "",
				IncludedExpressions:  nil,
			},
			{
				Opcode:               ditypes.OpReadUserRegister,
				Arg1:                 0x1,
				Arg2:                 0x8,
				Arg3:                 0x0,
				CollectionIdentifier: "",
				Label:                "",
				IncludedExpressions:  nil,
			},
			{
				Opcode:               ditypes.OpDereferenceDynamicToOutput,
				Arg1:                 ConfigProbeStringMaxSize,
				Arg2:                 0x0,
				Arg3:                 0x0,
				CollectionIdentifier: "",
				Label:                "",
				IncludedExpressions:  nil,
			},
		},
		FieldOffset:      0x0,
		DoNotCapture:     false,
		NotCaptureReason: 0x0,
		ParameterPieces: []*ditypes.Parameter{
			{
				Name:                "str",
				ID:                  "CGXYYI",
				Type:                "*uint8",
				TotalSize:           8,
				Kind:                0x16,
				Location:            &ditypes.Location{InReg: true, StackOffset: 0, Register: 0, NeedsDereference: false, PointerOffset: 0x0},
				LocationExpressions: nil,
				FieldOffset:         0x0,
				DoNotCapture:        false,
				NotCaptureReason:    0x0,
				ParameterPieces: []*ditypes.Parameter{
					{
						Name:                "",
						ID:                  "",
						Type:                "uint8",
						TotalSize:           1,
						Kind:                0x8,
						Location:            (*ditypes.Location)(nil),
						LocationExpressions: nil,
						FieldOffset:         0x0,
						DoNotCapture:        false,
						NotCaptureReason:    0x0,
						ParameterPieces:     nil,
					},
				},
			},
			{
				Name:      "len",
				ID:        "",
				Type:      "int",
				TotalSize: 8,
				Kind:      0x2,
				Location:  &ditypes.Location{InReg: true, StackOffset: 0, Register: 1, NeedsDereference: false, PointerOffset: 0x0},
				LocationExpressions: []ditypes.LocationExpression{
					{
						Opcode:               ditypes.OpReadUserRegister,
						Arg1:                 0x1,
						Arg2:                 0x8,
						Arg3:                 0x0,
						CollectionIdentifier: "",
						Label:                "",
						IncludedExpressions:  nil,
					},
					{
						Opcode:               ditypes.OpPop,
						Arg1:                 0x1,
						Arg2:                 0x2,
						Arg3:                 0x0,
						CollectionIdentifier: "",
						Label:                "",
						IncludedExpressions:  nil,
					},
				},
				FieldOffset:      0x8,
				DoNotCapture:     false,
				NotCaptureReason: 0x0,
				ParameterPieces:  nil,
			},
		},
	},
	{
		Name:      "configPath",
		ID:        "",
		Type:      "string",
		TotalSize: 16,
		Kind:      0x18,
		Location:  (*ditypes.Location)(nil),
		LocationExpressions: []ditypes.LocationExpression{
			{
				Opcode:               ditypes.OpReadUserRegister,
				Arg1:                 0x2,
				Arg2:                 0x8,
				Arg3:                 0x0,
				CollectionIdentifier: "",
				Label:                "",
				IncludedExpressions:  nil,
			},
			{
				Opcode:               ditypes.OpReadUserRegister,
				Arg1:                 0x3,
				Arg2:                 0x8,
				Arg3:                 0x0,
				CollectionIdentifier: "",
				Label:                "",
				IncludedExpressions:  nil,
			},
			{
				Opcode:               ditypes.OpDereferenceDynamicToOutput,
				Arg1:                 ConfigProbeStringMaxSize,
				Arg2:                 0x0,
				Arg3:                 0x0,
				CollectionIdentifier: "",
				Label:                "",
				IncludedExpressions:  nil,
			},
		},
		FieldOffset:      0x0,
		DoNotCapture:     false,
		NotCaptureReason: 0x0,
		ParameterPieces: []*ditypes.Parameter{
			{
				Name:                "str",
				ID:                  "EGSMLI",
				Type:                "*uint8",
				TotalSize:           8,
				Kind:                0x16,
				Location:            &ditypes.Location{InReg: true, StackOffset: 0, Register: 2, NeedsDereference: false, PointerOffset: 0x0},
				LocationExpressions: nil,
				FieldOffset:         0x0,
				DoNotCapture:        false,
				NotCaptureReason:    0x0,
				ParameterPieces: []*ditypes.Parameter{
					{
						Name:                "",
						ID:                  "",
						Type:                "uint8",
						TotalSize:           1,
						Kind:                0x8,
						Location:            (*ditypes.Location)(nil),
						LocationExpressions: nil,
						FieldOffset:         0x0,
						DoNotCapture:        false,
						NotCaptureReason:    0x0,
						ParameterPieces:     nil,
					},
				},
			},
			{
				Name:      "len",
				ID:        "",
				Type:      "int",
				TotalSize: 8,
				Kind:      0x2,
				Location:  &ditypes.Location{InReg: true, StackOffset: 0, Register: 3, NeedsDereference: false, PointerOffset: 0x0},
				LocationExpressions: []ditypes.LocationExpression{
					{
						Opcode:               ditypes.OpReadUserRegister,
						Arg1:                 0x3,
						Arg2:                 0x8,
						Arg3:                 0x0,
						CollectionIdentifier: "",
						Label:                "",
						IncludedExpressions:  nil,
					},
					{
						Opcode:               ditypes.OpPop,
						Arg1:                 0x1,
						Arg2:                 0x2,
						Arg3:                 0x0,
						CollectionIdentifier: "",
						Label:                "",
						IncludedExpressions:  nil,
					},
				},
				FieldOffset:      0x8,
				DoNotCapture:     false,
				NotCaptureReason: 0x0,
				ParameterPieces:  nil,
			},
		},
	},
	{
		Name:      "configContent",
		ID:        "",
		Type:      "string",
		TotalSize: 16,
		Kind:      0x18,
		Location:  (*ditypes.Location)(nil),
		LocationExpressions: []ditypes.LocationExpression{
			{
				Opcode:               ditypes.OpReadUserRegister,
				Arg1:                 0x4,
				Arg2:                 0x8,
				Arg3:                 0x0,
				CollectionIdentifier: "",
				Label:                "",
				IncludedExpressions:  nil,
			},
			{
				Opcode:               ditypes.OpReadUserRegister,
				Arg1:                 0x5,
				Arg2:                 0x8,
				Arg3:                 0x0,
				CollectionIdentifier: "",
				Label:                "",
				IncludedExpressions:  nil,
			},
			{
				Opcode:               ditypes.OpDereferenceDynamicToOutput,
				Arg1:                 ConfigProbeStringMaxSize,
				Arg2:                 0x0,
				Arg3:                 0x0,
				CollectionIdentifier: "",
				Label:                "",
				IncludedExpressions:  nil,
			},
		},
		FieldOffset:      0x0,
		DoNotCapture:     false,
		NotCaptureReason: 0x0,
		ParameterPieces: []*ditypes.Parameter{
			{
				Name:                "str",
				ID:                  "PWEHVX",
				Type:                "*uint8",
				TotalSize:           8,
				Kind:                0x16,
				Location:            &ditypes.Location{InReg: true, StackOffset: 0, Register: 4, NeedsDereference: false, PointerOffset: 0x0},
				LocationExpressions: nil,
				FieldOffset:         0x0,
				DoNotCapture:        false,
				NotCaptureReason:    0x0,
				ParameterPieces: []*ditypes.Parameter{
					{
						Name:                "",
						ID:                  "",
						Type:                "uint8",
						TotalSize:           1,
						Kind:                0x8,
						Location:            (*ditypes.Location)(nil),
						LocationExpressions: nil,
						FieldOffset:         0x0,
						DoNotCapture:        false,
						NotCaptureReason:    0x0,
						ParameterPieces:     nil,
					},
				},
			},
			{
				Name:      "len",
				ID:        "",
				Type:      "int",
				TotalSize: 8,
				Kind:      0x2,
				Location:  &ditypes.Location{InReg: true, StackOffset: 0, Register: 5, NeedsDereference: false, PointerOffset: 0x0},
				LocationExpressions: []ditypes.LocationExpression{
					{
						Opcode:               ditypes.OpReadUserRegister,
						Arg1:                 0x5,
						Arg2:                 0x8,
						Arg3:                 0x0,
						CollectionIdentifier: "",
						Label:                "",
						IncludedExpressions:  nil,
					},
					{
						Opcode:               ditypes.OpPop,
						Arg1:                 0x1,
						Arg2:                 0x2,
						Arg3:                 0x0,
						CollectionIdentifier: "",
						Label:                "",
						IncludedExpressions:  nil,
					},
				},
				FieldOffset:      0x8,
				DoNotCapture:     false,
				NotCaptureReason: 0x0,
				ParameterPieces:  nil,
			},
		},
	},
}
