load("@rules_go//go:def.bzl", "go_test")

go_test(
    name = "agent-subcommands_test",
    srcs = [
        "check_common_test.go",
        "check_nix_test.go",
        "check_win_test.go",
        "config_common_test.go",
        "config_nix_test.go",
        "config_win_test.go",
        "configcheck_common_test.go",
        "configcheck_nix_test.go",
        "configcheck_win_test.go",
        "diagnose_common_test.go",
        "diagnose_nix_test.go",
        "diagnose_win_test.go",
        "dogstatsdreplay_common_test.go",
        "dogstatsdreplay_nix_test.go",
        "flare_common_test.go",
        "flare_nix_test.go",
        "flare_win_test.go",
        "health_common_test.go",
        "health_nix_test.go",
        "health_win_test.go",
        "hostname_azure_nix_test.go",
        "hostname_ec2_common_test.go",
        "hostname_ec2_nix_test.go",
        "hostname_ec2_win_test.go",
        "hostname_gcp_nix_test.go",
        "run_common_test.go",
        "run_nix_test.go",
        "run_win_test.go",
        "secret_common_test.go",
        "secret_nix_test.go",
        "secret_win_test.go",
        "status_common_test.go",
        "status_nix_test.go",
        "status_win_test.go",
    ],
    # keep
    data = [
        "check/fixtures/hello.py",
        "check/fixtures/hello.yaml",
        "dogstatsdreplay/fixtures/metrics_capture.zstd",
        "status/fixtures/custom_check.py",
        "status/fixtures/custom_check.yaml",
    ],
    # keep
    embedsrcs = [
        "check/fixtures/hello.py",
        "check/fixtures/hello.yaml",
        "dogstatsdreplay/fixtures/metrics_capture.zstd",
        "status/fixtures/custom_check.py",
        "status/fixtures/custom_check.yaml",
        "//test/new-e2e/tests/agent-subcommands/flare:fixtures/datadog-agent.yaml",
        "//test/new-e2e/tests/agent-subcommands/flare:fixtures/security-agent.yaml",
        "//test/new-e2e/tests/agent-subcommands/flare:fixtures/system-probe.yaml",
        "//test/new-e2e/tests/agent-subcommands/config:fixtures/datadog-agent.yaml",
    ],
    gotags = ["test"],
    deps = [
        "//test/e2e-framework/components/datadog/agentparams",
        "//test/e2e-framework/components/os",
        "//test/e2e-framework/scenarios/aws/ec2",
        "//test/e2e-framework/testing/components",
        "//test/e2e-framework/testing/e2e",
        "//test/e2e-framework/testing/environments",
        "//test/e2e-framework/testing/provisioners/aws/host",
        "//test/e2e-framework/testing/provisioners/azure/host/linux",
        "//test/e2e-framework/testing/provisioners/gcp/host/linux",
        "//test/e2e-framework/testing/testcommon/check",
        "//test/e2e-framework/testing/utils/e2e/client",
        "//test/e2e-framework/testing/utils/e2e/client/agentclient",
        "//test/fakeintake/aggregator",
        "//test/fakeintake/api",
        "//test/fakeintake/client",
        "//test/fakeintake/client/flare",
        "//test/new-e2e/tests/agent-configuration/secretsutils",
        "//test/new-e2e/tests/agent-platform/common",
        "//test/new-e2e/tests/agent-platform/common/process",
        "//test/new-e2e/tests/agent-platform/common/svc-manager",
        "//test/new-e2e/tests/agent-subcommands/config",
        "//test/new-e2e/tests/agent-subcommands/flare",
        "//test/new-e2e/tests/windows/common/agent",
        "@com_github_cenkalti_backoff_v7//:backoff",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
        "@in_yaml_go_yaml_v2//:yaml",
    ],
)
