load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "fx",
    srcs = ["fx.go"],
    importpath = "github.com/DataDog/datadog-agent/comp/sbom/usage/fx",
    visibility = ["//visibility:public"],
    deps = [
        "//comp/sbom/usage/def",
        "//comp/sbom/usage/impl",
        "//pkg/util/fxutil",
        "@org_uber_go_fx//:fx",
    ],
)
