load("@rules_go//go:def.bzl", "go_library")

package(default_package_metadata = ["//pkg/opentelemetry-mapping-go/inframetadata:go_package_metadata"])

go_library(
    name = "gohai",
    srcs = [
        "gohai.go",
        "processes.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/pkg/opentelemetry-mapping-go/inframetadata/gohai",
    visibility = ["//visibility:public"],
)
