load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

dd_agent_go_test(
    name = "remote-flags_test",
    srcs = [
        "remote_flags_recover_test.go",
        "remote_flags_test.go",
    ],
    deps = [
        "//test/e2e-framework/components/datadog/agentparams",
        "//test/e2e-framework/scenarios/aws/ec2",
        "//test/e2e-framework/testing/e2e",
        "//test/e2e-framework/testing/environments",
        "//test/e2e-framework/testing/provisioners/aws/host",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
