load("@rules_go//go:def.bzl", "go_library")

package(default_package_metadata = ["//comp/logs-library:go_package_metadata"])

go_library(
    name = "mock",
    srcs = ["kubehealth_mock.go"],
    importpath = "github.com/DataDog/datadog-agent/comp/logs-library/kubehealth/mock",
    visibility = ["//visibility:public"],
    deps = [
        "//comp/def",
        "//comp/logs-library/kubehealth/def",
        "//pkg/status/health",
    ],
)
