#!/bin/sh
#
# Perform necessary datadog-updater removal steps after package is uninstalled.
#
# .deb: STEP 3 of 5

readonly INSTALL_DIR=/opt/datadog/updater
readonly PACKAGES_DIR=/opt/datadog-packages
readonly LOG_DIR=/var/log/datadog
readonly CONFIG_DIR=/etc/datadog-agent
readonly PACKAGES_LOCK_DIR=/var/run/datadog-packages

set -e

case "$1" in
    purge)
        echo "Deleting dd-agent user"
        deluser dd-agent --quiet
        echo "Deleting dd-agent group"
        (getent group dd-agent >/dev/null && delgroup dd-agent --quiet) || true
        echo "Force-deleting $INSTALL_DIR"
        $INSTALL_DIR/bin/updater/updater purge
        rm -rf $INSTALL_DIR
        rm -rf $LOG_DIR
        rm -rf $CONFIG_DIR
        rm -rf $PACKAGES_DIR
        rm -rf $PACKAGES_LOCK_DIR
    ;;
    remove)
        rm "$CONFIG_DIR/install_info" || true
        $INSTALL_DIR/bin/updater/updater purge
    ;;
    *)
    ;;
esac

exit 0
