#!/bin/sh
#
# Perform necessary datadog-updater removal steps after package is uninstalled.
#
# .deb: STEP 3 of 5

INSTALL_DIR=/opt/datadog
LOG_DIR=/var/log/datadog
CONFIG_DIR=/etc/datadog-agent

set -e

case "$1" in
    purge)
        echo "Deleting dd-agent user"
        deluser dd-agent --quiet
        echo "Deleting dd-updater user"
        deluser dd-updater --quiet
        echo "Deleting dd-agent group"
        (getent group dd-agent >/dev/null && delgroup dd-agent --quiet) || true
        echo "Deleting dd-updater group"
        (getent group dd-updater >/dev/null && delgroup dd-updater --quiet) || true
        echo "Force-deleting $INSTALL_DIR"
        rm -rf $INSTALL_DIR
        rm -rf $LOG_DIR
        rm -rf $CONFIG_DIR
    ;;
    remove)
        rm "$CONFIG_DIR/install_info" || true
    ;;
    *)
    ;;
esac

exit 0
