#!/bin/sh
#
# Perform necessary datadog-updater setup steps after package is installed.
#
# .deb: STEP 5 of 5

INSTALL_DIR=/opt/datadog
LOG_DIR=/var/log/datadog
CONFIG_DIR=/etc/datadog-agent

add_user_and_group() {
    # Only create group and/or user if they don't already exist
    NAME=$1
    HOME_DIR=$2
    getent group "$NAME" >/dev/null || (echo "Creating $NAME group" && addgroup --system "$NAME" --quiet)
    set +e
    id -u "$NAME" >/dev/null 2>&1
    USER_EXISTS=$?
    set -e
    if [ ! $USER_EXISTS -eq 0 ]; then
        echo "Creating $NAME user"
        adduser --system "$NAME" --disabled-login --shell /usr/sbin/nologin --home "$HOME_DIR" --no-create-home --group --quiet
    elif id -nG "$NAME" | grep --invert-match --word-regexp --quiet "$NAME"; then
        # User exists but is not part of the $NAME group
        echo "Adding $NAME user to $NAME group"
        usermod -g "$NAME" "$NAME"
    fi
}

enable_stable_agents() {
    if command -v systemctl >/dev/null 2>&1; then
        # Force systemd to ignore the sysvinit scripts. Only cosmetic, remove some irrelevant warnings during upgrade
        SYSTEMCTL_SKIP_SYSV=true systemctl enable datadog-agent-process || true
        SYSTEMCTL_SKIP_SYSV=true systemctl enable datadog-agent-sysprobe || true
        SYSTEMCTL_SKIP_SYSV=true systemctl enable datadog-agent-trace || true
        SYSTEMCTL_SKIP_SYSV=true systemctl enable datadog-agent-security || true
        SYSTEMCTL_SKIP_SYSV=true systemctl enable datadog-agent || true
        # experiment agents are not enabled as we don't systemctl enable them
    fi


}

set -e
case "$1" in
    configure)
        add_user_and_group 'dd-agent' $INSTALL_DIR/agents
        add_user_and_group 'dd-updater' $INSTALL_DIR
        usermod -g dd-agent dd-updater
    ;;
    abort-upgrade|abort-remove|abort-deconfigure)
    ;;
    *)
    ;;
esac
#DEBHELPER#

# Set the installation information if not already present;
# This is done in posttrans for .rpm packages
if [ ! -f "$CONFIG_DIR/install_info" ]; then

    if command -v dpkg >/dev/null 2>&1 && command -v dpkg-query >/dev/null 2>&1; then
        tool=dpkg
        tool_version=dpkg-$(dpkg-query --showformat='${Version}' --show dpkg  | cut -d "." -f 1-3 || echo "unknown")
    else
        tool=unknown
        tool_version=unknown
    fi

    install_info_content="---
install_method:
  tool: $tool
  tool_version: $tool_version
  installer_version: deb_package
  installer: updater
"
    echo "$install_info_content" > $CONFIG_DIR/install_info
fi

# Set proper rights to the dd-agent user
chown -R dd-agent:dd-agent ${CONFIG_DIR}
chown -R dd-agent:dd-agent ${LOG_DIR}
chown -R dd-updater:dd-updater ${INSTALL_DIR}

chmod -R 755 ${INSTALL_DIR}

# Make system-probe configs read-only
chmod 0440 ${CONFIG_DIR}/system-probe.yaml.example || true
if [ -f "$CONFIG_DIR/system-probe.yaml" ]; then
    chmod 0440 ${CONFIG_DIR}/system-probe.yaml || true
fi

# Make security-agent config read-only
chmod 0440 ${CONFIG_DIR}/security-agent.yaml.example || true
if [ -f "$CONFIG_DIR/security-agent.yaml" ]; then
    chmod 0440 ${CONFIG_DIR}/security-agent.yaml || true
fi

if [ -d "$CONFIG_DIR/compliance.d" ]; then
    chown -R root:root ${CONFIG_DIR}/compliance.d || true
fi

if [ -d "$CONFIG_DIR/runtime-security.d" ]; then
    chown -R root:root ${CONFIG_DIR}/runtime-security.d || true
fi

# start udpater
SYSTEMCTL_SKIP_SYSV=true systemctl enable datadog-updater || true
SYSTEMCTL_SKIP_SYSV=true systemctl start datadog-updater || true
enable_stable_agents

exit 0
