#!/bin/sh
#
# Perform necessary datadog-updater removal steps after package is uninstalled.
#
# .deb: STEP 3 of 5

INSTALL_DIR=/opt/datadog
PACKAGES_DIR=/opt/datadog-packages
LOG_DIR=/var/log/datadog
CONFIG_DIR=/etc/datadog-agent
PACKAGES_LOCK_DIR=/var/run/datadog-packages

set -e

case "$1" in
    purge)
        echo "Deleting dd-agent user"
        deluser dd-agent --quiet
        echo "Deleting dd-agent group"
        (getent group dd-agent >/dev/null && delgroup dd-agent --quiet) || true
        echo "Force-deleting $INSTALL_DIR"
        rm -rf $INSTALL_DIR
        rm -rf $LOG_DIR
        rm -rf $CONFIG_DIR
        rm -rf $PACKAGES_DIR
        rm -rf $PACKAGES_LOCK_DIR
    ;;
    remove)
        rm "$CONFIG_DIR/install_info" || true
        rm "$CONFIG_DIR/install.json" || true
    ;;
    *)
    ;;
esac

exit 0
