#!/bin/sh
#
#
# .deb: STEP 1 of 5

readonly INSTALL_DIR=/opt/datadog/updater

SYSTEMCTL_SKIP_SYSV=true systemctl stop datadog-updater || true
SYSTEMCTL_SKIP_SYSV=true systemctl disable datadog-updater || true

set -e

case "$1" in
    remove)
        $INSTALL_DIR/bin/updater/updater purge
    ;;
    *)
    ;;
esac
exit 0
