load("@rules_go//go:def.bzl", "go_library")

package(default_package_metadata = ["//pkg/util/fxutil:go_package_metadata"])

go_library(
    name = "logging",
    srcs = [
        "logging.go",
        "sender.go",
        "tracer.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/pkg/util/fxutil/logging",
    visibility = ["//visibility:public"],
    deps = [
        "@org_uber_go_fx//:fx",
        "@org_uber_go_fx//fxevent",
    ],
)
