load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

go_library(
    name = "sdc",
    srcs = ["docs.go"],
    importpath = "github.com/DataDog/datadog-agent/test/new-e2e/tests/agent-metric-pipelines/sdc",
    visibility = ["//visibility:public"],
)

dd_agent_go_test(
    name = "sdc_test",
    srcs = ["sdc_nix_test.go"],
    embed = [":sdc"],
    embedsrcs = ["fixtures/custom_sdc.py"],
    deps = [
        "//test/e2e-framework/components/datadog/agentparams",
        "//test/e2e-framework/scenarios/aws/ec2",
        "//test/e2e-framework/testing/e2e",
        "//test/e2e-framework/testing/environments",
        "//test/e2e-framework/testing/provisioners/aws/host",
        "//test/fakeintake/aggregator",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
