load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go_package_metadata:defs.bzl", "go_package_metadata")

package(default_package_metadata = [":go_package_metadata"])

go_package_metadata(
    name = "go_package_metadata",
    module = "github.com/DataDog/datadog-agent/comp/core/hostname/hostnameinterface/mock",
)

go_library(
    name = "mock",
    srcs = [
        "doc.go",
        "mock.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/comp/core/hostname/hostnameinterface/mock",
    visibility = ["//visibility:public"],
    deps = [
        "//comp/core/hostname/hostnameinterface/def",
        "//pkg/util/fxutil",
        "@org_uber_go_fx//:fx",
    ],
)
