#!/bin/sh
#
# Perform necessary datadog-agentless-scanner setup steps before package is installed.
#
# .deb: STEP 2 of 5

SERVICE_NAME=datadog-agentless-scanner

set -e
if [ -f "/lib/systemd/system/$SERVICE_NAME.service" ] || [ -f "/usr/lib/systemd/system/$SERVICE_NAME.service" ]; then
    # Stop an already running agent
    # supports systemd, upstart and sysvinit
    if command -v systemctl >/dev/null 2>&1; then
        systemctl stop $SERVICE_NAME || true
    elif command -v initctl >/dev/null 2>&1; then
        initctl stop $SERVICE_NAME || true
    elif command -v service >/dev/null 2>&1; then
        service $SERVICE_NAME stop || true
    else
        echo "[ WARNING ]\tCannot detect a supported init system. The datadog-agentless-scanner package only provides service files for systemd, upstart and sysvinit."
    fi
fi

exit 0
