load("@rules_go//go:def.bzl", "go_library")

package(default_package_metadata = ["//test/e2e-framework:go_package_metadata"])

go_library(
    name = "filepermissions",
    srcs = [
        "permissions.go",
        "permissions_nix.go",
        "permissions_win.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/test/e2e-framework/components/datadog/agentparams/filepermissions",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/util/option",
        "//test/e2e-framework/common",
    ],
)
