load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "impl-testbench",
    srcs = [
        "reporter.go",
        "sse.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/comp/anomalydetection/reporter/impl-testbench",
    visibility = ["//comp/anomalydetection/reporter/fx-testbench:__pkg__"],
    deps = ["//comp/anomalydetection/reporter/def"],
)
