load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

go_library(
    name = "install-test",
    srcs = [
        "assert.go",
        "base.go",
        "installtester.go",
        "system_file_tester.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/test/new-e2e/tests/windows/install-test",
    target_compatible_with = ["@platforms//os:windows"],
    visibility = ["//visibility:public"],
    deps = [
        "//test/e2e-framework/testing/components",
        "//test/e2e-framework/testing/e2e",
        "//test/e2e-framework/testing/environments",
        "//test/e2e-framework/testing/provisioners/aws/host/windows",
        "//test/e2e-framework/testing/runner",
        "//test/e2e-framework/testing/runner/parameters",
        "//test/e2e-framework/testing/utils/common",
        "//test/e2e-framework/testing/utils/e2e/client",
        "//test/e2e-framework/testing/utils/e2e/client/agentclientparams",
        "//test/new-e2e/tests/agent-platform/common",
        "//test/new-e2e/tests/agent-platform/common/helper",
        "//test/new-e2e/tests/windows",
        "//test/new-e2e/tests/windows/common",
        "//test/new-e2e/tests/windows/common/agent",
        "//test/new-e2e/tests/windows/install-test/service-test",
        "@com_github_google_uuid//:uuid",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
        "@com_github_stretchr_testify//suite",
        "@in_yaml_go_yaml_v3//:yaml",
    ],
)

dd_agent_go_test(
    name = "install-test_test",
    srcs = [
        "agent_keep_rights_test.go",
        "agent_user_test.go",
        "autologger_test.go",
        "config_root_test.go",
        "install_subservices_test.go",
        "install_test.go",
        "npm_test.go",
        "persisting_integrations_test.go",
        "procmgr_localsystem_test.go",
        "upgrade_test.go",
    ],
    embed = [":install-test"],
    deps = [
        "//test/e2e-framework/testing/components",
        "//test/e2e-framework/testing/runner",
        "//test/e2e-framework/testing/runner/parameters",
        "//test/new-e2e/tests/agent-platform/common",
        "//test/new-e2e/tests/agent-platform/common/bound-port",
        "//test/new-e2e/tests/windows/common",
        "//test/new-e2e/tests/windows/common/agent",
        "//test/new-e2e/tests/windows/install-test/service-test",
        "@com_github_cenkalti_backoff_v7//:backoff",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
        "@com_github_stretchr_testify//suite",
        "@org_golang_x_text//encoding/unicode",
        "@org_golang_x_text//transform",
    ],
)
