// Unless explicitly stated otherwise all files in this repository are licensed
// under the Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2016-present Datadog, Inc.

package model

var bpfMapNames = []string{
	"path_id",
	"enabled_events",
	"buffer_selector",
	"dr_erpc_state",
	"dr_erpc_buffer",
	"inode_discarder",
	"discarders_revi",
	"filter_policy",
	"mmap_flags_appr",
	"mmap_protection",
	"mprotect_vm_pro",
	"mprotect_req_pr",
	"open_flags_appr",
	"pipefs_mountid",
	"selinux_enforce",
	"splice_entry_fl",
	"splice_exit_fla",
	"activity_dumps_",
	"activity_dump_c",
	"traced_cgroups",
	"cgroup_wait_lis",
	"traced_pids",
	"traced_comms",
	"basename_approv",
	"register_netdev",
	"netdevice_looku",
	"fd_link_pid",
	"activity_dump_r",
	"mount_ref",
	"bpf_maps",
	"bpf_progs",
	"tgid_fd_map_id",
	"tgid_fd_prog_id",
	"syscalls",
	"proc_cache",
	"pid_cache",
	"pid_ignored",
	"exec_count_fb",
	"exec_count_bb",
	"exec_pid_transf",
	"netns_cache",
	"span_tls",
	"inode_discarder",
	"pid_discarders",
	"pathnames",
	"flow_pid",
	"conntrack",
	"io_uring_ctx_pi",
	"veth_state_mach",
	"veth_devices",
	"veth_device_nam",
	"exec_file_cache",
	"syscall_monitor",
	"syscall_table",
	"cgroup_tracing_",
	"discarder_stats",
	"discarder_stats",
	"str_array_buffe",
	"process_event_g",
	"dr_erpc_stats_f",
	"dr_erpc_stats_b",
	"is_discarded_by",
	"dns_event",
	"packets",
	"selinux_write_b",
	"events",
	"events_stats",
	"events_ringbuf_",
}
