// Unless explicitly stated otherwise all files in this repository are licensed
// under the Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2016-present Datadog, Inc.

package model

var bpfMapNames = []string{
	"path_id",
	"enabled_events",
	"buffer_selector",
	"dr_erpc_state",
	"dr_erpc_buffer",
	"inode_discarder_",
	"discarders_revis",
	"filter_policy",
	"mmap_flags_appro",
	"mmap_protection_",
	"mprotect_vm_prot",
	"mprotect_req_pro",
	"open_flags_appro",
	"pipefs_mountid",
	"selinux_enforce_",
	"splice_entry_fla",
	"splice_exit_flag",
	"activity_dumps_c",
	"activity_dump_co",
	"traced_cgroups",
	"cgroup_wait_list",
	"traced_pids",
	"traced_comms",
	"basename_approve",
	"register_netdevi",
	"netdevice_lookup",
	"fd_link_pid",
	"activity_dump_ra",
	"mount_ref",
	"bpf_maps",
	"bpf_progs",
	"tgid_fd_map_id",
	"tgid_fd_prog_id",
	"syscalls",
	"proc_cache",
	"pid_cache",
	"pid_ignored",
	"exec_count_fb",
	"exec_count_bb",
	"exec_pid_transfe",
	"netns_cache",
	"span_tls",
	"inode_discarders",
	"pid_discarders",
	"pathnames",
	"flow_pid",
	"conntrack",
	"io_uring_ctx_pid",
	"veth_state_machi",
	"veth_devices",
	"veth_device_name",
	"exec_file_cache",
	"syscall_monitor",
	"syscall_table",
	"cgroup_tracing_e",
	"discarder_stats_",
	"discarder_stats_",
	"str_array_buffer",
	"process_event_ge",
	"dr_erpc_stats_fb",
	"dr_erpc_stats_bb",
	"is_discarded_by_",
	"dns_event",
	"packets",
	"selinux_write_bu",
	"events",
	"events_stats",
	"events_ringbuf_s",
}
