load("@rules_go//go:def.bzl", "go_library")

package(default_package_metadata = ["//pkg/metrics:go_package_metadata"])

go_library(
    name = "event",
    srcs = ["event.go"],
    importpath = "github.com/DataDog/datadog-agent/pkg/metrics/event",
    visibility = ["//visibility:public"],
    deps = ["//pkg/tagger/types"],
)
