// Unless explicitly stated otherwise all files in this repository are licensed
// under the Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2016-present Datadog, Inc.

package observerimpl

import (
	"math/rand"
	"testing"

	observer "github.com/DataDog/datadog-agent/comp/observer/def"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// testHLShiftDetector returns a detector pinned to the Average aggregate so
// per-test bookkeeping (state-key counts, anomaly counts) stays predictable —
// matches the convention in metrics_detector_wasserstein_test.go and
// metrics_detector_tukey_biweight_test.go.
func testHLShiftDetector() *HLShiftDetector {
	d := NewHLShiftDetector()
	d.Aggregations = []observer.Aggregate{observer.AggregateAverage}
	return d
}

// addHLShiftPoints pushes n points generated by valueFn(i) at unit-second
// intervals starting from startTS, returning the next timestamp. Mirrors
// addWassersteinPoints / the loda+scanmw test idiom.
func addHLShiftPoints(storage *timeSeriesStorage, n int, startTS int64, valueFn func(i int) float64) int64 {
	ts := startTS
	for i := 0; i < n; i++ {
		storage.Add("ns", "metric", valueFn(i), ts, nil)
		ts++
	}
	return ts
}

// TestHLShift_RegisteredInCatalog verifies the H-L shift detector is reachable
// from defaultCatalog() under its registered name and that the catalog factory
// produces a *HLShiftDetector.
//
// NOTE: the original plan called for TestHLShift_DefaultEnabledIsFalse, but
// stage-1 shipped the catalog entry with defaultEnabled=true. The stage-2
// execution rules explicitly forbid touching component_catalog.go, so the
// default-false guard is out of scope for this stage. This test asserts only
// the registration invariant — the same precedent set by
// TestTukeyBiweight_RegisteredInCatalog after the same stage-1 / stage-2
// split. A flip back to defaultEnabled=false (matching the candidate
// description's intent) can be made in a follow-up without touching this file.
func TestHLShift_RegisteredInCatalog(t *testing.T) {
	cat := defaultCatalog()
	var found *componentEntry
	for i := range cat.entries {
		if cat.entries[i].name == "hl_shift" {
			found = &cat.entries[i]
			break
		}
	}
	require.NotNil(t, found, "hl_shift entry must exist in the catalog")
	require.Equal(t, componentDetector, found.kind)

	instance := found.factory(found.defaultConfig)
	_, ok := instance.(*HLShiftDetector)
	require.True(t, ok, "factory must produce *HLShiftDetector")
}

// TestHLShift_NoFireOnFlat verifies that a perfectly constant series produces
// zero anomalies. With madRef=0 the scaleDenom falls back to |medRef|·0.01,
// but delta_HL is also exactly 0 for two identical-value windows, so the
// MAD-scaled magnitude gate stays below ShiftThresholdMAD.
func TestHLShift_NoFireOnFlat(t *testing.T) {
	d := testHLShiftDetector()
	storage := newTimeSeriesStorage()

	addHLShiftPoints(storage, 200, 1, func(_ int) float64 { return 10.0 })

	result := d.Detect(storage, 200)
	assert.Empty(t, result.Anomalies, "constant series must not fire")
}

// TestHLShift_NoFireOnNoise verifies the false-positive budget under pure
// N(0, 1) noise. The H-L shift estimator on two windows of i.i.d. N(0, 1)
// samples has a sample median of pairwise differences with std ~ √(2)·1.253/N
// ≈ 0.044 at N=40, so |delta_HL|/MAD(ref) ≈ 0.044 — orders of magnitude below
// ShiftThresholdMAD=4. Allow ≤1 anomaly to give the same noise budget as
// MannKendall (matches the catalog-wide convention).
func TestHLShift_NoFireOnNoise(t *testing.T) {
	d := testHLShiftDetector()
	storage := newTimeSeriesStorage()
	rng := rand.New(rand.NewSource(42)) //nolint:gosec // deterministic test seed

	addHLShiftPoints(storage, 200, 1, func(_ int) float64 { return rng.NormFloat64() })

	result := d.Detect(storage, 200)
	assert.LessOrEqual(t, len(result.Anomalies), 1, "pure N(0,1) noise must fire at most once")
}

// TestHLShift_FiresOnLevelShift exercises the canonical positive case: 80
// stable points at mean 0 followed by 80 shifted points at mean +5. Once cur
// has rolled past the 75% same-direction threshold (k=32 of 40 cur values
// above medRef), the dual gate fires exactly once and the cooldown suppresses
// the rest of the trace.
func TestHLShift_FiresOnLevelShift(t *testing.T) {
	d := testHLShiftDetector()
	storage := newTimeSeriesStorage()
	rng := rand.New(rand.NewSource(42)) //nolint:gosec // deterministic test seed

	ts := addHLShiftPoints(storage, 80, 1, func(_ int) float64 { return rng.NormFloat64() })
	ts = addHLShiftPoints(storage, 80, ts, func(_ int) float64 { return 5.0 + rng.NormFloat64() })

	result := d.Detect(storage, ts-1)
	require.Len(t, result.Anomalies, 1, "a clean +5σ level shift must fire exactly once")

	a := result.Anomalies[0]
	assert.Equal(t, "hl_shift", a.DetectorName)
	assert.Contains(t, a.Title, "H-L shift:")
	assert.Contains(t, a.Description, "increasing")
	require.NotNil(t, a.Score, "anomaly must carry a score")
	assert.GreaterOrEqual(t, *a.Score, 4.0, "shiftMAD-derived score must clear the threshold")
}

// TestHLShift_RobustToSingleOutlierInRef verifies the 50%-breakdown property
// of the Walsh-difference median. We replicate the level-shift trace from
// TestHLShift_FiresOnLevelShift, but inject a single +50 sensor glitch into
// the stable phase positioned so it stays inside the ref window through the
// scoring tick that fires (point 50 is in ref for ticks 90..129; the canonical
// fire tick is 112).
//
// A single ref outlier perturbs at most N=40 of the N²=1600 pairwise
// differences (the row where ref[i] is the outlier), so the median sits in
// the unperturbed bulk and delta_HL is unaffected. Wasserstein-1 over-fires
// in this configuration because the outlier shifts an entire order-statistic
// position; H-L must still produce a clean increasing fire — that contract is
// what this test pins.
func TestHLShift_RobustToSingleOutlierInRef(t *testing.T) {
	d := testHLShiftDetector()
	storage := newTimeSeriesStorage()
	rng := rand.New(rand.NewSource(42)) //nolint:gosec // deterministic test seed

	ts := addHLShiftPoints(storage, 80, 1, func(i int) float64 {
		if i == 49 {
			// 0-indexed point 49 is the 50th input → timestamp 50, which
			// lives in ref through ticks 90..129. The shift starts at point
			// 81 and the canonical fire at tick 112 — so the outlier is in
			// ref at fire time.
			return 50.0
		}
		return rng.NormFloat64()
	})
	ts = addHLShiftPoints(storage, 80, ts, func(_ int) float64 { return 5.0 + rng.NormFloat64() })

	result := d.Detect(storage, ts-1)
	require.NotEmpty(t, result.Anomalies,
		"single +50 sensor glitch in ref must NOT block detection of a real +5 shift")
	a := result.Anomalies[0]
	assert.Equal(t, "hl_shift", a.DetectorName)
	assert.Contains(t, a.Description, "increasing",
		"shift direction must be reported as increasing despite the ref outlier")
	require.NotNil(t, a.Score)
	assert.GreaterOrEqual(t, *a.Score, 4.0,
		"shiftMAD-derived score must clear the threshold even with one ref outlier")
}

// TestHLShift_NoFireOnSingleOutlierInCur is the structural anti-overfire test:
// a flat 119-point series with a single +50 spike at the end. By tick 120 cur
// holds 39 flat values + 1 spike; ref is fully flat. Wasserstein-1 over-fires
// here because the spike yanks an entire order-statistic position; the
// majority-moved confirmation gate (75% of cur must move in delta_HL's
// direction) blocks it for H-L since only 1/40 cur values moved.
func TestHLShift_NoFireOnSingleOutlierInCur(t *testing.T) {
	d := testHLShiftDetector()
	storage := newTimeSeriesStorage()

	// 119 flat points then a spike at point 120. By tick 120 the windows are
	// ref=[41..80] flat and cur=[81..120] = 39 flat + 1 spike, and the
	// ScoreEvery cadence (80, 84, ..., 120) lands a scoring tick exactly on
	// the spike-bearing point. madRef=0 → scaleDenom falls back to
	// |medRef|·0.01 = 0.1, so the test does NOT rely on noise to set the
	// scale; it pins the structural confirm-fraction gate.
	ts := addHLShiftPoints(storage, 119, 1, func(_ int) float64 { return 10.0 })
	storage.Add("ns", "metric", 100.0, ts, nil)

	result := d.Detect(storage, ts)
	assert.Empty(t, result.Anomalies,
		"single +50 outlier in cur must NOT fire — the 75%% confirm gate blocks it (only 1/40 moved)")
}

// TestHLShift_RemoveSeriesClearsState verifies the SeriesRemover contract:
// per-(ref, agg) state is dropped when storage frees a ref, so the detector
// state map cannot grow unbounded with cumulative series cardinality. Other
// series' state must be untouched. Mirrors TestWasserstein_RemoveSeriesClearsState.
func TestHLShift_RemoveSeriesClearsState(t *testing.T) {
	d := NewHLShiftDetector() // default Aggregations: [Average, Count]
	storage := newTimeSeriesStorage()

	// Register 2 distinct series with enough points to land in the detector's
	// per-series map (any Detect call instantiates state for every listed
	// series, even with no points yet ingested).
	for s := 0; s < 2; s++ {
		name := "metric" + string(rune('A'+s))
		for i := 0; i < 5; i++ {
			storage.Add("ns", name, float64(i), int64(i+1), nil)
		}
	}

	d.Detect(storage, 5)
	require.Len(t, d.series, 2*len(d.Aggregations),
		"each series should have one state entry per aggregation")

	metas := storage.ListSeries(observer.WorkloadSeriesFilter())
	require.Len(t, metas, 2)
	survivor := metas[1].Ref

	d.RemoveSeries([]observer.SeriesRef{metas[0].Ref})

	// Only state for the surviving series should remain — and only for that
	// ref·agg pair.
	assert.Len(t, d.series, len(d.Aggregations),
		"only state for the surviving series should remain after RemoveSeries")
	for k := range d.series {
		assert.Equal(t, survivor, k.ref, "remaining state must belong to the surviving ref")
	}
	assert.Nil(t, d.cachedSeries, "RemoveSeries must invalidate the cached series list")
}
