# latest LTS
FROM --platform=$BUILDPLATFORM ubuntu:20.04

ARG TARGETARCH
ARG GO_VERSION=1.20.8
ENV DEBIAN_FRONTEND=noninteractive
ENV DATADOG_AGENT_EMBEDDED_PATH=/opt/datadog-agent/embedded

RUN apt-get update && apt-get upgrade -y && \
    # Common + Agent (Core/Trace/Process) dependencies
    apt-get install -y build-essential apt-transport-https libsystemd-dev cmake sudo vim git curl procps ruby ruby-dev autoconf automake libtool libtool-bin gettext autopoint checkpolicy policycoreutils policycoreutils-python-utils bison pkg-config docker.io ninja-build \
    # Python setup
    python3 python3-dev python3-venv python3-pip

RUN curl -sL https://storage.googleapis.com/golang/go${GO_VERSION}.linux-${TARGETARCH}.tar.gz | tar -C /usr/local -xz

# GOPATH needs to be in /home/datadog because rtloader/CMakeLists.txt
# makes some unfortunate assumptions
ENV GOPATH="/home/datadog/go" \
    GOROOT=/usr/local/go \
    PATH="${PATH}:${GOPATH}/bin:/usr/local/go/bin"

COPY ./requirements.txt ${GOPATH}/src/github.com/DataDog/datadog-agent/
WORKDIR ${GOPATH}/src/github.com/DataDog/datadog-agent
RUN pip3 install -r ${GOPATH}/src/github.com/DataDog/datadog-agent/requirements.txt

COPY . ${GOPATH}/src/github.com/DataDog/datadog-agent/
WORKDIR ${GOPATH}/src/github.com/DataDog/datadog-agent
RUN git config --global --add safe.directory /home/datadog/go/src/github.com/DataDog/datadog-agent
RUN invoke install-tools
RUN invoke deps

# there may be previous build artifacts from leaked CMake caches of rtloader if run on host
RUN git clean -dfX ./rtloader/

WORKDIR ${GOPATH}/src/github.com/DataDog/datadog-agent
RUN CGO_ENABLED=1 GOEXPERIMENT=boringcrypto invoke agent.build --build-exclude=systemd
