# This Makefile is used within the release process of the Datadog Agent 5:
# https://github.com/DataDog/dd-agent-omnibus/blob/fad8aeb/config/software/datadog-trace-agent.rb#L105

# if the TRACE_AGENT_VERSION environment variable isn't set, default to 0.99.0
TRACE_AGENT_VERSION := $(if $(TRACE_AGENT_VERSION),$(TRACE_AGENT_VERSION), 0.99.0)
TRACE_DIR := cmd/trace-agent

# break up the version
SPLAT = $(subst ., ,$(TRACE_AGENT_VERSION))
GET_VERSION_PART = $(shell echo $(word $1, $(SPLAT)) | sed 's/[^0-9]*//g')
VERSION_MAJOR = $(call GET_VERSION_PART,1)
VERSION_MINOR = $(call GET_VERSION_PART,2)
VERSION_PATCH = $(call GET_VERSION_PART,3)

# account for some defaults
VERSION_MAJOR := $(if $(VERSION_MAJOR),$(VERSION_MAJOR), 0)
VERSION_MINOR := $(if $(VERSION_MINOR),$(VERSION_MINOR), 0)
VERSION_PATCH := $(if $(VERSION_PATCH),$(VERSION_PATCH), 0)

# windows flags
WINUTIL_DIR := pkg/util/winutil/messagestrings
DEFS := --define MAJ_VER=$(VERSION_MAJOR) --define MIN_VER=$(VERSION_MINOR) --define PATCH_VER=$(VERSION_PATCH)
TARGET := pe-x86-64

install:
	# generate versioning information and installing the binary.
	go generate ./pkg/trace/info
	go install ./$(TRACE_DIR)

ci:
	# task used by CI
	go install ./$(TRACE_DIR)
	go test -v -race ./...

windows:
	# pre-packages resources needed for the windows release
	windmc --target $(TARGET) -r $(WINUTIL_DIR) -h $(WINUTIL_DIR) $(WINUTIL_DIR)/messagestrings.mc
	windres -i $(WINUTIL_DIR)/messagestrings.rc --target=$(TARGET) -O coff -o $(WINUTIL_DIR)/rsrc.syso
	windres $(DEFS) -i $(TRACE_DIR)/windows/resources/trace-agent.rc --target=$(TARGET) -O coff -o $(TRACE_DIR)/rsrc.syso

