load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "credential",
    srcs = [
        "authorize.go",
        "directive.go",
        "lookup.go",
        "provider.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/pkg/credential",
    visibility = ["//visibility:public"],
)
