source 'https://rubygems.org'

# Install omnibus
gem 'chef-sugar', git: 'https://github.com/chef/chef-sugar.git', tag: 'v5.1.12'
gem 'omnibus', git: 'https://github.com/DataDog/omnibus-ruby.git', ref: (ENV['OMNIBUS_RUBY_VERSION'] || 'datadog-5.5.0')

gem 'mixlib-cli', '~> 2.1.0'
