load("@rules_go//go:def.bzl", "go_library")

package(default_package_metadata = ["//pkg/security/secl:go_package_metadata"])

go_library(
    name = "args",
    srcs = ["parse.go"],
    importpath = "github.com/DataDog/datadog-agent/pkg/security/secl/args",
    visibility = ["//visibility:public"],
    deps = ["//pkg/security/secl/model"],
)
