load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

go_library(
    name = "impl",
    srcs = [
        "authored_scripts_catalog.go",
        "authored_scripts_catalog_unsupported.go",
        "privateactionrunner.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/comp/privateactionrunner/impl",
    visibility = ["//visibility:public"],
    deps = [
        "//comp/core/config",
        "//comp/core/hostname",
        "//comp/core/hostname/hostnameinterface/def",
        "//comp/core/ipc/def",
        "//comp/core/log/def",
        "//comp/core/tagger/def",
        "//comp/def",
        "//comp/dogstatsd/statsd/def",
        "//comp/forwarder/eventplatform/def",
        "//comp/kubeactions/helmactions/def",
        "//comp/kubeactions/kubeactions/def",
        "//comp/networkpath/traceroute/def",
        "//comp/privateactionrunner/def",
        "//comp/remote-config/rcclient/def",
        "//pkg/config/env",
        "//pkg/config/model",
        "//pkg/config/utils",
        "//pkg/fips",
        "//pkg/fleet/installer/telemetry",
        "//pkg/privateactionrunner/adapters/config",
        "//pkg/privateactionrunner/adapters/parversion",
        "//pkg/privateactionrunner/adapters/rcclient",
        "//pkg/privateactionrunner/autoconnections",
        "//pkg/privateactionrunner/enrollment",
        "//pkg/privateactionrunner/executor",
        "//pkg/privateactionrunner/libs/encryptioncontext",
        "//pkg/privateactionrunner/observability",
        "//pkg/privateactionrunner/opms",
        "//pkg/privateactionrunner/runners",
        "//pkg/privateactionrunner/task-verifier",
        "//pkg/privateactionrunner/util",
        "//pkg/util/http",
        "@com_github_datadog_datadog_go_v5//statsd",
        "@org_golang_google_grpc//:grpc",
        "@org_golang_google_grpc//credentials",
    ] + select({
        "@rules_go//go/platform:aix": [
            "//pkg/privateactionrunner/bundle-support/authoredscripts",
        ],
        "@rules_go//go/platform:android": [
            "//pkg/privateactionrunner/bundle-support/authoredscripts",
        ],
        "@rules_go//go/platform:darwin": [
            "//pkg/privateactionrunner/bundle-support/authoredscripts",
        ],
        "@rules_go//go/platform:dragonfly": [
            "//pkg/privateactionrunner/bundle-support/authoredscripts",
        ],
        "@rules_go//go/platform:freebsd": [
            "//pkg/privateactionrunner/bundle-support/authoredscripts",
        ],
        "@rules_go//go/platform:illumos": [
            "//pkg/privateactionrunner/bundle-support/authoredscripts",
        ],
        "@rules_go//go/platform:ios": [
            "//pkg/privateactionrunner/bundle-support/authoredscripts",
        ],
        "@rules_go//go/platform:js": [
            "//pkg/privateactionrunner/bundle-support/authoredscripts",
        ],
        "@rules_go//go/platform:linux": [
            "//pkg/privateactionrunner/bundle-support/authoredscripts",
        ],
        "@rules_go//go/platform:netbsd": [
            "//pkg/privateactionrunner/bundle-support/authoredscripts",
        ],
        "@rules_go//go/platform:openbsd": [
            "//pkg/privateactionrunner/bundle-support/authoredscripts",
        ],
        "@rules_go//go/platform:osx": [
            "//pkg/privateactionrunner/bundle-support/authoredscripts",
        ],
        "@rules_go//go/platform:plan9": [
            "//pkg/privateactionrunner/bundle-support/authoredscripts",
        ],
        "@rules_go//go/platform:qnx": [
            "//pkg/privateactionrunner/bundle-support/authoredscripts",
        ],
        "@rules_go//go/platform:solaris": [
            "//pkg/privateactionrunner/bundle-support/authoredscripts",
        ],
        "@rules_go//go/platform:windows": [
            "//pkg/privateactionrunner/bundle-support/authoredscripts",
        ],
        "//conditions:default": [],
    }),
)

dd_agent_go_test(
    name = "impl_test",
    srcs = ["privateactionrunner_test.go"],
    embed = [":impl"],
    deps = [
        "@com_github_datadog_datadog_go_v5//statsd",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
