load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go_package_metadata:defs.bzl", "go_package_metadata")

package(default_package_metadata = [":go_package_metadata"])

go_package_metadata(
    name = "go_package_metadata",
    module = "github.com/DataDog/datadog-agent/comp/core/secrets/noop-impl",
)

go_library(
    name = "noop-impl",
    srcs = ["secret_noop.go"],
    importpath = "github.com/DataDog/datadog-agent/comp/core/secrets/noop-impl",
    visibility = ["//visibility:public"],
    deps = [
        "//comp/api/api/def",
        "//comp/core/flare/types",
        "//comp/core/secrets/def",
        "//comp/core/secrets/noop-impl/types",
        "//comp/core/status",
    ],
)
