load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "e2ectlenv",
    srcs = ["e2ectlenv.go"],
    importpath = "github.com/DataDog/datadog-agent/test/new-e2e/utils/e2ectlenv",
    visibility = ["//visibility:public"],
    deps = [
        "//test/e2e-framework/testing/provisioner",
    ],
)
