build:
	docker build -t docker.io/stackstate/stackstate-agent-runner-gitlab:latest7 .
try:
	docker run -it docker.io/stackstate/stackstate-agent-runner-gitlab:latest7 bash
push:
	docker push docker.io/stackstate/stackstate-agent-runner-gitlab:latest7
