load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

dd_agent_go_test(
    name = "cspm_test",
    srcs = [
        "cspm_test.go",
        "docker_host_test.go",
        "host_benchmarks_container_nix_test.go",
        "host_benchmarks_diag_nix_test.go",
        "host_benchmarks_nix_test.go",
        "host_benchmarks_probes_nix_test.go",
    ],
    data = [
        "testdata/golden/README.md",
        "testdata/golden/cis-al2023.txt",
        "testdata/golden/cis-almalinux9.txt",
        "testdata/golden/cis-rhel10.txt",
        "testdata/golden/cis-rhel8.txt",
        "testdata/golden/cis-rhel9.txt",
        "testdata/golden/cis-ubuntu2404.txt",
        "values.yaml",
    ],
    embedsrcs = [
        "testdata/golden/README.md",
        "testdata/golden/cis-al2023.txt",
        "testdata/golden/cis-almalinux9.txt",
        "testdata/golden/cis-rhel10.txt",
        "testdata/golden/cis-rhel8.txt",
        "testdata/golden/cis-rhel9.txt",
        "testdata/golden/cis-ubuntu2404.txt",
        "values.yaml",
    ],
    deps = [
        "//test/e2e-framework/components/datadog/agentparams",
        "//test/e2e-framework/components/datadog/dockeragentparams",
        "//test/e2e-framework/components/datadog/kubernetesagentparams",
        "//test/e2e-framework/components/os",
        "//test/e2e-framework/scenarios/aws/ec2",
        "//test/e2e-framework/scenarios/aws/ec2docker",
        "//test/e2e-framework/scenarios/aws/kindvm",
        "//test/e2e-framework/testing/e2e",
        "//test/e2e-framework/testing/environments",
        "//test/e2e-framework/testing/provisioners/aws/docker",
        "//test/e2e-framework/testing/provisioners/aws/host",
        "//test/e2e-framework/testing/provisioners/aws/kubernetes/kindvm",
        "@com_github_pulumi_pulumi_sdk_v3//go/pulumi",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
        "@io_k8s_api//core/v1:core",
        "@io_k8s_apimachinery//pkg/apis/meta/v1:meta",
        "@io_k8s_apimachinery//pkg/fields",
    ],
)
