load("//bazel/rules/ebpf:ebpf.bzl", "ebpf_program_suite")

ebpf_program_suite(
    name = "tracer-fentry",
    src = "tracer-fentry.c",
    core = True,
    extra_flags = [
        "-Ipkg/network/ebpf/c/co-re",
        "-Ipkg/network/ebpf/c",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/ebpf/c:hdr/bpf_bypass",
        "//pkg/ebpf/c:hdr/bpf_endian",
        "//pkg/ebpf/c:hdr/bpf_metadata",
        "//pkg/ebpf/c:hdr/bpf_telemetry",
        "//pkg/ebpf/c:hdr/bpf_tracing",
        "//pkg/ebpf/c:hdr/ktypes",
        "//pkg/network/ebpf/c:hdr/ip",
        "//pkg/network/ebpf/c:hdr/ipv6",
        "//pkg/network/ebpf/c:hdr/pid_tgid",
        "//pkg/network/ebpf/c:hdr/protocols/classification/protocol-classification",
        "//pkg/network/ebpf/c:hdr/protocols/tls/tls-certs",
        "//pkg/network/ebpf/c:hdr/skb",
        "//pkg/network/ebpf/c:hdr/sock",
        "//pkg/network/ebpf/c:hdr/tracer/bind",
        "//pkg/network/ebpf/c:hdr/tracer/events",
        "//pkg/network/ebpf/c:hdr/tracer/maps",
        "//pkg/network/ebpf/c:hdr/tracer/port",
        "//pkg/network/ebpf/c:hdr/tracer/stats",
        "//pkg/network/ebpf/c:hdr/tracer/telemetry",
        "//pkg/network/ebpf/c:hdr/tracer/tracer",
    ],
)
