#!/bin/sh
#
# Perform necessary datadog-agent setup steps after package is installed.
# NOTE: part of the setup is done in the posttrans (rpm-only) script
#
# .rpm: STEP 3 of 6

INSTALL_DIR=/opt/datadog-agent
LOG_DIR=/var/log/datadog
CONFIG_DIR=/etc/datadog-agent

# Set proper rights to the dd-agent user
chown -R root:dd-agent ${CONFIG_DIR}
find ${CONFIG_DIR} -type d -not -path ${CONFIG_DIR}/conf.d -exec chmod 2750 {} \;
find ${CONFIG_DIR} -type f -not -path ${CONFIG_DIR}/conf.d -exec chmod 640 {} \;
find ${CONFIG_DIR}/conf.d -type d -exec chmod 3770 {} \;
find ${CONFIG_DIR}/conf.d -type f -exec chmod 660 {} \;
chown -R dd-agent:dd-agent ${LOG_DIR}
chown -R dd-agent:dd-agent ${INSTALL_DIR}

# Make the system-probe and security-agent binaries and eBPF programs owned by root
chown root:root ${INSTALL_DIR}/embedded/bin/system-probe
chown root:root ${INSTALL_DIR}/embedded/bin/security-agent
chown -R root:root ${INSTALL_DIR}/embedded/share/system-probe/ebpf
chown -R root:root ${INSTALL_DIR}/embedded/share/system-probe/java

exit 0
