#! /bin/sh
#
# This script is RPM-specific
# It is run at the very end of an install/upgrade of the package
# It is NOT run on removal of the package
#
# .rpm: STEP 6 of 6

INSTALL_DIR=/opt/datadog-agent
CONFIG_DIR=/etc/datadog-agent
SERVICE_NAME=datadog-agent
LOG_DIR=/var/log/datadog
CONFIG_DIR=/etc/datadog-agent

# Create a symlink to the agent's binary
ln -sf $INSTALL_DIR/bin/agent/agent /usr/bin/datadog-agent

# Set up `dd-agent` user and group
if ! getent group dd-agent >/dev/null; then
    groupadd -r dd-agent
fi
if ! getent passwd dd-agent >/dev/null; then
    useradd -r -M -g dd-agent -d $INSTALL_DIR -s /sbin/nologin -c "Datadog Agent" dd-agent
    if ! usermod -L dd-agent; then
        echo "[ WARNING ]\tCannot lock the 'dd-agent' user account"
    fi
fi

KNOWN_DISTRIBUTION="(Debian|Ubuntu|RedHat|CentOS|openSUSE|Amazon|Arista|SUSE|Rocky|AlmaLinux|Oracle)"
DISTRIBUTION=$(lsb_release -d 2>/dev/null | grep -Eo $KNOWN_DISTRIBUTION || grep -Eo $KNOWN_DISTRIBUTION /etc/issue 2>/dev/null || grep -Eo $KNOWN_DISTRIBUTION /etc/Eos-release 2>/dev/null || grep -m1 -Eo $KNOWN_DISTRIBUTION /etc/os-release 2>/dev/null || uname -s)

# Only install selinux policy on a few known distributions
INSTALL_SELINUX_POLICY="false"
if [ "$DISTRIBUTION" = "CentOS" ] || [ "$DISTRIBUTION" = "RedHat" ] || [ "$DISTRIBUTION" = "Rocky" ] || [ "$DISTRIBUTION" = "AlmaLinux" ] || [ "$DISTRIBUTION" = "Oracle" ]; then
    OS_RELEASE_VERSION=$(grep VERSION_ID /etc/os-release | cut -d = -f 2 | cut -d . -f 1 | tr -d '"')
    if [ "$OS_RELEASE_VERSION" = "7" ]; then
        INSTALL_SELINUX_POLICY="true"
    fi
fi

if [ "$INSTALL_SELINUX_POLICY" = "true" ]; then
    # Setup SELinux policy and label if SELinux detected on the host
    if command -v semodule >/dev/null 2>&1 && [ -f "$INSTALL_DIR/embedded/bin/system-probe" ]; then
        echo "Loading SELinux policy module for datadog-agent."
        semodule -v -i $CONFIG_DIR/selinux/system_probe_policy.pp >/dev/null 2>&1
        if [ "$?" != "0" ]; then
            echo "Couldn’t load system-probe policy."
            echo "To be able to run system-probe on your host, please install or update the selinux-policy-targeted and"
            echo "policycoreutils-python (or policycoreutils-python-utils depending on your distribution) packages."
            echo "Then run the following commands, or reinstall datadog-agent:"
            echo "    semodule -i $CONFIG_DIR/selinux/system_probe_policy.pp"
            echo "    semanage fcontext -a -t system_probe_t $INSTALL_DIR/embedded/bin/system-probe"
            echo "    semanage fcontext -a -t system_probe_t $INSTALL_DIR/bin/agent/agent"
            echo "    restorecon -v $INSTALL_DIR/embedded/bin/system-probe $INSTALL_DIR/bin/agent/agent"
        else
            echo "Labeling SELinux type for the system-probe binary."
            if command -v semanage >/dev/null 2>&1 && command -v restorecon >/dev/null 2>&1; then
                semanage fcontext -a -t system_probe_t $INSTALL_DIR/embedded/bin/system-probe && semanage fcontext -a -t system_probe_t $INSTALL_DIR/bin/agent/agent && restorecon -v $INSTALL_DIR/embedded/bin/system-probe && restorecon -v $INSTALL_DIR/bin/agent/agent
                if [ "$?" != "0" ]; then
                    echo "Couldn’t install system-probe policy."
                    echo "To be able to run system-probe on your host, please install or update the selinux-policy-targeted and"
                    echo "policycoreutils-python (or policycoreutils-python-utils depending on your distribution) packages."
                    echo "Then run the following commands, or reinstall datadog-agent:"
                    echo "    semodule -i $CONFIG_DIR/selinux/system_probe_policy.pp"
                    echo "    semanage fcontext -a -t system_probe_t $INSTALL_DIR/embedded/bin/system-probe"
                    echo "    semanage fcontext -a -t system_probe_t $INSTALL_DIR/bin/agent/agent"
                    echo "    restorecon -v $INSTALL_DIR/embedded/bin/system-probe $INSTALL_DIR/bin/agent/agent"
                fi
            else
                echo "Couldn’t load system-probe policy (missing selinux utilities)."
                echo "To be able to run system-probe on your host, please install or update the selinux-policy-targeted and"
                echo "policycoreutils-python (or policycoreutils-python-utils depending on your distribution) packages."
                echo "Then run the following commands, or reinstall datadog-agent:"
                echo "    semodule -i $CONFIG_DIR/selinux/system_probe_policy.pp"
                echo "    semanage fcontext -a -t system_probe_t $INSTALL_DIR/embedded/bin/system-probe"
                echo "    semanage fcontext -a -t system_probe_t $INSTALL_DIR/bin/agent/agent"
                echo "    restorecon -v $INSTALL_DIR/embedded/bin/system-probe $INSTALL_DIR/bin/agent/agent"
            fi
        fi
    fi
fi

# Set the installation information if not already present;
# This is done in the postinst script for .deb packages
if [ ! -f "$CONFIG_DIR/install_info" ]; then

    if command -v rpm >/dev/null 2>&1; then
        tool=rpm
        # Omnibus will put this script verbatim inside RPM specfile before building.
        # We need to escape the "%" so that the rpm build machinery doesn't expand
        # it as a macro (which would expand to the version of Agent being built).
        # NOTE: on some distros (e.g. opensuse 15.4), "rpm" package doesn't exist,
        # it's called "rpm-ndb". We query version of package which contains /bin/rpm file.
        tool_version=rpm-$(rpm -q -f /bin/rpm --queryformat "%%{VERSION}" || echo "unknown")
    else
        tool=unknown
        tool_version=unknown
    fi

    # Distinguish SUSE since it has a different package
    if [ -f "/etc/SuSE-release" ] || [ "$DISTRIBUTION" = "openSUSE" ] || [ "$DISTRIBUTION" = "SUSE" ]; then
        installer_version="rpm_suse_package"
    else
        installer_version="rpm_package"
    fi

    install_info_content="---
install_method:
  tool: $tool
  tool_version: $tool_version
  installer_version: $installer_version
"
    echo "$install_info_content" >$CONFIG_DIR/install_info
fi

set +e
generate_install_id() {
    # Try generating a UUID based on /proc/sys/kernel/random/uuid
    uuid=$(cat /proc/sys/kernel/random/uuid 2>/dev/null)
    # If that does not work, then try uuidgen
    if [ ${#uuid} -ne 36 ]; then
        uuid=$(uuidgen 2>/dev/null)
    fi
    # Convert to lowercase
    uuid=$(echo "$uuid" | tr '[:upper:]' '[:lower:]')
    printf "$uuid"
}

generate_install_signature() {
    install_id="$1"
    install_type="$2"
    install_time="$3"
    printf "{\"install_id\":\"$install_id\",\"install_type\":\"$install_type\",\"install_time\":$install_time}"
}

if [ ! -f "$CONFIG_DIR/install.json" ]; then
    install_id=$(generate_install_id)
    install_type="linux_manual_with_rpm"
    install_time=$(date +%s)
    install_signature=$(generate_install_signature "$install_id" "$install_type" "$install_time")
    echo "$install_signature" >$CONFIG_DIR/install.json
fi
set -e

if [ -f "$INSTALL_DIR/embedded/bin/python" ]; then
    ${INSTALL_DIR}/embedded/bin/python "${INSTALL_DIR}/python-scripts/post.py" "${INSTALL_DIR}" || true
fi
if [ -x ${INSTALL_DIR}/embedded/bin/fipsinstall.sh ]; then
    ${INSTALL_DIR}/embedded/bin/fipsinstall.sh
fi

# Set proper rights to the dd-agent user
chown -R dd-agent:dd-agent ${CONFIG_DIR}
chown -R dd-agent:dd-agent ${LOG_DIR}
chown -R dd-agent:dd-agent ${INSTALL_DIR}

# Make system-probe configs read-only
chmod 0440 ${CONFIG_DIR}/system-probe.yaml.example || true
if [ -f "$CONFIG_DIR/system-probe.yaml" ]; then
    chmod 0440 ${CONFIG_DIR}/system-probe.yaml || true
fi

# Make security-agent config read-only
chmod 0440 ${CONFIG_DIR}/security-agent.yaml.example || true
if [ -f "$CONFIG_DIR/security-agent.yaml" ]; then
    chmod 0440 ${CONFIG_DIR}/security-agent.yaml || true
fi

if [ -d "$CONFIG_DIR/compliance.d" ]; then
    chown -R root:root ${CONFIG_DIR}/compliance.d || true
fi

if [ -d "$CONFIG_DIR/runtime-security.d" ]; then
    chown -R root:root ${CONFIG_DIR}/runtime-security.d || true
fi

# Make the system-probe and security-agent binaries and eBPF programs owned by root
chown root:root ${INSTALL_DIR}/embedded/bin/system-probe
chown root:root ${INSTALL_DIR}/embedded/bin/security-agent
chown -R root:root ${INSTALL_DIR}/embedded/share/system-probe/ebpf
chown -R root:root ${INSTALL_DIR}/embedded/share/system-probe/java

echo "Enabling service $SERVICE_NAME"
if command -v systemctl >/dev/null 2>&1; then
    systemctl enable $SERVICE_NAME || echo "[ WARNING ]\tCannot enable $SERVICE_NAME with systemctl"
elif command -v initctl >/dev/null 2>&1; then
    # start/stop policy is already defined in the upstart job file
    :
else
    echo "[ WARNING ]\tCannot detect a supported init system. The datadog-agent package only provides service files for systemd and upstart."
fi

# TODO: Use a configcheck command on the agent to determine if it's safe to restart,
# and avoid restarting when a check conf is invalid
if [ -f "$CONFIG_DIR/datadog.yaml" ]; then
    echo "(Re)starting $SERVICE_NAME now..."
    if command -v systemctl >/dev/null 2>&1; then
        systemctl restart $SERVICE_NAME || true
    elif command -v initctl >/dev/null 2>&1; then
        initctl start $SERVICE_NAME || initctl restart $SERVICE_NAME || true
    else
        echo "[ WARNING ]\tCannot detect a supported init system. The datadog-agent package only provides service files for systemd and upstart."
    fi
else
    # No datadog.yaml file is present. This is probably a clean install made with the
    # step-by-step instructions/an automation tool, and the config file will be added next.
    echo "No datadog.yaml file detected, not starting the agent"
fi

exit 0
