load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

go_library(
    name = "jetson",
    srcs = [
        "cpuMetricsSender.go",
        "doc.go",
        "gpuMetricsSender.go",
        "iramMetricsSender.go",
        "jetson.go",
        "metricsSender.go",
        "powerMetricsSender.go",
        "ramMetricsSender.go",
        "stub.go",
        "swapMetricsSender.go",
        "temperatureMetricsSender.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/pkg/collector/corechecks/nvidia/jetson",
    visibility = ["//visibility:public"],
    deps = select({
        "@rules_go//go/platform:aix": [
            "//pkg/collector/check",
            "//pkg/util/option",
        ],
        "@rules_go//go/platform:android": [
            "//comp/core/autodiscovery/integration",
            "//pkg/aggregator/sender",
            "//pkg/collector/check",
            "//pkg/collector/corechecks",
            "//pkg/metrics",
            "//pkg/util/log",
            "//pkg/util/option",
            "@in_yaml_go_yaml_v3//:yaml",
        ],
        "@rules_go//go/platform:darwin": [
            "//pkg/collector/check",
            "//pkg/util/option",
        ],
        "@rules_go//go/platform:dragonfly": [
            "//pkg/collector/check",
            "//pkg/util/option",
        ],
        "@rules_go//go/platform:freebsd": [
            "//pkg/collector/check",
            "//pkg/util/option",
        ],
        "@rules_go//go/platform:illumos": [
            "//pkg/collector/check",
            "//pkg/util/option",
        ],
        "@rules_go//go/platform:ios": [
            "//pkg/collector/check",
            "//pkg/util/option",
        ],
        "@rules_go//go/platform:js": [
            "//pkg/collector/check",
            "//pkg/util/option",
        ],
        "@rules_go//go/platform:linux": [
            "//comp/core/autodiscovery/integration",
            "//pkg/aggregator/sender",
            "//pkg/collector/check",
            "//pkg/collector/corechecks",
            "//pkg/metrics",
            "//pkg/util/log",
            "//pkg/util/option",
            "@in_yaml_go_yaml_v3//:yaml",
        ],
        "@rules_go//go/platform:netbsd": [
            "//pkg/collector/check",
            "//pkg/util/option",
        ],
        "@rules_go//go/platform:openbsd": [
            "//pkg/collector/check",
            "//pkg/util/option",
        ],
        "@rules_go//go/platform:osx": [
            "//pkg/collector/check",
            "//pkg/util/option",
        ],
        "@rules_go//go/platform:plan9": [
            "//pkg/collector/check",
            "//pkg/util/option",
        ],
        "@rules_go//go/platform:qnx": [
            "//pkg/collector/check",
            "//pkg/util/option",
        ],
        "@rules_go//go/platform:solaris": [
            "//pkg/collector/check",
            "//pkg/util/option",
        ],
        "@rules_go//go/platform:windows": [
            "//pkg/collector/check",
            "//pkg/util/option",
        ],
        "//conditions:default": [],
    }),
)

dd_agent_go_test(
    name = "jetson_test",
    srcs = ["jetson_test.go"],
    embed = [":jetson"],
    gotags_sets = [["jetson"]],
    include_default = False,
    deps = select({
        "@rules_go//go/platform:android": [
            "//comp/core/autodiscovery/integration",
            "//pkg/aggregator/mocksender",
            "@com_github_stretchr_testify//assert",
            "@com_github_stretchr_testify//require",
        ],
        "@rules_go//go/platform:linux": [
            "//comp/core/autodiscovery/integration",
            "//pkg/aggregator/mocksender",
            "@com_github_stretchr_testify//assert",
            "@com_github_stretchr_testify//require",
        ],
        "//conditions:default": [],
    }),
)
