load("@rules_go//go:def.bzl", "go_library")

package(default_package_metadata = ["//pkg/util/testutil:go_package_metadata"])

go_library(
    name = "docker",
    srcs = [
        "config.go",
        "get.go",
        "run.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/pkg/util/testutil/docker",
    tags = ["test"],
    visibility = ["//visibility:public"],
    deps = ["//pkg/util/testutil"],
)
