load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

go_library(
    name = "jmxfetch",
    srcs = [
        "jmxfetch.go",
        "jmxfetch_nix.go",
        "jmxfetch_windows.go",
        "limiter.go",
        "runner.go",
        "scheduler.go",
        "state.go",
        "stub.go",
        "utils.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/pkg/jmxfetch",
    visibility = ["//visibility:public"],
    deps = select({
        "@rules_go//go/platform:aix": [
            "//comp/agent/jmxlogger/def",
            "//comp/core/autodiscovery/def",
            "//comp/core/autodiscovery/integration",
            "//comp/core/ipc/def",
            "//comp/dogstatsd/server/def",
        ],
        "@rules_go//go/platform:android": [
            "//comp/agent/jmxlogger/def",
            "//comp/core/autodiscovery/def",
            "//comp/core/autodiscovery/integration",
            "//comp/core/ipc/def",
            "//comp/core/workloadfilter/def",
            "//comp/dogstatsd/config",
            "//comp/dogstatsd/server/def",
            "//pkg/collector/check",
            "//pkg/config/helper",
            "//pkg/config/setup",
            "//pkg/config/utils",
            "//pkg/status/health",
            "//pkg/status/jmx",
            "//pkg/util/cache",
            "//pkg/util/defaultpaths",
            "//pkg/util/log",
            "//pkg/util/net",
            "@in_yaml_go_yaml_v3//:yaml",
        ],
        "@rules_go//go/platform:darwin": [
            "//comp/agent/jmxlogger/def",
            "//comp/core/autodiscovery/def",
            "//comp/core/autodiscovery/integration",
            "//comp/core/ipc/def",
            "//comp/core/workloadfilter/def",
            "//comp/dogstatsd/config",
            "//comp/dogstatsd/server/def",
            "//pkg/collector/check",
            "//pkg/config/helper",
            "//pkg/config/setup",
            "//pkg/config/utils",
            "//pkg/status/health",
            "//pkg/status/jmx",
            "//pkg/util/cache",
            "//pkg/util/defaultpaths",
            "//pkg/util/log",
            "//pkg/util/net",
            "@in_yaml_go_yaml_v3//:yaml",
        ],
        "@rules_go//go/platform:dragonfly": [
            "//comp/agent/jmxlogger/def",
            "//comp/core/autodiscovery/def",
            "//comp/core/autodiscovery/integration",
            "//comp/core/ipc/def",
            "//comp/core/workloadfilter/def",
            "//comp/dogstatsd/config",
            "//comp/dogstatsd/server/def",
            "//pkg/collector/check",
            "//pkg/config/helper",
            "//pkg/config/setup",
            "//pkg/config/utils",
            "//pkg/status/health",
            "//pkg/status/jmx",
            "//pkg/util/cache",
            "//pkg/util/defaultpaths",
            "//pkg/util/log",
            "//pkg/util/net",
            "@in_yaml_go_yaml_v3//:yaml",
        ],
        "@rules_go//go/platform:freebsd": [
            "//comp/agent/jmxlogger/def",
            "//comp/core/autodiscovery/def",
            "//comp/core/autodiscovery/integration",
            "//comp/core/ipc/def",
            "//comp/core/workloadfilter/def",
            "//comp/dogstatsd/config",
            "//comp/dogstatsd/server/def",
            "//pkg/collector/check",
            "//pkg/config/helper",
            "//pkg/config/setup",
            "//pkg/config/utils",
            "//pkg/status/health",
            "//pkg/status/jmx",
            "//pkg/util/cache",
            "//pkg/util/defaultpaths",
            "//pkg/util/log",
            "//pkg/util/net",
            "@in_yaml_go_yaml_v3//:yaml",
        ],
        "@rules_go//go/platform:illumos": [
            "//comp/agent/jmxlogger/def",
            "//comp/core/autodiscovery/def",
            "//comp/core/autodiscovery/integration",
            "//comp/core/ipc/def",
            "//comp/core/workloadfilter/def",
            "//comp/dogstatsd/config",
            "//comp/dogstatsd/server/def",
            "//pkg/collector/check",
            "//pkg/config/helper",
            "//pkg/config/setup",
            "//pkg/config/utils",
            "//pkg/status/health",
            "//pkg/status/jmx",
            "//pkg/util/cache",
            "//pkg/util/defaultpaths",
            "//pkg/util/log",
            "//pkg/util/net",
            "@in_yaml_go_yaml_v3//:yaml",
        ],
        "@rules_go//go/platform:ios": [
            "//comp/agent/jmxlogger/def",
            "//comp/core/autodiscovery/def",
            "//comp/core/autodiscovery/integration",
            "//comp/core/ipc/def",
            "//comp/core/workloadfilter/def",
            "//comp/dogstatsd/config",
            "//comp/dogstatsd/server/def",
            "//pkg/collector/check",
            "//pkg/config/helper",
            "//pkg/config/setup",
            "//pkg/config/utils",
            "//pkg/status/health",
            "//pkg/status/jmx",
            "//pkg/util/cache",
            "//pkg/util/defaultpaths",
            "//pkg/util/log",
            "//pkg/util/net",
            "@in_yaml_go_yaml_v3//:yaml",
        ],
        "@rules_go//go/platform:js": [
            "//comp/agent/jmxlogger/def",
            "//comp/core/autodiscovery/def",
            "//comp/core/autodiscovery/integration",
            "//comp/core/ipc/def",
            "//comp/core/workloadfilter/def",
            "//comp/dogstatsd/config",
            "//comp/dogstatsd/server/def",
            "//pkg/collector/check",
            "//pkg/config/helper",
            "//pkg/config/setup",
            "//pkg/config/utils",
            "//pkg/status/health",
            "//pkg/status/jmx",
            "//pkg/util/cache",
            "//pkg/util/defaultpaths",
            "//pkg/util/log",
            "//pkg/util/net",
            "@in_yaml_go_yaml_v3//:yaml",
        ],
        "@rules_go//go/platform:linux": [
            "//comp/agent/jmxlogger/def",
            "//comp/core/autodiscovery/def",
            "//comp/core/autodiscovery/integration",
            "//comp/core/ipc/def",
            "//comp/core/workloadfilter/def",
            "//comp/dogstatsd/config",
            "//comp/dogstatsd/server/def",
            "//pkg/collector/check",
            "//pkg/config/helper",
            "//pkg/config/setup",
            "//pkg/config/utils",
            "//pkg/status/health",
            "//pkg/status/jmx",
            "//pkg/util/cache",
            "//pkg/util/defaultpaths",
            "//pkg/util/log",
            "//pkg/util/net",
            "@in_yaml_go_yaml_v3//:yaml",
        ],
        "@rules_go//go/platform:netbsd": [
            "//comp/agent/jmxlogger/def",
            "//comp/core/autodiscovery/def",
            "//comp/core/autodiscovery/integration",
            "//comp/core/ipc/def",
            "//comp/core/workloadfilter/def",
            "//comp/dogstatsd/config",
            "//comp/dogstatsd/server/def",
            "//pkg/collector/check",
            "//pkg/config/helper",
            "//pkg/config/setup",
            "//pkg/config/utils",
            "//pkg/status/health",
            "//pkg/status/jmx",
            "//pkg/util/cache",
            "//pkg/util/defaultpaths",
            "//pkg/util/log",
            "//pkg/util/net",
            "@in_yaml_go_yaml_v3//:yaml",
        ],
        "@rules_go//go/platform:openbsd": [
            "//comp/agent/jmxlogger/def",
            "//comp/core/autodiscovery/def",
            "//comp/core/autodiscovery/integration",
            "//comp/core/ipc/def",
            "//comp/core/workloadfilter/def",
            "//comp/dogstatsd/config",
            "//comp/dogstatsd/server/def",
            "//pkg/collector/check",
            "//pkg/config/helper",
            "//pkg/config/setup",
            "//pkg/config/utils",
            "//pkg/status/health",
            "//pkg/status/jmx",
            "//pkg/util/cache",
            "//pkg/util/defaultpaths",
            "//pkg/util/log",
            "//pkg/util/net",
            "@in_yaml_go_yaml_v3//:yaml",
        ],
        "@rules_go//go/platform:osx": [
            "//comp/agent/jmxlogger/def",
            "//comp/core/autodiscovery/def",
            "//comp/core/autodiscovery/integration",
            "//comp/core/ipc/def",
            "//comp/core/workloadfilter/def",
            "//comp/dogstatsd/config",
            "//comp/dogstatsd/server/def",
            "//pkg/collector/check",
            "//pkg/config/helper",
            "//pkg/config/setup",
            "//pkg/config/utils",
            "//pkg/status/health",
            "//pkg/status/jmx",
            "//pkg/util/cache",
            "//pkg/util/defaultpaths",
            "//pkg/util/log",
            "//pkg/util/net",
            "@in_yaml_go_yaml_v3//:yaml",
        ],
        "@rules_go//go/platform:plan9": [
            "//comp/agent/jmxlogger/def",
            "//comp/core/autodiscovery/def",
            "//comp/core/autodiscovery/integration",
            "//comp/core/ipc/def",
            "//comp/core/workloadfilter/def",
            "//comp/dogstatsd/config",
            "//comp/dogstatsd/server/def",
            "//pkg/collector/check",
            "//pkg/config/helper",
            "//pkg/config/setup",
            "//pkg/config/utils",
            "//pkg/status/health",
            "//pkg/status/jmx",
            "//pkg/util/cache",
            "//pkg/util/defaultpaths",
            "//pkg/util/log",
            "//pkg/util/net",
            "@in_yaml_go_yaml_v3//:yaml",
        ],
        "@rules_go//go/platform:qnx": [
            "//comp/agent/jmxlogger/def",
            "//comp/core/autodiscovery/def",
            "//comp/core/autodiscovery/integration",
            "//comp/core/ipc/def",
            "//comp/core/workloadfilter/def",
            "//comp/dogstatsd/config",
            "//comp/dogstatsd/server/def",
            "//pkg/collector/check",
            "//pkg/config/helper",
            "//pkg/config/setup",
            "//pkg/config/utils",
            "//pkg/status/health",
            "//pkg/status/jmx",
            "//pkg/util/cache",
            "//pkg/util/defaultpaths",
            "//pkg/util/log",
            "//pkg/util/net",
            "@in_yaml_go_yaml_v3//:yaml",
        ],
        "@rules_go//go/platform:solaris": [
            "//comp/agent/jmxlogger/def",
            "//comp/core/autodiscovery/def",
            "//comp/core/autodiscovery/integration",
            "//comp/core/ipc/def",
            "//comp/core/workloadfilter/def",
            "//comp/dogstatsd/config",
            "//comp/dogstatsd/server/def",
            "//pkg/collector/check",
            "//pkg/config/helper",
            "//pkg/config/setup",
            "//pkg/config/utils",
            "//pkg/status/health",
            "//pkg/status/jmx",
            "//pkg/util/cache",
            "//pkg/util/defaultpaths",
            "//pkg/util/log",
            "//pkg/util/net",
            "@in_yaml_go_yaml_v3//:yaml",
        ],
        "@rules_go//go/platform:windows": [
            "//comp/agent/jmxlogger/def",
            "//comp/core/autodiscovery/def",
            "//comp/core/autodiscovery/integration",
            "//comp/core/ipc/def",
            "//comp/core/workloadfilter/def",
            "//comp/dogstatsd/config",
            "//comp/dogstatsd/server/def",
            "//pkg/collector/check",
            "//pkg/config/helper",
            "//pkg/config/setup",
            "//pkg/config/utils",
            "//pkg/status/health",
            "//pkg/status/jmx",
            "//pkg/util/cache",
            "//pkg/util/defaultpaths",
            "//pkg/util/log",
            "//pkg/util/net",
            "@in_yaml_go_yaml_v3//:yaml",
        ],
        "//conditions:default": [],
    }),
)

dd_agent_go_test(
    name = "jmxfetch_test",
    srcs = [
        "jmxfetch_nix_test.go",
        "jmxfetch_test.go",
        "limiter_test.go",
        "runner_test.go",
        "utils_test.go",
    ],
    data = glob(["testdata/**"]),
    embed = [":jmxfetch"],
    gotags_sets = [["main_agent"]],
    deps = [
        "@com_github_stretchr_testify//require",
    ] + select({
        "@rules_go//go/platform:android": [
            "//comp/core/autodiscovery/integration",
            "//pkg/config/mock",
            "@com_github_stretchr_testify//assert",
            "@in_yaml_go_yaml_v3//:yaml",
        ],
        "@rules_go//go/platform:darwin": [
            "//comp/core/autodiscovery/integration",
            "//pkg/config/mock",
            "@com_github_stretchr_testify//assert",
            "@in_yaml_go_yaml_v3//:yaml",
        ],
        "@rules_go//go/platform:dragonfly": [
            "//comp/core/autodiscovery/integration",
            "//pkg/config/mock",
            "@com_github_stretchr_testify//assert",
            "@in_yaml_go_yaml_v3//:yaml",
        ],
        "@rules_go//go/platform:freebsd": [
            "//comp/core/autodiscovery/integration",
            "//pkg/config/mock",
            "@com_github_stretchr_testify//assert",
            "@in_yaml_go_yaml_v3//:yaml",
        ],
        "@rules_go//go/platform:illumos": [
            "//comp/core/autodiscovery/integration",
            "//pkg/config/mock",
            "@com_github_stretchr_testify//assert",
            "@in_yaml_go_yaml_v3//:yaml",
        ],
        "@rules_go//go/platform:ios": [
            "//comp/core/autodiscovery/integration",
            "//pkg/config/mock",
            "@com_github_stretchr_testify//assert",
            "@in_yaml_go_yaml_v3//:yaml",
        ],
        "@rules_go//go/platform:js": [
            "//comp/core/autodiscovery/integration",
            "//pkg/config/mock",
            "@com_github_stretchr_testify//assert",
            "@in_yaml_go_yaml_v3//:yaml",
        ],
        "@rules_go//go/platform:linux": [
            "//comp/core/autodiscovery/integration",
            "//pkg/config/mock",
            "@com_github_stretchr_testify//assert",
            "@in_yaml_go_yaml_v3//:yaml",
        ],
        "@rules_go//go/platform:netbsd": [
            "//comp/core/autodiscovery/integration",
            "//pkg/config/mock",
            "@com_github_stretchr_testify//assert",
            "@in_yaml_go_yaml_v3//:yaml",
        ],
        "@rules_go//go/platform:openbsd": [
            "//comp/core/autodiscovery/integration",
            "//pkg/config/mock",
            "@com_github_stretchr_testify//assert",
            "@in_yaml_go_yaml_v3//:yaml",
        ],
        "@rules_go//go/platform:osx": [
            "//comp/core/autodiscovery/integration",
            "//pkg/config/mock",
            "@com_github_stretchr_testify//assert",
            "@in_yaml_go_yaml_v3//:yaml",
        ],
        "@rules_go//go/platform:plan9": [
            "//comp/core/autodiscovery/integration",
            "//pkg/config/mock",
            "@com_github_stretchr_testify//assert",
            "@in_yaml_go_yaml_v3//:yaml",
        ],
        "@rules_go//go/platform:qnx": [
            "//comp/core/autodiscovery/integration",
            "//pkg/config/mock",
            "@com_github_stretchr_testify//assert",
            "@in_yaml_go_yaml_v3//:yaml",
        ],
        "@rules_go//go/platform:solaris": [
            "//comp/core/autodiscovery/integration",
            "//pkg/config/mock",
            "@com_github_stretchr_testify//assert",
            "@in_yaml_go_yaml_v3//:yaml",
        ],
        "@rules_go//go/platform:windows": [
            "//comp/core/autodiscovery/integration",
            "//pkg/config/mock",
            "@com_github_stretchr_testify//assert",
            "@in_yaml_go_yaml_v3//:yaml",
        ],
        "//conditions:default": [],
    }),
)
