load("@rules_go//go:def.bzl", "go_binary", "go_library")
load("//bazel/rules/go_package_metadata:defs.bzl", "go_package_metadata")

package(default_package_metadata = [":go_package_metadata"])

go_package_metadata(
    name = "go_package_metadata",
    module = "github.com/DataDog/datadog-agent/internal/tools/gotest-custom",
)

go_library(
    name = "gotest-custom_lib",
    srcs = ["main.go"],
    importpath = "github.com/DataDog/datadog-agent/internal/tools/gotest-custom",
    visibility = ["//visibility:private"],
    deps = ["@com_github_google_shlex//:shlex"],
)

go_binary(
    name = "gotest-custom",
    embed = [":gotest-custom_lib"],
    visibility = ["//:__subpackages__"],
)
