# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 1.8.4"

Vagrant.configure("2") do |config|

  config.vm.communicator = "winrm"

  config.vm.synced_folder ".", "/vagrant", disabled: true
  gopath = ENV['GOPATH'].gsub('\\', '/')
  config.vm.synced_folder gopath + "/src/github.com/DataDog", "/Users/dogdev/go/src/github.com/DataDog"

  config.vm.define "win-10-prl", autostart: false  do |cfg|
    cfg.vm.box     = "windows_10_ent_parallels.box"
  end
  config.vm.define "win-10-vmw", autostart: false  do |cfg|
    cfg.vm.box     = "windows_10_ent_vmware.box"
  end
  config.vm.define "win-10-vbx", autostart: false  do |cfg|
    cfg.vm.box     = "windows_10_ent_virtualbox.box"
  end
  config.vm.define "win-srv-prl", autostart: false do |cfg|
    cfg.vm.box     = "windows_2019_core_parallels.box"
  end
  config.vm.define "win-srv-vmw", autostart: false do |cfg|
    cfg.vm.box     = "windows_2019_core_vmware.box"
  end
  config.vm.define "win-srv-vbx", autostart: false do |cfg|
    cfg.vm.box     = "windows_2019_core_virtualbox.box"
  end
end
