load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

dd_agent_go_test(
    name = "ddi_test",
    srcs = ["ddi_test.go"],
    embedsrcs = ["fixtures/helm-values.yaml"],
    importpath = "github.com/DataDog/datadog-agent/test/new-e2e/tests/ddi",
    tags = ["manual"],
    deps = [
        "//test/e2e-framework/common/config",
        "//test/e2e-framework/common/utils",
        "//test/e2e-framework/components/datadog/apps/nginx",
        "//test/e2e-framework/components/datadog/kubernetesagentparams",
        "//test/e2e-framework/components/kubernetes",
        "//test/e2e-framework/scenarios/aws/kindvm",
        "//test/e2e-framework/testing/e2e",
        "//test/e2e-framework/testing/environments",
        "//test/e2e-framework/testing/provisioners/aws/kubernetes/kindvm",
        "//test/fakeintake/aggregator",
        "//test/fakeintake/client",
        "@com_github_datadog_datadog_operator_api//datadoghq/v1alpha1",
        "@com_github_pulumi_pulumi_kubernetes_sdk_v4//go/kubernetes",
        "@com_github_pulumi_pulumi_kubernetes_sdk_v4//go/kubernetes/yaml",
        "@com_github_pulumi_pulumi_sdk_v3//go/pulumi",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
        "@io_k8s_api//autoscaling/v2:autoscaling",
        "@io_k8s_apimachinery//pkg/apis/meta/v1:meta",
        "@io_k8s_apimachinery//pkg/apis/meta/v1/unstructured",
        "@io_k8s_apimachinery//pkg/runtime",
        "@io_k8s_apimachinery//pkg/runtime/schema",
        "@io_k8s_client_go//dynamic",
    ],
)
