load("@rules_go//go:def.bzl", "go_test")

go_test(
    name = "otel-agent_test",
    srcs = [
        "complete_test.go",
        "dogtel_secrets_test.go",
        "dogtel_standalone_test.go",
        "gateway_test.go",
        "head_based_sampling_test.go",
        "host_metrics_receiver_test.go",
        "infraattributes_eks_test.go",
        "infraattributes_test.go",
        "loadbalancing_test.go",
        "logs_tags_as_ddtags_test.go",
        "minimal_test.go",
        "no_dd_exporter_test.go",
        "receive_resource_spans_v2_test.go",
        "sampling_test.go",
    ],
    data = [
        "config/complete.yml",
        "config/dogtel-secrets.yml",
        "config/dogtel-standalone.yml",
        "config/gateway.yml",
        "config/hostmetricsreceiver.yml",
        "config/ia.yml",
        "config/loadbalancing.yml",
        "config/logs_tags_as_ddtags.yml",
        "config/minimal.yml",
        "config/no-dd-exporter.yml",
        "config/sampling.yml",
        "config/sampling-head-based.yml",
        "testdata/minimal-full-config.yml",
        "testdata/minimal-full-config-datadogextension.yml",
        "testdata/minimal-provided-config.yml",
        "testdata/no-dd-exporter-full-config.yml",
        "testdata/no-dd-exporter-provided-config.yml",
        "testdata/sources.json",
    ],
    embedsrcs = [
        "config/complete.yml",
        "config/dogtel-secrets.yml",
        "config/dogtel-standalone.yml",
        "config/gateway.yml",
        "config/hostmetricsreceiver.yml",
        "config/ia.yml",
        "config/loadbalancing.yml",
        "config/logs_tags_as_ddtags.yml",
        "config/minimal.yml",
        "config/no-dd-exporter.yml",
        "config/sampling-head-based.yml",
        "config/sampling.yml",
        "testdata/minimal-full-config-datadogextension.yml",
        "testdata/minimal-full-config.yml",
        "testdata/minimal-provided-config.yml",
        "testdata/no-dd-exporter-full-config.yml",
        "testdata/no-dd-exporter-provided-config.yml",
        "testdata/sources.json",
    ],
    gotags = ["test"],
    deps = [
        "//comp/core/tagger/types",
        "//test/e2e-framework/common/config",
        "//test/e2e-framework/components/datadog/agent",
        "//test/e2e-framework/components/datadog/fakeintake",
        "//test/e2e-framework/components/datadog/kubernetesagentparams",
        "//test/e2e-framework/components/datadog/otel-standalone",
        "//test/e2e-framework/scenarios/aws/eks",
        "//test/e2e-framework/scenarios/aws/kindvm",
        "//test/e2e-framework/testing/e2e",
        "//test/e2e-framework/testing/environments",
        "//test/e2e-framework/testing/provisioners",
        "//test/e2e-framework/testing/provisioners/aws/kubernetes/eks",
        "//test/e2e-framework/testing/provisioners/aws/kubernetes/kindvm",
        "//test/e2e-framework/testing/provisioners/local/kubernetes",
        "//test/e2e-framework/testing/runner",
        "//test/e2e-framework/testing/runner/parameters",
        "//test/new-e2e/tests/otel/utils",
        "@com_github_pulumi_pulumi_kubernetes_sdk_v4//go/kubernetes",
        "@com_github_pulumi_pulumi_kubernetes_sdk_v4//go/kubernetes/core/v1:core",
        "@com_github_pulumi_pulumi_sdk_v3//go/pulumi",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
        "@io_k8s_api//core/v1:core",
        "@io_k8s_apimachinery//pkg/apis/meta/v1:meta",
        "@io_k8s_apimachinery//pkg/fields",
    ],
)
