load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "tombstone",
    srcs = ["tombstone.go"],
    importpath = "github.com/DataDog/datadog-agent/pkg/dyninst/module/tombstone",
    tags = ["manual"],
    visibility = ["//visibility:public"],
    deps = select({
        "@rules_go//go/platform:android": [
            "//pkg/dyninst/module/statedir",
            "//pkg/util/backoff",
            "//pkg/util/log",
            "//pkg/version",
        ],
        "@rules_go//go/platform:linux": [
            "//pkg/dyninst/module/statedir",
            "//pkg/util/backoff",
            "//pkg/util/log",
            "//pkg/version",
        ],
        "//conditions:default": [],
    }),
)
