load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go_package_metadata:defs.bzl", "go_package_metadata")

package(default_package_metadata = [":go_package_metadata"])

go_package_metadata(
    name = "go_package_metadata",
    module = "github.com/DataDog/datadog-agent/test/otel",
)

go_library(
    name = "otel",
    srcs = ["dependencies.go"],
    importpath = "github.com/DataDog/datadog-agent/test/otel",
    visibility = ["//visibility:public"],
    deps = [
        "//comp/core/config",
        "//comp/core/hostname/hostnameinterface/def",
        "//comp/core/log/def",
        "//comp/otelcol/logsagentpipeline/def",
        "//comp/otelcol/logsagentpipeline/impl",
        "//comp/otelcol/otlp/components/datadogconfig",
        "//comp/otelcol/otlp/components/exporter/logsagentexporter",
        "//comp/otelcol/otlp/components/metricsclient",
        "//pkg/config/model",
        "//pkg/config/setup/constants",
        "//pkg/proto/pbgo/trace",
        "//pkg/trace/api",
        "//pkg/util/compression/impl-noop",
    ],
)
