load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

# gazelle:go_canonical_test_tag_set anomalydetection_recorder

go_library(
    name = "impl",
    srcs = [
        "config.go",
        "configured_component.go",
        "recorder.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/comp/anomalydetection/recorder/impl",
    tags = ["manual"],
    visibility = ["//visibility:public"],
    deps = [
        "//comp/anomalydetection/observer/def",
        "//comp/anomalydetection/recorder/def",
        "//comp/core/config",
        "//comp/def",
        "//pkg/util/option",
    ],
)

dd_agent_go_test(
    name = "impl_test",
    srcs = [
        "component_test.go",
        "recorder_test.go",
    ],
    embed = [":impl"],
    gotags_sets = [["anomalydetection_recorder"]],
    include_default = False,
    tags = ["manual"],
    deps = [
        "//comp/anomalydetection/observer/def",
        "//comp/anomalydetection/recorder/def",
        "//comp/core/config",
        "//comp/def",
        "//pkg/tagset",
        "//pkg/metrics",
        "//pkg/util/option",
        "@com_github_stretchr_testify//require",
    ],
)
