load("@rules_go//go:def.bzl", "go_test")

exports_files([
    "fixtures/secrets.json",
    "fixtures/secrets.yaml",
    "fixtures/secrets_merged.yaml",
])

go_test(
    name = "sgc-embedded_test",
    srcs = ["sgc_multi_backend_nix_test.go"],
    data = [
        "fixtures/secrets.json",
        "fixtures/secrets.yaml",
        "fixtures/secrets_merged.yaml",
    ],
    embedsrcs = [
        "fixtures/secrets.json",
        "fixtures/secrets.yaml",
        "fixtures/secrets_merged.yaml",
    ],
    gotags = ["test"],
    deps = [
        "//test/e2e-framework/components/datadog/agentparams",
        "//test/e2e-framework/components/datadog/agentparams/filepermissions",
        "//test/e2e-framework/scenarios/aws/ec2",
        "//test/e2e-framework/testing/e2e",
        "//test/e2e-framework/testing/environments",
        "//test/e2e-framework/testing/provisioners/aws/host",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
