SECURITY_START_LOG = "Successfully connected to the runtime security module"
SYS_PROBE_START_LOG = "runtime security started"
SEC_AGENT_PATH = "/opt/datadog-agent/embedded/bin/security-agent"

CSPM_START_LOG = "Loading compliance rules from"
CSPM_RUNNING_DOCKER_CHECK_LOG = "Running check: cis-docker-1.2.0-5.4"
CSPM_K8S_WORKER_RULE = "cis-kubernetes-1.5.1-4.2.6"
CSPM_K8S_MASTER_RULE = "cis-kubernetes-1.5.1-3.2.1"
CSPM_RUNNING_K8S_WORKER_CHECK_LOG = f"Running check: {CSPM_K8S_WORKER_RULE}"
CSPM_RUNNING_K8S_MASTER_CHECK_LOG = f"Running check: {CSPM_K8S_MASTER_RULE}"
