load("@rules_pkg//pkg:install.bzl", "pkg_install")
load("@rules_pkg//pkg:mappings.bzl", "pkg_attributes", "pkg_files")
load(":test_binaries.bzl", "TEST_BINARIES")

pkg_files(
    name = "test_binaries",
    testonly = True,
    srcs = TEST_BINARIES.keys(),
    attributes = pkg_attributes(mode = "0755"),
    renames = TEST_BINARIES,
    #TODO(regis): turn below guard into a transition with `--@rules_go//go/toolchain:sdk_name=go_civisibility_sdk`
    target_compatible_with = select({
        "@go_civisibility_sdk//:match_sdk_name": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
)

pkg_install(
    name = "install_test_binaries",
    testonly = True,
    srcs = [":test_binaries"],
)
