load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go_package_metadata:defs.bzl", "go_package_metadata")

package(default_package_metadata = [":go_package_metadata"])

go_package_metadata(
    name = "go_package_metadata",
    module = "github.com/DataDog/datadog-agent/pkg/config/model",
)

go_library(
    name = "model",
    srcs = [
        "config_overrides.go",
        "config_overrides_test_helpers.go",
        "doc.go",
        "stringify.go",
        "types.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/pkg/config/model",
    visibility = ["//visibility:public"],
)
