load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "productcomposition",
    srcs = [
        "composition.go",
        "python.go",  # //go:build python
        "python_disabled.go",  # //go:build !python
    ],
    importpath = "github.com/DataDog/datadog-agent/cmd/agent/internal/productcomposition",
    visibility = ["//cmd/agent:__pkg__"],
    deps = [
        "//cmd/agent/command",
        "//comp/collector/pythonruntime/fx-python",
        "//comp/core/autodiscovery/discoverer/fx-python",
        "//comp/core/gui/impl/pythonchecks/fx-python",
        "//comp/core/status",
        "//comp/metadata/host/impl/pythoninfo/fx-python",
        "//pkg/collector/python",
        "@org_uber_go_fx//:fx",
    ],
)
