load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "environments",
    srcs = [
        "coverage.go",
        "dockerhost.go",
        "ecs.go",
        "environments.go",
        "host.go",
        "kubernetes.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/test/e2e-framework/testing/environments",
    visibility = ["//visibility:public"],
    deps = [
        "//test/e2e-framework/components/os/types",
        "//test/e2e-framework/components/outputs",
        "//test/e2e-framework/scenarios/outputs",
        "//test/e2e-framework/testing/components",
        "//test/e2e-framework/testing/provisioner",
        "//test/e2e-framework/testing/utils/common",
        "//test/e2e-framework/testing/utils/e2e/client",
        "//test/e2e-framework/testing/utils/e2e/client/agentclient",
        "//test/e2e-framework/testing/utils/e2e/client/agentclientparams",
        "@io_k8s_api//core/v1:core",
        "@io_k8s_apimachinery//pkg/apis/meta/v1:meta",
        "@io_k8s_apimachinery//pkg/fields",
    ],
)
