load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

go_library(
    name = "credentials",
    srcs = ["credentials.go"],
    importpath = "github.com/DataDog/datadog-agent/comp/core/autodiscovery/providers/ndm/credentials",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/config/model",
        "//pkg/config/structure",
        "//pkg/snmp/gosnmplib",
    ],
)

dd_agent_go_test(
    name = "credentials_test",
    srcs = ["credentials_test.go"],
    embed = [":credentials"],
    deps = [
        "//pkg/config/mock",
        "//pkg/config/model",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
