load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

go_library(
    name = "loclist",
    srcs = [
        "fix.go",
        "locations.go",
        "parse.go",
        "reader.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/pkg/dyninst/dwarf/loclist",
    tags = ["manual"],
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/dyninst/dwarf/dwarfutil",
        "//pkg/dyninst/ir",
    ],
)

dd_agent_go_test(
    name = "loclist_test",
    srcs = [
        "fuzz_test.go",
        "parse_test.go",
    ],
    embed = [":loclist"],
    gotags_sets = [["linux_bpf"]],
    include_default = False,
)
