load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

go_library(
    name = "remote",
    srcs = ["generic.go"],
    importpath = "github.com/DataDog/datadog-agent/comp/core/workloadmeta/collectors/internal/remote",
    visibility = ["//comp/core/workloadmeta/collectors:__subpackages__"],
    deps = [
        "//comp/core/ipc/def",
        "//comp/core/workloadmeta/def",
        "//comp/core/workloadmeta/telemetry",
        "//pkg/config/model",
        "//pkg/util/grpc",
        "//pkg/util/log",
        "//pkg/util/system/socket",
        "@com_github_cenkalti_backoff_v7//:backoff",
        "@com_github_mdlayher_vsock//:vsock",
        "@org_golang_google_grpc//:grpc",
        "@org_golang_google_grpc//credentials",
        "@org_golang_google_grpc//metadata",
    ],
)

dd_agent_go_test(
    name = "remote_test",
    srcs = ["generic_test.go"],
    embed = [":remote"],
    deps = [
        "//comp/core/ipc/mock",
        "//comp/core/workloadmeta/def",
        "//pkg/config/mock",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
        "@org_golang_google_grpc//:grpc",
        "@org_golang_google_grpc//codes",
        "@org_golang_google_grpc//credentials",
        "@org_golang_google_grpc//status",
    ],
)
