load("@rules_go//go:def.bzl", "go_binary", "go_library")
load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")
load("//bazel/rules/go_package_metadata:defs.bzl", "go_package_metadata")

package(default_package_metadata = [":go_package_metadata"])

go_package_metadata(
    name = "go_package_metadata",
    module = "github.com/DataDog/datadog-agent/internal/tools/worksynchronizer",
)

go_library(
    name = "worksynchronizer_lib",
    srcs = ["worksynchronizer.go"],
    importpath = "github.com/DataDog/datadog-agent/internal/tools/worksynchronizer",
    visibility = ["//visibility:private"],
    deps = [
        "@in_yaml_go_yaml_v3//:yaml",
        "@org_golang_x_mod//modfile",
    ],
)

go_binary(
    name = "worksynchronizer",
    embed = [":worksynchronizer_lib"],
    visibility = ["//:__subpackages__"],
)

dd_agent_go_test(
    name = "worksynchronizer_test",
    srcs = ["worksynchronizer_test.go"],
    data = glob(["testdata/**"]),
    embed = [":worksynchronizer_lib"],
    deps = [
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
