load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "kind",
    srcs = ["config.go"],
    importpath = "github.com/DataDog/datadog-agent/test/e2e-framework/cmd/internal/envconfig/kind",
    visibility = ["//test/e2e-framework/cmd:__subpackages__"],
    deps = ["//test/e2e-framework/cmd/internal/configschema"],
)
