// Unless explicitly stated otherwise all files in this repository are licensed
// under the Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2016-2020 Datadog, Inc.

package obfuscate

// keywords indicates reserved words across SQL dialects. When required, the value
// is their associated TokenKind if needed to be identified by filters.
var keywords = map[string]TokenKind{
	// Keywords which require token identifiers
	"AS":        As,
	"FALSE":     BooleanLiteral,
	"FROM":      From,
	"INSERT":    Insert,
	"INTO":      Into,
	"JOIN":      Join,
	"LIMIT":     Limit,
	"NULL":      Null,
	"SAVEPOINT": Savepoint,
	"TRUE":      BooleanLiteral,
	"UPDATE":    Update,

	// Common SQL Keywords (Shared across 2 or more dialects)
	"ADD":               Keyword,
	"ALL":               Keyword,
	"ALLOCATE":          Keyword,
	"ALTER":             Keyword,
	"ANALYZE":           Keyword,
	"AND":               Keyword,
	"ANY":               Keyword,
	"ARRAY":             Keyword,
	"ASC":               Keyword,
	"AT":                Keyword,
	"AUTHORIZATION":     Keyword,
	"BEFORE":            Keyword,
	"BEGIN":             Keyword,
	"BETWEEN":           Keyword,
	"BINARY":            Keyword,
	"BOTH":              Keyword,
	"BY":                Keyword,
	"CASCADE":           Keyword,
	"CASE":              Keyword,
	"CAST":              Keyword,
	"CHANGE":            Keyword,
	"CHAR":              Keyword,
	"CHARACTER":         Keyword,
	"CHECK":             Keyword,
	"CLOSE":             Keyword,
	"COALESCE":          Keyword,
	"COLLATE":           Keyword,
	"COLUMN":            Keyword,
	"COMMIT":            Keyword,
	"CONNECT":           Keyword,
	"CONSTRAINT":        Keyword,
	"CONSTRAINTS":       Keyword,
	"CONTINUE":          Keyword,
	"CONVERT":           Keyword,
	"CREATE":            Keyword,
	"CROSS":             Keyword,
	"CURRENT":           Keyword,
	"CURRENT_DATE":      Keyword,
	"CURRENT_TIME":      Keyword,
	"CURRENT_TIMESTAMP": Keyword,
	"CURRENT_USER":      Keyword,
	"CURSOR":            Keyword,
	"DATABASE":          Keyword,
	"DATE":              Keyword,
	"DEALLOCATE":        Keyword,
	"DEC":               Keyword,
	"DECIMAL":           Keyword,
	"DECLARE":           Keyword,
	"DEFAULT":           Keyword,
	"DEFERRABLE":        Keyword,
	"DEFERRED":          Keyword,
	"DELETE":            Keyword,
	"DESC":              Keyword,
	"DESCRIBE":          Keyword,
	"DISCONNECT":        Keyword,
	"DISTINCT":          Keyword,
	"DOUBLE":            Keyword,
	"DROP":              Keyword,
	"EACH":              Keyword,
	"ELSE":              Keyword,
	"END":               Keyword,
	"ESCAPE":            Keyword,
	"EXCEPT":            Keyword,
	"EXECUTE":           Keyword,
	"EXISTS":            Keyword,
	"EXPLAIN":           Keyword,
	"FETCH":             Keyword,
	"FLOAT":             Keyword,
	"FOR":               Keyword,
	"FORCE":             Keyword,
	"FOREIGN":           Keyword,
	"FULL":              Keyword,
	"FUNCTION":          Keyword,
	"GET":               Keyword,
	"GLOBAL":            Keyword,
	"GRANT":             Keyword,
	"GROUP":             Keyword,
	"GROUPS":            Keyword,
	"HAVING":            Keyword,
	"IF":                Keyword,
	"IMMEDIATE":         Keyword,
	"IN":                Keyword,
	"INDEX":             Keyword,
	"INDICATOR":         Keyword,
	"INITIALLY":         Keyword,
	"INNER":             Keyword,
	"INSENSITIVE":       Keyword,
	"INT":               Keyword,
	"INTEGER":           Keyword,
	"INTERSECT":         Keyword,
	"INTERVAL":          Keyword,
	"IS":                Keyword,
	"KEY":               Keyword,
	"LEADING":           Keyword,
	"LEFT":              Keyword,
	"LEVEL":             Keyword,
	"LIKE":              Keyword,
	"LOCALTIME":         Keyword,
	"LOCALTIMESTAMP":    Keyword,
	"LONG":              Keyword,
	"MATCH":             Keyword,
	"MAXVALUE":          Keyword,
	"MODIFY":            Keyword,
	"NATIONAL":          Keyword,
	"NATURAL":           Keyword,
	"NEW":               Keyword,
	"NEXT":              Keyword,
	"NONE":              Keyword,
	"NOT":               Keyword,
	"OF":                Keyword,
	"OLD":               Keyword,
	"ON":                Keyword,
	"ONLY":              Keyword,
	"OPEN":              Keyword,
	"OPTION":            Keyword,
	"OR":                Keyword,
	"ORDER":             Keyword,
	"OUTER":             Keyword,
	"OVERLAPS":          Keyword,
	"PARTITION":         Keyword,
	"PASSWORD":          Keyword,
	"PRECISION":         Keyword,
	"PRESERVE":          Keyword,
	"PRIMARY":           Keyword,
	"PRIVILEGES":        Keyword,
	"PROCEDURE":         Keyword,
	"PUBLIC":            Keyword,
	"RANGE":             Keyword,
	"READ":              Keyword,
	"REAL":              Keyword,
	"REFERENCES":        Keyword,
	"RENAME":            Keyword,
	"REVOKE":            Keyword,
	"RIGHT":             Keyword,
	"ROLLBACK":          Keyword,
	"ROWS":              Keyword,
	"SCHEMA":            Keyword,
	"SELECT":            Keyword,
	"SESSION_USER":      Keyword,
	"SET":               Keyword,
	"SMALLINT":          Keyword,
	"SOME":              Keyword,
	"SYSTEM":            Keyword,
	"TABLE":             Keyword,
	"THEN":              Keyword,
	"TIME":              Keyword,
	"TO":                Keyword,
	"TRAILING":          Keyword,
	"TRIGGER":           Keyword,
	"TRUNCATE":          Keyword,
	"UNION":             Keyword,
	"UNIQUE":            Keyword,
	"UNLOCK":            Keyword,
	"USAGE":             Keyword,
	"USE":               Keyword,
	"USER":              Keyword,
	"USING":             Keyword,
	"VALUE":             Keyword,
	"VALUES":            Keyword,
	"VIEW":              Keyword,
	"WHEN":              Keyword,
	"WHERE":             Keyword,
	"WITH":              Keyword,
	"WRITE":             Keyword,
	"YEAR":              Keyword,
	"ZONE":              Keyword,

	// MySQL Keywords (Reserved Only)
	"ACCESSIBLE":                    Keyword,
	"ASENSITIVE":                    Keyword,
	"BIGINT":                        Keyword,
	"BLOB":                          Keyword,
	"CALL":                          Keyword,
	"CONDITION":                     Keyword,
	"CUBE":                          Keyword,
	"CUME_DIST":                     Keyword,
	"DATABASES":                     Keyword,
	"DAY_HOUR":                      Keyword,
	"DAY_MICROSECOND":               Keyword,
	"DAY_MINUTE":                    Keyword,
	"DAY_SECOND":                    Keyword,
	"DELAYED":                       Keyword,
	"DENSE_RANK":                    Keyword,
	"DETERMINISTIC":                 Keyword,
	"DISTINCTROW":                   Keyword,
	"DIV":                           Keyword,
	"DUAL":                          Keyword,
	"ELSEIF":                        Keyword,
	"EMPTY":                         Keyword,
	"ENCLOSED":                      Keyword,
	"ESCAPED":                       Keyword,
	"EXIT":                          Keyword,
	"FIRST_VALUE":                   Keyword,
	"FLOAT4":                        Keyword,
	"FLOAT8":                        Keyword,
	"FULLTEXT":                      Keyword,
	"GENERATED":                     Keyword,
	"GROUPING":                      Keyword,
	"HIGH_PRIORITY":                 Keyword,
	"HOUR_MICROSECOND":              Keyword,
	"HOUR_MINUTE":                   Keyword,
	"HOUR_SECOND":                   Keyword,
	"IGNORE":                        Keyword,
	"INFILE":                        Keyword,
	"INOUT":                         Keyword,
	"INT1":                          Keyword,
	"INT2":                          Keyword,
	"INT3":                          Keyword,
	"INT4":                          Keyword,
	"INT8":                          Keyword,
	"IO_AFTER_GTIDS":                Keyword,
	"IO_BEFORE_GTIDS":               Keyword,
	"ITERATE":                       Keyword,
	"JSON_TABLE":                    Keyword,
	"KEYS":                          Keyword,
	"KILL":                          Keyword,
	"LAG":                           Keyword,
	"LAST_VALUE":                    Keyword,
	"LATERAL":                       Keyword,
	"LEAD":                          Keyword,
	"LEAVE":                         Keyword,
	"LINEAR":                        Keyword,
	"LINES":                         Keyword,
	"LOAD":                          Keyword,
	"LOCK":                          Keyword,
	"LONGBLOB":                      Keyword,
	"LONGTEXT":                      Keyword,
	"LOOP":                          Keyword,
	"LOW_PRIORITY":                  Keyword,
	"MASTER_BIND":                   Keyword,
	"MASTER_SSL_VERIFY_SERVER_CERT": Keyword,
	"MEDIUMBLOB":                    Keyword,
	"MEDIUMINT":                     Keyword,
	"MEDIUMTEXT":                    Keyword,
	"MIDDLEINT":                     Keyword,
	"MINUTE_MICROSECOND":            Keyword,
	"MINUTE_SECOND":                 Keyword,
	"MOD":                           Keyword,
	"MODIFIES":                      Keyword,
	"NO_WRITE_TO_BINLOG":            Keyword,
	"NTH_VALUE":                     Keyword,
	"NTILE":                         Keyword,
	"NUMERIC":                       Keyword,
	"OPTIMIZE":                      Keyword,
	"OPTIMIZER_COSTS":               Keyword,
	"OPTIONALLY":                    Keyword,
	"OUT":                           Keyword,
	"OUTFILE":                       Keyword,
	"OVER":                          Keyword,
	"PERCENT_RANK":                  Keyword,
	"PURGE":                         Keyword,
	"RANK":                          Keyword,
	"READS":                         Keyword,
	"READ_WRITE":                    Keyword,
	"RECURSIVE":                     Keyword,
	"REGEXP":                        Keyword,
	"RELEASE":                       Keyword,
	"REPEAT":                        Keyword,
	"REPLACE":                       Keyword,
	"REQUIRE":                       Keyword,
	"RESIGNAL":                      Keyword,
	"RESTRICT":                      Keyword,
	"RETURN":                        Keyword,
	"RLIKE":                         Keyword,
	"ROW":                           Keyword,
	"ROW_NUMBER":                    Keyword,
	"SCHEMAS":                       Keyword,
	"SECOND_MICROSECOND":            Keyword,
	"SENSITIVE":                     Keyword,
	"SEPARATOR":                     Keyword,
	"SHOW":                          Keyword,
	"SIGNAL":                        Keyword,
	"SPATIAL":                       Keyword,
	"SPECIFIC":                      Keyword,
	"SQL":                           Keyword,
	"SQLEXCEPTION":                  Keyword,
	"SQLSTATE":                      Keyword,
	"SQLWARNING":                    Keyword,
	"SQL_BIG_RESULT":                Keyword,
	"SQL_CALC_FOUND_ROWS":           Keyword,
	"SQL_SMALL_RESULT":              Keyword,
	"SSL":                           Keyword,
	"STARTING":                      Keyword,
	"STORED":                        Keyword,
	"STRAIGHT_JOIN":                 Keyword,
	"TERMINATED":                    Keyword,
	"TINYBLOB":                      Keyword,
	"TINYINT":                       Keyword,
	"TINYTEXT":                      Keyword,
	"UNDO":                          Keyword,
	"UNSIGNED":                      Keyword,
	"UTC_DATE":                      Keyword,
	"UTC_TIME":                      Keyword,
	"UTC_TIMESTAMP":                 Keyword,
	"VARBINARY":                     Keyword,
	"VARCHAR":                       Keyword,
	"VARCHARACTER":                  Keyword,
	"VARYING":                       Keyword,
	"VIRTUAL":                       Keyword,
	"WHILE":                         Keyword,
	"WINDOW":                        Keyword,
	"XOR":                           Keyword,
	"YEAR_MONTH":                    Keyword,
	"ZEROFILL":                      Keyword,

	// Postgres Keywords (Reserved Only)
	"ANALYSE":      Keyword,
	"ASYMMETRIC":   Keyword,
	"CURRENT_ROLE": Keyword,
	"DO":           Keyword,
	"FREEZE":       Keyword,
	"ILIKE":        Keyword,
	"ISNULL":       Keyword,
	"NOTNULL":      Keyword,
	"OFF":          Keyword,
	"OFFSET":       Keyword,
	"PLACING":      Keyword,
	"SIMILAR":      Keyword,
	"SYMMETRIC":    Keyword,
	"VERBOSE":      Keyword,

	// SQL Server Keywords (Reserved Only)
	"ABSOLUTE":         Keyword,
	"ACTION":           Keyword,
	"ADA":              Keyword,
	"ARE":              Keyword,
	"ASSERTION":        Keyword,
	"AVG":              Keyword,
	"BIT":              Keyword,
	"BIT_LENGTH":       Keyword,
	"CASCADED":         Keyword,
	"CATALOG":          Keyword,
	"CHAR_LENGTH":      Keyword,
	"CHARACTER_LENGTH": Keyword,
	"COLLATION":        Keyword,
	"CONNECTION":       Keyword,
	"CORRESPONDING":    Keyword,
	"COUNT":            Keyword,
	"DAY":              Keyword,
	"DESCRIPTOR":       Keyword,
	"DIAGNOSTICS":      Keyword,
	"DOMAIN":           Keyword,
	"END-EXEC":         Keyword,
	"EXCEPTION":        Keyword,
	"EXEC":             Keyword,
	"EXTERNAL":         Keyword,
	"EXTRACT":          Keyword,
	"FIRST":            Keyword,
	"FORTRAN":          Keyword,
	"FOUND":            Keyword,
	"GO":               Keyword,
	"GOTO":             Keyword,
	"HOUR":             Keyword,
	"IDENTITY":         Keyword,
	"INCLUDE":          Keyword,
	"INPUT":            Keyword,
	"ISOLATION":        Keyword,
	"LANGUAGE":         Keyword,
	"LAST":             Keyword,
	"LOCAL":            Keyword,
	"LOWER":            Keyword,
	"MAX":              Keyword,
	"MIN":              Keyword,
	"MINUTE":           Keyword,
	"MODULE":           Keyword,
	"MONTH":            Keyword,
	"NAMES":            Keyword,
	"NCHAR":            Keyword,
	"NO":               Keyword,
	"NULLIF":           Keyword,
	"OCTET_LENGTH":     Keyword,
	"OUTPUT":           Keyword,
	"PAD":              Keyword,
	"PARTIAL":          Keyword,
	"PASCAL":           Keyword,
	"POSITION":         Keyword,
	"PREPARE":          Keyword,
	"PRIOR":            Keyword,
	"RELATIVE":         Keyword,
	"SCROLL":           Keyword,
	"SECOND":           Keyword,
	"SECTION":          Keyword,
	"SESSION":          Keyword,
	"SIZE":             Keyword,
	"SPACE":            Keyword,
	"SQLCA":            Keyword,
	"SQLCODE":          Keyword,
	"SQLERROR":         Keyword,
	"SUBSTRING":        Keyword,
	"SUM":              Keyword,
	"SYSTEM_USER":      Keyword,
	"TEMPORARY":        Keyword,
	"TIMESTAMP":        Keyword,
	"TIMEZONE_HOUR":    Keyword,
	"TIMEZONE_MINUTE":  Keyword,
	"TRANSACTION":      Keyword,
	"TRANSLATE":        Keyword,
	"TRANSLATION":      Keyword,
	"TRIM":             Keyword,
	"UNKNOWN":          Keyword,
	"UPPER":            Keyword,
	"WHENEVER":         Keyword,
	"WORK":             Keyword,

	// Oracle Keywords (Reserved Only)
	// Disabled for now due to higher probability of false normalization on other dialects.
	// E.g. uppercasing a table named "account"
	// These keywords can be enabled when dialect can be reliably determined from tags.
	// "ACCESS":                    Keyword,
	// "ACCOUNT":                   Keyword,
	// "ADMIN":                     Keyword,
	// "AFTER":                     Keyword,
	// "ARCHIVELOG":                Keyword,
	// "AUTHENTICATED":             Keyword,
	// "AUTOMATIC":                 Keyword,
	// "BACKUP":                    Keyword,
	// "BFILE":                     Keyword,
	// "BITMAP":                    Keyword,
	// "BLOCK":                     Keyword,
	// "BODY":                      Keyword,
	// "CACHE":                     Keyword,
	// "CACHE_INSTANCES":           Keyword,
	// "CHAINED":                   Keyword,
	// "CHAR_CS":                   Keyword,
	// "CHECKPOINT":                Keyword,
	// "CHOOSE":                    Keyword,
	// "CLEAR":                     Keyword,
	// "CLOB":                      Keyword,
	// "CLOSE_CACHED_OPEN_CURSORS": Keyword,
	// "COMMENT":                   Keyword,
	// "COMPATIBILITY":             Keyword,
	// "COMPILE":                   Keyword,
	// "COMPOSITE_LIMIT":           Keyword,
	// "COMPRESS":                  Keyword,
	// "CONNECT_TIME":              Keyword,
	// "CONTENTS":                  Keyword,
	// "CONTROLFILE":               Keyword,
	// "CPU_PER_CALL":              Keyword,
	// "CPU_PER_SESSION":           Keyword,
	// "CURRENT_SCHEMA":            Keyword,
	// "CYCLE":                     Keyword,
	// "DANGLING":                  Keyword,
	// "DATAFILE":                  Keyword,
	// "DATAFILES":                 Keyword,
	// "DATAOBJNO":                 Keyword,
	// "DBA":                       Keyword,
	// "DBHIGH":                    Keyword,
	// "DBLOW":                     Keyword,
	// "DBMAC":                     Keyword,
	// "DEBUG":                     Keyword,
	// "DEGREE":                    Keyword,
	// "DEREF":                     Keyword,
	// "DIRECTORY":                 Keyword,
	// "DISABLE":                   Keyword,
	// "DISMOUNT":                  Keyword,
	// "DISTRIBUTED":               Keyword,
	// "DML":                       Keyword,
	// "DUMP":                      Keyword,
	// "ENABLE":                    Keyword,
	// "ENFORCE":                   Keyword,
	// "ENTRY":                     Keyword,
	// "EXCEPTIONS":                Keyword,
	// "EXCHANGE":                  Keyword,
	// "EXCLUDING":                 Keyword,
	// "EXCLUSIVE":                 Keyword,
	// "EXPIRE":                    Keyword,
	// "EXTENT":                    Keyword,
	// "EXTENTS":                   Keyword,
	// "EXTERNALLY":                Keyword,
	// "FAILED_LOGIN_ATTEMPTS":     Keyword,
	// "FAST":                      Keyword,
	// "FILE":                      Keyword,
	// "FIRST_ROWS":                Keyword,
	// "FLAGGER":                   Keyword,
	// "FLOB":                      Keyword,
	// "FLUSH":                     Keyword,
	// "FREELIST":                  Keyword,
	// "FREELISTS":                 Keyword,
	// "GLOBALLY":                  Keyword,
	// "GLOBAL_NAME":               Keyword,
	// "HASH":                      Keyword,
	// "HASHKEYS":                  Keyword,
	// "HEADER":                    Keyword,
	// "HEAP":                      Keyword,
	// "IDENTIFIED":                Keyword,
	// "IDGENERATORS":              Keyword,
	// "IDLE_TIME":                 Keyword,
	// "INCLUDING":                 Keyword,
	// "INCREMENT":                 Keyword,
	// "INDEXED":                   Keyword,
	// "INDEXES":                   Keyword,
	// "IND_PARTITION":             Keyword,
	// "INITIAL":                   Keyword,
	// "INITRANS":                  Keyword,
	// "INSTANCE":                  Keyword,
	// "INSTANCES":                 Keyword,
	// "INSTEAD":                   Keyword,
	// "INTERMEDIATE":              Keyword,
	// "ISOLATION_LEVEL":           Keyword,
	// "KEEP":                      Keyword,
	// "LABEL":                     Keyword,
	// "LAYER":                     Keyword,
	// "LESS":                      Keyword,
	// "LIBRARY":                   Keyword,
	// "LINK":                      Keyword,
	// "LIST":                      Keyword,
	// "LOB":                       Keyword,
	// "LOCKED":                    Keyword,
	// "LOG":                       Keyword,
	// "LOGFILE":                   Keyword,
	// "LOGGING":                   Keyword,
	// "LOGICAL_READS_PER_CALL":    Keyword,
	// "LOGICAL_READS_PER_SESSION": Keyword,
	// "MANAGE":                    Keyword,
	// "MASTER":                    Keyword,
	// "MAXARCHLOGS":               Keyword,
	// "MAXDATAFILES":              Keyword,
	// "MAXEXTENTS":                Keyword,
	// "MAXINSTANCES":              Keyword,
	// "MAXLOGFILES":               Keyword,
	// "MAXLOGHISTORY":             Keyword,
	// "MAXLOGMEMBERS":             Keyword,
	// "MAXSIZE":                   Keyword,
	// "MAXTRANS":                  Keyword,
	// "MEMBER":                    Keyword,
	// "MINEXTENTS":                Keyword,
	// "MINIMUM":                   Keyword,
	// "MINUS":                     Keyword,
	// "MINVALUE":                  Keyword,
	// "MLSLABEL":                  Keyword,
	// "MLS_LABEL_FORMAT":          Keyword,
	// "MODE":                      Keyword,
	// "MOUNT":                     Keyword,
	// "MOVE":                      Keyword,
	// "MTS_DISPATCHERS":           Keyword,
	// "MULTISET":                  Keyword,
	// "NCHAR_CS":                  Keyword,
	// "NCLOB":                     Keyword,
	// "NEEDED":                    Keyword,
	// "NESTED":                    Keyword,
	// "NETWORK":                   Keyword,
	// "NOARCHIVELOG":              Keyword,
	// "NOAUDIT":                   Keyword,
	// "NOCACHE":                   Keyword,
	// "NOCOMPRESS":                Keyword,
	// "NOCYCLE":                   Keyword,
	// "NOFORCE":                   Keyword,
	// "NOLOGGING":                 Keyword,
	// "NOMAXVALUE":                Keyword,
	// "NOMINVALUE":                Keyword,
	// "NOORDER":                   Keyword,
	// "NOOVERRIDE":                Keyword,
	// "NOPARALLEL":                Keyword,
	// "NOREVERSE":                 Keyword,
	// "NORMAL":                    Keyword,
	// "NOSORT":                    Keyword,
	// "NOTHING":                   Keyword,
	// "NOWAIT":                    Keyword,
	// "NUMBER":                    Keyword,
	// "NVARCHAR2":                 Keyword,
	// "OBJECT":                    Keyword,
	// "OBJNO":                     Keyword,
	// "OBJNO_REUSE":               Keyword,
	// "OFFLINE":                   Keyword,
	// "OID":                       Keyword,
	// "OIDINDEX":                  Keyword,
	// "ONLINE":                    Keyword,
	// "OPCODE":                    Keyword,
	// "OPTIMAL":                   Keyword,
	// "OPTIMIZER_GOAL":            Keyword,
	// "ORGANIZATION":              Keyword,
	// "OSLABEL":                   Keyword,
	// "OVERFLOW":                  Keyword,
	// "OWN":                       Keyword,
	// "PACKAGE":                   Keyword,
	// "PARALLEL":                  Keyword,
	// "PASSWORD_GRACE_TIME":       Keyword,
	// "PASSWORD_LIFE_TIME":        Keyword,
	// "PASSWORD_LOCK_TIME":        Keyword,
	// "PASSWORD_REUSE_MAX":        Keyword,
	// "PASSWORD_REUSE_TIME":       Keyword,
	// "PASSWORD_VERIFY_FUNCTION":  Keyword,
	// "PCTFREE":                   Keyword,
	// "PCTINCREASE":               Keyword,
	// "PCTTHRESHOLD":              Keyword,
	// "PCTUSED":                   Keyword,
	// "PCTVERSION":                Keyword,
	// "PERCENT":                   Keyword,
	// "PERMANENT":                 Keyword,
	// "PLAN":                      Keyword,
	// "PLSQL_DEBUG":               Keyword,
	// "POST_TRANSACTION":          Keyword,
	// "PRIVATE":                   Keyword,
	// "PRIVATE_SGA":               Keyword,
	// "PRIVILEGE":                 Keyword,
	// "PROFILE":                   Keyword,
	// "QUEUE":                     Keyword,
	// "QUOTA":                     Keyword,
	// "RAW":                       Keyword,
	// "RBA":                       Keyword,
	// "READUP":                    Keyword,
	// "REBUILD":                   Keyword,
	// "RECOVER":                   Keyword,
	// "RECOVERABLE":               Keyword,
	// "RECOVERY":                  Keyword,
	// "REF":                       Keyword,
	// "REFERENCING":               Keyword,
	// "REFRESH":                   Keyword,
	// "RESET":                     Keyword,
	// "RESETLOGS":                 Keyword,
	// "RESIZE":                    Keyword,
	// "RESOURCE":                  Keyword,
	// "RESTRICTED":                Keyword,
	// "RETURNING":                 Keyword,
	// "REUSE":                     Keyword,
	// "REVERSE":                   Keyword,
	// "ROLE":                      Keyword,
	// "ROLES":                     Keyword,
	// "ROWID":                     Keyword,
	// "ROWNUM":                    Keyword,
	// "RULE":                      Keyword,
	// "SAMPLE":                    Keyword,
	// "SB4":                       Keyword,
	// "SCAN_INSTANCES":            Keyword,
	// "SCN":                       Keyword,
	// "SCOPE":                     Keyword,
	// "SD_ALL":                    Keyword,
	// "SD_INHIBIT":                Keyword,
	// "SD_SHOW":                   Keyword,
	// "SEGMENT":                   Keyword,
	// "SEG_BLOCK":                 Keyword,
	// "SEG_FILE":                  Keyword,
	// "SEQUENCE":                  Keyword,
	// "SERIALIZABLE":              Keyword,
	// "SESSIONS_PER_USER":         Keyword,
	// "SESSION_CACHED_CURSORS":    Keyword,
	// "SHARE":                     Keyword,
	// "SHARED":                    Keyword,
	// "SHARED_POOL":               Keyword,
	// "SHRINK":                    Keyword,
	// "SKIP":                      Keyword,
	// "SKIP_UNUSABLE_INDEXES":     Keyword,
	// "SNAPSHOT":                  Keyword,
	// "SORT":                      Keyword,
	// "SPECIFICATION":             Keyword,
	// "SPLIT":                     Keyword,
	// "SQL_TRACE":                 Keyword,
	// "STANDBY":                   Keyword,
	// "START":                     Keyword,
	// "STATEMENT_ID":              Keyword,
	// "STATISTICS":                Keyword,
	// "STOP":                      Keyword,
	// "STORAGE":                   Keyword,
	// "STORE":                     Keyword,
	// "STRUCTURE":                 Keyword,
	// "SUCCESSFUL":                Keyword,
	// "SWITCH":                    Keyword,
	// "SYNONYM":                   Keyword,
	// "SYSDATE":                   Keyword,
	// "SYSDBA":                    Keyword,
	// "SYSOPER":                   Keyword,
	// "SYS_OP_ENFORCE_NOT_NULL$":  Keyword,
	// "SYS_OP_NTCIMG$":            Keyword,
	// "TABLES":                    Keyword,
	// "TABLESPACE":                Keyword,
	// "TABLESPACE_NO":             Keyword,
	// "TABNO":                     Keyword,
	// "THAN":                      Keyword,
	// "THE":                       Keyword,
	// "THREAD":                    Keyword,
	// "TOPLEVEL":                  Keyword,
	// "TRACE":                     Keyword,
	// "TRACING":                   Keyword,
	// "TRANSITIONAL":              Keyword,
	// "TRIGGERS":                  Keyword,
	// "TX":                        Keyword,
	// "TYPE":                      Keyword,
	// "UB2":                       Keyword,
	// "UBA":                       Keyword,
	// "UID":                       Keyword,
	// "UNARCHIVED":                Keyword,
	// "UNLIMITED":                 Keyword,
	// "UNRECOVERABLE":             Keyword,
	// "UNTIL":                     Keyword,
	// "UNUSABLE":                  Keyword,
	// "UNUSED":                    Keyword,
	// "UPDATABLE":                 Keyword,
	// "VALIDATE":                  Keyword,
	// "VALIDATION":                Keyword,
	// "VARCHAR2":                  Keyword,
	// "WITHOUT":                   Keyword,
	// "WRITEDOWN":                 Keyword,
	// "WRITEUP":                   Keyword,
	// "XID":                       Keyword,

	// Cassandra Keywords (Reserved Only)
	"AGGREGATE":    Keyword,
	"ALLOW":        Keyword,
	"APPLY":        Keyword,
	"AUTHORIZE":    Keyword,
	"BATCH":        Keyword,
	"COLUMNFAMILY": Keyword,
	"EACH_QUORUM":  Keyword,
	"ENTRIES":      Keyword,
	"INET":         Keyword,
	"INFINITY":     Keyword,
	"KEYSPACE":     Keyword,
	"KEYSPACES":    Keyword,
	"LOCAL_ONE":    Keyword,
	"LOCAL_QUORUM": Keyword,
	"MATERIALIZED": Keyword,
	"NAN":          Keyword,
	"NORECURSIVE":  Keyword,
	"ONE":          Keyword,
	"PER":          Keyword,
	"QUORUM":       Keyword,
	"THREE":        Keyword,
	"TOKEN":        Keyword,
	"TWO":          Keyword,
	"UNLOGGED":     Keyword,
}
