load("@rules_go//go:def.bzl", "go_library")

package(default_package_metadata = ["//pkg/trace:go_package_metadata"])

go_library(
    name = "header",
    srcs = ["headers.go"],
    importpath = "github.com/DataDog/datadog-agent/pkg/trace/api/internal/header",
    visibility = ["//pkg/trace/api:__subpackages__"],
)
