load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "envstore",
    srcs = ["envstore.go"],
    importpath = "github.com/DataDog/datadog-agent/test/e2e-framework/cmd/e2ectl/internal/envstore",
    visibility = ["//test/e2e-framework/cmd/e2ectl:__subpackages__"],
    deps = ["//test/e2e-framework/cmd/e2ectl/internal/config"],
)
