load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "pcap",
    srcs = ["config.go"],
    embedsrcs = ["config/pcap-helm-values.yaml"],
    importpath = "github.com/DataDog/datadog-agent/test/new-e2e/tests/pcap",
    visibility = ["//visibility:public"],
)

go_test(
    name = "pcap_test",
    srcs = ["eks_pcap_test.go"],
    embed = [":pcap"],
    gotags = ["test"],
    deps = [
        "//test/e2e-framework/common/config",
        "//test/e2e-framework/components/datadog/apps/npm-tools",
        "//test/e2e-framework/components/datadog/kubernetesagentparams",
        "//test/e2e-framework/components/kubernetes",
        "//test/e2e-framework/resources/aws",
        "//test/e2e-framework/scenarios/aws/eks",
        "//test/e2e-framework/scenarios/aws/fakeintake",
        "//test/e2e-framework/testing/e2e",
        "//test/e2e-framework/testing/environments",
        "//test/e2e-framework/testing/provisioners",
        "//test/fakeintake/api",
        "@com_github_google_uuid//:uuid",
        "@com_github_pulumi_pulumi_kubernetes_sdk_v4//go/kubernetes",
        "@com_github_pulumi_pulumi_sdk_v3//go/pulumi",
        "@com_github_stretchr_testify//assert",
        "@io_k8s_apimachinery//pkg/apis/meta/v1:meta",
    ],
)
