load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "configure",
    srcs = ["configure.go"],
    importpath = "github.com/DataDog/datadog-agent/test/e2e-framework/testing/installers/host/configure",
    visibility = ["//visibility:public"],
    deps = [
        "//test/e2e-framework/components/outputs",
        "//test/e2e-framework/testing/components",
        "//test/e2e-framework/testing/environments",
        "//test/e2e-framework/testing/installers/agentconfig",
    ],
)
