filegroup(
    name = "runtime",
    srcs = [
        "bin/wine",
        "bin/wineserver",
    ] + glob(
        [
            "lib/**",
            "share/wine/**",
        ],
        # Static import libraries are only needed to build against Wine.
        exclude = ["**/*.a"],
    ),
    visibility = ["@//bazel/tools/wine:__pkg__"],
)
