load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

dd_agent_go_test(
    name = "agent-devx_test",
    srcs = ["base_test.go"],
    deps = [
        "//test/e2e-framework/testing/e2e",
        "//test/e2e-framework/testing/environments",
        "//test/e2e-framework/testing/provisioners/aws/host",
    ],
)
