load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "config",
    srcs = [
        "config.go",
        "helper.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/pkg/networkpath/traceroute/config",
    visibility = ["//visibility:public"],
    deps = ["//pkg/networkpath/payload"],
)

go_test(
    name = "config_test",
    srcs = ["helper_test.go"],
    embed = [":config"],
    gotags = ["test"],
    deps = ["@com_github_stretchr_testify//assert"],
)
