load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "def",
    srcs = ["component.go"],
    importpath = "github.com/DataDog/datadog-agent/comp/sbom/usage/def",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/sbom/usage",
        "@com_github_datadog_agent_payload_v5//cyclonedx_v1_4",
    ],
)
