load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go_package_metadata:defs.bzl", "go_package_metadata")

package(default_package_metadata = [":go_package_metadata"])

go_package_metadata(
    name = "go_package_metadata",
    module = "github.com/DataDog/datadog-agent/comp/forwarder/orchestrator/orchestratorinterface",
)

go_library(
    name = "orchestratorinterface",
    srcs = [
        "component.go",
        "doc.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/comp/forwarder/orchestrator/orchestratorinterface",
    visibility = ["//visibility:public"],
    deps = ["//comp/forwarder/defaultforwarder/def"],
)
