load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

# gazelle:dd_agent_go_test on

go_library(
    name = "impl",
    srcs = [
        "report.go",
        "source_stub.go",
        "source_trivy.go",
        "usage.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/comp/sbom/usage/impl",
    visibility = ["//visibility:public"],
    deps = [
        "//comp/core/config",
        "//comp/core/flare/types",
        "//comp/core/log/def",
        "//comp/core/status",
        "//comp/core/workloadmeta/def",
        "//comp/def",
        "//comp/sbom/usage/def",
        "//pkg/sbom/collectors/procfs",
        "//pkg/sbom/scanner",
        "//pkg/sbom/usage",
        "//pkg/util/option",
        "//pkg/util/trivy",
        "@com_github_datadog_agent_payload_v5//cyclonedx_v1_4",
    ],
)

dd_agent_go_test(
    name = "impl_test",
    srcs = ["usage_test.go"],
    embed = [":impl"],
    deps = ["//pkg/sbom/usage"],
)
