load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

go_library(
    name = "status",
    srcs = ["status.go"],
    embedsrcs = [
        "status_templates/remote_agents.tmpl",
        "status_templates/remote_agents_html.tmpl",
    ],
    importpath = "github.com/DataDog/datadog-agent/comp/core/remoteagentregistry/status",
    visibility = ["//visibility:public"],
    deps = [
        "//comp/core/remoteagentregistry/def",
        "//comp/core/status",
    ],
)

dd_agent_go_test(
    name = "status_test",
    srcs = ["status_test.go"],
    embed = [":status"],
    deps = [
        "//comp/core/remoteagentregistry/def",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
        "@org_golang_x_net//html",
    ],
)
