// Code generated by protoc-gen-go. DO NOT EDIT.
// source: remoteconfig.proto

package pbgo

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ConfigMetas struct {
	Roots                []*TopMeta       `protobuf:"bytes,1,rep,name=roots,proto3" json:"roots,omitempty"`
	Timestamp            *TopMeta         `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Snapshot             *TopMeta         `protobuf:"bytes,3,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	TopTargets           *TopMeta         `protobuf:"bytes,4,opt,name=topTargets,proto3" json:"topTargets,omitempty"`
	DelegatedTargets     []*DelegatedMeta `protobuf:"bytes,5,rep,name=delegatedTargets,proto3" json:"delegatedTargets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ConfigMetas) Reset()         { *m = ConfigMetas{} }
func (m *ConfigMetas) String() string { return proto.CompactTextString(m) }
func (*ConfigMetas) ProtoMessage()    {}
func (*ConfigMetas) Descriptor() ([]byte, []int) {
	return fileDescriptor_e19cd78713df8f37, []int{0}
}

func (m *ConfigMetas) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigMetas.Unmarshal(m, b)
}
func (m *ConfigMetas) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigMetas.Marshal(b, m, deterministic)
}
func (m *ConfigMetas) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigMetas.Merge(m, src)
}
func (m *ConfigMetas) XXX_Size() int {
	return xxx_messageInfo_ConfigMetas.Size(m)
}
func (m *ConfigMetas) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigMetas.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigMetas proto.InternalMessageInfo

func (m *ConfigMetas) GetRoots() []*TopMeta {
	if m != nil {
		return m.Roots
	}
	return nil
}

func (m *ConfigMetas) GetTimestamp() *TopMeta {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *ConfigMetas) GetSnapshot() *TopMeta {
	if m != nil {
		return m.Snapshot
	}
	return nil
}

func (m *ConfigMetas) GetTopTargets() *TopMeta {
	if m != nil {
		return m.TopTargets
	}
	return nil
}

func (m *ConfigMetas) GetDelegatedTargets() []*DelegatedMeta {
	if m != nil {
		return m.DelegatedTargets
	}
	return nil
}

type DirectorMetas struct {
	Roots                []*TopMeta `protobuf:"bytes,1,rep,name=roots,proto3" json:"roots,omitempty"`
	Timestamp            *TopMeta   `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Snapshot             *TopMeta   `protobuf:"bytes,3,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	Targets              *TopMeta   `protobuf:"bytes,4,opt,name=targets,proto3" json:"targets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *DirectorMetas) Reset()         { *m = DirectorMetas{} }
func (m *DirectorMetas) String() string { return proto.CompactTextString(m) }
func (*DirectorMetas) ProtoMessage()    {}
func (*DirectorMetas) Descriptor() ([]byte, []int) {
	return fileDescriptor_e19cd78713df8f37, []int{1}
}

func (m *DirectorMetas) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DirectorMetas.Unmarshal(m, b)
}
func (m *DirectorMetas) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DirectorMetas.Marshal(b, m, deterministic)
}
func (m *DirectorMetas) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DirectorMetas.Merge(m, src)
}
func (m *DirectorMetas) XXX_Size() int {
	return xxx_messageInfo_DirectorMetas.Size(m)
}
func (m *DirectorMetas) XXX_DiscardUnknown() {
	xxx_messageInfo_DirectorMetas.DiscardUnknown(m)
}

var xxx_messageInfo_DirectorMetas proto.InternalMessageInfo

func (m *DirectorMetas) GetRoots() []*TopMeta {
	if m != nil {
		return m.Roots
	}
	return nil
}

func (m *DirectorMetas) GetTimestamp() *TopMeta {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *DirectorMetas) GetSnapshot() *TopMeta {
	if m != nil {
		return m.Snapshot
	}
	return nil
}

func (m *DirectorMetas) GetTargets() *TopMeta {
	if m != nil {
		return m.Targets
	}
	return nil
}

type DelegatedMeta struct {
	Version              uint64   `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Role                 string   `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Raw                  []byte   `protobuf:"bytes,3,opt,name=raw,proto3" json:"raw,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelegatedMeta) Reset()         { *m = DelegatedMeta{} }
func (m *DelegatedMeta) String() string { return proto.CompactTextString(m) }
func (*DelegatedMeta) ProtoMessage()    {}
func (*DelegatedMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_e19cd78713df8f37, []int{2}
}

func (m *DelegatedMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelegatedMeta.Unmarshal(m, b)
}
func (m *DelegatedMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelegatedMeta.Marshal(b, m, deterministic)
}
func (m *DelegatedMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelegatedMeta.Merge(m, src)
}
func (m *DelegatedMeta) XXX_Size() int {
	return xxx_messageInfo_DelegatedMeta.Size(m)
}
func (m *DelegatedMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_DelegatedMeta.DiscardUnknown(m)
}

var xxx_messageInfo_DelegatedMeta proto.InternalMessageInfo

func (m *DelegatedMeta) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *DelegatedMeta) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *DelegatedMeta) GetRaw() []byte {
	if m != nil {
		return m.Raw
	}
	return nil
}

type TopMeta struct {
	Version              uint64   `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Raw                  []byte   `protobuf:"bytes,2,opt,name=raw,proto3" json:"raw,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TopMeta) Reset()         { *m = TopMeta{} }
func (m *TopMeta) String() string { return proto.CompactTextString(m) }
func (*TopMeta) ProtoMessage()    {}
func (*TopMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_e19cd78713df8f37, []int{3}
}

func (m *TopMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopMeta.Unmarshal(m, b)
}
func (m *TopMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopMeta.Marshal(b, m, deterministic)
}
func (m *TopMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopMeta.Merge(m, src)
}
func (m *TopMeta) XXX_Size() int {
	return xxx_messageInfo_TopMeta.Size(m)
}
func (m *TopMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_TopMeta.DiscardUnknown(m)
}

var xxx_messageInfo_TopMeta proto.InternalMessageInfo

func (m *TopMeta) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *TopMeta) GetRaw() []byte {
	if m != nil {
		return m.Raw
	}
	return nil
}

type File struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Raw                  []byte   `protobuf:"bytes,2,opt,name=raw,proto3" json:"raw,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_e19cd78713df8f37, []int{4}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *File) GetRaw() []byte {
	if m != nil {
		return m.Raw
	}
	return nil
}

type LatestConfigsRequest struct {
	Hostname     string `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	AgentVersion string `protobuf:"bytes,2,opt,name=agentVersion,proto3" json:"agentVersion,omitempty"`
	// timestamp and snapshot versions move in tandem so they are the same.
	CurrentConfigSnapshotVersion uint64    `protobuf:"varint,3,opt,name=current_config_snapshot_version,json=currentConfigSnapshotVersion,proto3" json:"current_config_snapshot_version,omitempty"`
	CurrentConfigRootVersion     uint64    `protobuf:"varint,9,opt,name=current_config_root_version,json=currentConfigRootVersion,proto3" json:"current_config_root_version,omitempty"`
	CurrentDirectorRootVersion   uint64    `protobuf:"varint,8,opt,name=current_director_root_version,json=currentDirectorRootVersion,proto3" json:"current_director_root_version,omitempty"`
	Products                     []string  `protobuf:"bytes,4,rep,name=products,proto3" json:"products,omitempty"`
	NewProducts                  []string  `protobuf:"bytes,5,rep,name=new_products,json=newProducts,proto3" json:"new_products,omitempty"`
	ActiveClients                []*Client `protobuf:"bytes,6,rep,name=active_clients,json=activeClients,proto3" json:"active_clients,omitempty"`
	BackendClientState           []byte    `protobuf:"bytes,10,opt,name=backend_client_state,json=backendClientState,proto3" json:"backend_client_state,omitempty"`
	HasError                     bool      `protobuf:"varint,11,opt,name=has_error,json=hasError,proto3" json:"has_error,omitempty"`
	Error                        string    `protobuf:"bytes,12,opt,name=error,proto3" json:"error,omitempty"`
	TraceAgentEnv                string    `protobuf:"bytes,13,opt,name=trace_agent_env,json=traceAgentEnv,proto3" json:"trace_agent_env,omitempty"`
	XXX_NoUnkeyedLiteral         struct{}  `json:"-"`
	XXX_unrecognized             []byte    `json:"-"`
	XXX_sizecache                int32     `json:"-"`
}

func (m *LatestConfigsRequest) Reset()         { *m = LatestConfigsRequest{} }
func (m *LatestConfigsRequest) String() string { return proto.CompactTextString(m) }
func (*LatestConfigsRequest) ProtoMessage()    {}
func (*LatestConfigsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e19cd78713df8f37, []int{5}
}

func (m *LatestConfigsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LatestConfigsRequest.Unmarshal(m, b)
}
func (m *LatestConfigsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LatestConfigsRequest.Marshal(b, m, deterministic)
}
func (m *LatestConfigsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LatestConfigsRequest.Merge(m, src)
}
func (m *LatestConfigsRequest) XXX_Size() int {
	return xxx_messageInfo_LatestConfigsRequest.Size(m)
}
func (m *LatestConfigsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LatestConfigsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LatestConfigsRequest proto.InternalMessageInfo

func (m *LatestConfigsRequest) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *LatestConfigsRequest) GetAgentVersion() string {
	if m != nil {
		return m.AgentVersion
	}
	return ""
}

func (m *LatestConfigsRequest) GetCurrentConfigSnapshotVersion() uint64 {
	if m != nil {
		return m.CurrentConfigSnapshotVersion
	}
	return 0
}

func (m *LatestConfigsRequest) GetCurrentConfigRootVersion() uint64 {
	if m != nil {
		return m.CurrentConfigRootVersion
	}
	return 0
}

func (m *LatestConfigsRequest) GetCurrentDirectorRootVersion() uint64 {
	if m != nil {
		return m.CurrentDirectorRootVersion
	}
	return 0
}

func (m *LatestConfigsRequest) GetProducts() []string {
	if m != nil {
		return m.Products
	}
	return nil
}

func (m *LatestConfigsRequest) GetNewProducts() []string {
	if m != nil {
		return m.NewProducts
	}
	return nil
}

func (m *LatestConfigsRequest) GetActiveClients() []*Client {
	if m != nil {
		return m.ActiveClients
	}
	return nil
}

func (m *LatestConfigsRequest) GetBackendClientState() []byte {
	if m != nil {
		return m.BackendClientState
	}
	return nil
}

func (m *LatestConfigsRequest) GetHasError() bool {
	if m != nil {
		return m.HasError
	}
	return false
}

func (m *LatestConfigsRequest) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *LatestConfigsRequest) GetTraceAgentEnv() string {
	if m != nil {
		return m.TraceAgentEnv
	}
	return ""
}

type LatestConfigsResponse struct {
	ConfigMetas          *ConfigMetas   `protobuf:"bytes,1,opt,name=config_metas,json=configMetas,proto3" json:"config_metas,omitempty"`
	DirectorMetas        *DirectorMetas `protobuf:"bytes,2,opt,name=director_metas,json=directorMetas,proto3" json:"director_metas,omitempty"`
	TargetFiles          []*File        `protobuf:"bytes,3,rep,name=target_files,json=targetFiles,proto3" json:"target_files,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *LatestConfigsResponse) Reset()         { *m = LatestConfigsResponse{} }
func (m *LatestConfigsResponse) String() string { return proto.CompactTextString(m) }
func (*LatestConfigsResponse) ProtoMessage()    {}
func (*LatestConfigsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e19cd78713df8f37, []int{6}
}

func (m *LatestConfigsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LatestConfigsResponse.Unmarshal(m, b)
}
func (m *LatestConfigsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LatestConfigsResponse.Marshal(b, m, deterministic)
}
func (m *LatestConfigsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LatestConfigsResponse.Merge(m, src)
}
func (m *LatestConfigsResponse) XXX_Size() int {
	return xxx_messageInfo_LatestConfigsResponse.Size(m)
}
func (m *LatestConfigsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LatestConfigsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LatestConfigsResponse proto.InternalMessageInfo

func (m *LatestConfigsResponse) GetConfigMetas() *ConfigMetas {
	if m != nil {
		return m.ConfigMetas
	}
	return nil
}

func (m *LatestConfigsResponse) GetDirectorMetas() *DirectorMetas {
	if m != nil {
		return m.DirectorMetas
	}
	return nil
}

func (m *LatestConfigsResponse) GetTargetFiles() []*File {
	if m != nil {
		return m.TargetFiles
	}
	return nil
}

type OrgDataResponse struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrgDataResponse) Reset()         { *m = OrgDataResponse{} }
func (m *OrgDataResponse) String() string { return proto.CompactTextString(m) }
func (*OrgDataResponse) ProtoMessage()    {}
func (*OrgDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e19cd78713df8f37, []int{7}
}

func (m *OrgDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrgDataResponse.Unmarshal(m, b)
}
func (m *OrgDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrgDataResponse.Marshal(b, m, deterministic)
}
func (m *OrgDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrgDataResponse.Merge(m, src)
}
func (m *OrgDataResponse) XXX_Size() int {
	return xxx_messageInfo_OrgDataResponse.Size(m)
}
func (m *OrgDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OrgDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OrgDataResponse proto.InternalMessageInfo

func (m *OrgDataResponse) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type Client struct {
	State                *ClientState  `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Id                   string        `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Products             []string      `protobuf:"bytes,3,rep,name=products,proto3" json:"products,omitempty"`
	IsTracer             bool          `protobuf:"varint,6,opt,name=is_tracer,json=isTracer,proto3" json:"is_tracer,omitempty"`
	ClientTracer         *ClientTracer `protobuf:"bytes,7,opt,name=client_tracer,json=clientTracer,proto3" json:"client_tracer,omitempty"`
	IsAgent              bool          `protobuf:"varint,8,opt,name=is_agent,json=isAgent,proto3" json:"is_agent,omitempty"`
	ClientAgent          *ClientAgent  `protobuf:"bytes,9,opt,name=client_agent,json=clientAgent,proto3" json:"client_agent,omitempty"`
	LastSeen             uint64        `protobuf:"varint,10,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	Capabilities         []byte        `protobuf:"bytes,11,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Client) Reset()         { *m = Client{} }
func (m *Client) String() string { return proto.CompactTextString(m) }
func (*Client) ProtoMessage()    {}
func (*Client) Descriptor() ([]byte, []int) {
	return fileDescriptor_e19cd78713df8f37, []int{8}
}

func (m *Client) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Client.Unmarshal(m, b)
}
func (m *Client) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Client.Marshal(b, m, deterministic)
}
func (m *Client) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Client.Merge(m, src)
}
func (m *Client) XXX_Size() int {
	return xxx_messageInfo_Client.Size(m)
}
func (m *Client) XXX_DiscardUnknown() {
	xxx_messageInfo_Client.DiscardUnknown(m)
}

var xxx_messageInfo_Client proto.InternalMessageInfo

func (m *Client) GetState() *ClientState {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *Client) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Client) GetProducts() []string {
	if m != nil {
		return m.Products
	}
	return nil
}

func (m *Client) GetIsTracer() bool {
	if m != nil {
		return m.IsTracer
	}
	return false
}

func (m *Client) GetClientTracer() *ClientTracer {
	if m != nil {
		return m.ClientTracer
	}
	return nil
}

func (m *Client) GetIsAgent() bool {
	if m != nil {
		return m.IsAgent
	}
	return false
}

func (m *Client) GetClientAgent() *ClientAgent {
	if m != nil {
		return m.ClientAgent
	}
	return nil
}

func (m *Client) GetLastSeen() uint64 {
	if m != nil {
		return m.LastSeen
	}
	return 0
}

func (m *Client) GetCapabilities() []byte {
	if m != nil {
		return m.Capabilities
	}
	return nil
}

type ClientTracer struct {
	RuntimeId            string   `protobuf:"bytes,1,opt,name=runtime_id,json=runtimeId,proto3" json:"runtime_id,omitempty"`
	Language             string   `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	TracerVersion        string   `protobuf:"bytes,3,opt,name=tracer_version,json=tracerVersion,proto3" json:"tracer_version,omitempty"`
	Service              string   `protobuf:"bytes,4,opt,name=service,proto3" json:"service,omitempty"`
	Env                  string   `protobuf:"bytes,5,opt,name=env,proto3" json:"env,omitempty"`
	AppVersion           string   `protobuf:"bytes,6,opt,name=app_version,json=appVersion,proto3" json:"app_version,omitempty"`
	Tags                 []string `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientTracer) Reset()         { *m = ClientTracer{} }
func (m *ClientTracer) String() string { return proto.CompactTextString(m) }
func (*ClientTracer) ProtoMessage()    {}
func (*ClientTracer) Descriptor() ([]byte, []int) {
	return fileDescriptor_e19cd78713df8f37, []int{9}
}

func (m *ClientTracer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientTracer.Unmarshal(m, b)
}
func (m *ClientTracer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientTracer.Marshal(b, m, deterministic)
}
func (m *ClientTracer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientTracer.Merge(m, src)
}
func (m *ClientTracer) XXX_Size() int {
	return xxx_messageInfo_ClientTracer.Size(m)
}
func (m *ClientTracer) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientTracer.DiscardUnknown(m)
}

var xxx_messageInfo_ClientTracer proto.InternalMessageInfo

func (m *ClientTracer) GetRuntimeId() string {
	if m != nil {
		return m.RuntimeId
	}
	return ""
}

func (m *ClientTracer) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *ClientTracer) GetTracerVersion() string {
	if m != nil {
		return m.TracerVersion
	}
	return ""
}

func (m *ClientTracer) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *ClientTracer) GetEnv() string {
	if m != nil {
		return m.Env
	}
	return ""
}

func (m *ClientTracer) GetAppVersion() string {
	if m != nil {
		return m.AppVersion
	}
	return ""
}

func (m *ClientTracer) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type ClientAgent struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientAgent) Reset()         { *m = ClientAgent{} }
func (m *ClientAgent) String() string { return proto.CompactTextString(m) }
func (*ClientAgent) ProtoMessage()    {}
func (*ClientAgent) Descriptor() ([]byte, []int) {
	return fileDescriptor_e19cd78713df8f37, []int{10}
}

func (m *ClientAgent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientAgent.Unmarshal(m, b)
}
func (m *ClientAgent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientAgent.Marshal(b, m, deterministic)
}
func (m *ClientAgent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientAgent.Merge(m, src)
}
func (m *ClientAgent) XXX_Size() int {
	return xxx_messageInfo_ClientAgent.Size(m)
}
func (m *ClientAgent) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientAgent.DiscardUnknown(m)
}

var xxx_messageInfo_ClientAgent proto.InternalMessageInfo

func (m *ClientAgent) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ClientAgent) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type ConfigState struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version              uint64   `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Product              string   `protobuf:"bytes,3,opt,name=product,proto3" json:"product,omitempty"`
	ApplyState           uint64   `protobuf:"varint,4,opt,name=apply_state,json=applyState,proto3" json:"apply_state,omitempty"`
	ApplyError           string   `protobuf:"bytes,5,opt,name=apply_error,json=applyError,proto3" json:"apply_error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigState) Reset()         { *m = ConfigState{} }
func (m *ConfigState) String() string { return proto.CompactTextString(m) }
func (*ConfigState) ProtoMessage()    {}
func (*ConfigState) Descriptor() ([]byte, []int) {
	return fileDescriptor_e19cd78713df8f37, []int{11}
}

func (m *ConfigState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigState.Unmarshal(m, b)
}
func (m *ConfigState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigState.Marshal(b, m, deterministic)
}
func (m *ConfigState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigState.Merge(m, src)
}
func (m *ConfigState) XXX_Size() int {
	return xxx_messageInfo_ConfigState.Size(m)
}
func (m *ConfigState) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigState.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigState proto.InternalMessageInfo

func (m *ConfigState) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ConfigState) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ConfigState) GetProduct() string {
	if m != nil {
		return m.Product
	}
	return ""
}

func (m *ConfigState) GetApplyState() uint64 {
	if m != nil {
		return m.ApplyState
	}
	return 0
}

func (m *ConfigState) GetApplyError() string {
	if m != nil {
		return m.ApplyError
	}
	return ""
}

type ClientState struct {
	RootVersion          uint64         `protobuf:"varint,1,opt,name=root_version,json=rootVersion,proto3" json:"root_version,omitempty"`
	TargetsVersion       uint64         `protobuf:"varint,2,opt,name=targets_version,json=targetsVersion,proto3" json:"targets_version,omitempty"`
	ConfigStates         []*ConfigState `protobuf:"bytes,3,rep,name=config_states,json=configStates,proto3" json:"config_states,omitempty"`
	HasError             bool           `protobuf:"varint,4,opt,name=has_error,json=hasError,proto3" json:"has_error,omitempty"`
	Error                string         `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	BackendClientState   []byte         `protobuf:"bytes,6,opt,name=backend_client_state,json=backendClientState,proto3" json:"backend_client_state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ClientState) Reset()         { *m = ClientState{} }
func (m *ClientState) String() string { return proto.CompactTextString(m) }
func (*ClientState) ProtoMessage()    {}
func (*ClientState) Descriptor() ([]byte, []int) {
	return fileDescriptor_e19cd78713df8f37, []int{12}
}

func (m *ClientState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientState.Unmarshal(m, b)
}
func (m *ClientState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientState.Marshal(b, m, deterministic)
}
func (m *ClientState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientState.Merge(m, src)
}
func (m *ClientState) XXX_Size() int {
	return xxx_messageInfo_ClientState.Size(m)
}
func (m *ClientState) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientState.DiscardUnknown(m)
}

var xxx_messageInfo_ClientState proto.InternalMessageInfo

func (m *ClientState) GetRootVersion() uint64 {
	if m != nil {
		return m.RootVersion
	}
	return 0
}

func (m *ClientState) GetTargetsVersion() uint64 {
	if m != nil {
		return m.TargetsVersion
	}
	return 0
}

func (m *ClientState) GetConfigStates() []*ConfigState {
	if m != nil {
		return m.ConfigStates
	}
	return nil
}

func (m *ClientState) GetHasError() bool {
	if m != nil {
		return m.HasError
	}
	return false
}

func (m *ClientState) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ClientState) GetBackendClientState() []byte {
	if m != nil {
		return m.BackendClientState
	}
	return nil
}

type TargetFileHash struct {
	Algorithm            string   `protobuf:"bytes,1,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	Hash                 string   `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TargetFileHash) Reset()         { *m = TargetFileHash{} }
func (m *TargetFileHash) String() string { return proto.CompactTextString(m) }
func (*TargetFileHash) ProtoMessage()    {}
func (*TargetFileHash) Descriptor() ([]byte, []int) {
	return fileDescriptor_e19cd78713df8f37, []int{13}
}

func (m *TargetFileHash) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TargetFileHash.Unmarshal(m, b)
}
func (m *TargetFileHash) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TargetFileHash.Marshal(b, m, deterministic)
}
func (m *TargetFileHash) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TargetFileHash.Merge(m, src)
}
func (m *TargetFileHash) XXX_Size() int {
	return xxx_messageInfo_TargetFileHash.Size(m)
}
func (m *TargetFileHash) XXX_DiscardUnknown() {
	xxx_messageInfo_TargetFileHash.DiscardUnknown(m)
}

var xxx_messageInfo_TargetFileHash proto.InternalMessageInfo

func (m *TargetFileHash) GetAlgorithm() string {
	if m != nil {
		return m.Algorithm
	}
	return ""
}

func (m *TargetFileHash) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type TargetFileMeta struct {
	Path                 string            `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Length               int64             `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	Hashes               []*TargetFileHash `protobuf:"bytes,3,rep,name=hashes,proto3" json:"hashes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *TargetFileMeta) Reset()         { *m = TargetFileMeta{} }
func (m *TargetFileMeta) String() string { return proto.CompactTextString(m) }
func (*TargetFileMeta) ProtoMessage()    {}
func (*TargetFileMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_e19cd78713df8f37, []int{14}
}

func (m *TargetFileMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TargetFileMeta.Unmarshal(m, b)
}
func (m *TargetFileMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TargetFileMeta.Marshal(b, m, deterministic)
}
func (m *TargetFileMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TargetFileMeta.Merge(m, src)
}
func (m *TargetFileMeta) XXX_Size() int {
	return xxx_messageInfo_TargetFileMeta.Size(m)
}
func (m *TargetFileMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_TargetFileMeta.DiscardUnknown(m)
}

var xxx_messageInfo_TargetFileMeta proto.InternalMessageInfo

func (m *TargetFileMeta) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *TargetFileMeta) GetLength() int64 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *TargetFileMeta) GetHashes() []*TargetFileHash {
	if m != nil {
		return m.Hashes
	}
	return nil
}

type ClientGetConfigsRequest struct {
	Client               *Client           `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	CachedTargetFiles    []*TargetFileMeta `protobuf:"bytes,2,rep,name=cached_target_files,json=cachedTargetFiles,proto3" json:"cached_target_files,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ClientGetConfigsRequest) Reset()         { *m = ClientGetConfigsRequest{} }
func (m *ClientGetConfigsRequest) String() string { return proto.CompactTextString(m) }
func (*ClientGetConfigsRequest) ProtoMessage()    {}
func (*ClientGetConfigsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e19cd78713df8f37, []int{15}
}

func (m *ClientGetConfigsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientGetConfigsRequest.Unmarshal(m, b)
}
func (m *ClientGetConfigsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientGetConfigsRequest.Marshal(b, m, deterministic)
}
func (m *ClientGetConfigsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientGetConfigsRequest.Merge(m, src)
}
func (m *ClientGetConfigsRequest) XXX_Size() int {
	return xxx_messageInfo_ClientGetConfigsRequest.Size(m)
}
func (m *ClientGetConfigsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientGetConfigsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClientGetConfigsRequest proto.InternalMessageInfo

func (m *ClientGetConfigsRequest) GetClient() *Client {
	if m != nil {
		return m.Client
	}
	return nil
}

func (m *ClientGetConfigsRequest) GetCachedTargetFiles() []*TargetFileMeta {
	if m != nil {
		return m.CachedTargetFiles
	}
	return nil
}

type ClientGetConfigsResponse struct {
	Roots                [][]byte `protobuf:"bytes,1,rep,name=roots,proto3" json:"roots,omitempty"`
	Targets              []byte   `protobuf:"bytes,2,opt,name=targets,proto3" json:"targets,omitempty"`
	TargetFiles          []*File  `protobuf:"bytes,3,rep,name=target_files,json=targetFiles,proto3" json:"target_files,omitempty"`
	ClientConfigs        []string `protobuf:"bytes,4,rep,name=client_configs,json=clientConfigs,proto3" json:"client_configs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientGetConfigsResponse) Reset()         { *m = ClientGetConfigsResponse{} }
func (m *ClientGetConfigsResponse) String() string { return proto.CompactTextString(m) }
func (*ClientGetConfigsResponse) ProtoMessage()    {}
func (*ClientGetConfigsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e19cd78713df8f37, []int{16}
}

func (m *ClientGetConfigsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientGetConfigsResponse.Unmarshal(m, b)
}
func (m *ClientGetConfigsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientGetConfigsResponse.Marshal(b, m, deterministic)
}
func (m *ClientGetConfigsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientGetConfigsResponse.Merge(m, src)
}
func (m *ClientGetConfigsResponse) XXX_Size() int {
	return xxx_messageInfo_ClientGetConfigsResponse.Size(m)
}
func (m *ClientGetConfigsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientGetConfigsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClientGetConfigsResponse proto.InternalMessageInfo

func (m *ClientGetConfigsResponse) GetRoots() [][]byte {
	if m != nil {
		return m.Roots
	}
	return nil
}

func (m *ClientGetConfigsResponse) GetTargets() []byte {
	if m != nil {
		return m.Targets
	}
	return nil
}

func (m *ClientGetConfigsResponse) GetTargetFiles() []*File {
	if m != nil {
		return m.TargetFiles
	}
	return nil
}

func (m *ClientGetConfigsResponse) GetClientConfigs() []string {
	if m != nil {
		return m.ClientConfigs
	}
	return nil
}

type FileMetaState struct {
	Version              uint64   `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Hash                 string   `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileMetaState) Reset()         { *m = FileMetaState{} }
func (m *FileMetaState) String() string { return proto.CompactTextString(m) }
func (*FileMetaState) ProtoMessage()    {}
func (*FileMetaState) Descriptor() ([]byte, []int) {
	return fileDescriptor_e19cd78713df8f37, []int{17}
}

func (m *FileMetaState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileMetaState.Unmarshal(m, b)
}
func (m *FileMetaState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileMetaState.Marshal(b, m, deterministic)
}
func (m *FileMetaState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileMetaState.Merge(m, src)
}
func (m *FileMetaState) XXX_Size() int {
	return xxx_messageInfo_FileMetaState.Size(m)
}
func (m *FileMetaState) XXX_DiscardUnknown() {
	xxx_messageInfo_FileMetaState.DiscardUnknown(m)
}

var xxx_messageInfo_FileMetaState proto.InternalMessageInfo

func (m *FileMetaState) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *FileMetaState) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type GetStateConfigResponse struct {
	ConfigState          map[string]*FileMetaState `protobuf:"bytes,1,rep,name=config_state,json=configState,proto3" json:"config_state,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	DirectorState        map[string]*FileMetaState `protobuf:"bytes,2,rep,name=director_state,json=directorState,proto3" json:"director_state,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	TargetFilenames      map[string]string         `protobuf:"bytes,3,rep,name=target_filenames,json=targetFilenames,proto3" json:"target_filenames,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *GetStateConfigResponse) Reset()         { *m = GetStateConfigResponse{} }
func (m *GetStateConfigResponse) String() string { return proto.CompactTextString(m) }
func (*GetStateConfigResponse) ProtoMessage()    {}
func (*GetStateConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e19cd78713df8f37, []int{18}
}

func (m *GetStateConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStateConfigResponse.Unmarshal(m, b)
}
func (m *GetStateConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStateConfigResponse.Marshal(b, m, deterministic)
}
func (m *GetStateConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStateConfigResponse.Merge(m, src)
}
func (m *GetStateConfigResponse) XXX_Size() int {
	return xxx_messageInfo_GetStateConfigResponse.Size(m)
}
func (m *GetStateConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStateConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetStateConfigResponse proto.InternalMessageInfo

func (m *GetStateConfigResponse) GetConfigState() map[string]*FileMetaState {
	if m != nil {
		return m.ConfigState
	}
	return nil
}

func (m *GetStateConfigResponse) GetDirectorState() map[string]*FileMetaState {
	if m != nil {
		return m.DirectorState
	}
	return nil
}

func (m *GetStateConfigResponse) GetTargetFilenames() map[string]string {
	if m != nil {
		return m.TargetFilenames
	}
	return nil
}

type TracerPredicateV1 struct {
	ClientID             string   `protobuf:"bytes,1,opt,name=clientID,proto3" json:"clientID,omitempty"`
	Service              string   `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Environment          string   `protobuf:"bytes,3,opt,name=environment,proto3" json:"environment,omitempty"`
	AppVersion           string   `protobuf:"bytes,4,opt,name=appVersion,proto3" json:"appVersion,omitempty"`
	TracerVersion        string   `protobuf:"bytes,5,opt,name=tracerVersion,proto3" json:"tracerVersion,omitempty"`
	Language             string   `protobuf:"bytes,6,opt,name=language,proto3" json:"language,omitempty"`
	RuntimeID            string   `protobuf:"bytes,7,opt,name=runtimeID,proto3" json:"runtimeID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TracerPredicateV1) Reset()         { *m = TracerPredicateV1{} }
func (m *TracerPredicateV1) String() string { return proto.CompactTextString(m) }
func (*TracerPredicateV1) ProtoMessage()    {}
func (*TracerPredicateV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_e19cd78713df8f37, []int{19}
}

func (m *TracerPredicateV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TracerPredicateV1.Unmarshal(m, b)
}
func (m *TracerPredicateV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TracerPredicateV1.Marshal(b, m, deterministic)
}
func (m *TracerPredicateV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TracerPredicateV1.Merge(m, src)
}
func (m *TracerPredicateV1) XXX_Size() int {
	return xxx_messageInfo_TracerPredicateV1.Size(m)
}
func (m *TracerPredicateV1) XXX_DiscardUnknown() {
	xxx_messageInfo_TracerPredicateV1.DiscardUnknown(m)
}

var xxx_messageInfo_TracerPredicateV1 proto.InternalMessageInfo

func (m *TracerPredicateV1) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

func (m *TracerPredicateV1) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *TracerPredicateV1) GetEnvironment() string {
	if m != nil {
		return m.Environment
	}
	return ""
}

func (m *TracerPredicateV1) GetAppVersion() string {
	if m != nil {
		return m.AppVersion
	}
	return ""
}

func (m *TracerPredicateV1) GetTracerVersion() string {
	if m != nil {
		return m.TracerVersion
	}
	return ""
}

func (m *TracerPredicateV1) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *TracerPredicateV1) GetRuntimeID() string {
	if m != nil {
		return m.RuntimeID
	}
	return ""
}

type TracerPredicates struct {
	TracerPredicatesV1   []*TracerPredicateV1 `protobuf:"bytes,1,rep,name=tracer_predicates_v1,json=tracerPredicatesV1,proto3" json:"tracer_predicates_v1,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TracerPredicates) Reset()         { *m = TracerPredicates{} }
func (m *TracerPredicates) String() string { return proto.CompactTextString(m) }
func (*TracerPredicates) ProtoMessage()    {}
func (*TracerPredicates) Descriptor() ([]byte, []int) {
	return fileDescriptor_e19cd78713df8f37, []int{20}
}

func (m *TracerPredicates) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TracerPredicates.Unmarshal(m, b)
}
func (m *TracerPredicates) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TracerPredicates.Marshal(b, m, deterministic)
}
func (m *TracerPredicates) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TracerPredicates.Merge(m, src)
}
func (m *TracerPredicates) XXX_Size() int {
	return xxx_messageInfo_TracerPredicates.Size(m)
}
func (m *TracerPredicates) XXX_DiscardUnknown() {
	xxx_messageInfo_TracerPredicates.DiscardUnknown(m)
}

var xxx_messageInfo_TracerPredicates proto.InternalMessageInfo

func (m *TracerPredicates) GetTracerPredicatesV1() []*TracerPredicateV1 {
	if m != nil {
		return m.TracerPredicatesV1
	}
	return nil
}

func init() {
	proto.RegisterType((*ConfigMetas)(nil), "datadog.config.ConfigMetas")
	proto.RegisterType((*DirectorMetas)(nil), "datadog.config.DirectorMetas")
	proto.RegisterType((*DelegatedMeta)(nil), "datadog.config.DelegatedMeta")
	proto.RegisterType((*TopMeta)(nil), "datadog.config.TopMeta")
	proto.RegisterType((*File)(nil), "datadog.config.File")
	proto.RegisterType((*LatestConfigsRequest)(nil), "datadog.config.LatestConfigsRequest")
	proto.RegisterType((*LatestConfigsResponse)(nil), "datadog.config.LatestConfigsResponse")
	proto.RegisterType((*OrgDataResponse)(nil), "datadog.config.OrgDataResponse")
	proto.RegisterType((*Client)(nil), "datadog.config.Client")
	proto.RegisterType((*ClientTracer)(nil), "datadog.config.ClientTracer")
	proto.RegisterType((*ClientAgent)(nil), "datadog.config.ClientAgent")
	proto.RegisterType((*ConfigState)(nil), "datadog.config.ConfigState")
	proto.RegisterType((*ClientState)(nil), "datadog.config.ClientState")
	proto.RegisterType((*TargetFileHash)(nil), "datadog.config.TargetFileHash")
	proto.RegisterType((*TargetFileMeta)(nil), "datadog.config.TargetFileMeta")
	proto.RegisterType((*ClientGetConfigsRequest)(nil), "datadog.config.ClientGetConfigsRequest")
	proto.RegisterType((*ClientGetConfigsResponse)(nil), "datadog.config.ClientGetConfigsResponse")
	proto.RegisterType((*FileMetaState)(nil), "datadog.config.FileMetaState")
	proto.RegisterType((*GetStateConfigResponse)(nil), "datadog.config.GetStateConfigResponse")
	proto.RegisterMapType((map[string]*FileMetaState)(nil), "datadog.config.GetStateConfigResponse.ConfigStateEntry")
	proto.RegisterMapType((map[string]*FileMetaState)(nil), "datadog.config.GetStateConfigResponse.DirectorStateEntry")
	proto.RegisterMapType((map[string]string)(nil), "datadog.config.GetStateConfigResponse.TargetFilenamesEntry")
	proto.RegisterType((*TracerPredicateV1)(nil), "datadog.config.TracerPredicateV1")
	proto.RegisterType((*TracerPredicates)(nil), "datadog.config.TracerPredicates")
}

func init() {
	proto.RegisterFile("remoteconfig.proto", fileDescriptor_e19cd78713df8f37)
}

var fileDescriptor_e19cd78713df8f37 = []byte{
	// 1452 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x58, 0xcb, 0x8e, 0xdc, 0x44,
	0x17, 0x96, 0xbb, 0xdd, 0xb7, 0xd3, 0x97, 0xe9, 0xd4, 0xdf, 0x7f, 0x62, 0x66, 0x26, 0xc9, 0xc4,
	0x22, 0x90, 0x05, 0x4c, 0x98, 0x44, 0x21, 0x40, 0x14, 0x44, 0x92, 0x1e, 0x72, 0x11, 0x90, 0xc8,
	0x33, 0x9a, 0x45, 0x24, 0x64, 0x6a, 0xdc, 0x15, 0xb7, 0x15, 0xb7, 0x6d, 0x5c, 0xd5, 0x1d, 0xcd,
	0x8e, 0x77, 0x60, 0xc5, 0x2b, 0x44, 0x3c, 0x05, 0x6f, 0xc0, 0x86, 0x1d, 0x4f, 0xc0, 0x82, 0x57,
	0x40, 0x75, 0x73, 0x97, 0xdd, 0xd3, 0xc3, 0x08, 0xb1, 0x60, 0x57, 0xa7, 0x7c, 0xce, 0xa9, 0x3a,
	0xb7, 0xef, 0x2b, 0x19, 0x50, 0x4e, 0x66, 0x29, 0x23, 0x41, 0x9a, 0xbc, 0x8a, 0xc2, 0xdd, 0x2c,
	0x4f, 0x59, 0x8a, 0x06, 0x13, 0xcc, 0xf0, 0x24, 0x0d, 0x77, 0xe5, 0xae, 0xfb, 0x73, 0x0d, 0xba,
	0x8f, 0xc4, 0xf2, 0x6b, 0xc2, 0x30, 0x45, 0x1f, 0x42, 0x23, 0x4f, 0x53, 0x46, 0x1d, 0x6b, 0xa7,
	0x7e, 0xa3, 0x7b, 0xeb, 0xd2, 0x6e, 0x59, 0x7f, 0xf7, 0x30, 0xcd, 0xb8, 0xa2, 0x27, 0xb5, 0xd0,
	0x1d, 0xe8, 0xb0, 0x68, 0x46, 0x28, 0xc3, 0xb3, 0xcc, 0xa9, 0xed, 0x58, 0x67, 0x99, 0x2c, 0x35,
	0xd1, 0x6d, 0x68, 0xd3, 0x04, 0x67, 0x74, 0x9a, 0x32, 0xa7, 0x7e, 0xb6, 0x55, 0xa1, 0x88, 0xee,
	0x02, 0xb0, 0x34, 0x3b, 0xc4, 0x79, 0x48, 0x18, 0x75, 0xec, 0xb3, 0xcd, 0x0c, 0x55, 0xf4, 0x14,
	0x86, 0x13, 0x12, 0x93, 0x10, 0x33, 0x32, 0xd1, 0xe6, 0x0d, 0x11, 0xde, 0xe5, 0xaa, 0xf9, 0x58,
	0xeb, 0x09, 0x27, 0x2b, 0x66, 0xee, 0xef, 0x16, 0xf4, 0xc7, 0x51, 0x4e, 0x02, 0x96, 0xe6, 0xff,
	0xf9, 0x84, 0xed, 0x41, 0x8b, 0x9d, 0x2f, 0x5b, 0x5a, 0xcf, 0x7d, 0x0e, 0xfd, 0x52, 0x0a, 0x90,
	0x03, 0xad, 0x05, 0xc9, 0x69, 0x94, 0x26, 0x8e, 0xb5, 0x63, 0xdd, 0xb0, 0x3d, 0x2d, 0x22, 0x04,
	0x76, 0x9e, 0xc6, 0x44, 0x04, 0xd1, 0xf1, 0xc4, 0x1a, 0x0d, 0xa1, 0x9e, 0xe3, 0x37, 0xe2, 0x86,
	0x3d, 0x8f, 0x2f, 0xdd, 0x3b, 0xd0, 0x52, 0x87, 0x9c, 0xe1, 0x4a, 0x99, 0xd5, 0x96, 0x66, 0x1f,
	0x80, 0xfd, 0x65, 0x14, 0x13, 0x7e, 0x48, 0x86, 0xd9, 0x54, 0x18, 0x74, 0x3c, 0xb1, 0x3e, 0x45,
	0xfb, 0xad, 0x0d, 0xa3, 0xaf, 0x30, 0x23, 0x94, 0xc9, 0x56, 0xa6, 0x1e, 0xf9, 0x7e, 0x4e, 0x28,
	0x43, 0x9b, 0xd0, 0x9e, 0xa6, 0x94, 0x25, 0x78, 0x46, 0x94, 0x8b, 0x42, 0x46, 0x2e, 0xf4, 0x70,
	0x48, 0x12, 0x76, 0xa4, 0xee, 0x24, 0xe3, 0x28, 0xed, 0xa1, 0x7d, 0xb8, 0x1a, 0xcc, 0xf3, 0x9c,
	0x24, 0xcc, 0x97, 0x19, 0xf3, 0x75, 0x72, 0x7d, 0x1d, 0x4a, 0x5d, 0x84, 0xb2, 0xad, 0xd4, 0xe4,
	0xf9, 0x07, 0x4a, 0x49, 0xbb, 0xb9, 0x0f, 0x5b, 0x15, 0x37, 0xbc, 0x19, 0x0a, 0x17, 0x1d, 0xe1,
	0xc2, 0x29, 0xb9, 0xf0, 0xd2, 0xa5, 0xf9, 0x03, 0xb8, 0xac, 0xcd, 0x27, 0xaa, 0xf7, 0xca, 0x0e,
	0xda, 0xc2, 0xc1, 0xa6, 0x52, 0xd2, 0xfd, 0x69, 0xba, 0xd8, 0x84, 0x76, 0x96, 0xa7, 0x93, 0x79,
	0x20, 0x7a, 0xa1, 0xce, 0x13, 0xa1, 0x65, 0x74, 0x0d, 0x7a, 0x09, 0x79, 0xe3, 0x17, 0xdf, 0x1b,
	0xe2, 0x7b, 0x37, 0x21, 0x6f, 0x5e, 0x68, 0x95, 0xfb, 0x30, 0xc0, 0x01, 0x8b, 0x16, 0xc4, 0x0f,
	0xe2, 0x88, 0x24, 0x8c, 0x3a, 0x4d, 0xd1, 0xed, 0x17, 0xab, 0x0d, 0xf5, 0x48, 0x7c, 0xf6, 0xfa,
	0x52, 0x5b, 0x4a, 0x14, 0x7d, 0x04, 0xa3, 0x63, 0x1c, 0xbc, 0x26, 0xc9, 0x44, 0xd9, 0xfb, 0x94,
	0x61, 0x46, 0x1c, 0x10, 0x25, 0x44, 0xea, 0x9b, 0xd4, 0x3e, 0xe0, 0x5f, 0xd0, 0x16, 0x74, 0xa6,
	0x98, 0xfa, 0x24, 0xcf, 0xd3, 0xdc, 0xe9, 0xee, 0x58, 0x37, 0xda, 0x5e, 0x7b, 0x8a, 0xe9, 0x3e,
	0x97, 0xd1, 0x08, 0x1a, 0xf2, 0x43, 0x4f, 0x94, 0x4c, 0x0a, 0xe8, 0x3d, 0xd8, 0x60, 0x39, 0x0e,
	0x88, 0x2f, 0x2a, 0xe8, 0x93, 0x64, 0xe1, 0xf4, 0xc5, 0xf7, 0xbe, 0xd8, 0x7e, 0xc0, 0x77, 0xf7,
	0x93, 0x85, 0xfb, 0x9b, 0x05, 0xff, 0xaf, 0x34, 0x0b, 0xcd, 0xd2, 0x84, 0x12, 0xf4, 0x39, 0xf4,
	0x54, 0x79, 0x66, 0x7c, 0xb4, 0x45, 0xc7, 0x74, 0x6f, 0x6d, 0xad, 0xc4, 0xb8, 0x84, 0x4b, 0xaf,
	0x1b, 0x18, 0xd8, 0x39, 0x86, 0x41, 0x51, 0x1f, 0xe9, 0x41, 0x0e, 0xf8, 0x2a, 0xca, 0x98, 0x08,
	0xe2, 0xf5, 0x27, 0x25, 0x40, 0xb9, 0x0b, 0x3d, 0x39, 0x8d, 0xfe, 0xab, 0x28, 0x26, 0xd4, 0xa9,
	0x8b, 0x4c, 0x8f, 0xaa, 0x3e, 0xf8, 0x78, 0x78, 0x5d, 0xa9, 0xc9, 0xd7, 0xd4, 0xbd, 0x0e, 0x1b,
	0xcf, 0xf3, 0x70, 0x8c, 0x19, 0x2e, 0x22, 0x42, 0x60, 0xcf, 0xe7, 0xd1, 0x44, 0x8f, 0x0f, 0x5f,
	0xbb, 0x7f, 0xd6, 0xa0, 0x29, 0x53, 0x8d, 0xf6, 0xa0, 0x21, 0x0b, 0xb1, 0x2e, 0xd2, 0x65, 0x45,
	0x3c, 0xa9, 0x89, 0x06, 0x50, 0x8b, 0x26, 0x6a, 0x56, 0x6a, 0xd1, 0xa4, 0xd4, 0x58, 0xf5, 0x4a,
	0x63, 0x6d, 0x41, 0x27, 0xa2, 0xbe, 0xc8, 0x7e, 0xee, 0x34, 0x65, 0x11, 0x23, 0x7a, 0x28, 0x64,
	0xf4, 0x00, 0xfa, 0xaa, 0x17, 0x94, 0x42, 0x4b, 0xdc, 0x61, 0xfb, 0xf4, 0x3b, 0x48, 0x23, 0xaf,
	0x17, 0x18, 0x12, 0x7a, 0x07, 0xda, 0x11, 0x95, 0xe5, 0x16, 0x23, 0xd0, 0xf6, 0x5a, 0x11, 0x15,
	0x75, 0x16, 0xa5, 0x94, 0xde, 0xe5, 0xe7, 0xce, 0x59, 0x01, 0x0a, 0x13, 0xaf, 0x1b, 0x2c, 0x05,
	0x7e, 0xf5, 0x18, 0x53, 0xe6, 0x53, 0x42, 0x12, 0xd1, 0xa6, 0xb6, 0xd7, 0xe6, 0x1b, 0x07, 0x84,
	0x24, 0x1c, 0x39, 0x02, 0x9c, 0xe1, 0xe3, 0x28, 0x8e, 0x58, 0x44, 0xa8, 0xe8, 0xcf, 0x9e, 0x57,
	0xda, 0x7b, 0x66, 0xb7, 0xed, 0x61, 0xe3, 0x99, 0xdd, 0x6e, 0x0c, 0x9b, 0xee, 0xaf, 0x16, 0xf4,
	0xcc, 0x30, 0xd0, 0x65, 0x80, 0x7c, 0x9e, 0x70, 0x74, 0xf7, 0x8b, 0xe2, 0x74, 0xd4, 0xce, 0x53,
	0x91, 0xd3, 0x18, 0x27, 0xe1, 0x1c, 0x87, 0x1a, 0x5d, 0x0b, 0x19, 0x5d, 0x87, 0x81, 0xcc, 0x57,
	0x09, 0x80, 0x74, 0x93, 0xe7, 0x7a, 0xde, 0x1d, 0x68, 0x51, 0x92, 0x2f, 0xa2, 0x80, 0x08, 0xe8,
	0xef, 0x78, 0x5a, 0xe4, 0xe8, 0xc9, 0x47, 0xa3, 0x21, 0x76, 0xf9, 0x12, 0x5d, 0x85, 0x2e, 0xce,
	0xb2, 0xc2, 0x5f, 0x53, 0x7c, 0x01, 0x9c, 0x65, 0x47, 0x4b, 0xa4, 0x67, 0x38, 0xa4, 0x4e, 0x4b,
	0xd4, 0x57, 0xac, 0xdd, 0x7b, 0xd0, 0x35, 0x92, 0xc7, 0x55, 0x0c, 0x90, 0x15, 0x6b, 0x13, 0xef,
	0x65, 0x14, 0x5a, 0x74, 0x7f, 0xb4, 0xf4, 0xa3, 0xe3, 0xc0, 0x68, 0x2a, 0xab, 0x68, 0xaa, 0x8a,
	0xa5, 0xc1, 0x14, 0x0e, 0xb4, 0x54, 0x7b, 0xa9, 0xb8, 0xb5, 0xa8, 0xa2, 0x88, 0x4f, 0x14, 0xb4,
	0xd8, 0xc2, 0x0e, 0xc4, 0x96, 0x3c, 0xa4, 0x50, 0x90, 0xd8, 0xd1, 0x28, 0xc2, 0x8c, 0x4f, 0x04,
	0xac, 0xb8, 0x3f, 0xd4, 0x74, 0x4c, 0xd2, 0xe0, 0x1a, 0xf4, 0x4a, 0x28, 0x2b, 0x49, 0xab, 0x9b,
	0x1b, 0xb0, 0xfa, 0x3e, 0x6c, 0x28, 0xe6, 0xf4, 0xcb, 0x17, 0x1e, 0xa8, 0x6d, 0xad, 0xf8, 0x05,
	0xf4, 0x35, 0x81, 0x70, 0xdf, 0x7a, 0xaa, 0xd7, 0x60, 0x8b, 0x9c, 0x38, 0x05, 0x46, 0x42, 0xa0,
	0x65, 0x44, 0xb4, 0xd7, 0x21, 0x62, 0xc3, 0x44, 0xc4, 0x75, 0xb0, 0xdb, 0x5c, 0x07, 0xbb, 0xee,
	0x13, 0x18, 0x1c, 0x16, 0x88, 0xf2, 0x04, 0xd3, 0x29, 0xda, 0x86, 0x0e, 0x8e, 0xc3, 0x34, 0x8f,
	0xd8, 0x74, 0xa6, 0x3b, 0xb5, 0xd8, 0xe0, 0x65, 0x9f, 0x62, 0x3a, 0x55, 0xb5, 0x10, 0xeb, 0x67,
	0x76, 0xbb, 0x36, 0xac, 0xbb, 0xcc, 0xf4, 0x24, 0xe8, 0xff, 0x34, 0x2a, 0xbf, 0x08, 0xcd, 0x98,
	0x24, 0x21, 0x9b, 0x8a, 0xb4, 0xd5, 0x3d, 0x25, 0xa1, 0x8f, 0xa1, 0xc9, 0x7d, 0x15, 0x79, 0xba,
	0xb2, 0xf2, 0x70, 0x29, 0xdd, 0xd2, 0x53, 0xda, 0xee, 0x4f, 0x16, 0x5c, 0x92, 0xf1, 0x3c, 0x26,
	0xd5, 0xb7, 0xc0, 0x2e, 0x34, 0x65, 0x16, 0x14, 0xda, 0xad, 0xe3, 0x2e, 0xa5, 0x85, 0xbe, 0x81,
	0xff, 0x05, 0x38, 0x98, 0x92, 0x89, 0x5f, 0x82, 0xe3, 0xda, 0xdf, 0x5d, 0x48, 0x3c, 0xa8, 0x2e,
	0x48, 0xd3, 0x43, 0x03, 0x9e, 0xdf, 0x5a, 0xe0, 0xac, 0xde, 0x4d, 0x01, 0xf5, 0xc8, 0x7c, 0x45,
	0xf6, 0xf4, 0x63, 0xd1, 0x59, 0x3e, 0xe0, 0xe4, 0x6b, 0x47, 0x8b, 0xff, 0x98, 0x24, 0x38, 0x7e,
	0xa8, 0x5e, 0x90, 0x2a, 0xfa, 0x39, 0xa0, 0xc0, 0x58, 0xdd, 0xcb, 0xbd, 0x0f, 0x7d, 0x1d, 0x8b,
	0x1c, 0x86, 0x33, 0xdf, 0x81, 0xa2, 0x07, 0x6a, 0xcb, 0x1e, 0x70, 0x7f, 0xb1, 0xe1, 0xe2, 0x63,
	0x22, 0x9b, 0x4a, 0xbd, 0x67, 0x74, 0xa4, 0x2f, 0x0b, 0x92, 0xd5, 0xd4, 0xc3, 0x6f, 0x7e, 0xb7,
	0x7a, 0xf3, 0xd3, 0xad, 0xcd, 0xf9, 0xd8, 0x4f, 0x58, 0x7e, 0xa2, 0x09, 0x58, 0x5e, 0xf2, 0x3b,
	0x83, 0x80, 0xa5, 0x77, 0x59, 0xad, 0x4f, 0xcf, 0xe9, 0x5d, 0xf3, 0xb2, 0xe1, 0xbf, 0x20, 0x67,
	0x79, 0xc2, 0x2b, 0x18, 0x1a, 0x79, 0xe7, 0x30, 0xa7, 0x73, 0x7f, 0xef, 0x9c, 0x67, 0x2c, 0x5b,
	0x42, 0x58, 0xcb, 0x53, 0x36, 0x58, 0x79, 0x77, 0xf3, 0x5b, 0x18, 0x56, 0x43, 0xe5, 0xc8, 0xfd,
	0x9a, 0x9c, 0xa8, 0xf9, 0xe1, 0x4b, 0x74, 0x1b, 0x1a, 0x0b, 0x1c, 0xcf, 0xc9, 0xba, 0x77, 0x46,
	0xa9, 0x84, 0x9e, 0xd4, 0xfd, 0xac, 0xf6, 0x89, 0xb5, 0xe9, 0x03, 0x5a, 0x8d, 0xf5, 0xdf, 0x3c,
	0xe0, 0x21, 0x8c, 0x4e, 0x0b, 0xf4, 0x94, 0x23, 0x46, 0xe6, 0x11, 0x1d, 0xc3, 0x87, 0xfb, 0x87,
	0x05, 0x17, 0x24, 0x61, 0xbe, 0xc8, 0xc9, 0x24, 0x0a, 0x30, 0x23, 0x47, 0x7b, 0x9c, 0x1c, 0x65,
	0xab, 0x3e, 0x1d, 0xeb, 0x27, 0xbd, 0x96, 0x4d, 0xd6, 0xab, 0x95, 0x59, 0x6f, 0x07, 0xba, 0x24,
	0x59, 0x44, 0x79, 0x9a, 0xcc, 0x38, 0x02, 0x48, 0xbc, 0x32, 0xb7, 0xd0, 0x15, 0x30, 0x28, 0x4f,
	0x91, 0xa6, 0x49, 0x82, 0xef, 0x42, 0x99, 0x62, 0x15, 0xd4, 0x56, 0x78, 0xd7, 0xa4, 0xee, 0x66,
	0x85, 0xba, 0xb7, 0xa1, 0xe0, 0xf8, 0xb1, 0x78, 0xed, 0x18, 0xa4, 0x3f, 0x76, 0x43, 0x18, 0x56,
	0x82, 0xa5, 0xe8, 0x00, 0x46, 0x8a, 0xec, 0xb3, 0x62, 0xd3, 0x5f, 0xec, 0xa9, 0x99, 0xb9, 0xb6,
	0x82, 0x41, 0xd5, 0x64, 0x79, 0x88, 0x55, 0x5c, 0x1e, 0xed, 0x3d, 0x1c, 0xbe, 0x1c, 0x64, 0xaf,
	0xc3, 0x9b, 0xe2, 0x77, 0xc0, 0xcd, 0xec, 0x38, 0x4c, 0x8f, 0x9b, 0x62, 0x7d, 0xfb, 0xaf, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x72, 0xa4, 0x77, 0xd8, 0x30, 0x10, 0x00, 0x00,
}
