load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

go_library(
    name = "impl",
    srcs = ["fleetstatus.go"],
    embedsrcs = [
        "status_templates/fleetstatus.tmpl",
        "status_templates/fleetstatusHTML.tmpl",
    ],
    importpath = "github.com/DataDog/datadog-agent/comp/fleetstatus/impl",
    visibility = ["//visibility:public"],
    deps = [
        "//comp/core/config",
        "//comp/core/status",
        "//comp/updater/localapiclient/def",
        "//pkg/proto/pbgo/core",
    ],
)

dd_agent_go_test(
    name = "impl_test",
    srcs = ["fleetstatus_test.go"],
    embed = [":impl"],
    deps = [
        "//comp/core/config",
        "//comp/updater/localapi/def",
        "//comp/updater/localapiclient/def",
        "//pkg/proto/pbgo/core",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
