load("@rules_go//go:def.bzl", "go_library")

package(default_package_metadata = ["//pkg/template:go_package_metadata"])

go_library(
    name = "text",
    srcs = [
        "doc.go",
        "exec.go",
        "funcs.go",
        "helper.go",
        "option.go",
        "template.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/pkg/template/text",
    visibility = ["//visibility:public"],
    deps = ["//pkg/template/internal/fmtsort"],
)
