load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "byohost",
    srcs = ["descriptor.go"],
    importpath = "github.com/DataDog/datadog-agent/test/e2e-framework/testing/provisioners/local/host/byohost",
    visibility = ["//visibility:public"],
    deps = [
        "//test/e2e-framework/components",
        "//test/e2e-framework/components/os",
        "//test/e2e-framework/components/remote",
    ],
)
