load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "btf",
    srcs = ["cache.go"],
    importpath = "github.com/DataDog/datadog-agent/pkg/ebpf/btf",
    visibility = ["//visibility:public"],
    deps = select({
        "@rules_go//go/platform:android": [
            "@com_github_cilium_ebpf//btf",
        ],
        "@rules_go//go/platform:linux": [
            "@com_github_cilium_ebpf//btf",
        ],
        "//conditions:default": [],
    }),
)
