load("@rules_go//go:def.bzl", "go_binary", "go_library")
load("//bazel/rules/go_package_metadata:defs.bzl", "go_package_metadata")

package(default_package_metadata = [":go_package_metadata"])

go_package_metadata(
    name = "go_package_metadata",
    module = "github.com/DataDog/datadog-agent/internal/tools/independent-lint",
)

go_library(
    name = "independent-lint_lib",
    srcs = ["independent.go"],
    importpath = "github.com/DataDog/datadog-agent/internal/tools/independent-lint",
    visibility = ["//visibility:private"],
    deps = [
        "@org_golang_x_mod//modfile",
        "@org_golang_x_mod//module",
    ],
)

go_binary(
    name = "independent-lint",
    embed = [":independent-lint_lib"],
    visibility = ["//:__subpackages__"],
)
