load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

go_library(
    name = "installer",
    srcs = [
        "default_packages.go",
        "installer.go",
        "installer_darwin.go",
        "installer_ocipkg.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/pkg/fleet/installer",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/fleet/installer/config",
        "//pkg/fleet/installer/db",
        "//pkg/fleet/installer/env",
        "//pkg/fleet/installer/errors",
        "//pkg/fleet/installer/oci",
        "//pkg/fleet/installer/packages",
        "//pkg/fleet/installer/packages/extensions",
        "//pkg/fleet/installer/paths",
        "//pkg/fleet/installer/repository",
        "//pkg/fleet/installer/telemetry",
        "//pkg/util/log",
        "//pkg/version",
    ] + select({
        "@rules_go//go/platform:darwin": [
            "//pkg/fleet/installer/macpkg",
        ],
        "@rules_go//go/platform:ios": [
            "//pkg/fleet/installer/macpkg",
        ],
        "//conditions:default": [],
    }),
)

dd_agent_go_test(
    name = "installer_test",
    srcs = [
        "default_packages_test.go",
        "installer_darwin_test.go",
        "installer_ocipkg_test.go",
        "installer_test.go",
    ],
    embed = [":installer"],
    deps = [
        "//pkg/fleet/installer/config",
        "//pkg/fleet/installer/db",
        "//pkg/fleet/installer/env",
        "//pkg/fleet/installer/fixtures",
        "//pkg/fleet/installer/oci",
        "//pkg/fleet/installer/packages",
        "//pkg/fleet/installer/packages/extensions",
        "//pkg/fleet/installer/repository",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//mock",
    ] + select({
        "@rules_go//go/platform:darwin": [
            "//pkg/fleet/installer/macpkg",
            "@com_github_stretchr_testify//require",
        ],
        "@rules_go//go/platform:ios": [
            "//pkg/fleet/installer/macpkg",
            "@com_github_stretchr_testify//require",
        ],
        "//conditions:default": [],
    }),
)
