load("@rules_go//go:def.bzl", "go_library")

package(default_package_metadata = ["//test/fakeintake:go_package_metadata"])

go_library(
    name = "flare",
    srcs = [
        "flare.go",
        "parse_flare.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/test/fakeintake/client/flare",
    visibility = ["//visibility:public"],
    deps = ["//test/fakeintake/api"],
)
