[package]
name = "dd-procmgrd"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[features]
test-helpers = []

[lib]
name = "dd_procmgrd"
path = "src/lib.rs"
doctest = false

[[bin]]
name = "dd-procmgrd"
path = "src/bins/dd-procmgrd.rs"

[[bin]]
name = "dd-procmgr"
path = "src/bins/dd-procmgr.rs"

[dependencies]
anyhow.workspace = true
clap = { workspace = true, features = ["derive"] }
log.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
serde_yaml.workspace = true
dd-agent-log.workspace = true
dd-procmgr-client.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "signal", "process", "fs", "time", "sync"] }
tokio-stream = { workspace = true, features = ["net"] }
tonic = { workspace = true, features = ["transport"] }
tonic-reflection.workspace = true
uuid.workspace = true

[target.'cfg(unix)'.dependencies]
libc.workspace = true
nix = { workspace = true, features = ["signal", "process", "user"] }

[target.'cfg(windows)'.dependencies]
windows-registry.workspace = true
windows-sys = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_System_JobObjects",
    "Win32_System_Services",
    "Win32_System_Threading",
    "Win32_System_Console",
    "Win32_System_Environment",
    "Win32_Security",
    "Win32_Security_Authorization",
    "Win32_Security_Authentication_Identity",
    "Win32_System_Registry",
    "Win32_System_WindowsProgramming",
    "Win32_Storage_FileSystem",
    "Win32_UI_Shell",
] }

[target.'cfg(unix)'.dev-dependencies]
nix = { workspace = true, features = ["signal", "process", "user"] }

[dev-dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tempfile.workspace = true

[[test]]
name = "e2e"
path = "tests/e2e/main.rs"
required-features = ["test-helpers"]
