load("@rules_go//go:def.bzl", "go_library")

package(default_package_metadata = ["//pkg/trace:go_package_metadata"])

go_library(
    name = "pb",
    srcs = ["util.go"],
    importpath = "github.com/DataDog/datadog-agent/pkg/trace/pb",
    visibility = ["//visibility:public"],
    deps = ["@org_golang_google_protobuf//runtime/protoiface"],
)
