load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "impl",
    srcs = ["statusapi.go"],
    importpath = "github.com/DataDog/datadog-agent/comp/updater/statusapi/impl",
    visibility = ["//visibility:public"],
    deps = [
        "//comp/def",
        "//comp/updater/statusapi/def",
        "//comp/updater/updater/def",
        "//pkg/fleet/daemon",
    ],
)
