load("@rules_go//go:def.bzl", "go_library")

package(default_package_metadata = ["//comp/forwarder/defaultforwarder:go_package_metadata"])

go_library(
    name = "endpoints",
    srcs = ["endpoints.go"],
    importpath = "github.com/DataDog/datadog-agent/comp/forwarder/defaultforwarder/endpoints",
    visibility = ["//visibility:public"],
    deps = ["//comp/forwarder/defaultforwarder/transaction"],
)
