load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

go_library(
    name = "remote-config",
    srcs = ["remoteconfig.go"],
    importpath = "github.com/DataDog/datadog-agent/test/new-e2e/tests/remote-config",
    visibility = ["//visibility:public"],
)

dd_agent_go_test(
    name = "remote-config_test",
    srcs = [
        "mrf_logs_service_allowlist_test.go",
        "rc_ssl_config_test.go",
        "tracer_test.go",
        "utils_test.go",
    ],
    data = [
        "fixtures/rc-enabled.yaml",
        "fixtures/ssl_mismatch.yaml",
        "fixtures/tracer-payload.json",
    ],
    embed = [":remote-config"],
    embedsrcs = [
        "fixtures/rc-enabled.yaml",
        "fixtures/ssl_mismatch.yaml",
        "fixtures/tracer-payload.json",
    ],
    tags = ["manual"],
    deps = [
        "//test/e2e-framework/components/datadog/agent",
        "//test/e2e-framework/components/datadog/agentparams",
        "//test/e2e-framework/components/datadog/fakeintake",
        "//test/e2e-framework/resources/aws",
        "//test/e2e-framework/scenarios/aws/ec2",
        "//test/e2e-framework/scenarios/aws/fakeintake",
        "//test/e2e-framework/testing/components",
        "//test/e2e-framework/testing/e2e",
        "//test/e2e-framework/testing/environments",
        "//test/e2e-framework/testing/provisioners",
        "//test/e2e-framework/testing/provisioners/aws/host",
        "//test/e2e-framework/testing/utils/common",
        "//test/e2e-framework/testing/utils/e2e/client",
        "//test/e2e-framework/testing/utils/e2e/client/agentclient",
        "//test/fakeintake/client",
        "@com_github_pulumi_pulumi_sdk_v3//go/pulumi",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
