//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by customaction.rc

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE 101
#define _APS_NEXT_COMMAND_VALUE 40001
#define _APS_NEXT_CONTROL_VALUE 1001
#define _APS_NEXT_SYMED_VALUE 101
#endif
#endif

#define RC_FILE_VERSION MAJ_VER, MIN_VER, PATCH_VER, 0

#define STRINGIFY(x) #x
#define TO_STRING(x) STRINGIFY(x)

#define FILE_VERSION_STRING TO_STRING(MAJ_VER.MIN_VER.PATCH_VER .0)

#define STRINGTABLE_BASE 100
#define IDS_DATADOG_PATH (STRINGTABLE_BASE + 0)
#define IDS_DATADOG_KEY_ROOT_BASE (STRINGTABLE_BASE + 1)
#define IDS_DATADOG_ACL_KEY_DATADOG_BASE (STRINGTABLE_BASE + 2)
#define IDS_DATADOG_KEY_PATH (STRINGTABLE_BASE + 3)

#define IDS_DATADOG_SERVICE_NAME (STRINGTABLE_BASE + 4)
#define IDS_DATADOG_AGENT_USER_NAME (STRINGTABLE_BASE + 5)
#define IDS_DATADOG_AGENT_USER_DESCRIPTION (STRINGTABLE_BASE + 6)

#define IDS_TRACE_SERVICE_NAME (STRINGTABLE_BASE + 7)
#define IDS_PROCESS_SERVICE_NAME (STRINGTABLE_BASE + 8)
#define IDS_AGENT_SERVICE_NAME (STRINGTABLE_BASE + 9)

#define IDS_PROPERTY_DDAGENTUSER (STRINGTABLE_BASE + 10)
#define IDS_PROPERTY_DDAGENTUSER_PASSWORD (STRINGTABLE_BASE + 11)
#define IDS_PROPERTY_PROGRAMDATA (STRINGTABLE_BASE + 12)
#define IDS_PROPERTY_PROGRAMFILESDIR (STRINGTABLE_BASE + 13)

#define IDS_LOGSSUFFIX (STRINGTABLE_BASE + 14)
#define IDS_AUTHTOKENSUFFIX (STRINGTABLE_BASE + 15)
#define IDS_DATADOGYAML (STRINGTABLE_BASE + 16)
#define IDS_INSTALLINFO (STRINGTABLE_BASE + 17)
#define IDS_CONFDSUFFIX (STRINGTABLE_BASE + 18)
#define IDS_LOGSDIRSUFFIX (STRINGTABLE_BASE + 19)
#define IDS_PROGRAMDATADATADOG (STRINGTABLE_BASE + 20)

#define IDS_REGKEY_ROLLBACK_KEY_NAME (STRINGTABLE_BASE + 21)
#define IDS_REGKEY_UNINSTALL_KEY_NAME (STRINGTABLE_BASE + 22)

#define IDS_AGENT_SYSTEM_PROBE_SERVICE_NAME (STRINGTABLE_BASE + 23)
#define IDS_REGKEY_INSTALLED_USER (STRINGTABLE_BASE + 24)
#define IDS_REGKEY_INSTALLED_DOMAIN (STRINGTABLE_BASE + 25)
#define IDS_REGKEY_CLOSEDSRC_ENABLED (STRINGTABLE_BASE + 26)

#define INSTALLTABLE_BASE 200
#define IDS_CREATED_DD_USER_NAME (INSTALLTABLE_BASE + 0)
#define IDS_CREATED_DD_USER_DOMAIN (INSTALLTABLE_BASE + 1)
#define IDS_INSTALLED_SERVICES (INSTALLTABLE_BASE + 2)
