load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

go_library(
    name = "httphelpers",
    srcs = [
        "client.go",
        "middleware.go",
        "vsock_dial_linux.go",
        "vsock_dial_other.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/comp/core/ipc/httphelpers",
    visibility = ["//visibility:public"],
    deps = [
        "//comp/core/ipc/def",
        "//pkg/config/model",
        "//pkg/util/log",
        "//pkg/util/system",
        "//pkg/util/system/socket",
    ] + select({
        "@rules_go//go/platform:aix": [
            "@com_github_mdlayher_vsock//:vsock",
        ],
        "@rules_go//go/platform:android": [
            "@com_github_mdlayher_socket//:socket",
            "@org_golang_x_sys//unix",
        ],
        "@rules_go//go/platform:darwin": [
            "@com_github_mdlayher_vsock//:vsock",
        ],
        "@rules_go//go/platform:dragonfly": [
            "@com_github_mdlayher_vsock//:vsock",
        ],
        "@rules_go//go/platform:freebsd": [
            "@com_github_mdlayher_vsock//:vsock",
        ],
        "@rules_go//go/platform:illumos": [
            "@com_github_mdlayher_vsock//:vsock",
        ],
        "@rules_go//go/platform:ios": [
            "@com_github_mdlayher_vsock//:vsock",
        ],
        "@rules_go//go/platform:js": [
            "@com_github_mdlayher_vsock//:vsock",
        ],
        "@rules_go//go/platform:linux": [
            "@com_github_mdlayher_socket//:socket",
            "@org_golang_x_sys//unix",
        ],
        "@rules_go//go/platform:netbsd": [
            "@com_github_mdlayher_vsock//:vsock",
        ],
        "@rules_go//go/platform:openbsd": [
            "@com_github_mdlayher_vsock//:vsock",
        ],
        "@rules_go//go/platform:osx": [
            "@com_github_mdlayher_vsock//:vsock",
        ],
        "@rules_go//go/platform:plan9": [
            "@com_github_mdlayher_vsock//:vsock",
        ],
        "@rules_go//go/platform:qnx": [
            "@com_github_mdlayher_vsock//:vsock",
        ],
        "@rules_go//go/platform:solaris": [
            "@com_github_mdlayher_vsock//:vsock",
        ],
        "@rules_go//go/platform:windows": [
            "@com_github_mdlayher_vsock//:vsock",
        ],
        "//conditions:default": [],
    }),
)

dd_agent_go_test(
    name = "httphelpers_test",
    srcs = ["client_test.go"],
    embed = [":httphelpers"],
    deps = [
        "//comp/core/config",
        "//comp/core/ipc/def",
        "//pkg/api/security/cert",
        "//pkg/config/model",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
