load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

go_library(
    name = "dockerhost",
    srcs = ["dockerhost.go"],
    importpath = "github.com/DataDog/datadog-agent/test/e2e-framework/cmd/e2ectl/internal/drivers/dockerhost",
    visibility = ["//test/e2e-framework/cmd/e2ectl:__subpackages__"],
    deps = [
        "//test/e2e-framework/cmd/e2ectl/internal/config",
        "//test/e2e-framework/cmd/e2ectl/internal/drivers/pulumiworker",
        "//test/e2e-framework/cmd/e2ectl/internal/envstore",
        "//test/e2e-framework/cmd/e2ectl/internal/installer",
        "//test/e2e-framework/cmd/e2ectl/workerclient",
        "//test/e2e-framework/cmd/internal/envconfig/dockerhost",
    ],
)

dd_agent_go_test(
    name = "dockerhost_test",
    srcs = ["dockerhost_test.go"],
    embed = [":dockerhost"],
    deps = [
        "//test/e2e-framework/cmd/e2ectl/workerclient",
    ],
)
