load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

go_library(
    name = "eksidentity",
    srcs = ["resolver.go"],
    importpath = "github.com/DataDog/datadog-agent/pkg/util/kubernetes/eksidentity",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/util/cache",
        "//pkg/util/ec2/tags",
        "//pkg/util/eks",
        "//pkg/util/kubernetes/cloudprovider",
        "//pkg/util/kubernetes/clustername",
    ],
)

dd_agent_go_test(
    name = "eksidentity_test",
    srcs = ["resolver_test.go"],
    embed = [":eksidentity"],
    deps = [
        "//pkg/util/cache",
        "//pkg/util/eks",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
