load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go_package_metadata:defs.bzl", "go_package_metadata")

package(default_package_metadata = [":go_package_metadata"])

go_package_metadata(
    name = "go_package_metadata",
    module = "github.com/DataDog/datadog-agent/comp/otelcol/logsagentpipeline/logsagentpipelineimpl",
)

go_library(
    name = "logsagentpipelineimpl",
    srcs = ["logsagentpipeline.go"],
    importpath = "github.com/DataDog/datadog-agent/comp/otelcol/logsagentpipeline/logsagentpipelineimpl",
    visibility = ["//visibility:public"],
    deps = [
        "//comp/otelcol/logsagentpipeline/def",
        "//comp/otelcol/logsagentpipeline/fx",
        "//comp/otelcol/logsagentpipeline/impl",
        "//pkg/util/fxutil",
    ],
)
