load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

go_library(
    name = "impl-trace",
    srcs = ["remoteagent.go"],
    importpath = "github.com/DataDog/datadog-agent/comp/core/remoteagent/impl-trace",
    visibility = ["//visibility:public"],
    deps = [
        "//comp/core/config",
        "//comp/core/ipc/def",
        "//comp/core/log/def",
        "//comp/core/remoteagent/def",
        "//comp/core/remoteagent/helper",
        "//comp/def",
        "//comp/trace/status/def",
        "//pkg/proto/pbgo/core",
        "//pkg/util/flavor",
        "@org_golang_google_grpc//:grpc",
    ],
)

dd_agent_go_test(
    name = "impl-trace_test",
    srcs = ["remoteagent_test.go"],
    embed = [":impl-trace"],
    deps = [
        "//pkg/proto/pbgo/core",
        "@com_github_stretchr_testify//require",
        "@org_golang_google_grpc//:grpc",
    ],
)
