load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

go_library(
    name = "eudm",
    srcs = ["hostname.go"],
    importpath = "github.com/DataDog/datadog-agent/pkg/util/hostname/eudm",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/inventory/systeminfo",
        "//pkg/util/hostname/validate",
    ],
)

dd_agent_go_test(
    name = "eudm_test",
    srcs = ["hostname_test.go"],
    embed = [":eudm"],
    deps = [
        "//pkg/inventory/systeminfo",
        "@com_github_stretchr_testify//require",
    ],
)
