load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

go_library(
    name = "connectcmd",
    srcs = [
        "connect.go",
        "kube.go",
        "ssh.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/test/e2e-framework/cmd/e2ectl/internal/connectcmd",
    visibility = ["//test/e2e-framework/cmd/e2ectl:__subpackages__"],
    deps = [
        "//test/e2e-framework/cmd/e2ectl/internal/envstore",
        "//test/e2e-framework/cmd/e2ectl/internal/localinfra",
        "//test/e2e-framework/components/outputs",
        "//test/e2e-framework/testing/provisioner",
        "//test/e2e-framework/testing/runner",
        "//test/e2e-framework/testing/runner/parameters",
        "@io_k8s_client_go//tools/clientcmd",
        "@io_k8s_client_go//tools/clientcmd/api",
    ],
)

dd_agent_go_test(
    name = "connectcmd_test",
    srcs = ["connect_test.go"],
    embed = [":connectcmd"],
    deps = [
        "//test/e2e-framework/cmd/e2ectl/internal/envstore",
        "//test/e2e-framework/testing/provisioner",
        "@io_k8s_client_go//tools/clientcmd",
    ],
)
