"""Toolchain to wrap the pkgbuild binary.

Type: @macos_pkgbuild//:tool_toolchain_type

Toolchains:
- @macos_pkgbuild//:macos_pkgbuild_toolchain: provides the tool
- @macos_pkgbuild//:macos_pkgbuild_missing_toolchain: provides a fallback toolchain for exec platforms where pkgbuild might not be available.
"""
