load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "testutil",
    srcs = [
        "client_builder.go",
        "helpers.go",
        "server.go",
        "server_builder.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/pkg/network/protocols/tls/gotls/testutil",
    tags = ["manual"],
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/network/protocols/http/testutil",
        "//pkg/network/testutil",
        "//pkg/network/usm/testutil",
        "//pkg/util/testutil",
        "//pkg/util/testutil/docker",
        "@com_github_stretchr_testify//require",
    ] + select({
        "@rules_go//go/platform:android": [
            "//pkg/network/config",
            "//pkg/network/usm/config",
            "//pkg/util/kernel",
        ],
        "@rules_go//go/platform:linux": [
            "//pkg/network/config",
            "//pkg/network/usm/config",
            "//pkg/util/kernel",
        ],
        "//conditions:default": [],
    }),
)
