load("@rules_go//go:def.bzl", "go_library")

package(default_package_metadata = ["//comp/serializer/logscompression:go_package_metadata"])

go_library(
    name = "def",
    srcs = ["component.go"],
    importpath = "github.com/DataDog/datadog-agent/comp/serializer/logscompression/def",
    visibility = ["//visibility:public"],
    deps = ["//pkg/util/compression"],
)
