load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

go_library(
    name = "yara",
    srcs = [
        "config.go",
        "consumer.go",
        "dedupe.go",
        "doc.go",
        "engine_libyara.go",
        "engine_standin.go",
        "fileaccess.go",
        "metrics.go",
        "pipeline.go",
        "pool.go",
        "report.go",
        "rules.go",
        "standin.go",
        "stats.go",
        "types.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/pkg/eventmonitor/consumers/yara",
    visibility = ["//visibility:public"],
    deps = select({
        "@rules_go//go/platform:android": [
            "//pkg/config/model",
            "//pkg/config/setup",
            "//pkg/eventmonitor",
            "//pkg/security/probe",
            "//pkg/security/secl/containerutils",
            "//pkg/security/secl/model",
            "//pkg/security/utils",
            "//pkg/util/log",
            "@com_github_datadog_datadog_go_v5//statsd",
            "@com_github_hashicorp_golang_lru_v2//simplelru",
            "@com_github_hillu_go_yara_v4//:go-yara",
        ],
        "@rules_go//go/platform:linux": [
            "//pkg/config/model",
            "//pkg/config/setup",
            "//pkg/eventmonitor",
            "//pkg/security/probe",
            "//pkg/security/secl/containerutils",
            "//pkg/security/secl/model",
            "//pkg/security/utils",
            "//pkg/util/log",
            "@com_github_datadog_datadog_go_v5//statsd",
            "@com_github_hashicorp_golang_lru_v2//simplelru",
            "@com_github_hillu_go_yara_v4//:go-yara",
        ],
        "//conditions:default": [],
    }),
)

dd_agent_go_test(
    name = "yara_test",
    srcs = [
        "consumer_test.go",
        "dedupe_test.go",
        "engine_libyara_test.go",
        "fileaccess_test.go",
        "metrics_test.go",
        "pipeline_evm_test.go",
        "pipeline_test.go",
        "pool_test.go",
        "report_test.go",
        "rules_test.go",
        "standin_test.go",
    ],
    embed = [":yara"],
    gotags_sets = [["yara"]],
    deps = select({
        "@rules_go//go/platform:android": [
            "//pkg/config/mock",
            "//pkg/eventmonitor",
            "//pkg/eventmonitor/testutil",
            "//pkg/security/secl/containerutils",
            "//pkg/security/secl/model",
            "//pkg/security/utils",
            "//pkg/util/log",
            "@com_github_datadog_datadog_go_v5//statsd",
            "@com_github_stretchr_testify//assert",
            "@com_github_stretchr_testify//require",
            "@org_uber_go_goleak//:goleak",
        ],
        "@rules_go//go/platform:linux": [
            "//pkg/config/mock",
            "//pkg/eventmonitor",
            "//pkg/eventmonitor/testutil",
            "//pkg/security/secl/containerutils",
            "//pkg/security/secl/model",
            "//pkg/security/utils",
            "//pkg/util/log",
            "@com_github_datadog_datadog_go_v5//statsd",
            "@com_github_stretchr_testify//assert",
            "@com_github_stretchr_testify//require",
            "@org_uber_go_goleak//:goleak",
        ],
        "//conditions:default": [],
    }),
)
