FROM golang:1.23-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build \
  -tags "serverless otlp" \
  -o /serverless-init \
  ./cmd/serverless-init/

FROM gcr.io/distroless/static-debian12

COPY --from=builder /serverless-init /serverless-init

ENTRYPOINT ["/serverless-init"]
