load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_binary(
    name = "generate_luts",
    embed = [":internal_lib"],
    gotags = ["manual_luts_generator"],
    tags = ["manual"],
    target_compatible_with = ["@platforms//os:linux"],
    visibility = ["//visibility:public"],
)

go_library(
    name = "internal_lib",
    srcs = ["generate_luts.go"],
    importpath = "github.com/DataDog/datadog-agent/pkg/network/protocols/http/gotls/lookup/internal",
    visibility = ["//visibility:private"],
    deps = [
        "//pkg/network/go/bininspect",
        "//pkg/network/go/goversion",
        "//pkg/network/go/lutgen",
        "//pkg/util/safeelf",
    ],
)
