load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

go_library(
    name = "aas",
    srcs = ["inventory.go"],
    importpath = "github.com/DataDog/datadog-agent/comp/metadata/inventoryagent/aas",
    visibility = ["//visibility:public"],
    deps = [
        "//comp/core/config",
        "//comp/metadata/inventoryagent/def",
        "//pkg/config/model",
        "//pkg/trace/traceutil",
        "@com_github_google_uuid//:uuid",
        "@org_uber_go_fx//:fx",
    ],
)

dd_agent_go_test(
    name = "aas_test",
    srcs = ["inventory_test.go"],
    embed = [":aas"],
    deps = [
        "//pkg/config/mock",
        "//pkg/config/model",
        "@com_github_stretchr_testify//assert",
    ],
)
