load("@rules_go//go:def.bzl", "go_library")

package(default_package_metadata = ["//comp/core/secrets/noop-impl:go_package_metadata"])

go_library(
    name = "types",
    srcs = ["types.go"],
    importpath = "github.com/DataDog/datadog-agent/comp/core/secrets/noop-impl/types",
    visibility = ["//visibility:public"],
    deps = ["//comp/core/secrets/def"],
)
