load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

go_library(
    name = "impl",
    srcs = [
        "integrations_jmx.go",
        "integrations_nojmx.go",
        "inventorychecks.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/comp/metadata/inventorychecks/impl",
    visibility = ["//visibility:public"],
    deps = [
        "//comp/api/api/def",
        "//comp/collector/collector/def",
        "//comp/core/autodiscovery/providers",
        "//comp/core/config",
        "//comp/core/flare/types",
        "//comp/core/hostname/hostnameinterface/def",
        "//comp/core/log/def",
        "//comp/logs/agent/def",
        "//comp/metadata/internal/util",
        "//comp/metadata/inventorychecks/def",
        "//comp/metadata/runner/def",
        "//pkg/collector/check",
        "//pkg/collector/check/id",
        "//pkg/logs/sources",
        "//pkg/serializer",
        "//pkg/serializer/marshaler",
        "//pkg/util/http",
        "//pkg/util/option",
        "//pkg/util/uuid",
    ] + select({
        "@rules_go//go/platform:android": [
            "//comp/core/autodiscovery/integration",
            "//pkg/jmxfetch",
            "//pkg/status/jmx",
            "//pkg/util/scrubber",
            "@in_yaml_go_yaml_v3//:yaml",
        ],
        "@rules_go//go/platform:darwin": [
            "//comp/core/autodiscovery/integration",
            "//pkg/jmxfetch",
            "//pkg/status/jmx",
            "//pkg/util/scrubber",
            "@in_yaml_go_yaml_v3//:yaml",
        ],
        "@rules_go//go/platform:dragonfly": [
            "//comp/core/autodiscovery/integration",
            "//pkg/jmxfetch",
            "//pkg/status/jmx",
            "//pkg/util/scrubber",
            "@in_yaml_go_yaml_v3//:yaml",
        ],
        "@rules_go//go/platform:freebsd": [
            "//comp/core/autodiscovery/integration",
            "//pkg/jmxfetch",
            "//pkg/status/jmx",
            "//pkg/util/scrubber",
            "@in_yaml_go_yaml_v3//:yaml",
        ],
        "@rules_go//go/platform:illumos": [
            "//comp/core/autodiscovery/integration",
            "//pkg/jmxfetch",
            "//pkg/status/jmx",
            "//pkg/util/scrubber",
            "@in_yaml_go_yaml_v3//:yaml",
        ],
        "@rules_go//go/platform:ios": [
            "//comp/core/autodiscovery/integration",
            "//pkg/jmxfetch",
            "//pkg/status/jmx",
            "//pkg/util/scrubber",
            "@in_yaml_go_yaml_v3//:yaml",
        ],
        "@rules_go//go/platform:js": [
            "//comp/core/autodiscovery/integration",
            "//pkg/jmxfetch",
            "//pkg/status/jmx",
            "//pkg/util/scrubber",
            "@in_yaml_go_yaml_v3//:yaml",
        ],
        "@rules_go//go/platform:linux": [
            "//comp/core/autodiscovery/integration",
            "//pkg/jmxfetch",
            "//pkg/status/jmx",
            "//pkg/util/scrubber",
            "@in_yaml_go_yaml_v3//:yaml",
        ],
        "@rules_go//go/platform:netbsd": [
            "//comp/core/autodiscovery/integration",
            "//pkg/jmxfetch",
            "//pkg/status/jmx",
            "//pkg/util/scrubber",
            "@in_yaml_go_yaml_v3//:yaml",
        ],
        "@rules_go//go/platform:openbsd": [
            "//comp/core/autodiscovery/integration",
            "//pkg/jmxfetch",
            "//pkg/status/jmx",
            "//pkg/util/scrubber",
            "@in_yaml_go_yaml_v3//:yaml",
        ],
        "@rules_go//go/platform:osx": [
            "//comp/core/autodiscovery/integration",
            "//pkg/jmxfetch",
            "//pkg/status/jmx",
            "//pkg/util/scrubber",
            "@in_yaml_go_yaml_v3//:yaml",
        ],
        "@rules_go//go/platform:plan9": [
            "//comp/core/autodiscovery/integration",
            "//pkg/jmxfetch",
            "//pkg/status/jmx",
            "//pkg/util/scrubber",
            "@in_yaml_go_yaml_v3//:yaml",
        ],
        "@rules_go//go/platform:qnx": [
            "//comp/core/autodiscovery/integration",
            "//pkg/jmxfetch",
            "//pkg/status/jmx",
            "//pkg/util/scrubber",
            "@in_yaml_go_yaml_v3//:yaml",
        ],
        "@rules_go//go/platform:solaris": [
            "//comp/core/autodiscovery/integration",
            "//pkg/jmxfetch",
            "//pkg/status/jmx",
            "//pkg/util/scrubber",
            "@in_yaml_go_yaml_v3//:yaml",
        ],
        "@rules_go//go/platform:windows": [
            "//comp/core/autodiscovery/integration",
            "//pkg/jmxfetch",
            "//pkg/status/jmx",
            "//pkg/util/scrubber",
            "@in_yaml_go_yaml_v3//:yaml",
        ],
        "//conditions:default": [],
    }),
)

dd_agent_go_test(
    name = "impl_test",
    srcs = [
        "integrations_jmx_test.go",
        "inventorychecks_test.go",
    ],
    embed = [":impl"],
    gotags_sets = [["main_agent"]],
    deps = [
        "//comp/collector/collector/def",
        "//comp/collector/collector/mock",
        "//comp/core",
        "//comp/core/autodiscovery/providers",
        "//comp/core/config",
        "//comp/core/hostname/hostnameimpl",
        "//comp/core/hostname/hostnameinterface/def",
        "//comp/core/log/def",
        "//comp/core/log/mock",
        "//comp/core/secrets/fx-noop",
        "//comp/core/tagger/def",
        "//comp/core/tagger/fx-mock",
        "//comp/core/workloadmeta/def",
        "//comp/core/workloadmeta/fx-mock",
        "//comp/logs",
        "//comp/logs/agent/config",
        "//comp/logs/agent/def",
        "//comp/logs/agent/mock",
        "//comp/metadata/inventoryagent/mock",
        "//comp/serializer/logscompression/fx-mock",
        "//pkg/collector/check",
        "//pkg/collector/check/id",
        "//pkg/logs/sources",
        "//pkg/serializer",
        "//pkg/serializer/mocks",
        "//pkg/util/fxutil",
        "//pkg/util/option",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
        "@org_uber_go_fx//:fx",
    ] + select({
        "@rules_go//go/platform:android": [
            "//comp/core/autodiscovery/integration",
            "//pkg/jmxfetch",
            "//pkg/status/jmx",
        ],
        "@rules_go//go/platform:darwin": [
            "//comp/core/autodiscovery/integration",
            "//pkg/jmxfetch",
            "//pkg/status/jmx",
        ],
        "@rules_go//go/platform:dragonfly": [
            "//comp/core/autodiscovery/integration",
            "//pkg/jmxfetch",
            "//pkg/status/jmx",
        ],
        "@rules_go//go/platform:freebsd": [
            "//comp/core/autodiscovery/integration",
            "//pkg/jmxfetch",
            "//pkg/status/jmx",
        ],
        "@rules_go//go/platform:illumos": [
            "//comp/core/autodiscovery/integration",
            "//pkg/jmxfetch",
            "//pkg/status/jmx",
        ],
        "@rules_go//go/platform:ios": [
            "//comp/core/autodiscovery/integration",
            "//pkg/jmxfetch",
            "//pkg/status/jmx",
        ],
        "@rules_go//go/platform:js": [
            "//comp/core/autodiscovery/integration",
            "//pkg/jmxfetch",
            "//pkg/status/jmx",
        ],
        "@rules_go//go/platform:linux": [
            "//comp/core/autodiscovery/integration",
            "//pkg/jmxfetch",
            "//pkg/status/jmx",
        ],
        "@rules_go//go/platform:netbsd": [
            "//comp/core/autodiscovery/integration",
            "//pkg/jmxfetch",
            "//pkg/status/jmx",
        ],
        "@rules_go//go/platform:openbsd": [
            "//comp/core/autodiscovery/integration",
            "//pkg/jmxfetch",
            "//pkg/status/jmx",
        ],
        "@rules_go//go/platform:osx": [
            "//comp/core/autodiscovery/integration",
            "//pkg/jmxfetch",
            "//pkg/status/jmx",
        ],
        "@rules_go//go/platform:plan9": [
            "//comp/core/autodiscovery/integration",
            "//pkg/jmxfetch",
            "//pkg/status/jmx",
        ],
        "@rules_go//go/platform:qnx": [
            "//comp/core/autodiscovery/integration",
            "//pkg/jmxfetch",
            "//pkg/status/jmx",
        ],
        "@rules_go//go/platform:solaris": [
            "//comp/core/autodiscovery/integration",
            "//pkg/jmxfetch",
            "//pkg/status/jmx",
        ],
        "@rules_go//go/platform:windows": [
            "//comp/core/autodiscovery/integration",
            "//pkg/jmxfetch",
            "//pkg/status/jmx",
        ],
        "//conditions:default": [],
    }),
)
