load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

go_library(
    name = "symdbprinter",
    srcs = ["symdbprinter.go"],
    importpath = "github.com/DataDog/datadog-agent/pkg/dyninst/symdb/symdbprinter",
    tags = ["manual"],
    visibility = ["//visibility:public"],
    deps = ["//pkg/dyninst/symdb/uploader"],
)

dd_agent_go_test(
    name = "symdbprinter_test",
    srcs = ["symdbprinter_test.go"],
    embed = [":symdbprinter"],
    include_default = False,
    tag_sets = ["linux_bpf"],
    target_compatible_with = ["@platforms//os:linux"],
    deps = [
        "//pkg/dyninst/symdb",
        "//pkg/dyninst/symdb/uploader",
        "@com_github_stretchr_testify//require",
    ],
)
