load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "identity",
    srcs = ["enroll.go"],
    importpath = "github.com/DataDog/datadog-agent/cmd/privateactionrunner/subcommands/identity",
    visibility = ["//visibility:public"],
    deps = [
        "//comp/core/config",
        "//comp/core/log/def",
        "//pkg/privateactionrunner/adapters/config",
        "//pkg/privateactionrunner/autoconnections",
        "//pkg/privateactionrunner/enrollment",
        "//pkg/privateactionrunner/util",
    ],
)
