load("@rules_go//go:def.bzl", "go_library")

package(default_package_metadata = ["//test/new-e2e:go_package_metadata"])

go_library(
    name = "installer",
    srcs = ["installer.go"],
    importpath = "github.com/DataDog/datadog-agent/test/new-e2e/tests/fleet/installer",
    visibility = ["//visibility:public"],
    deps = [
        "//test/e2e-framework/components/os",
        "//test/e2e-framework/testing/environments",
        "@com_github_stretchr_testify//assert",
    ],
)
