load("@rules_go//go:def.bzl", "go_library")

package(default_package_metadata = ["//pkg/remoteconfig/state:go_package_metadata"])

go_library(
    name = "apmsampling",
    srcs = ["sampler_config.go"],
    importpath = "github.com/DataDog/datadog-agent/pkg/remoteconfig/state/products/apmsampling",
    visibility = ["//visibility:public"],
)
