load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

go_library(
    name = "model",
    srcs = [
        "model.go",
        "prm.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/pkg/collector/corechecks/gpu/model",
    visibility = ["//visibility:public"],
)

dd_agent_go_test(
    name = "model_test",
    srcs = ["model_test.go"],
    embed = [":model"],
    deps = ["@com_github_stretchr_testify//require"],
)
