load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

go_library(
    name = "networkdevices",
    srcs = [
        "connectivity_check.go",
        "entrypoint.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/pkg/privateactionrunner/bundles/remoteaction/networkdevices",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/networkdevice/pinger",
        "//pkg/privateactionrunner/libs/encryptioncontext",
        "//pkg/privateactionrunner/libs/privateconnection",
        "//pkg/privateactionrunner/types",
        "//pkg/snmp/gosnmplib",
        "@com_github_gosnmp_gosnmp//:gosnmp",
        "@org_golang_x_sync//errgroup",
    ],
)

dd_agent_go_test(
    name = "networkdevices_test",
    srcs = ["connectivity_check_test.go"],
    embed = [":networkdevices"],
    deps = [
        "//pkg/privateactionrunner/libs/encryptioncontext",
        "//pkg/privateactionrunner/types",
        "@com_github_stretchr_testify//require",
    ],
)
