load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "compiler",
    srcs = [
        "compiler.go",
        "stdarg.h",
    ],
    embedsrcs = select({
        "@rules_go//go/platform:android": [
            "stdarg.h",
        ],
        "@rules_go//go/platform:linux": [
            "stdarg.h",
        ],
        "//conditions:default": [],
    }),
    importpath = "github.com/DataDog/datadog-agent/pkg/ebpf/compiler",
    visibility = ["//visibility:public"],
    deps = select({
        "@rules_go//go/platform:android": [
            "//pkg/util/defaultpaths",
            "//pkg/util/kernel",
            "//pkg/util/log",
        ],
        "@rules_go//go/platform:linux": [
            "//pkg/util/defaultpaths",
            "//pkg/util/kernel",
            "//pkg/util/log",
        ],
        "//conditions:default": [],
    }),
)
