#!/bin/sh
#
# Perform necessary datadog-agent setup steps after package is installed.
#
# .deb: STEP 5 of 5

INSTALL_DIR=/opt/datadog-agent

# If we are inside the Docker container, do nothing
if [ -n "$DOCKER_DD_AGENT" ]; then
    echo "Installation from docker-dd-agent, nothing to do in postinst"
    exit 0
fi

# Run FIPS installation script if available. Mandatory to execute the agent binary in FIPS mode.
if [ -x ${INSTALL_DIR}/embedded/bin/fipsinstall.sh ]; then
    ${INSTALL_DIR}/embedded/bin/fipsinstall.sh
fi

# Run post install script. Instructions can be found in pkg/fleet/installer/packages/datadog_agent_linux.go
${INSTALL_DIR}/embedded/bin/installer postinst datadog-agent deb

exit 0
