load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

go_library(
    name = "eks",
    srcs = ["eks.go"],
    importpath = "github.com/DataDog/datadog-agent/test/e2e-framework/cmd/e2ectl/internal/drivers/eks",
    visibility = ["//test/e2e-framework/cmd/e2ectl:__subpackages__"],
    deps = [
        "//test/e2e-framework/cmd/e2ectl/internal/config",
        "//test/e2e-framework/cmd/e2ectl/internal/drivers/pulumiworker",
        "//test/e2e-framework/cmd/e2ectl/internal/envstore",
        "//test/e2e-framework/cmd/e2ectl/internal/installer",
        "//test/e2e-framework/cmd/e2ectl/workerclient",
        "//test/e2e-framework/cmd/internal/envconfig/eks",
        "//test/e2e-framework/components/outputs",
        "//test/e2e-framework/testing/provisioner",
    ],
)

dd_agent_go_test(
    name = "eks_test",
    srcs = ["eks_test.go"],
    embed = [":eks"],
    deps = [
        "//test/e2e-framework/cmd/e2ectl/internal/envstore",
        "//test/e2e-framework/cmd/e2ectl/workerclient",
        "//test/e2e-framework/testing/provisioner",
    ],
)
