load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "fx",
    srcs = ["fx.go"],
    importpath = "github.com/DataDog/datadog-agent/comp/privateactionrunner/fx",
    visibility = ["//visibility:public"],
    deps = [
        "//comp/privateactionrunner/def",
        "//comp/privateactionrunner/impl",
        "//pkg/util/fxutil",
        "@org_uber_go_fx//:fx",
    ],
)

go_test(
    name = "fx_test",
    srcs = ["fx_test.go"],
    embed = [":fx"],
    deps = [
        "//comp/privateactionrunner/impl",
        "@com_github_stretchr_testify//require",
        "@org_uber_go_fx//:fx",
    ],
)
