load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

go_library(
    name = "fx",
    srcs = ["fx.go"],
    importpath = "github.com/DataDog/datadog-agent/comp/privateactionrunner/fx",
    visibility = ["//visibility:public"],
    deps = [
        "//comp/core/config",
        "//comp/privateactionrunner/def",
        "//comp/privateactionrunner/impl",
        "//comp/remote-config/rcclient/types",
        "//pkg/privateactionrunner/task-verifier",
        "//pkg/remoteconfig/state",
        "//pkg/util/fxutil",
        "@org_uber_go_fx//:fx",
    ],
)

dd_agent_go_test(
    name = "fx_test",
    srcs = ["fx_test.go"],
    embed = [":fx"],
    deps = [
        "//comp/core/config",
        "//comp/privateactionrunner/def",
        "//pkg/remoteconfig/state",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
