load("@rules_go//go:def.bzl", "go_binary", "go_library")

package(default_package_metadata = ["//pkg/dyninst/testprogs/progs:go_package_metadata"])

go_library(
    name = "simple_lib",
    srcs = ["main.go"],
    importpath = "github.com/DataDog/datadog-agent/pkg/dyninst/testprogs/progs/simple",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "simple",
    embed = [":simple_lib"],
    visibility = ["//visibility:public"],
)
