// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: datadog/remoteagent/command.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ParameterType defines the supported parameter types for command parameters.
type ParameterType int32

const (
	ParameterType_PARAMETER_TYPE_UNSPECIFIED  ParameterType = 0
	ParameterType_PARAMETER_TYPE_STRING       ParameterType = 1
	ParameterType_PARAMETER_TYPE_INT          ParameterType = 2
	ParameterType_PARAMETER_TYPE_UINT         ParameterType = 3
	ParameterType_PARAMETER_TYPE_FLOAT        ParameterType = 4
	ParameterType_PARAMETER_TYPE_BOOL         ParameterType = 5
	ParameterType_PARAMETER_TYPE_STRING_SLICE ParameterType = 8
	ParameterType_PARAMETER_TYPE_INT_SLICE    ParameterType = 9
	ParameterType_PARAMETER_TYPE_UINT_SLICE   ParameterType = 10
	ParameterType_PARAMETER_TYPE_FLOAT_SLICE  ParameterType = 11
)

// Enum value maps for ParameterType.
var (
	ParameterType_name = map[int32]string{
		0:  "PARAMETER_TYPE_UNSPECIFIED",
		1:  "PARAMETER_TYPE_STRING",
		2:  "PARAMETER_TYPE_INT",
		3:  "PARAMETER_TYPE_UINT",
		4:  "PARAMETER_TYPE_FLOAT",
		5:  "PARAMETER_TYPE_BOOL",
		8:  "PARAMETER_TYPE_STRING_SLICE",
		9:  "PARAMETER_TYPE_INT_SLICE",
		10: "PARAMETER_TYPE_UINT_SLICE",
		11: "PARAMETER_TYPE_FLOAT_SLICE",
	}
	ParameterType_value = map[string]int32{
		"PARAMETER_TYPE_UNSPECIFIED":  0,
		"PARAMETER_TYPE_STRING":       1,
		"PARAMETER_TYPE_INT":          2,
		"PARAMETER_TYPE_UINT":         3,
		"PARAMETER_TYPE_FLOAT":        4,
		"PARAMETER_TYPE_BOOL":         5,
		"PARAMETER_TYPE_STRING_SLICE": 8,
		"PARAMETER_TYPE_INT_SLICE":    9,
		"PARAMETER_TYPE_UINT_SLICE":   10,
		"PARAMETER_TYPE_FLOAT_SLICE":  11,
	}
)

func (x ParameterType) Enum() *ParameterType {
	p := new(ParameterType)
	*p = x
	return p
}

func (x ParameterType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ParameterType) Descriptor() protoreflect.EnumDescriptor {
	return file_datadog_remoteagent_command_proto_enumTypes[0].Descriptor()
}

func (ParameterType) Type() protoreflect.EnumType {
	return &file_datadog_remoteagent_command_proto_enumTypes[0]
}

func (x ParameterType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ParameterType.Descriptor instead.
func (ParameterType) EnumDescriptor() ([]byte, []int) {
	return file_datadog_remoteagent_command_proto_rawDescGZIP(), []int{0}
}

// CommandParameter describes a single parameter (flag or positional argument) for a command.
type CommandParameter struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Name         string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ShortName    string                 `protobuf:"bytes,2,opt,name=short_name,json=shortName,proto3" json:"short_name,omitempty"`
	Helper       string                 `protobuf:"bytes,3,opt,name=helper,proto3" json:"helper,omitempty"`
	Type         ParameterType          `protobuf:"varint,4,opt,name=type,proto3,enum=datadog.remoteagent.command.v1.ParameterType" json:"type,omitempty"`
	Required     bool                   `protobuf:"varint,5,opt,name=required,proto3" json:"required,omitempty"`
	IsFlag       bool                   `protobuf:"varint,6,opt,name=is_flag,json=isFlag,proto3" json:"is_flag,omitempty"`
	IsPersistent bool                   `protobuf:"varint,7,opt,name=is_persistent,json=isPersistent,proto3" json:"is_persistent,omitempty"`
	// Optional default value. When present, the field corresponding to the
	// parameter's type is read; other fields are ignored.
	DefaultValue  *ParameterDefaultValue `protobuf:"bytes,8,opt,name=default_value,json=defaultValue,proto3,oneof" json:"default_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandParameter) Reset() {
	*x = CommandParameter{}
	mi := &file_datadog_remoteagent_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandParameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandParameter) ProtoMessage() {}

func (x *CommandParameter) ProtoReflect() protoreflect.Message {
	mi := &file_datadog_remoteagent_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandParameter.ProtoReflect.Descriptor instead.
func (*CommandParameter) Descriptor() ([]byte, []int) {
	return file_datadog_remoteagent_command_proto_rawDescGZIP(), []int{0}
}

func (x *CommandParameter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CommandParameter) GetShortName() string {
	if x != nil {
		return x.ShortName
	}
	return ""
}

func (x *CommandParameter) GetHelper() string {
	if x != nil {
		return x.Helper
	}
	return ""
}

func (x *CommandParameter) GetType() ParameterType {
	if x != nil {
		return x.Type
	}
	return ParameterType_PARAMETER_TYPE_UNSPECIFIED
}

func (x *CommandParameter) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *CommandParameter) GetIsFlag() bool {
	if x != nil {
		return x.IsFlag
	}
	return false
}

func (x *CommandParameter) GetIsPersistent() bool {
	if x != nil {
		return x.IsPersistent
	}
	return false
}

func (x *CommandParameter) GetDefaultValue() *ParameterDefaultValue {
	if x != nil {
		return x.DefaultValue
	}
	return nil
}

// ParameterDefaultValue holds a default value for a command parameter.
// Only the field matching the parameter's ParameterType is read.
type ParameterDefaultValue struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	StringDefault      string                 `protobuf:"bytes,1,opt,name=string_default,json=stringDefault,proto3" json:"string_default,omitempty"`
	IntDefault         int64                  `protobuf:"varint,2,opt,name=int_default,json=intDefault,proto3" json:"int_default,omitempty"`
	UintDefault        uint64                 `protobuf:"varint,3,opt,name=uint_default,json=uintDefault,proto3" json:"uint_default,omitempty"`
	FloatDefault       float64                `protobuf:"fixed64,4,opt,name=float_default,json=floatDefault,proto3" json:"float_default,omitempty"`
	BoolDefault        bool                   `protobuf:"varint,5,opt,name=bool_default,json=boolDefault,proto3" json:"bool_default,omitempty"`
	StringSliceDefault []string               `protobuf:"bytes,6,rep,name=string_slice_default,json=stringSliceDefault,proto3" json:"string_slice_default,omitempty"`
	IntSliceDefault    []int64                `protobuf:"varint,7,rep,packed,name=int_slice_default,json=intSliceDefault,proto3" json:"int_slice_default,omitempty"`
	UintSliceDefault   []uint64               `protobuf:"varint,8,rep,packed,name=uint_slice_default,json=uintSliceDefault,proto3" json:"uint_slice_default,omitempty"`
	FloatSliceDefault  []float64              `protobuf:"fixed64,9,rep,packed,name=float_slice_default,json=floatSliceDefault,proto3" json:"float_slice_default,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ParameterDefaultValue) Reset() {
	*x = ParameterDefaultValue{}
	mi := &file_datadog_remoteagent_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParameterDefaultValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParameterDefaultValue) ProtoMessage() {}

func (x *ParameterDefaultValue) ProtoReflect() protoreflect.Message {
	mi := &file_datadog_remoteagent_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParameterDefaultValue.ProtoReflect.Descriptor instead.
func (*ParameterDefaultValue) Descriptor() ([]byte, []int) {
	return file_datadog_remoteagent_command_proto_rawDescGZIP(), []int{1}
}

func (x *ParameterDefaultValue) GetStringDefault() string {
	if x != nil {
		return x.StringDefault
	}
	return ""
}

func (x *ParameterDefaultValue) GetIntDefault() int64 {
	if x != nil {
		return x.IntDefault
	}
	return 0
}

func (x *ParameterDefaultValue) GetUintDefault() uint64 {
	if x != nil {
		return x.UintDefault
	}
	return 0
}

func (x *ParameterDefaultValue) GetFloatDefault() float64 {
	if x != nil {
		return x.FloatDefault
	}
	return 0
}

func (x *ParameterDefaultValue) GetBoolDefault() bool {
	if x != nil {
		return x.BoolDefault
	}
	return false
}

func (x *ParameterDefaultValue) GetStringSliceDefault() []string {
	if x != nil {
		return x.StringSliceDefault
	}
	return nil
}

func (x *ParameterDefaultValue) GetIntSliceDefault() []int64 {
	if x != nil {
		return x.IntSliceDefault
	}
	return nil
}

func (x *ParameterDefaultValue) GetUintSliceDefault() []uint64 {
	if x != nil {
		return x.UintSliceDefault
	}
	return nil
}

func (x *ParameterDefaultValue) GetFloatSliceDefault() []float64 {
	if x != nil {
		return x.FloatSliceDefault
	}
	return nil
}

// Command describes a CLI command that a remote agent exposes.
type Command struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ShortName       string                 `protobuf:"bytes,2,opt,name=short_name,json=shortName,proto3" json:"short_name,omitempty"`
	Helper          string                 `protobuf:"bytes,3,opt,name=helper,proto3" json:"helper,omitempty"`
	LongDescription string                 `protobuf:"bytes,4,opt,name=long_description,json=longDescription,proto3" json:"long_description,omitempty"`
	Parameters      []*CommandParameter    `protobuf:"bytes,5,rep,name=parameters,proto3" json:"parameters,omitempty"`
	Children        []*Command             `protobuf:"bytes,6,rep,name=children,proto3" json:"children,omitempty"`
	// Alias allows this command to override an existing Core Agent subcommand.
	// When set, invoking `agent <alias>` routes to this remote command instead
	// of the local subcommand. When the remote agent disconnects, the local
	// subcommand takes over again.
	Alias         string `protobuf:"bytes,7,opt,name=alias,proto3" json:"alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_datadog_remoteagent_command_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_datadog_remoteagent_command_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_datadog_remoteagent_command_proto_rawDescGZIP(), []int{2}
}

func (x *Command) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Command) GetShortName() string {
	if x != nil {
		return x.ShortName
	}
	return ""
}

func (x *Command) GetHelper() string {
	if x != nil {
		return x.Helper
	}
	return ""
}

func (x *Command) GetLongDescription() string {
	if x != nil {
		return x.LongDescription
	}
	return ""
}

func (x *Command) GetParameters() []*CommandParameter {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *Command) GetChildren() []*Command {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *Command) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

// ExecuteCommandRequest is sent to execute a specific command on a remote agent.
type ExecuteCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandPath   string                 `protobuf:"bytes,1,opt,name=command_path,json=commandPath,proto3" json:"command_path,omitempty"`
	Arguments     *structpb.Struct       `protobuf:"bytes,2,opt,name=arguments,proto3" json:"arguments,omitempty"`
	JsonOutput    bool                   `protobuf:"varint,3,opt,name=json_output,json=jsonOutput,proto3" json:"json_output,omitempty"`
	Verbose       bool                   `protobuf:"varint,5,opt,name=verbose,proto3" json:"verbose,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteCommandRequest) Reset() {
	*x = ExecuteCommandRequest{}
	mi := &file_datadog_remoteagent_command_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteCommandRequest) ProtoMessage() {}

func (x *ExecuteCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datadog_remoteagent_command_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteCommandRequest.ProtoReflect.Descriptor instead.
func (*ExecuteCommandRequest) Descriptor() ([]byte, []int) {
	return file_datadog_remoteagent_command_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteCommandRequest) GetCommandPath() string {
	if x != nil {
		return x.CommandPath
	}
	return ""
}

func (x *ExecuteCommandRequest) GetArguments() *structpb.Struct {
	if x != nil {
		return x.Arguments
	}
	return nil
}

func (x *ExecuteCommandRequest) GetJsonOutput() bool {
	if x != nil {
		return x.JsonOutput
	}
	return false
}

func (x *ExecuteCommandRequest) GetVerbose() bool {
	if x != nil {
		return x.Verbose
	}
	return false
}

// ExecuteCommandResponse contains the result of executing a command.
type ExecuteCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout        string                 `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
	BinaryOutput  []byte                 `protobuf:"bytes,4,opt,name=binary_output,json=binaryOutput,proto3" json:"binary_output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteCommandResponse) Reset() {
	*x = ExecuteCommandResponse{}
	mi := &file_datadog_remoteagent_command_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteCommandResponse) ProtoMessage() {}

func (x *ExecuteCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_datadog_remoteagent_command_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteCommandResponse.ProtoReflect.Descriptor instead.
func (*ExecuteCommandResponse) Descriptor() ([]byte, []int) {
	return file_datadog_remoteagent_command_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteCommandResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecuteCommandResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *ExecuteCommandResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *ExecuteCommandResponse) GetBinaryOutput() []byte {
	if x != nil {
		return x.BinaryOutput
	}
	return nil
}

// ListRemoteCommandsRequest is sent to list all commands available on a remote agent.
type ListRemoteCommandsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRemoteCommandsRequest) Reset() {
	*x = ListRemoteCommandsRequest{}
	mi := &file_datadog_remoteagent_command_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRemoteCommandsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRemoteCommandsRequest) ProtoMessage() {}

func (x *ListRemoteCommandsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datadog_remoteagent_command_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRemoteCommandsRequest.ProtoReflect.Descriptor instead.
func (*ListRemoteCommandsRequest) Descriptor() ([]byte, []int) {
	return file_datadog_remoteagent_command_proto_rawDescGZIP(), []int{5}
}

// ListRemoteCommandsResponse contains the list of commands available on a remote agent.
type ListRemoteCommandsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commands      []*Command             `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRemoteCommandsResponse) Reset() {
	*x = ListRemoteCommandsResponse{}
	mi := &file_datadog_remoteagent_command_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRemoteCommandsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRemoteCommandsResponse) ProtoMessage() {}

func (x *ListRemoteCommandsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_datadog_remoteagent_command_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRemoteCommandsResponse.ProtoReflect.Descriptor instead.
func (*ListRemoteCommandsResponse) Descriptor() ([]byte, []int) {
	return file_datadog_remoteagent_command_proto_rawDescGZIP(), []int{6}
}

func (x *ListRemoteCommandsResponse) GetCommands() []*Command {
	if x != nil {
		return x.Commands
	}
	return nil
}

// RemoteAgentCommandGroup groups commands by the remote agent that provides them.
type RemoteAgentCommandGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentName     string                 `protobuf:"bytes,1,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	AgentFlavor   string                 `protobuf:"bytes,2,opt,name=agent_flavor,json=agentFlavor,proto3" json:"agent_flavor,omitempty"`
	Commands      []*Command             `protobuf:"bytes,3,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoteAgentCommandGroup) Reset() {
	*x = RemoteAgentCommandGroup{}
	mi := &file_datadog_remoteagent_command_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteAgentCommandGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteAgentCommandGroup) ProtoMessage() {}

func (x *RemoteAgentCommandGroup) ProtoReflect() protoreflect.Message {
	mi := &file_datadog_remoteagent_command_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteAgentCommandGroup.ProtoReflect.Descriptor instead.
func (*RemoteAgentCommandGroup) Descriptor() ([]byte, []int) {
	return file_datadog_remoteagent_command_proto_rawDescGZIP(), []int{7}
}

func (x *RemoteAgentCommandGroup) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *RemoteAgentCommandGroup) GetAgentFlavor() string {
	if x != nil {
		return x.AgentFlavor
	}
	return ""
}

func (x *RemoteAgentCommandGroup) GetCommands() []*Command {
	if x != nil {
		return x.Commands
	}
	return nil
}

// ListAllRemoteCommandsResponse contains commands grouped by remote agent.
// Used by the Core Agent proxy to provide agent attribution.
type ListAllRemoteCommandsResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	AgentCommands []*RemoteAgentCommandGroup `protobuf:"bytes,1,rep,name=agent_commands,json=agentCommands,proto3" json:"agent_commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllRemoteCommandsResponse) Reset() {
	*x = ListAllRemoteCommandsResponse{}
	mi := &file_datadog_remoteagent_command_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllRemoteCommandsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllRemoteCommandsResponse) ProtoMessage() {}

func (x *ListAllRemoteCommandsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_datadog_remoteagent_command_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllRemoteCommandsResponse.ProtoReflect.Descriptor instead.
func (*ListAllRemoteCommandsResponse) Descriptor() ([]byte, []int) {
	return file_datadog_remoteagent_command_proto_rawDescGZIP(), []int{8}
}

func (x *ListAllRemoteCommandsResponse) GetAgentCommands() []*RemoteAgentCommandGroup {
	if x != nil {
		return x.AgentCommands
	}
	return nil
}

var File_datadog_remoteagent_command_proto protoreflect.FileDescriptor

const file_datadog_remoteagent_command_proto_rawDesc = "" +
	"\n" +
	"!datadog/remoteagent/command.proto\x12\x1edatadog.remoteagent.command.v1\x1a\x1cgoogle/protobuf/struct.proto\"\xed\x02\n" +
	"\x10CommandParameter\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"short_name\x18\x02 \x01(\tR\tshortName\x12\x16\n" +
	"\x06helper\x18\x03 \x01(\tR\x06helper\x12A\n" +
	"\x04type\x18\x04 \x01(\x0e2-.datadog.remoteagent.command.v1.ParameterTypeR\x04type\x12\x1a\n" +
	"\brequired\x18\x05 \x01(\bR\brequired\x12\x17\n" +
	"\ais_flag\x18\x06 \x01(\bR\x06isFlag\x12#\n" +
	"\ris_persistent\x18\a \x01(\bR\fisPersistent\x12_\n" +
	"\rdefault_value\x18\b \x01(\v25.datadog.remoteagent.command.v1.ParameterDefaultValueH\x00R\fdefaultValue\x88\x01\x01B\x10\n" +
	"\x0e_default_value\"\x86\x03\n" +
	"\x15ParameterDefaultValue\x12%\n" +
	"\x0estring_default\x18\x01 \x01(\tR\rstringDefault\x12\x1f\n" +
	"\vint_default\x18\x02 \x01(\x03R\n" +
	"intDefault\x12!\n" +
	"\fuint_default\x18\x03 \x01(\x04R\vuintDefault\x12#\n" +
	"\rfloat_default\x18\x04 \x01(\x01R\ffloatDefault\x12!\n" +
	"\fbool_default\x18\x05 \x01(\bR\vboolDefault\x120\n" +
	"\x14string_slice_default\x18\x06 \x03(\tR\x12stringSliceDefault\x12*\n" +
	"\x11int_slice_default\x18\a \x03(\x03R\x0fintSliceDefault\x12,\n" +
	"\x12uint_slice_default\x18\b \x03(\x04R\x10uintSliceDefault\x12.\n" +
	"\x13float_slice_default\x18\t \x03(\x01R\x11floatSliceDefault\"\xac\x02\n" +
	"\aCommand\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"short_name\x18\x02 \x01(\tR\tshortName\x12\x16\n" +
	"\x06helper\x18\x03 \x01(\tR\x06helper\x12)\n" +
	"\x10long_description\x18\x04 \x01(\tR\x0flongDescription\x12P\n" +
	"\n" +
	"parameters\x18\x05 \x03(\v20.datadog.remoteagent.command.v1.CommandParameterR\n" +
	"parameters\x12C\n" +
	"\bchildren\x18\x06 \x03(\v2'.datadog.remoteagent.command.v1.CommandR\bchildren\x12\x14\n" +
	"\x05alias\x18\a \x01(\tR\x05alias\"\xac\x01\n" +
	"\x15ExecuteCommandRequest\x12!\n" +
	"\fcommand_path\x18\x01 \x01(\tR\vcommandPath\x125\n" +
	"\targuments\x18\x02 \x01(\v2\x17.google.protobuf.StructR\targuments\x12\x1f\n" +
	"\vjson_output\x18\x03 \x01(\bR\n" +
	"jsonOutput\x12\x18\n" +
	"\averbose\x18\x05 \x01(\bR\averbose\"\x8a\x01\n" +
	"\x16ExecuteCommandResponse\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x02 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x03 \x01(\tR\x06stderr\x12#\n" +
	"\rbinary_output\x18\x04 \x01(\fR\fbinaryOutput\"\x1b\n" +
	"\x19ListRemoteCommandsRequest\"a\n" +
	"\x1aListRemoteCommandsResponse\x12C\n" +
	"\bcommands\x18\x01 \x03(\v2'.datadog.remoteagent.command.v1.CommandR\bcommands\"\xa0\x01\n" +
	"\x17RemoteAgentCommandGroup\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x01 \x01(\tR\tagentName\x12!\n" +
	"\fagent_flavor\x18\x02 \x01(\tR\vagentFlavor\x12C\n" +
	"\bcommands\x18\x03 \x03(\v2'.datadog.remoteagent.command.v1.CommandR\bcommands\"\x7f\n" +
	"\x1dListAllRemoteCommandsResponse\x12^\n" +
	"\x0eagent_commands\x18\x01 \x03(\v27.datadog.remoteagent.command.v1.RemoteAgentCommandGroupR\ragentCommands*\xac\x02\n" +
	"\rParameterType\x12\x1e\n" +
	"\x1aPARAMETER_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15PARAMETER_TYPE_STRING\x10\x01\x12\x16\n" +
	"\x12PARAMETER_TYPE_INT\x10\x02\x12\x17\n" +
	"\x13PARAMETER_TYPE_UINT\x10\x03\x12\x18\n" +
	"\x14PARAMETER_TYPE_FLOAT\x10\x04\x12\x17\n" +
	"\x13PARAMETER_TYPE_BOOL\x10\x05\x12\x1f\n" +
	"\x1bPARAMETER_TYPE_STRING_SLICE\x10\b\x12\x1c\n" +
	"\x18PARAMETER_TYPE_INT_SLICE\x10\t\x12\x1d\n" +
	"\x19PARAMETER_TYPE_UINT_SLICE\x10\n" +
	"\x12\x1e\n" +
	"\x1aPARAMETER_TYPE_FLOAT_SLICE\x10\v2\xa0\x02\n" +
	"\x15RemoteCommandProvider\x12\x85\x01\n" +
	"\fListCommands\x129.datadog.remoteagent.command.v1.ListRemoteCommandsRequest\x1a:.datadog.remoteagent.command.v1.ListRemoteCommandsResponse\x12\x7f\n" +
	"\x0eExecuteCommand\x125.datadog.remoteagent.command.v1.ExecuteCommandRequest\x1a6.datadog.remoteagent.command.v1.ExecuteCommandResponseB\x15Z\x13pkg/proto/pbgo/coreb\x06proto3"

var (
	file_datadog_remoteagent_command_proto_rawDescOnce sync.Once
	file_datadog_remoteagent_command_proto_rawDescData []byte
)

func file_datadog_remoteagent_command_proto_rawDescGZIP() []byte {
	file_datadog_remoteagent_command_proto_rawDescOnce.Do(func() {
		file_datadog_remoteagent_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_datadog_remoteagent_command_proto_rawDesc), len(file_datadog_remoteagent_command_proto_rawDesc)))
	})
	return file_datadog_remoteagent_command_proto_rawDescData
}

var file_datadog_remoteagent_command_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_datadog_remoteagent_command_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_datadog_remoteagent_command_proto_goTypes = []any{
	(ParameterType)(0),                    // 0: datadog.remoteagent.command.v1.ParameterType
	(*CommandParameter)(nil),              // 1: datadog.remoteagent.command.v1.CommandParameter
	(*ParameterDefaultValue)(nil),         // 2: datadog.remoteagent.command.v1.ParameterDefaultValue
	(*Command)(nil),                       // 3: datadog.remoteagent.command.v1.Command
	(*ExecuteCommandRequest)(nil),         // 4: datadog.remoteagent.command.v1.ExecuteCommandRequest
	(*ExecuteCommandResponse)(nil),        // 5: datadog.remoteagent.command.v1.ExecuteCommandResponse
	(*ListRemoteCommandsRequest)(nil),     // 6: datadog.remoteagent.command.v1.ListRemoteCommandsRequest
	(*ListRemoteCommandsResponse)(nil),    // 7: datadog.remoteagent.command.v1.ListRemoteCommandsResponse
	(*RemoteAgentCommandGroup)(nil),       // 8: datadog.remoteagent.command.v1.RemoteAgentCommandGroup
	(*ListAllRemoteCommandsResponse)(nil), // 9: datadog.remoteagent.command.v1.ListAllRemoteCommandsResponse
	(*structpb.Struct)(nil),               // 10: google.protobuf.Struct
}
var file_datadog_remoteagent_command_proto_depIdxs = []int32{
	0,  // 0: datadog.remoteagent.command.v1.CommandParameter.type:type_name -> datadog.remoteagent.command.v1.ParameterType
	2,  // 1: datadog.remoteagent.command.v1.CommandParameter.default_value:type_name -> datadog.remoteagent.command.v1.ParameterDefaultValue
	1,  // 2: datadog.remoteagent.command.v1.Command.parameters:type_name -> datadog.remoteagent.command.v1.CommandParameter
	3,  // 3: datadog.remoteagent.command.v1.Command.children:type_name -> datadog.remoteagent.command.v1.Command
	10, // 4: datadog.remoteagent.command.v1.ExecuteCommandRequest.arguments:type_name -> google.protobuf.Struct
	3,  // 5: datadog.remoteagent.command.v1.ListRemoteCommandsResponse.commands:type_name -> datadog.remoteagent.command.v1.Command
	3,  // 6: datadog.remoteagent.command.v1.RemoteAgentCommandGroup.commands:type_name -> datadog.remoteagent.command.v1.Command
	8,  // 7: datadog.remoteagent.command.v1.ListAllRemoteCommandsResponse.agent_commands:type_name -> datadog.remoteagent.command.v1.RemoteAgentCommandGroup
	6,  // 8: datadog.remoteagent.command.v1.RemoteCommandProvider.ListCommands:input_type -> datadog.remoteagent.command.v1.ListRemoteCommandsRequest
	4,  // 9: datadog.remoteagent.command.v1.RemoteCommandProvider.ExecuteCommand:input_type -> datadog.remoteagent.command.v1.ExecuteCommandRequest
	7,  // 10: datadog.remoteagent.command.v1.RemoteCommandProvider.ListCommands:output_type -> datadog.remoteagent.command.v1.ListRemoteCommandsResponse
	5,  // 11: datadog.remoteagent.command.v1.RemoteCommandProvider.ExecuteCommand:output_type -> datadog.remoteagent.command.v1.ExecuteCommandResponse
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_datadog_remoteagent_command_proto_init() }
func file_datadog_remoteagent_command_proto_init() {
	if File_datadog_remoteagent_command_proto != nil {
		return
	}
	file_datadog_remoteagent_command_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_datadog_remoteagent_command_proto_rawDesc), len(file_datadog_remoteagent_command_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_datadog_remoteagent_command_proto_goTypes,
		DependencyIndexes: file_datadog_remoteagent_command_proto_depIdxs,
		EnumInfos:         file_datadog_remoteagent_command_proto_enumTypes,
		MessageInfos:      file_datadog_remoteagent_command_proto_msgTypes,
	}.Build()
	File_datadog_remoteagent_command_proto = out.File
	file_datadog_remoteagent_command_proto_goTypes = nil
	file_datadog_remoteagent_command_proto_depIdxs = nil
}
