// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: datadog/remoteagent/observer.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetTracesRequest is sent by core-agent to request buffered traces.
type GetTracesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// max_items limits the number of traces returned (0 = no limit).
	MaxItems      uint32 `protobuf:"varint,1,opt,name=max_items,json=maxItems,proto3" json:"max_items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTracesRequest) Reset() {
	*x = GetTracesRequest{}
	mi := &file_datadog_remoteagent_observer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTracesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTracesRequest) ProtoMessage() {}

func (x *GetTracesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datadog_remoteagent_observer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTracesRequest.ProtoReflect.Descriptor instead.
func (*GetTracesRequest) Descriptor() ([]byte, []int) {
	return file_datadog_remoteagent_observer_proto_rawDescGZIP(), []int{0}
}

func (x *GetTracesRequest) GetMaxItems() uint32 {
	if x != nil {
		return x.MaxItems
	}
	return 0
}

// GetTracesResponse contains buffered traces from trace-agent.
type GetTracesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// traces contains the buffered trace data.
	Traces []*TraceChunkData `protobuf:"bytes,1,rep,name=traces,proto3" json:"traces,omitempty"`
	// dropped_count indicates how many traces were dropped due to buffer overflow.
	DroppedCount uint64 `protobuf:"varint,2,opt,name=dropped_count,json=droppedCount,proto3" json:"dropped_count,omitempty"`
	// has_more indicates if there is more data available in the buffer.
	HasMore bool `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	// stats_payloads contains msgpack-encoded StatsPayload objects (trace stats/metrics).
	StatsPayloads [][]byte `protobuf:"bytes,4,rep,name=stats_payloads,json=statsPayloads,proto3" json:"stats_payloads,omitempty"`
	// stats_dropped_count indicates how many stats payloads were dropped due to buffer overflow.
	StatsDroppedCount uint64 `protobuf:"varint,5,opt,name=stats_dropped_count,json=statsDroppedCount,proto3" json:"stats_dropped_count,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetTracesResponse) Reset() {
	*x = GetTracesResponse{}
	mi := &file_datadog_remoteagent_observer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTracesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTracesResponse) ProtoMessage() {}

func (x *GetTracesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_datadog_remoteagent_observer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTracesResponse.ProtoReflect.Descriptor instead.
func (*GetTracesResponse) Descriptor() ([]byte, []int) {
	return file_datadog_remoteagent_observer_proto_rawDescGZIP(), []int{1}
}

func (x *GetTracesResponse) GetTraces() []*TraceChunkData {
	if x != nil {
		return x.Traces
	}
	return nil
}

func (x *GetTracesResponse) GetDroppedCount() uint64 {
	if x != nil {
		return x.DroppedCount
	}
	return 0
}

func (x *GetTracesResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *GetTracesResponse) GetStatsPayloads() [][]byte {
	if x != nil {
		return x.StatsPayloads
	}
	return nil
}

func (x *GetTracesResponse) GetStatsDroppedCount() uint64 {
	if x != nil {
		return x.StatsDroppedCount
	}
	return 0
}

// TraceChunkData wraps a serialized TracerPayload with metadata about when it was received.
type TraceChunkData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// payload_data contains the msgpack-serialized TracerPayload.
	// Use pb.TracerPayload.Unmarshal() to deserialize.
	PayloadData []byte `protobuf:"bytes,1,opt,name=payload_data,json=payloadData,proto3" json:"payload_data,omitempty"`
	// received_at_ns is when trace-agent received this trace (nanoseconds since epoch).
	ReceivedAtNs  int64 `protobuf:"varint,2,opt,name=received_at_ns,json=receivedAtNs,proto3" json:"received_at_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraceChunkData) Reset() {
	*x = TraceChunkData{}
	mi := &file_datadog_remoteagent_observer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceChunkData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceChunkData) ProtoMessage() {}

func (x *TraceChunkData) ProtoReflect() protoreflect.Message {
	mi := &file_datadog_remoteagent_observer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceChunkData.ProtoReflect.Descriptor instead.
func (*TraceChunkData) Descriptor() ([]byte, []int) {
	return file_datadog_remoteagent_observer_proto_rawDescGZIP(), []int{2}
}

func (x *TraceChunkData) GetPayloadData() []byte {
	if x != nil {
		return x.PayloadData
	}
	return nil
}

func (x *TraceChunkData) GetReceivedAtNs() int64 {
	if x != nil {
		return x.ReceivedAtNs
	}
	return 0
}

// GetProfilesRequest is sent by core-agent to request buffered profiles.
type GetProfilesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// max_items limits the number of profiles returned (0 = no limit).
	MaxItems      uint32 `protobuf:"varint,1,opt,name=max_items,json=maxItems,proto3" json:"max_items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfilesRequest) Reset() {
	*x = GetProfilesRequest{}
	mi := &file_datadog_remoteagent_observer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfilesRequest) ProtoMessage() {}

func (x *GetProfilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datadog_remoteagent_observer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfilesRequest.ProtoReflect.Descriptor instead.
func (*GetProfilesRequest) Descriptor() ([]byte, []int) {
	return file_datadog_remoteagent_observer_proto_rawDescGZIP(), []int{3}
}

func (x *GetProfilesRequest) GetMaxItems() uint32 {
	if x != nil {
		return x.MaxItems
	}
	return 0
}

// GetProfilesResponse contains buffered profiles from trace-agent.
type GetProfilesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// profiles contains the buffered profile data.
	Profiles []*ProfileData `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	// dropped_count indicates how many profiles were dropped due to buffer overflow.
	DroppedCount uint64 `protobuf:"varint,2,opt,name=dropped_count,json=droppedCount,proto3" json:"dropped_count,omitempty"`
	// has_more indicates if there is more data available in the buffer.
	HasMore       bool `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfilesResponse) Reset() {
	*x = GetProfilesResponse{}
	mi := &file_datadog_remoteagent_observer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfilesResponse) ProtoMessage() {}

func (x *GetProfilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_datadog_remoteagent_observer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfilesResponse.ProtoReflect.Descriptor instead.
func (*GetProfilesResponse) Descriptor() ([]byte, []int) {
	return file_datadog_remoteagent_observer_proto_rawDescGZIP(), []int{4}
}

func (x *GetProfilesResponse) GetProfiles() []*ProfileData {
	if x != nil {
		return x.Profiles
	}
	return nil
}

func (x *GetProfilesResponse) GetDroppedCount() uint64 {
	if x != nil {
		return x.DroppedCount
	}
	return 0
}

func (x *GetProfilesResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

// ProfileData contains profile metadata and optionally inline data.
// Profile format is language-agnostic (pprof for Go/Python, JFR for Java, etc.).
// The observer stores profiles as opaque binary blobs without parsing or transforming them.
type ProfileData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// profile_id is a unique identifier for this profile.
	ProfileId string `protobuf:"bytes,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	// profile_type identifies the kind of profile (cpu, heap, mutex, etc.).
	ProfileType string `protobuf:"bytes,2,opt,name=profile_type,json=profileType,proto3" json:"profile_type,omitempty"`
	// service is the name of the service that produced this profile.
	Service string `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	// env is the environment tag.
	Env string `protobuf:"bytes,4,opt,name=env,proto3" json:"env,omitempty"`
	// version is the application version.
	Version string `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	// hostname is where the profile was collected.
	Hostname string `protobuf:"bytes,6,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// container_id is the container where the profile was collected.
	ContainerId string `protobuf:"bytes,7,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	// timestamp_ns is when the profile was collected (nanoseconds since epoch).
	TimestampNs int64 `protobuf:"varint,8,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	// duration_ns is the profile duration (nanoseconds).
	DurationNs int64 `protobuf:"varint,9,opt,name=duration_ns,json=durationNs,proto3" json:"duration_ns,omitempty"`
	// tags are additional profile tags.
	Tags map[string]string `protobuf:"bytes,10,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// content_type is the original Content-Type header (format is language-specific).
	ContentType string `protobuf:"bytes,11,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	// inline_data contains the opaque binary profile data (may be empty if too large).
	InlineData []byte `protobuf:"bytes,12,opt,name=inline_data,json=inlineData,proto3" json:"inline_data,omitempty"`
	// received_at_ns is when trace-agent received this profile (nanoseconds since epoch).
	ReceivedAtNs  int64 `protobuf:"varint,13,opt,name=received_at_ns,json=receivedAtNs,proto3" json:"received_at_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileData) Reset() {
	*x = ProfileData{}
	mi := &file_datadog_remoteagent_observer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileData) ProtoMessage() {}

func (x *ProfileData) ProtoReflect() protoreflect.Message {
	mi := &file_datadog_remoteagent_observer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileData.ProtoReflect.Descriptor instead.
func (*ProfileData) Descriptor() ([]byte, []int) {
	return file_datadog_remoteagent_observer_proto_rawDescGZIP(), []int{5}
}

func (x *ProfileData) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *ProfileData) GetProfileType() string {
	if x != nil {
		return x.ProfileType
	}
	return ""
}

func (x *ProfileData) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *ProfileData) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

func (x *ProfileData) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ProfileData) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *ProfileData) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ProfileData) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *ProfileData) GetDurationNs() int64 {
	if x != nil {
		return x.DurationNs
	}
	return 0
}

func (x *ProfileData) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ProfileData) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ProfileData) GetInlineData() []byte {
	if x != nil {
		return x.InlineData
	}
	return nil
}

func (x *ProfileData) GetReceivedAtNs() int64 {
	if x != nil {
		return x.ReceivedAtNs
	}
	return 0
}

var File_datadog_remoteagent_observer_proto protoreflect.FileDescriptor

const file_datadog_remoteagent_observer_proto_rawDesc = "" +
	"\n" +
	"\"datadog/remoteagent/observer.proto\x12\x1fdatadog.remoteagent.observer.v1\"/\n" +
	"\x10GetTracesRequest\x12\x1b\n" +
	"\tmax_items\x18\x01 \x01(\rR\bmaxItems\"\xf3\x01\n" +
	"\x11GetTracesResponse\x12G\n" +
	"\x06traces\x18\x01 \x03(\v2/.datadog.remoteagent.observer.v1.TraceChunkDataR\x06traces\x12#\n" +
	"\rdropped_count\x18\x02 \x01(\x04R\fdroppedCount\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\x12%\n" +
	"\x0estats_payloads\x18\x04 \x03(\fR\rstatsPayloads\x12.\n" +
	"\x13stats_dropped_count\x18\x05 \x01(\x04R\x11statsDroppedCount\"Y\n" +
	"\x0eTraceChunkData\x12!\n" +
	"\fpayload_data\x18\x01 \x01(\fR\vpayloadData\x12$\n" +
	"\x0ereceived_at_ns\x18\x02 \x01(\x03R\freceivedAtNs\"1\n" +
	"\x12GetProfilesRequest\x12\x1b\n" +
	"\tmax_items\x18\x01 \x01(\rR\bmaxItems\"\x9f\x01\n" +
	"\x13GetProfilesResponse\x12H\n" +
	"\bprofiles\x18\x01 \x03(\v2,.datadog.remoteagent.observer.v1.ProfileDataR\bprofiles\x12#\n" +
	"\rdropped_count\x18\x02 \x01(\x04R\fdroppedCount\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\"\x87\x04\n" +
	"\vProfileData\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\tR\tprofileId\x12!\n" +
	"\fprofile_type\x18\x02 \x01(\tR\vprofileType\x12\x18\n" +
	"\aservice\x18\x03 \x01(\tR\aservice\x12\x10\n" +
	"\x03env\x18\x04 \x01(\tR\x03env\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12\x1a\n" +
	"\bhostname\x18\x06 \x01(\tR\bhostname\x12!\n" +
	"\fcontainer_id\x18\a \x01(\tR\vcontainerId\x12!\n" +
	"\ftimestamp_ns\x18\b \x01(\x03R\vtimestampNs\x12\x1f\n" +
	"\vduration_ns\x18\t \x01(\x03R\n" +
	"durationNs\x12J\n" +
	"\x04tags\x18\n" +
	" \x03(\v26.datadog.remoteagent.observer.v1.ProfileData.TagsEntryR\x04tags\x12!\n" +
	"\fcontent_type\x18\v \x01(\tR\vcontentType\x12\x1f\n" +
	"\vinline_data\x18\f \x01(\fR\n" +
	"inlineData\x12$\n" +
	"\x0ereceived_at_ns\x18\r \x01(\x03R\freceivedAtNs\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\x80\x02\n" +
	"\x10ObserverProvider\x12r\n" +
	"\tGetTraces\x121.datadog.remoteagent.observer.v1.GetTracesRequest\x1a2.datadog.remoteagent.observer.v1.GetTracesResponse\x12x\n" +
	"\vGetProfiles\x123.datadog.remoteagent.observer.v1.GetProfilesRequest\x1a4.datadog.remoteagent.observer.v1.GetProfilesResponseB\x15Z\x13pkg/proto/pbgo/coreb\x06proto3"

var (
	file_datadog_remoteagent_observer_proto_rawDescOnce sync.Once
	file_datadog_remoteagent_observer_proto_rawDescData []byte
)

func file_datadog_remoteagent_observer_proto_rawDescGZIP() []byte {
	file_datadog_remoteagent_observer_proto_rawDescOnce.Do(func() {
		file_datadog_remoteagent_observer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_datadog_remoteagent_observer_proto_rawDesc), len(file_datadog_remoteagent_observer_proto_rawDesc)))
	})
	return file_datadog_remoteagent_observer_proto_rawDescData
}

var file_datadog_remoteagent_observer_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_datadog_remoteagent_observer_proto_goTypes = []any{
	(*GetTracesRequest)(nil),    // 0: datadog.remoteagent.observer.v1.GetTracesRequest
	(*GetTracesResponse)(nil),   // 1: datadog.remoteagent.observer.v1.GetTracesResponse
	(*TraceChunkData)(nil),      // 2: datadog.remoteagent.observer.v1.TraceChunkData
	(*GetProfilesRequest)(nil),  // 3: datadog.remoteagent.observer.v1.GetProfilesRequest
	(*GetProfilesResponse)(nil), // 4: datadog.remoteagent.observer.v1.GetProfilesResponse
	(*ProfileData)(nil),         // 5: datadog.remoteagent.observer.v1.ProfileData
	nil,                         // 6: datadog.remoteagent.observer.v1.ProfileData.TagsEntry
}
var file_datadog_remoteagent_observer_proto_depIdxs = []int32{
	2, // 0: datadog.remoteagent.observer.v1.GetTracesResponse.traces:type_name -> datadog.remoteagent.observer.v1.TraceChunkData
	5, // 1: datadog.remoteagent.observer.v1.GetProfilesResponse.profiles:type_name -> datadog.remoteagent.observer.v1.ProfileData
	6, // 2: datadog.remoteagent.observer.v1.ProfileData.tags:type_name -> datadog.remoteagent.observer.v1.ProfileData.TagsEntry
	0, // 3: datadog.remoteagent.observer.v1.ObserverProvider.GetTraces:input_type -> datadog.remoteagent.observer.v1.GetTracesRequest
	3, // 4: datadog.remoteagent.observer.v1.ObserverProvider.GetProfiles:input_type -> datadog.remoteagent.observer.v1.GetProfilesRequest
	1, // 5: datadog.remoteagent.observer.v1.ObserverProvider.GetTraces:output_type -> datadog.remoteagent.observer.v1.GetTracesResponse
	4, // 6: datadog.remoteagent.observer.v1.ObserverProvider.GetProfiles:output_type -> datadog.remoteagent.observer.v1.GetProfilesResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_datadog_remoteagent_observer_proto_init() }
func file_datadog_remoteagent_observer_proto_init() {
	if File_datadog_remoteagent_observer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_datadog_remoteagent_observer_proto_rawDesc), len(file_datadog_remoteagent_observer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_datadog_remoteagent_observer_proto_goTypes,
		DependencyIndexes: file_datadog_remoteagent_observer_proto_depIdxs,
		MessageInfos:      file_datadog_remoteagent_observer_proto_msgTypes,
	}.Build()
	File_datadog_remoteagent_observer_proto = out.File
	file_datadog_remoteagent_observer_proto_goTypes = nil
	file_datadog_remoteagent_observer_proto_depIdxs = nil
}
