load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")
load("//bazel/rules/go_package_metadata:defs.bzl", "go_package_metadata")

package(default_package_metadata = [":go_package_metadata"])

go_package_metadata(
    name = "go_package_metadata",
    module = "github.com/DataDog/datadog-agent/pkg/config/basic",
)

go_library(
    name = "basic",
    srcs = [
        "convert.go",
        "validate_basic.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/pkg/config/basic",
    visibility = ["//visibility:public"],
    deps = ["@com_github_spf13_cast//:cast"],
)

dd_agent_go_test(
    name = "basic_test",
    srcs = [
        "convert_test.go",
        "validate_basic_test.go",
    ],
    embed = [":basic"],
    deps = [
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
