// Unless explicitly stated otherwise all files in this repository are licensed
// under the Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2016-present Datadog, Inc.

//go:build linux_bpf

// Package codegen is used to generate bpf program source code based on probe definitions
package codegen

import (
	"testing"

	"github.com/DataDog/datadog-agent/pkg/dynamicinstrumentation/ditypes"
	"github.com/stretchr/testify/assert"
)

func TestApplyCaptureDepth(t *testing.T) {
	tests := []struct {
		name           string
		parameters     []*ditypes.Parameter
		targetDepth    int
		expectedResult []*ditypes.Parameter
	}{
		{
			name: "Slice of uint depth 2 (should include element, fully capturing slice)",
			parameters: []*ditypes.Parameter{
				{
					Name:             "u",
					ID:               "",
					Type:             "[]uint",
					TotalSize:        24,
					Kind:             0x17,
					FieldOffset:      0x0,
					DoNotCapture:     false,
					NotCaptureReason: 0x0,
					ParameterPieces: []*ditypes.Parameter{
						{
							Name:                "array",
							ID:                  "KTOAUD",
							Type:                "*uint",
							TotalSize:           8,
							Kind:                0x16,
							LocationExpressions: nil,
							FieldOffset:         0x0,
							DoNotCapture:        false,
							NotCaptureReason:    ditypes.CaptureDepthReached,
							ParameterPieces: []*ditypes.Parameter{
								{
									Name:             "",
									ID:               "",
									Type:             "uint",
									TotalSize:        8,
									Kind:             0x7,
									FieldOffset:      0x0,
									DoNotCapture:     false,
									NotCaptureReason: ditypes.CaptureDepthReached,
									ParameterPieces:  nil,
								},
							},
						},
						{
							Name:             "len",
							ID:               "",
							Type:             "int",
							TotalSize:        8,
							Kind:             0x2,
							FieldOffset:      0x8,
							DoNotCapture:     false,
							NotCaptureReason: ditypes.CaptureDepthReached,
							ParameterPieces:  nil,
						},
						{
							Name:                "cap",
							ID:                  "",
							Type:                "int",
							TotalSize:           8,
							Kind:                0x2,
							LocationExpressions: nil,
							FieldOffset:         0x10,
							DoNotCapture:        false,
							NotCaptureReason:    ditypes.CaptureDepthReached,
							ParameterPieces:     nil,
						},
					},
				},
			},
			expectedResult: []*ditypes.Parameter{
				{
					Name:             "u",
					ID:               "",
					Type:             "[]uint",
					TotalSize:        24,
					Kind:             0x17,
					FieldOffset:      0x0,
					DoNotCapture:     false,
					NotCaptureReason: 0x0,
					ParameterPieces: []*ditypes.Parameter{
						{
							Name:                "array",
							ID:                  "KTOAUD",
							Type:                "*uint",
							TotalSize:           8,
							Kind:                0x16,
							LocationExpressions: nil,
							FieldOffset:         0x0,
							DoNotCapture:        false,
							NotCaptureReason:    ditypes.CaptureDepthReached,
							ParameterPieces: []*ditypes.Parameter{
								{
									Name:             "",
									ID:               "",
									Type:             "uint",
									TotalSize:        8,
									Kind:             0x7,
									FieldOffset:      0x0,
									DoNotCapture:     false,
									NotCaptureReason: ditypes.CaptureDepthReached,
									ParameterPieces:  nil,
								},
							},
						},
						{
							Name:             "len",
							ID:               "",
							Type:             "int",
							TotalSize:        8,
							Kind:             0x2,
							FieldOffset:      0x8,
							DoNotCapture:     false,
							NotCaptureReason: ditypes.CaptureDepthReached,
							ParameterPieces:  nil,
						},
						{
							Name:                "cap",
							ID:                  "",
							Type:                "int",
							TotalSize:           8,
							Kind:                0x2,
							LocationExpressions: nil,
							FieldOffset:         0x10,
							DoNotCapture:        false,
							NotCaptureReason:    ditypes.CaptureDepthReached,
							ParameterPieces:     nil,
						},
					},
				},
			},
			targetDepth: 2,
		},
		{
			name: "Slice of uint depth 0 (shouldn't capture slice at all)",
			parameters: []*ditypes.Parameter{
				{
					Name:             "u",
					ID:               "",
					Type:             "[]uint",
					TotalSize:        24,
					Kind:             0x17,
					FieldOffset:      0x0,
					DoNotCapture:     false,
					NotCaptureReason: 0x0,
					ParameterPieces: []*ditypes.Parameter{
						{
							Name:                "array",
							ID:                  "KTOAUD",
							Type:                "*uint",
							TotalSize:           8,
							Kind:                0x16,
							LocationExpressions: nil,
							FieldOffset:         0x0,
							DoNotCapture:        false,
							NotCaptureReason:    ditypes.CaptureDepthReached,
							ParameterPieces: []*ditypes.Parameter{
								{
									Name:             "actual uint",
									ID:               "",
									Type:             "uint",
									TotalSize:        8,
									Kind:             0x7,
									FieldOffset:      0x0,
									DoNotCapture:     false,
									NotCaptureReason: ditypes.CaptureDepthReached,
									ParameterPieces:  nil,
								},
							},
						},
						{
							Name:             "len",
							ID:               "",
							Type:             "int",
							TotalSize:        8,
							Kind:             0x2,
							FieldOffset:      0x8,
							DoNotCapture:     false,
							NotCaptureReason: ditypes.CaptureDepthReached,
							ParameterPieces:  nil,
						},
						{
							Name:                "cap",
							ID:                  "",
							Type:                "int",
							TotalSize:           8,
							Kind:                0x2,
							LocationExpressions: nil,
							FieldOffset:         0x10,
							DoNotCapture:        false,
							NotCaptureReason:    ditypes.CaptureDepthReached,
							ParameterPieces:     nil,
						},
					},
				},
			},
			expectedResult: []*ditypes.Parameter{
				{
					Name:             "u",
					ID:               "",
					Type:             "[]uint",
					TotalSize:        24,
					Kind:             0x17,
					FieldOffset:      0x0,
					DoNotCapture:     true,
					NotCaptureReason: ditypes.CaptureDepthReached,
					ParameterPieces: []*ditypes.Parameter{
						{
							Name:                "array",
							ID:                  "KTOAUD",
							Type:                "*uint",
							TotalSize:           8,
							Kind:                0x16,
							LocationExpressions: nil,
							FieldOffset:         0x0,
							DoNotCapture:        false,
							NotCaptureReason:    ditypes.CaptureDepthReached,
							ParameterPieces: []*ditypes.Parameter{
								{
									Name:             "actual uint",
									ID:               "",
									Type:             "uint",
									TotalSize:        8,
									Kind:             0x7,
									FieldOffset:      0x0,
									DoNotCapture:     true,
									NotCaptureReason: ditypes.CaptureDepthReached,
									ParameterPieces:  nil,
								},
							},
						},
						{
							Name:             "len",
							ID:               "",
							Type:             "int",
							TotalSize:        8,
							Kind:             0x2,
							FieldOffset:      0x8,
							DoNotCapture:     false,
							NotCaptureReason: ditypes.CaptureDepthReached,
							ParameterPieces:  nil,
						},
						{
							Name:                "cap",
							ID:                  "",
							Type:                "int",
							TotalSize:           8,
							Kind:                0x2,
							LocationExpressions: nil,
							FieldOffset:         0x10,
							DoNotCapture:        false,
							NotCaptureReason:    ditypes.CaptureDepthReached,
							ParameterPieces:     nil,
						},
					},
				},
			},
			targetDepth: 0,
		},
		{
			name: "Capture Depth Larger Than Tree Depth",
			parameters: []*ditypes.Parameter{
				{
					Name:                "x",
					ID:                  "",
					Type:                "github.com/DataDog/datadog-agent/pkg/dynamicinstrumentation/testutil/sample.aStruct",
					TotalSize:           4,
					Kind:                0x19,
					Location:            nil,
					LocationExpressions: nil,
					FieldOffset:         0x0,
					DoNotCapture:        false,
					NotCaptureReason:    0x0,
					ParameterPieces: []*ditypes.Parameter{
						{
							Name:             "aBool",
							ID:               "",
							Type:             "bool",
							TotalSize:        1,
							Kind:             0x1,
							Location:         &ditypes.Location{InReg: true, StackOffset: 0, Register: 0, NeedsDereference: false, PointerOffset: 0x0},
							FieldOffset:      0x0,
							DoNotCapture:     false,
							NotCaptureReason: 0x0,
							ParameterPieces:  nil,
						},
						{
							Name:             "aString",
							ID:               "",
							Type:             "string",
							TotalSize:        16,
							Kind:             0x18,
							Location:         nil,
							FieldOffset:      0x8,
							DoNotCapture:     false,
							NotCaptureReason: 0x0,
							ParameterPieces: []*ditypes.Parameter{
								{
									Name:                "str",
									ID:                  "SHJWBK",
									Type:                "*uint8",
									TotalSize:           8,
									Kind:                0x16,
									Location:            &ditypes.Location{InReg: true, StackOffset: 0, Register: 1, NeedsDereference: false, PointerOffset: 0x0},
									LocationExpressions: nil,
									FieldOffset:         0x0,
									DoNotCapture:        false,
									NotCaptureReason:    0x0,
									ParameterPieces: []*ditypes.Parameter{
										{
											Name:                "",
											ID:                  "",
											Type:                "uint8",
											TotalSize:           1,
											Kind:                0x8,
											Location:            nil,
											LocationExpressions: nil,
											FieldOffset:         0x0,
											DoNotCapture:        false,
											NotCaptureReason:    0x0,
											ParameterPieces:     nil,
										},
									},
								},
								{
									Name:             "len",
									ID:               "",
									Type:             "int",
									TotalSize:        8,
									Kind:             0x2,
									Location:         &ditypes.Location{InReg: true, StackOffset: 0, Register: 2, NeedsDereference: false, PointerOffset: 0x0},
									FieldOffset:      0x8,
									DoNotCapture:     false,
									NotCaptureReason: 0x0,
									ParameterPieces:  nil,
								},
							},
						},
						{
							Name:             "aNumber",
							ID:               "",
							Type:             "int",
							TotalSize:        8,
							Kind:             0x2,
							Location:         &ditypes.Location{InReg: true, StackOffset: 0, Register: 3, NeedsDereference: false, PointerOffset: 0x0},
							FieldOffset:      0x18,
							DoNotCapture:     false,
							NotCaptureReason: 0x0,
							ParameterPieces:  nil,
						},
						{
							Name:                "nested",
							ID:                  "",
							Type:                "github.com/DataDog/datadog-agent/pkg/dynamicinstrumentation/testutil/sample.nestedStruct",
							TotalSize:           2,
							Kind:                0x19,
							Location:            nil,
							LocationExpressions: nil,
							FieldOffset:         0x20,
							DoNotCapture:        false,
							NotCaptureReason:    0x0,
							ParameterPieces: []*ditypes.Parameter{
								{
									Name:             "anotherInt",
									ID:               "",
									Type:             "int",
									TotalSize:        8,
									Kind:             0x2,
									Location:         &ditypes.Location{InReg: true, StackOffset: 0, Register: 4, NeedsDereference: false, PointerOffset: 0x0},
									FieldOffset:      0x0,
									DoNotCapture:     false,
									NotCaptureReason: 0x0,
									ParameterPieces:  nil,
								},
								{
									Name:             "anotherString",
									ID:               "",
									Type:             "string",
									TotalSize:        16,
									Kind:             0x18,
									Location:         nil,
									FieldOffset:      0x8,
									DoNotCapture:     false,
									NotCaptureReason: 0x0,
									ParameterPieces: []*ditypes.Parameter{
										{
											Name:                "str",
											ID:                  "XKDYLV",
											Type:                "*uint8",
											TotalSize:           8,
											Kind:                0x16,
											Location:            &ditypes.Location{InReg: true, StackOffset: 0, Register: 5, NeedsDereference: false, PointerOffset: 0x0},
											LocationExpressions: nil,
											FieldOffset:         0x0,
											DoNotCapture:        false,
											NotCaptureReason:    0x0,
											ParameterPieces: []*ditypes.Parameter{
												{
													Name:                "",
													ID:                  "",
													Type:                "uint8",
													TotalSize:           1,
													Kind:                0x8,
													Location:            nil,
													LocationExpressions: nil,
													FieldOffset:         0x0,
													DoNotCapture:        false,
													NotCaptureReason:    0x0,
													ParameterPieces:     nil,
												},
											},
										},
										{
											Name:             "len",
											ID:               "",
											Type:             "int",
											TotalSize:        8,
											Kind:             0x2,
											Location:         &ditypes.Location{InReg: true, StackOffset: 0, Register: 6, NeedsDereference: false, PointerOffset: 0x0},
											FieldOffset:      0x8,
											DoNotCapture:     false,
											NotCaptureReason: 0x0,
											ParameterPieces:  nil,
										},
									},
								},
							},
						},
					},
				},
			},
			expectedResult: []*ditypes.Parameter{
				{
					Name:                "x",
					ID:                  "",
					Type:                "github.com/DataDog/datadog-agent/pkg/dynamicinstrumentation/testutil/sample.aStruct",
					TotalSize:           4,
					Kind:                0x19,
					Location:            nil,
					LocationExpressions: nil,
					FieldOffset:         0x0,
					DoNotCapture:        false,
					NotCaptureReason:    0x0,
					ParameterPieces: []*ditypes.Parameter{
						{
							Name:             "aBool",
							ID:               "",
							Type:             "bool",
							TotalSize:        1,
							Kind:             0x1,
							Location:         &ditypes.Location{InReg: true, StackOffset: 0, Register: 0, NeedsDereference: false, PointerOffset: 0x0},
							FieldOffset:      0x0,
							DoNotCapture:     false,
							NotCaptureReason: 0x0,
							ParameterPieces:  nil,
						},
						{
							Name:             "aString",
							ID:               "",
							Type:             "string",
							TotalSize:        16,
							Kind:             0x18,
							Location:         nil,
							FieldOffset:      0x8,
							DoNotCapture:     false,
							NotCaptureReason: 0x0,
							ParameterPieces: []*ditypes.Parameter{
								{
									Name:                "str",
									ID:                  "SHJWBK",
									Type:                "*uint8",
									TotalSize:           8,
									Kind:                0x16,
									Location:            &ditypes.Location{InReg: true, StackOffset: 0, Register: 1, NeedsDereference: false, PointerOffset: 0x0},
									LocationExpressions: nil,
									FieldOffset:         0x0,
									DoNotCapture:        false,
									NotCaptureReason:    0x0,
									ParameterPieces: []*ditypes.Parameter{
										{
											Name:                "",
											ID:                  "",
											Type:                "uint8",
											TotalSize:           1,
											Kind:                0x8,
											Location:            nil,
											LocationExpressions: nil,
											FieldOffset:         0x0,
											DoNotCapture:        false,
											NotCaptureReason:    0x0,
											ParameterPieces:     nil,
										},
									},
								},
								{
									Name:             "len",
									ID:               "",
									Type:             "int",
									TotalSize:        8,
									Kind:             0x2,
									Location:         &ditypes.Location{InReg: true, StackOffset: 0, Register: 2, NeedsDereference: false, PointerOffset: 0x0},
									FieldOffset:      0x8,
									DoNotCapture:     false,
									NotCaptureReason: 0x0,
									ParameterPieces:  nil,
								},
							},
						},
						{
							Name:             "aNumber",
							ID:               "",
							Type:             "int",
							TotalSize:        8,
							Kind:             0x2,
							Location:         &ditypes.Location{InReg: true, StackOffset: 0, Register: 3, NeedsDereference: false, PointerOffset: 0x0},
							FieldOffset:      0x18,
							DoNotCapture:     false,
							NotCaptureReason: 0x0,
							ParameterPieces:  nil,
						},
						{
							Name:                "nested",
							ID:                  "",
							Type:                "github.com/DataDog/datadog-agent/pkg/dynamicinstrumentation/testutil/sample.nestedStruct",
							TotalSize:           2,
							Kind:                0x19,
							Location:            nil,
							LocationExpressions: nil,
							FieldOffset:         0x20,
							DoNotCapture:        false,
							NotCaptureReason:    0x0,
							ParameterPieces: []*ditypes.Parameter{
								{
									Name:             "anotherInt",
									ID:               "",
									Type:             "int",
									TotalSize:        8,
									Kind:             0x2,
									Location:         &ditypes.Location{InReg: true, StackOffset: 0, Register: 4, NeedsDereference: false, PointerOffset: 0x0},
									FieldOffset:      0x0,
									DoNotCapture:     false,
									NotCaptureReason: 0x0,
									ParameterPieces:  nil,
								},
								{
									Name:             "anotherString",
									ID:               "",
									Type:             "string",
									TotalSize:        16,
									Kind:             0x18,
									Location:         nil,
									FieldOffset:      0x8,
									DoNotCapture:     false,
									NotCaptureReason: 0x0,
									ParameterPieces: []*ditypes.Parameter{
										{
											Name:                "str",
											ID:                  "XKDYLV",
											Type:                "*uint8",
											TotalSize:           8,
											Kind:                0x16,
											Location:            &ditypes.Location{InReg: true, StackOffset: 0, Register: 5, NeedsDereference: false, PointerOffset: 0x0},
											LocationExpressions: nil,
											FieldOffset:         0x0,
											DoNotCapture:        false,
											NotCaptureReason:    0x0,
											ParameterPieces: []*ditypes.Parameter{
												{
													Name:                "",
													ID:                  "",
													Type:                "uint8",
													TotalSize:           1,
													Kind:                0x8,
													Location:            nil,
													LocationExpressions: nil,
													FieldOffset:         0x0,
													DoNotCapture:        false,
													NotCaptureReason:    0x0,
													ParameterPieces:     nil,
												},
											},
										},
										{
											Name:             "len",
											ID:               "",
											Type:             "int",
											TotalSize:        8,
											Kind:             0x2,
											Location:         &ditypes.Location{InReg: true, StackOffset: 0, Register: 6, NeedsDereference: false, PointerOffset: 0x0},
											FieldOffset:      0x8,
											DoNotCapture:     false,
											NotCaptureReason: 0x0,
											ParameterPieces:  nil,
										},
									},
								},
							},
						},
					},
				},
			},
			targetDepth: 20,
		},
		{
			name: "Bool Pointer",
			parameters: []*ditypes.Parameter{
				{
					Name:                "z",
					ID:                  "",
					Type:                "*bool",
					TotalSize:           8,
					Kind:                0x16,
					Location:            &ditypes.Location{InReg: true, StackOffset: 0, Register: 0, NeedsDereference: false, PointerOffset: 0x0},
					LocationExpressions: nil,
					FieldOffset:         0x0,
					DoNotCapture:        false,
					NotCaptureReason:    0x0,
					ParameterPieces: []*ditypes.Parameter{
						{
							Name:             "",
							ID:               "",
							Type:             "bool",
							TotalSize:        1,
							Kind:             0x1,
							FieldOffset:      0x0,
							DoNotCapture:     false,
							NotCaptureReason: 0x0,
							ParameterPieces:  nil,
						},
					},
				},
			},
			expectedResult: []*ditypes.Parameter{
				{
					Name:                "z",
					ID:                  "",
					Type:                "*bool",
					TotalSize:           8,
					Kind:                0x16,
					Location:            &ditypes.Location{InReg: true, StackOffset: 0, Register: 0, NeedsDereference: false, PointerOffset: 0x0},
					LocationExpressions: nil,
					FieldOffset:         0x0,
					DoNotCapture:        true,
					NotCaptureReason:    ditypes.CaptureDepthReached,
					ParameterPieces: []*ditypes.Parameter{
						{
							Name:             "",
							ID:               "",
							Type:             "bool",
							TotalSize:        1,
							Kind:             0x1,
							FieldOffset:      0x0,
							DoNotCapture:     true,
							NotCaptureReason: ditypes.CaptureDepthReached,
							ParameterPieces:  nil,
						},
					},
				},
			},
			targetDepth: 0,
		},
		{
			name: "Struct Pointer, capture all",
			parameters: []*ditypes.Parameter{
				{
					Name:                "x",
					ID:                  "",
					Type:                "*github.com/DataDog/datadog-agent/pkg/dynamicinstrumentation/testutil/sample.nStruct",
					TotalSize:           8,
					Kind:                0x16,
					Location:            &ditypes.Location{InReg: true, StackOffset: 0, Register: 0, NeedsDereference: false, PointerOffset: 0x0},
					LocationExpressions: nil,
					FieldOffset:         0x0,
					DoNotCapture:        false,
					NotCaptureReason:    0x0,
					ParameterPieces: []*ditypes.Parameter{
						{
							Name:                "",
							ID:                  "",
							Type:                "github.com/DataDog/datadog-agent/pkg/dynamicinstrumentation/testutil/sample.nStruct",
							TotalSize:           3,
							Kind:                0x19,
							LocationExpressions: nil,
							FieldOffset:         0x0,
							DoNotCapture:        false,
							NotCaptureReason:    0x0,
							ParameterPieces: []*ditypes.Parameter{
								{
									Name:             "aBool",
									ID:               "",
									Type:             "bool",
									TotalSize:        1,
									Kind:             0x1,
									FieldOffset:      0x0,
									DoNotCapture:     false,
									NotCaptureReason: 0x0,
									ParameterPieces:  nil,
								},
								{
									Name:             "aInt",
									ID:               "",
									Type:             "int",
									TotalSize:        8,
									Kind:             0x2,
									FieldOffset:      0x8,
									DoNotCapture:     false,
									NotCaptureReason: 0x0,
									ParameterPieces:  nil,
								},
								{
									Name:             "aInt16",
									ID:               "",
									Type:             "int16",
									TotalSize:        2,
									Kind:             0x4,
									FieldOffset:      0x10,
									DoNotCapture:     false,
									NotCaptureReason: 0x0,
									ParameterPieces:  nil,
								},
							},
						},
					},
				},
			},
			expectedResult: []*ditypes.Parameter{
				{
					Name:                "x",
					ID:                  "",
					Type:                "*github.com/DataDog/datadog-agent/pkg/dynamicinstrumentation/testutil/sample.nStruct",
					TotalSize:           8,
					Kind:                0x16,
					Location:            &ditypes.Location{InReg: true, StackOffset: 0, Register: 0, NeedsDereference: false, PointerOffset: 0x0},
					LocationExpressions: nil,
					FieldOffset:         0x0,
					DoNotCapture:        false,
					NotCaptureReason:    0x0,
					ParameterPieces: []*ditypes.Parameter{
						{
							Name:                "",
							ID:                  "",
							Type:                "github.com/DataDog/datadog-agent/pkg/dynamicinstrumentation/testutil/sample.nStruct",
							TotalSize:           3,
							Kind:                0x19,
							LocationExpressions: nil,
							FieldOffset:         0x0,
							DoNotCapture:        false,
							NotCaptureReason:    0x0,
							ParameterPieces: []*ditypes.Parameter{
								{
									Name:             "aBool",
									ID:               "",
									Type:             "bool",
									TotalSize:        1,
									Kind:             0x1,
									FieldOffset:      0x0,
									DoNotCapture:     false,
									NotCaptureReason: 0x0,
									ParameterPieces:  nil,
								},
								{
									Name:             "aInt",
									ID:               "",
									Type:             "int",
									TotalSize:        8,
									Kind:             0x2,
									FieldOffset:      0x8,
									DoNotCapture:     false,
									NotCaptureReason: 0x0,
									ParameterPieces:  nil,
								},
								{
									Name:             "aInt16",
									ID:               "",
									Type:             "int16",
									TotalSize:        2,
									Kind:             0x4,
									FieldOffset:      0x10,
									DoNotCapture:     false,
									NotCaptureReason: 0x0,
									ParameterPieces:  nil,
								},
							},
						},
					},
				},
			},
			targetDepth: 2,
		},
		{
			name: "Struct Pointer, dont capture",
			parameters: []*ditypes.Parameter{
				{
					Name:                "x",
					ID:                  "",
					Type:                "*github.com/DataDog/datadog-agent/pkg/dynamicinstrumentation/testutil/sample.nStruct",
					TotalSize:           8,
					Kind:                0x16,
					Location:            &ditypes.Location{InReg: true, StackOffset: 0, Register: 0, NeedsDereference: false, PointerOffset: 0x0},
					LocationExpressions: nil,
					FieldOffset:         0x0,
					DoNotCapture:        false,
					NotCaptureReason:    0x0,
					ParameterPieces: []*ditypes.Parameter{
						{
							Name:                "",
							ID:                  "",
							Type:                "github.com/DataDog/datadog-agent/pkg/dynamicinstrumentation/testutil/sample.nStruct",
							TotalSize:           3,
							Kind:                0x19,
							LocationExpressions: nil,
							FieldOffset:         0x0,
							DoNotCapture:        false,
							NotCaptureReason:    0x0,
							ParameterPieces: []*ditypes.Parameter{
								{
									Name:             "aBool",
									ID:               "",
									Type:             "bool",
									TotalSize:        1,
									Kind:             0x1,
									FieldOffset:      0x0,
									DoNotCapture:     false,
									NotCaptureReason: 0x0,
									ParameterPieces:  nil,
								},
								{
									Name:             "aInt",
									ID:               "",
									Type:             "int",
									TotalSize:        8,
									Kind:             0x2,
									FieldOffset:      0x8,
									DoNotCapture:     false,
									NotCaptureReason: 0x0,
									ParameterPieces:  nil,
								},
								{
									Name:             "aInt16",
									ID:               "",
									Type:             "int16",
									TotalSize:        2,
									Kind:             0x4,
									FieldOffset:      0x10,
									DoNotCapture:     false,
									NotCaptureReason: 0x0,
									ParameterPieces:  nil,
								},
							},
						},
					},
				},
			},
			expectedResult: []*ditypes.Parameter{
				{
					Name:                "x",
					ID:                  "",
					Type:                "*github.com/DataDog/datadog-agent/pkg/dynamicinstrumentation/testutil/sample.nStruct",
					TotalSize:           8,
					Kind:                0x16,
					Location:            &ditypes.Location{InReg: true, StackOffset: 0, Register: 0, NeedsDereference: false, PointerOffset: 0x0},
					LocationExpressions: nil,
					FieldOffset:         0x0,
					DoNotCapture:        true,
					NotCaptureReason:    ditypes.CaptureDepthReached,
					ParameterPieces: []*ditypes.Parameter{
						{
							Name:                "",
							ID:                  "",
							Type:                "github.com/DataDog/datadog-agent/pkg/dynamicinstrumentation/testutil/sample.nStruct",
							TotalSize:           3,
							Kind:                0x19,
							LocationExpressions: nil,
							FieldOffset:         0x0,
							DoNotCapture:        true,
							NotCaptureReason:    ditypes.CaptureDepthReached,
							ParameterPieces: []*ditypes.Parameter{
								{
									Name:             "aBool",
									ID:               "",
									Type:             "bool",
									TotalSize:        1,
									Kind:             0x1,
									FieldOffset:      0x0,
									DoNotCapture:     true,
									NotCaptureReason: ditypes.CaptureDepthReached,
									ParameterPieces:  nil,
								},
								{
									Name:             "aInt",
									ID:               "",
									Type:             "int",
									TotalSize:        8,
									Kind:             0x2,
									FieldOffset:      0x8,
									DoNotCapture:     true,
									NotCaptureReason: ditypes.CaptureDepthReached,
									ParameterPieces:  nil,
								},
								{
									Name:             "aInt16",
									ID:               "",
									Type:             "int16",
									TotalSize:        2,
									Kind:             0x4,
									FieldOffset:      0x10,
									DoNotCapture:     true,
									NotCaptureReason: ditypes.CaptureDepthReached,
									ParameterPieces:  nil,
								},
							},
						},
					},
				},
			},
			targetDepth: 0,
		},
		{
			name: "struct with int and string pointer - capture all",
			parameters: []*ditypes.Parameter{
				{
					Name:                "z",
					ID:                  "",
					Type:                "github.com/DataDog/datadog-agent/pkg/dynamicinstrumentation/testutil/sample.spws",
					TotalSize:           2,
					Kind:                0x19,
					Location:            nil,
					LocationExpressions: nil,
					FieldOffset:         0x0,
					DoNotCapture:        false,
					NotCaptureReason:    0x0,
					ParameterPieces: []*ditypes.Parameter{
						{
							Name:             "a",
							ID:               "",
							Type:             "int",
							TotalSize:        8,
							Kind:             0x2,
							Location:         &ditypes.Location{InReg: true, StackOffset: 0, Register: 0, NeedsDereference: false, PointerOffset: 0x0},
							FieldOffset:      0x0,
							DoNotCapture:     false,
							NotCaptureReason: 0x0,
							ParameterPieces:  nil,
						},
						{
							Name:                "x",
							ID:                  "HVXBYS",
							Type:                "*string",
							TotalSize:           8,
							Kind:                0x16,
							Location:            &ditypes.Location{InReg: true, StackOffset: 0, Register: 1, NeedsDereference: false, PointerOffset: 0x0},
							LocationExpressions: nil,
							FieldOffset:         0x8,
							DoNotCapture:        false,
							NotCaptureReason:    0x0,
							ParameterPieces: []*ditypes.Parameter{
								{
									Name:             "",
									ID:               "",
									Type:             "string",
									TotalSize:        16,
									Kind:             0x18,
									FieldOffset:      0x0,
									DoNotCapture:     false,
									NotCaptureReason: 0x0,
									ParameterPieces: []*ditypes.Parameter{
										{
											Name:             "str",
											ID:               "YCXUAP",
											Type:             "*uint8",
											TotalSize:        8,
											Kind:             0x16,
											FieldOffset:      0x0,
											DoNotCapture:     false,
											NotCaptureReason: 0x0,
											ParameterPieces: []*ditypes.Parameter{
												{
													Name:             "",
													ID:               "",
													Type:             "uint8",
													TotalSize:        1,
													Kind:             0x8,
													FieldOffset:      0x0,
													DoNotCapture:     false,
													NotCaptureReason: 0x0,
													ParameterPieces:  nil,
												},
											},
										},
										{
											Name:             "len",
											ID:               "",
											Type:             "int",
											TotalSize:        8,
											Kind:             0x2,
											FieldOffset:      0x8,
											DoNotCapture:     false,
											NotCaptureReason: 0x0,
											ParameterPieces:  nil,
										},
									},
								},
							},
						},
					},
				},
			},
			expectedResult: []*ditypes.Parameter{
				{
					Name:                "z",
					ID:                  "",
					Type:                "github.com/DataDog/datadog-agent/pkg/dynamicinstrumentation/testutil/sample.spws",
					TotalSize:           2,
					Kind:                0x19,
					Location:            nil,
					LocationExpressions: nil,
					FieldOffset:         0x0,
					DoNotCapture:        false,
					NotCaptureReason:    0x0,
					ParameterPieces: []*ditypes.Parameter{
						{
							Name:             "a",
							ID:               "",
							Type:             "int",
							TotalSize:        8,
							Kind:             0x2,
							Location:         &ditypes.Location{InReg: true, StackOffset: 0, Register: 0, NeedsDereference: false, PointerOffset: 0x0},
							FieldOffset:      0x0,
							DoNotCapture:     false,
							NotCaptureReason: 0x0,
							ParameterPieces:  nil,
						},
						{
							Name:                "x",
							ID:                  "HVXBYS",
							Type:                "*string",
							TotalSize:           8,
							Kind:                0x16,
							Location:            &ditypes.Location{InReg: true, StackOffset: 0, Register: 1, NeedsDereference: false, PointerOffset: 0x0},
							LocationExpressions: nil,
							FieldOffset:         0x8,
							DoNotCapture:        false,
							NotCaptureReason:    0x0,
							ParameterPieces: []*ditypes.Parameter{
								{
									Name:             "",
									ID:               "",
									Type:             "string",
									TotalSize:        16,
									Kind:             0x18,
									FieldOffset:      0x0,
									DoNotCapture:     false,
									NotCaptureReason: 0x0,
									ParameterPieces: []*ditypes.Parameter{
										{
											Name:             "str",
											ID:               "YCXUAP",
											Type:             "*uint8",
											TotalSize:        8,
											Kind:             0x16,
											FieldOffset:      0x0,
											DoNotCapture:     false,
											NotCaptureReason: 0x0,
											ParameterPieces: []*ditypes.Parameter{
												{
													Name:             "",
													ID:               "",
													Type:             "uint8",
													TotalSize:        1,
													Kind:             0x8,
													FieldOffset:      0x0,
													DoNotCapture:     false,
													NotCaptureReason: 0x0,
													ParameterPieces:  nil,
												},
											},
										},
										{
											Name:             "len",
											ID:               "",
											Type:             "int",
											TotalSize:        8,
											Kind:             0x2,
											FieldOffset:      0x8,
											DoNotCapture:     false,
											NotCaptureReason: 0x0,
											ParameterPieces:  nil,
										},
									},
								},
							},
						},
					},
				},
			},
			targetDepth: 2,
		},
		{
			name: "struct with int and string pointer - capture none",
			parameters: []*ditypes.Parameter{
				{
					Name:                "z",
					ID:                  "",
					Type:                "github.com/DataDog/datadog-agent/pkg/dynamicinstrumentation/testutil/sample.spws",
					TotalSize:           2,
					Kind:                0x19,
					Location:            nil,
					LocationExpressions: nil,
					FieldOffset:         0x0,
					DoNotCapture:        false,
					NotCaptureReason:    0x0,
					ParameterPieces: []*ditypes.Parameter{
						{
							Name:             "a",
							ID:               "",
							Type:             "int",
							TotalSize:        8,
							Kind:             0x2,
							FieldOffset:      0x0,
							DoNotCapture:     false,
							NotCaptureReason: 0x0,
							ParameterPieces:  nil,
						},
						{
							Name:                "x",
							ID:                  "HVXBYS",
							Type:                "*string",
							TotalSize:           8,
							Kind:                0x16,
							LocationExpressions: nil,
							FieldOffset:         0x8,
							DoNotCapture:        false,
							NotCaptureReason:    0x0,
							ParameterPieces: []*ditypes.Parameter{
								{
									Name:             "",
									ID:               "",
									Type:             "string",
									TotalSize:        16,
									Kind:             0x18,
									FieldOffset:      0x0,
									DoNotCapture:     false,
									NotCaptureReason: 0x0,
									ParameterPieces: []*ditypes.Parameter{
										{
											Name:             "str",
											ID:               "YCXUAP",
											Type:             "*uint8",
											TotalSize:        8,
											Kind:             0x16,
											FieldOffset:      0x0,
											DoNotCapture:     false,
											NotCaptureReason: 0x0,
											ParameterPieces: []*ditypes.Parameter{
												{
													Name:             "",
													ID:               "",
													Type:             "uint8",
													TotalSize:        1,
													Kind:             0x8,
													FieldOffset:      0x0,
													DoNotCapture:     false,
													NotCaptureReason: 0x0,
													ParameterPieces:  nil,
												},
											},
										},
										{
											Name:             "len",
											ID:               "",
											Type:             "int",
											TotalSize:        8,
											Kind:             0x2,
											FieldOffset:      0x8,
											DoNotCapture:     false,
											NotCaptureReason: 0x0,
											ParameterPieces:  nil,
										},
									},
								},
							},
						},
					},
				},
			},
			expectedResult: []*ditypes.Parameter{
				{
					Name:                "z",
					ID:                  "",
					Type:                "github.com/DataDog/datadog-agent/pkg/dynamicinstrumentation/testutil/sample.spws",
					TotalSize:           2,
					Kind:                0x19,
					Location:            nil,
					LocationExpressions: nil,
					FieldOffset:         0x0,
					DoNotCapture:        true,
					NotCaptureReason:    ditypes.CaptureDepthReached,
					ParameterPieces: []*ditypes.Parameter{
						{
							Name:             "a",
							ID:               "",
							Type:             "int",
							TotalSize:        8,
							Kind:             0x2,
							FieldOffset:      0x0,
							DoNotCapture:     true,
							NotCaptureReason: ditypes.CaptureDepthReached,
							ParameterPieces:  nil,
						},
						{
							Name:                "x",
							ID:                  "HVXBYS",
							Type:                "*string",
							TotalSize:           8,
							Kind:                0x16,
							LocationExpressions: nil,
							FieldOffset:         0x8,
							DoNotCapture:        true,
							NotCaptureReason:    ditypes.CaptureDepthReached,
							ParameterPieces: []*ditypes.Parameter{
								{
									Name:             "",
									ID:               "",
									Type:             "string",
									TotalSize:        16,
									Kind:             0x18,
									FieldOffset:      0x0,
									DoNotCapture:     true,
									NotCaptureReason: ditypes.CaptureDepthReached,
									ParameterPieces: []*ditypes.Parameter{
										{
											Name:             "str",
											ID:               "YCXUAP",
											Type:             "*uint8",
											TotalSize:        8,
											Kind:             0x16,
											FieldOffset:      0x0,
											DoNotCapture:     true,
											NotCaptureReason: ditypes.CaptureDepthReached,
											ParameterPieces: []*ditypes.Parameter{
												{
													Name:             "",
													ID:               "",
													Type:             "uint8",
													TotalSize:        1,
													Kind:             0x8,
													FieldOffset:      0x0,
													DoNotCapture:     true,
													NotCaptureReason: ditypes.CaptureDepthReached,
													ParameterPieces:  nil,
												},
											},
										},
										{
											Name:             "len",
											ID:               "",
											Type:             "int",
											TotalSize:        8,
											Kind:             0x2,
											FieldOffset:      0x8,
											DoNotCapture:     true,
											NotCaptureReason: ditypes.CaptureDepthReached,
											ParameterPieces:  nil,
										},
									},
								},
							},
						},
					},
				},
			},
			targetDepth: 0,
		},
		{
			name: "Uint array",
			parameters: []*ditypes.Parameter{
				{
					Name:             "x",
					ID:               "",
					Type:             "[2]uint",
					TotalSize:        2,
					Kind:             0x11,
					Location:         &ditypes.Location{InReg: false, StackOffset: 16, Register: 0, NeedsDereference: false, PointerOffset: 0x0},
					FieldOffset:      0x0,
					DoNotCapture:     false,
					NotCaptureReason: 0x0,
					ParameterPieces: []*ditypes.Parameter{
						{
							Name:             "[2]uint[0]",
							ID:               "",
							Type:             "uint",
							TotalSize:        8,
							Kind:             0x7,
							FieldOffset:      0x0,
							DoNotCapture:     false,
							NotCaptureReason: 0x0,
							ParameterPieces:  nil,
						},
						{
							Name:             "[2]uint[1]",
							ID:               "",
							Type:             "uint",
							TotalSize:        8,
							Kind:             0x7,
							FieldOffset:      0x0,
							DoNotCapture:     false,
							NotCaptureReason: 0x0,
							ParameterPieces:  nil,
						},
					},
				},
			},
			expectedResult: []*ditypes.Parameter{
				{
					Name:             "x",
					ID:               "",
					Type:             "[2]uint",
					TotalSize:        2,
					Kind:             0x11,
					Location:         &ditypes.Location{InReg: false, StackOffset: 16, Register: 0, NeedsDereference: false, PointerOffset: 0x0},
					FieldOffset:      0x0,
					DoNotCapture:     false,
					NotCaptureReason: 0x0,
					ParameterPieces: []*ditypes.Parameter{
						{
							Name:             "[2]uint[0]",
							ID:               "",
							Type:             "uint",
							TotalSize:        8,
							Kind:             0x7,
							FieldOffset:      0x0,
							DoNotCapture:     false,
							NotCaptureReason: 0x0,
							ParameterPieces:  nil,
						},
						{
							Name:             "[2]uint[1]",
							ID:               "",
							Type:             "uint",
							TotalSize:        8,
							Kind:             0x7,
							FieldOffset:      0x0,
							DoNotCapture:     false,
							NotCaptureReason: 0x0,
							ParameterPieces:  nil,
						},
					},
				},
			},
			targetDepth: 2,
		},
		{
			name: "Uint array dont capture",
			parameters: []*ditypes.Parameter{
				{
					Name:             "x",
					ID:               "",
					Type:             "[2]uint",
					TotalSize:        2,
					Kind:             0x11,
					Location:         &ditypes.Location{InReg: false, StackOffset: 16, Register: 0, NeedsDereference: false, PointerOffset: 0x0},
					FieldOffset:      0x0,
					DoNotCapture:     false,
					NotCaptureReason: 0x0,
					ParameterPieces: []*ditypes.Parameter{
						{
							Name:             "[2]uint[0]",
							ID:               "",
							Type:             "uint",
							TotalSize:        8,
							Kind:             0x7,
							FieldOffset:      0x0,
							DoNotCapture:     false,
							NotCaptureReason: 0x0,
							ParameterPieces:  nil,
						},
						{
							Name:             "[2]uint[1]",
							ID:               "",
							Type:             "uint",
							TotalSize:        8,
							Kind:             0x7,
							FieldOffset:      0x0,
							DoNotCapture:     false,
							NotCaptureReason: 0x0,
							ParameterPieces:  nil,
						},
					},
				},
			},
			expectedResult: []*ditypes.Parameter{
				{
					Name:             "x",
					ID:               "",
					Type:             "[2]uint",
					TotalSize:        2,
					Kind:             0x11,
					Location:         &ditypes.Location{InReg: false, StackOffset: 16, Register: 0, NeedsDereference: false, PointerOffset: 0x0},
					FieldOffset:      0x0,
					DoNotCapture:     true,
					NotCaptureReason: ditypes.CaptureDepthReached,
					ParameterPieces: []*ditypes.Parameter{
						{
							Name:             "[2]uint[0]",
							ID:               "",
							Type:             "uint",
							TotalSize:        8,
							Kind:             0x7,
							FieldOffset:      0x0,
							DoNotCapture:     true,
							NotCaptureReason: ditypes.CaptureDepthReached,
							ParameterPieces:  nil,
						},
						{
							Name:             "[2]uint[1]",
							ID:               "",
							Type:             "uint",
							TotalSize:        8,
							Kind:             0x7,
							FieldOffset:      0x0,
							DoNotCapture:     true,
							NotCaptureReason: ditypes.CaptureDepthReached,
							ParameterPieces:  nil,
						},
					},
				},
			},
			targetDepth: 0,
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			setDepthLimit(test.parameters, test.targetDepth)
			assert.Equal(t, test.expectedResult, test.parameters)
		})
	}
}

func TestPruneDoNotCaptureParams(t *testing.T) {
	tests := []struct {
		name           string
		parameters     []*ditypes.Parameter
		targetDepth    int
		expectedResult []*ditypes.Parameter
	}{
		{
			name: "two layers",
			parameters: []*ditypes.Parameter{
				{
					Name:             "a",
					ID:               "",
					Type:             "int",
					TotalSize:        8,
					DoNotCapture:     false,
					NotCaptureReason: 0x0,
					ParameterPieces: []*ditypes.Parameter{
						{
							Name:             "a",
							ID:               "",
							Type:             "int",
							TotalSize:        8,
							DoNotCapture:     true,
							NotCaptureReason: 0x0,
							ParameterPieces:  nil,
						},
					},
				},
			},
			expectedResult: []*ditypes.Parameter{
				{
					Name:             "a",
					ID:               "",
					Type:             "int",
					TotalSize:        8,
					DoNotCapture:     false,
					NotCaptureReason: 0x0,
					ParameterPieces:  []*ditypes.Parameter{},
				},
			},
		},
		{
			name: "multi-tiered layers",
			parameters: []*ditypes.Parameter{
				{
					Name:             "a",
					ID:               "",
					Type:             "int",
					TotalSize:        8,
					DoNotCapture:     false,
					NotCaptureReason: 0x0,
					ParameterPieces: []*ditypes.Parameter{
						{
							Name:             "b",
							ID:               "",
							Type:             "int",
							TotalSize:        8,
							DoNotCapture:     false,
							NotCaptureReason: 0x0,
							ParameterPieces: []*ditypes.Parameter{
								{
									Name:             "d",
									ID:               "",
									Type:             "int",
									TotalSize:        8,
									DoNotCapture:     true,
									NotCaptureReason: 0x0,
									ParameterPieces:  []*ditypes.Parameter{},
								},
								{
									Name:             "e",
									ID:               "",
									Type:             "int",
									TotalSize:        8,
									DoNotCapture:     true,
									NotCaptureReason: 0x0,
									ParameterPieces:  []*ditypes.Parameter{},
								},
							},
						},
						{
							Name:             "c",
							ID:               "",
							Type:             "int",
							TotalSize:        8,
							DoNotCapture:     false,
							NotCaptureReason: 0x0,
							ParameterPieces:  []*ditypes.Parameter{},
						},
					},
				},
			},
			expectedResult: []*ditypes.Parameter{
				{
					Name:             "a",
					ID:               "",
					Type:             "int",
					TotalSize:        8,
					DoNotCapture:     false,
					NotCaptureReason: 0x0,
					ParameterPieces: []*ditypes.Parameter{
						{
							Name:             "b",
							ID:               "",
							Type:             "int",
							TotalSize:        8,
							DoNotCapture:     false,
							NotCaptureReason: 0x0,
							ParameterPieces:  []*ditypes.Parameter{},
						},
						{
							Name:             "c",
							ID:               "",
							Type:             "int",
							TotalSize:        8,
							DoNotCapture:     false,
							NotCaptureReason: 0x0,
							ParameterPieces:  []*ditypes.Parameter{},
						},
					},
				},
			},
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			p := pruneDoNotCaptureParams(test.parameters)
			assert.Equal(t, test.expectedResult, p)
		})
	}
}
