// Unless explicitly stated otherwise all files in this repository are licensed
// under the Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2016-present Datadog, Inc.

//go:build linux_bpf

// Package codegen is used to generate bpf program source code based on probe definitions
package codegen

import (
	"testing"

	"github.com/DataDog/datadog-agent/pkg/dynamicinstrumentation/ditypes"
	"github.com/stretchr/testify/assert"
)

func TestApplyCaptureDepth(t *testing.T) {
	tests := []struct {
		name           string
		parameters     []*ditypes.Parameter
		targetDepth    int
		expectedResult []*ditypes.Parameter
	}{
		{
			name: "Slice of uint depth 1 (should include element, fully capturing slice)",
			parameters: []*ditypes.Parameter{
				&ditypes.Parameter{
					Name:             "u",
					ID:               "",
					Type:             "[]uint",
					TotalSize:        24,
					Kind:             0x17,
					FieldOffset:      0x0,
					DoNotCapture:     false,
					NotCaptureReason: 0x0,
					ParameterPieces: []*ditypes.Parameter{
						&ditypes.Parameter{
							Name:                "array",
							ID:                  "KTOAUD",
							Type:                "*uint",
							TotalSize:           8,
							Kind:                0x16,
							LocationExpressions: nil,
							FieldOffset:         0x0,
							DoNotCapture:        false,
							NotCaptureReason:    0x4,
							ParameterPieces: []*ditypes.Parameter{
								&ditypes.Parameter{
									Name:             "",
									ID:               "",
									Type:             "uint",
									TotalSize:        8,
									Kind:             0x7,
									FieldOffset:      0x0,
									DoNotCapture:     false,
									NotCaptureReason: 0x4,
									ParameterPieces:  nil,
								},
							},
						},
						&ditypes.Parameter{
							Name:             "len",
							ID:               "",
							Type:             "int",
							TotalSize:        8,
							Kind:             0x2,
							FieldOffset:      0x8,
							DoNotCapture:     false,
							NotCaptureReason: 0x4,
							ParameterPieces:  nil,
						},
						&ditypes.Parameter{
							Name:                "cap",
							ID:                  "",
							Type:                "int",
							TotalSize:           8,
							Kind:                0x2,
							LocationExpressions: nil,
							FieldOffset:         0x10,
							DoNotCapture:        false,
							NotCaptureReason:    0x4,
							ParameterPieces:     nil,
						},
					},
				},
			},
			expectedResult: []*ditypes.Parameter{
				&ditypes.Parameter{
					Name:             "u",
					ID:               "",
					Type:             "[]uint",
					TotalSize:        24,
					Kind:             0x17,
					FieldOffset:      0x0,
					DoNotCapture:     false,
					NotCaptureReason: 0x0,
					ParameterPieces: []*ditypes.Parameter{
						&ditypes.Parameter{
							Name:                "array",
							ID:                  "KTOAUD",
							Type:                "*uint",
							TotalSize:           8,
							Kind:                0x16,
							LocationExpressions: nil,
							FieldOffset:         0x0,
							DoNotCapture:        false,
							NotCaptureReason:    0x4,
							ParameterPieces: []*ditypes.Parameter{
								&ditypes.Parameter{
									Name:             "",
									ID:               "",
									Type:             "uint",
									TotalSize:        8,
									Kind:             0x7,
									FieldOffset:      0x0,
									DoNotCapture:     false,
									NotCaptureReason: 0x4,
									ParameterPieces:  nil,
								},
							},
						},
						&ditypes.Parameter{
							Name:             "len",
							ID:               "",
							Type:             "int",
							TotalSize:        8,
							Kind:             0x2,
							FieldOffset:      0x8,
							DoNotCapture:     false,
							NotCaptureReason: 0x4,
							ParameterPieces:  nil,
						},
						&ditypes.Parameter{
							Name:                "cap",
							ID:                  "",
							Type:                "int",
							TotalSize:           8,
							Kind:                0x2,
							LocationExpressions: nil,
							FieldOffset:         0x10,
							DoNotCapture:        false,
							NotCaptureReason:    0x4,
							ParameterPieces:     nil,
						},
					},
				},
			},
			targetDepth: 1,
		},
		{
			name: "Slice of uint depth 0 (shouldn't capture slice at all)",
			parameters: []*ditypes.Parameter{
				&ditypes.Parameter{
					Name:             "u",
					ID:               "",
					Type:             "[]uint",
					TotalSize:        24,
					Kind:             0x17,
					FieldOffset:      0x0,
					DoNotCapture:     false,
					NotCaptureReason: 0x0,
					ParameterPieces: []*ditypes.Parameter{
						&ditypes.Parameter{
							Name:                "array",
							ID:                  "KTOAUD",
							Type:                "*uint",
							TotalSize:           8,
							Kind:                0x16,
							LocationExpressions: nil,
							FieldOffset:         0x0,
							DoNotCapture:        false,
							NotCaptureReason:    0x4,
							ParameterPieces: []*ditypes.Parameter{
								&ditypes.Parameter{
									Name:             "actual uint",
									ID:               "",
									Type:             "uint",
									TotalSize:        8,
									Kind:             0x7,
									FieldOffset:      0x0,
									DoNotCapture:     false,
									NotCaptureReason: 0x4,
									ParameterPieces:  nil,
								},
							},
						},
						&ditypes.Parameter{
							Name:             "len",
							ID:               "",
							Type:             "int",
							TotalSize:        8,
							Kind:             0x2,
							FieldOffset:      0x8,
							DoNotCapture:     false,
							NotCaptureReason: 0x4,
							ParameterPieces:  nil,
						},
						&ditypes.Parameter{
							Name:                "cap",
							ID:                  "",
							Type:                "int",
							TotalSize:           8,
							Kind:                0x2,
							LocationExpressions: nil,
							FieldOffset:         0x10,
							DoNotCapture:        false,
							NotCaptureReason:    0x4,
							ParameterPieces:     nil,
						},
					},
				},
			},
			expectedResult: []*ditypes.Parameter{
				&ditypes.Parameter{
					Name:             "u",
					ID:               "",
					Type:             "[]uint",
					TotalSize:        24,
					Kind:             0x17,
					FieldOffset:      0x0,
					DoNotCapture:     true,
					NotCaptureReason: 0x4,
					ParameterPieces: []*ditypes.Parameter{
						&ditypes.Parameter{
							Name:                "array",
							ID:                  "KTOAUD",
							Type:                "*uint",
							TotalSize:           8,
							Kind:                0x16,
							LocationExpressions: nil,
							FieldOffset:         0x0,
							DoNotCapture:        false,
							NotCaptureReason:    0x4,
							ParameterPieces: []*ditypes.Parameter{
								&ditypes.Parameter{
									Name:             "actual uint",
									ID:               "",
									Type:             "uint",
									TotalSize:        8,
									Kind:             0x7,
									FieldOffset:      0x0,
									DoNotCapture:     true,
									NotCaptureReason: 0x4,
									ParameterPieces:  nil,
								},
							},
						},
						&ditypes.Parameter{
							Name:             "len",
							ID:               "",
							Type:             "int",
							TotalSize:        8,
							Kind:             0x2,
							FieldOffset:      0x8,
							DoNotCapture:     false,
							NotCaptureReason: 0x4,
							ParameterPieces:  nil,
						},
						&ditypes.Parameter{
							Name:                "cap",
							ID:                  "",
							Type:                "int",
							TotalSize:           8,
							Kind:                0x2,
							LocationExpressions: nil,
							FieldOffset:         0x10,
							DoNotCapture:        false,
							NotCaptureReason:    0x4,
							ParameterPieces:     nil,
						},
					},
				},
			},
			targetDepth: 0,
		},
		{
			name: "Capture Depth Larger Than Tree Depth",
			parameters: []*ditypes.Parameter{
				&ditypes.Parameter{
					Name:                "x",
					ID:                  "",
					Type:                "github.com/DataDog/datadog-agent/pkg/dynamicinstrumentation/testutil/sample.aStruct",
					TotalSize:           4,
					Kind:                0x19,
					Location:            (*ditypes.Location)(nil),
					LocationExpressions: nil,
					FieldOffset:         0x0,
					DoNotCapture:        false,
					NotCaptureReason:    0x0,
					ParameterPieces: []*ditypes.Parameter{
						&ditypes.Parameter{
							Name:             "aBool",
							ID:               "",
							Type:             "bool",
							TotalSize:        1,
							Kind:             0x1,
							Location:         &ditypes.Location{InReg: true, StackOffset: 0, Register: 0, NeedsDereference: false, PointerOffset: 0x0},
							FieldOffset:      0x0,
							DoNotCapture:     false,
							NotCaptureReason: 0x0,
							ParameterPieces:  nil,
						},
						&ditypes.Parameter{
							Name:             "aString",
							ID:               "",
							Type:             "string",
							TotalSize:        16,
							Kind:             0x18,
							Location:         (*ditypes.Location)(nil),
							FieldOffset:      0x8,
							DoNotCapture:     false,
							NotCaptureReason: 0x0,
							ParameterPieces: []*ditypes.Parameter{
								&ditypes.Parameter{
									Name:                "str",
									ID:                  "SHJWBK",
									Type:                "*uint8",
									TotalSize:           8,
									Kind:                0x16,
									Location:            &ditypes.Location{InReg: true, StackOffset: 0, Register: 1, NeedsDereference: false, PointerOffset: 0x0},
									LocationExpressions: nil,
									FieldOffset:         0x0,
									DoNotCapture:        false,
									NotCaptureReason:    0x0,
									ParameterPieces: []*ditypes.Parameter{
										&ditypes.Parameter{
											Name:                "",
											ID:                  "",
											Type:                "uint8",
											TotalSize:           1,
											Kind:                0x8,
											Location:            (*ditypes.Location)(nil),
											LocationExpressions: nil,
											FieldOffset:         0x0,
											DoNotCapture:        false,
											NotCaptureReason:    0x0,
											ParameterPieces:     nil,
										},
									},
								},
								&ditypes.Parameter{
									Name:             "len",
									ID:               "",
									Type:             "int",
									TotalSize:        8,
									Kind:             0x2,
									Location:         &ditypes.Location{InReg: true, StackOffset: 0, Register: 2, NeedsDereference: false, PointerOffset: 0x0},
									FieldOffset:      0x8,
									DoNotCapture:     false,
									NotCaptureReason: 0x0,
									ParameterPieces:  nil,
								},
							},
						},
						&ditypes.Parameter{
							Name:             "aNumber",
							ID:               "",
							Type:             "int",
							TotalSize:        8,
							Kind:             0x2,
							Location:         &ditypes.Location{InReg: true, StackOffset: 0, Register: 3, NeedsDereference: false, PointerOffset: 0x0},
							FieldOffset:      0x18,
							DoNotCapture:     false,
							NotCaptureReason: 0x0,
							ParameterPieces:  nil,
						},
						&ditypes.Parameter{
							Name:                "nested",
							ID:                  "",
							Type:                "github.com/DataDog/datadog-agent/pkg/dynamicinstrumentation/testutil/sample.nestedStruct",
							TotalSize:           2,
							Kind:                0x19,
							Location:            (*ditypes.Location)(nil),
							LocationExpressions: nil,
							FieldOffset:         0x20,
							DoNotCapture:        false,
							NotCaptureReason:    0x0,
							ParameterPieces: []*ditypes.Parameter{
								&ditypes.Parameter{
									Name:             "anotherInt",
									ID:               "",
									Type:             "int",
									TotalSize:        8,
									Kind:             0x2,
									Location:         &ditypes.Location{InReg: true, StackOffset: 0, Register: 4, NeedsDereference: false, PointerOffset: 0x0},
									FieldOffset:      0x0,
									DoNotCapture:     false,
									NotCaptureReason: 0x0,
									ParameterPieces:  nil,
								},
								&ditypes.Parameter{
									Name:             "anotherString",
									ID:               "",
									Type:             "string",
									TotalSize:        16,
									Kind:             0x18,
									Location:         (*ditypes.Location)(nil),
									FieldOffset:      0x8,
									DoNotCapture:     false,
									NotCaptureReason: 0x0,
									ParameterPieces: []*ditypes.Parameter{
										&ditypes.Parameter{
											Name:                "str",
											ID:                  "XKDYLV",
											Type:                "*uint8",
											TotalSize:           8,
											Kind:                0x16,
											Location:            &ditypes.Location{InReg: true, StackOffset: 0, Register: 5, NeedsDereference: false, PointerOffset: 0x0},
											LocationExpressions: nil,
											FieldOffset:         0x0,
											DoNotCapture:        false,
											NotCaptureReason:    0x0,
											ParameterPieces: []*ditypes.Parameter{
												&ditypes.Parameter{
													Name:                "",
													ID:                  "",
													Type:                "uint8",
													TotalSize:           1,
													Kind:                0x8,
													Location:            (*ditypes.Location)(nil),
													LocationExpressions: nil,
													FieldOffset:         0x0,
													DoNotCapture:        false,
													NotCaptureReason:    0x0,
													ParameterPieces:     nil,
												},
											},
										},
										&ditypes.Parameter{
											Name:             "len",
											ID:               "",
											Type:             "int",
											TotalSize:        8,
											Kind:             0x2,
											Location:         &ditypes.Location{InReg: true, StackOffset: 0, Register: 6, NeedsDereference: false, PointerOffset: 0x0},
											FieldOffset:      0x8,
											DoNotCapture:     false,
											NotCaptureReason: 0x0,
											ParameterPieces:  nil,
										},
									},
								},
							},
						},
					},
				},
			},
			expectedResult: []*ditypes.Parameter{
				&ditypes.Parameter{
					Name:                "x",
					ID:                  "",
					Type:                "github.com/DataDog/datadog-agent/pkg/dynamicinstrumentation/testutil/sample.aStruct",
					TotalSize:           4,
					Kind:                0x19,
					Location:            (*ditypes.Location)(nil),
					LocationExpressions: nil,
					FieldOffset:         0x0,
					DoNotCapture:        false,
					NotCaptureReason:    0x0,
					ParameterPieces: []*ditypes.Parameter{
						&ditypes.Parameter{
							Name:             "aBool",
							ID:               "",
							Type:             "bool",
							TotalSize:        1,
							Kind:             0x1,
							Location:         &ditypes.Location{InReg: true, StackOffset: 0, Register: 0, NeedsDereference: false, PointerOffset: 0x0},
							FieldOffset:      0x0,
							DoNotCapture:     false,
							NotCaptureReason: 0x0,
							ParameterPieces:  nil,
						},
						&ditypes.Parameter{
							Name:             "aString",
							ID:               "",
							Type:             "string",
							TotalSize:        16,
							Kind:             0x18,
							Location:         (*ditypes.Location)(nil),
							FieldOffset:      0x8,
							DoNotCapture:     false,
							NotCaptureReason: 0x0,
							ParameterPieces: []*ditypes.Parameter{
								&ditypes.Parameter{
									Name:                "str",
									ID:                  "SHJWBK",
									Type:                "*uint8",
									TotalSize:           8,
									Kind:                0x16,
									Location:            &ditypes.Location{InReg: true, StackOffset: 0, Register: 1, NeedsDereference: false, PointerOffset: 0x0},
									LocationExpressions: nil,
									FieldOffset:         0x0,
									DoNotCapture:        false,
									NotCaptureReason:    0x0,
									ParameterPieces: []*ditypes.Parameter{
										&ditypes.Parameter{
											Name:                "",
											ID:                  "",
											Type:                "uint8",
											TotalSize:           1,
											Kind:                0x8,
											Location:            (*ditypes.Location)(nil),
											LocationExpressions: nil,
											FieldOffset:         0x0,
											DoNotCapture:        false,
											NotCaptureReason:    0x0,
											ParameterPieces:     nil,
										},
									},
								},
								&ditypes.Parameter{
									Name:             "len",
									ID:               "",
									Type:             "int",
									TotalSize:        8,
									Kind:             0x2,
									Location:         &ditypes.Location{InReg: true, StackOffset: 0, Register: 2, NeedsDereference: false, PointerOffset: 0x0},
									FieldOffset:      0x8,
									DoNotCapture:     false,
									NotCaptureReason: 0x0,
									ParameterPieces:  nil,
								},
							},
						},
						&ditypes.Parameter{
							Name:             "aNumber",
							ID:               "",
							Type:             "int",
							TotalSize:        8,
							Kind:             0x2,
							Location:         &ditypes.Location{InReg: true, StackOffset: 0, Register: 3, NeedsDereference: false, PointerOffset: 0x0},
							FieldOffset:      0x18,
							DoNotCapture:     false,
							NotCaptureReason: 0x0,
							ParameterPieces:  nil,
						},
						&ditypes.Parameter{
							Name:                "nested",
							ID:                  "",
							Type:                "github.com/DataDog/datadog-agent/pkg/dynamicinstrumentation/testutil/sample.nestedStruct",
							TotalSize:           2,
							Kind:                0x19,
							Location:            (*ditypes.Location)(nil),
							LocationExpressions: nil,
							FieldOffset:         0x20,
							DoNotCapture:        false,
							NotCaptureReason:    0x0,
							ParameterPieces: []*ditypes.Parameter{
								&ditypes.Parameter{
									Name:             "anotherInt",
									ID:               "",
									Type:             "int",
									TotalSize:        8,
									Kind:             0x2,
									Location:         &ditypes.Location{InReg: true, StackOffset: 0, Register: 4, NeedsDereference: false, PointerOffset: 0x0},
									FieldOffset:      0x0,
									DoNotCapture:     false,
									NotCaptureReason: 0x0,
									ParameterPieces:  nil,
								},
								&ditypes.Parameter{
									Name:             "anotherString",
									ID:               "",
									Type:             "string",
									TotalSize:        16,
									Kind:             0x18,
									Location:         (*ditypes.Location)(nil),
									FieldOffset:      0x8,
									DoNotCapture:     false,
									NotCaptureReason: 0x0,
									ParameterPieces: []*ditypes.Parameter{
										&ditypes.Parameter{
											Name:                "str",
											ID:                  "XKDYLV",
											Type:                "*uint8",
											TotalSize:           8,
											Kind:                0x16,
											Location:            &ditypes.Location{InReg: true, StackOffset: 0, Register: 5, NeedsDereference: false, PointerOffset: 0x0},
											LocationExpressions: nil,
											FieldOffset:         0x0,
											DoNotCapture:        false,
											NotCaptureReason:    0x0,
											ParameterPieces: []*ditypes.Parameter{
												&ditypes.Parameter{
													Name:                "",
													ID:                  "",
													Type:                "uint8",
													TotalSize:           1,
													Kind:                0x8,
													Location:            (*ditypes.Location)(nil),
													LocationExpressions: nil,
													FieldOffset:         0x0,
													DoNotCapture:        false,
													NotCaptureReason:    0x0,
													ParameterPieces:     nil,
												},
											},
										},
										&ditypes.Parameter{
											Name:             "len",
											ID:               "",
											Type:             "int",
											TotalSize:        8,
											Kind:             0x2,
											Location:         &ditypes.Location{InReg: true, StackOffset: 0, Register: 6, NeedsDereference: false, PointerOffset: 0x0},
											FieldOffset:      0x8,
											DoNotCapture:     false,
											NotCaptureReason: 0x0,
											ParameterPieces:  nil,
										},
									},
								},
							},
						},
					},
				},
			},
			targetDepth: 20,
		},
		{
			name: "Bool Pointer",
			parameters: []*ditypes.Parameter{
				{
					Name:                "z",
					ID:                  "",
					Type:                "*bool",
					TotalSize:           8,
					Kind:                0x16,
					Location:            &ditypes.Location{InReg: true, StackOffset: 0, Register: 0, NeedsDereference: false, PointerOffset: 0x0},
					LocationExpressions: nil,
					FieldOffset:         0x0,
					DoNotCapture:        false,
					NotCaptureReason:    0x0,
					ParameterPieces: []*ditypes.Parameter{
						{
							Name:             "",
							ID:               "",
							Type:             "bool",
							TotalSize:        1,
							Kind:             0x1,
							FieldOffset:      0x0,
							DoNotCapture:     false,
							NotCaptureReason: 0x0,
							ParameterPieces:  nil,
						},
					},
				},
			},
			expectedResult: []*ditypes.Parameter{
				{
					Name:                "z",
					ID:                  "",
					Type:                "*bool",
					TotalSize:           8,
					Kind:                0x16,
					Location:            &ditypes.Location{InReg: true, StackOffset: 0, Register: 0, NeedsDereference: false, PointerOffset: 0x0},
					LocationExpressions: nil,
					FieldOffset:         0x0,
					DoNotCapture:        true,
					NotCaptureReason:    0x0,
					ParameterPieces: []*ditypes.Parameter{
						{
							Name:             "",
							ID:               "",
							Type:             "bool",
							TotalSize:        1,
							Kind:             0x1,
							FieldOffset:      0x0,
							DoNotCapture:     true,
							NotCaptureReason: 0x0,
							ParameterPieces:  nil,
						},
					},
				},
			},
			targetDepth: 0,
		},

		// {
		// 	name:           "Capture Depth All Get Cut Off",
		// 	parameters:     []*ditypes.Parameter{},
		// 	expectedResult: []*ditypes.Parameter{},
		// 	targetDepth:    1,
		// },
		// {
		// 	name:           "Capture Depth One Leaf Cut Off",
		// 	parameters:     []*ditypes.Parameter{},
		// 	expectedResult: []*ditypes.Parameter{},
		// 	targetDepth:    1,
		// },
		// {
		// 	name:           "Nils",
		// 	parameters:     []*ditypes.Parameter{},
		// 	expectedResult: []*ditypes.Parameter{},
		// 	targetDepth:    2,
		// },
		// {
		// 	name:           "Empties",
		// 	parameters:     []*ditypes.Parameter{},
		// 	expectedResult: []*ditypes.Parameter{},
		// 	targetDepth:    2,
		// },
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			applyCaptureDepth(test.parameters, test.targetDepth)
			assert.Equal(t, test.expectedResult, test.parameters)
		})
	}
}
