load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

go_library(
    name = "fake",
    srcs = ["fake.go"],
    importpath = "github.com/DataDog/datadog-agent/pkg/logs/internal/smb/client/fake",
    visibility = [
        "//pkg/logs:__subpackages__",
        "@com_github_datadog_datadog_agent_pkg_logs_message//:__subpackages__",
        "@com_github_datadog_datadog_agent_pkg_logs_sources//:__subpackages__",
        "@com_github_datadog_datadog_agent_pkg_logs_status_statusinterface//:__subpackages__",
        "@com_github_datadog_datadog_agent_pkg_logs_status_utils//:__subpackages__",
        "@com_github_datadog_datadog_agent_pkg_logs_types//:__subpackages__",
        "@com_github_datadog_datadog_agent_pkg_logs_util_testutils//:__subpackages__",
    ],
    deps = [
        "//pkg/logs/internal/smb/client",
        "//pkg/logs/internal/smb/thirdparty/gosmb2/x/protocol",
    ],
)

dd_agent_go_test(
    name = "fake_test",
    srcs = ["fake_test.go"],
    embed = [":fake"],
    deps = [
        "//pkg/logs/internal/smb/client",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
