load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

go_library(
    name = "autoscaling",
    srcs = [
        "entrypoint.go",
        "update_autoscaler_limits.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/pkg/privateactionrunner/bundles/kubernetes/autoscaling",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/privateactionrunner/bundle-support/kubernetes",
        "//pkg/privateactionrunner/libs/privateconnection",
        "//pkg/privateactionrunner/types",
        "@io_k8s_api//autoscaling/v2:autoscaling",
        "@io_k8s_apimachinery//pkg/apis/meta/v1:meta",
        "@io_k8s_apimachinery//pkg/types",
        "@io_k8s_client_go//kubernetes",
    ],
)

dd_agent_go_test(
    name = "autoscaling_test",
    srcs = [
        "autoscaling_test.go",
        "update_autoscaler_limits_test.go",
    ],
    embed = [":autoscaling"],
    deps = [
        "//pkg/privateactionrunner/bundle-support/test",
        "//pkg/privateactionrunner/libs/privateconnection",
        "//pkg/privateactionrunner/types",
        "@com_github_stretchr_testify//suite",
        "@io_k8s_api//autoscaling/v2:autoscaling",
        "@io_k8s_apimachinery//pkg/apis/meta/v1:meta",
        "@io_k8s_apimachinery//pkg/types",
        "@io_k8s_client_go//kubernetes/fake",
        "@io_k8s_client_go//testing",
    ],
)
