load("@rules_go//go:def.bzl", "go_library")

package(default_package_metadata = ["//test/new-e2e:go_package_metadata"])

go_library(
    name = "consts",
    srcs = ["consts.go"],
    importpath = "github.com/DataDog/datadog-agent/test/new-e2e/tests/installer/windows/consts",
    visibility = ["//visibility:public"],
)
