load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

go_library(
    name = "rcstore",
    srcs = [
        "keystore.go",
        "tuf.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/test/fakeintake/server/rcstore",
    visibility = ["//visibility:public"],
)

dd_agent_go_test(
    name = "rcstore_test",
    srcs = ["tuf_test.go"],
    embed = [":rcstore"],
)
