# gazelle:ebpf_c on

load("//bazel/rules/ebpf:ebpf.bzl", "ebpf_prog")

_TEST_FLAGS = [
    "-g",
    "-DDEBUG=1",
]

ebpf_prog(
    name = "logdebug-test",
    src = "logdebug-test.c",
    core = True,
    extra_flags = _TEST_FLAGS,
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/ebpf/c:hdr/bpf_helpers",
        "//pkg/ebpf/c:hdr/bpf_helpers_custom",
        "//pkg/ebpf/c:hdr/bpf_metadata",
        "//pkg/ebpf/c:hdr/bpf_tracing",
        "//pkg/ebpf/c:hdr/ktypes",
    ],
)

ebpf_prog(
    name = "error_telemetry",
    src = "error_telemetry.c",
    core = True,
    extra_flags = _TEST_FLAGS,
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/ebpf/c:hdr/bpf_metadata",
        "//pkg/ebpf/c:hdr/bpf_telemetry",
        "//pkg/ebpf/c:hdr/bpf_tracing",
        "//pkg/ebpf/c:hdr/compiler",
        "//pkg/ebpf/c:hdr/ktypes",
        "//pkg/ebpf/c:hdr/map-defs",
    ],
)

ebpf_prog(
    name = "sleepable",
    src = "sleepable.c",
    # Included behind #ifdef COMPILE_RUNTIME, which is off for a CO-RE build.
    allowed_unused = ["pkg/ebpf/c/kconfig.h"],
    core = True,
    extra_flags = _TEST_FLAGS,
    deps = [
        "//pkg/ebpf/c:hdr/bpf_metadata",
        "//pkg/ebpf/c:hdr/bpf_telemetry",
        "//pkg/ebpf/c:hdr/bpf_tracing",
        "//pkg/ebpf/c:hdr/kconfig",
        "//pkg/ebpf/c:hdr/ktypes",
        "//pkg/ebpf/c:hdr/map-defs",
    ],
)

ebpf_prog(
    name = "uprobe_attacher-test",
    src = "uprobe_attacher-test.c",
    core = True,
    extra_flags = _TEST_FLAGS,
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/ebpf/c:hdr/bpf_helpers",
        "//pkg/ebpf/c:hdr/bpf_helpers_custom",
        "//pkg/ebpf/c:hdr/bpf_metadata",
        "//pkg/ebpf/c:hdr/bpf_tracing",
        "//pkg/ebpf/c:hdr/ktypes",
    ],
)
