load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "procnet",
    srcs = [
        "parser.go",
        "procnet.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/pkg/network/usm/procnet",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/util/kernel",
        "//pkg/util/kernel/netns",
    ],
)
