load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

go_library(
    name = "procnet",
    srcs = [
        "parser.go",
        "procnet.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/pkg/network/usm/procnet",
    tags = ["manual"],
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/util/kernel",
        "//pkg/util/kernel/netns",
    ],
)

dd_agent_go_test(
    name = "procnet_test",
    srcs = [
        "parser_test.go",
        "procnet_test.go",
    ],
    embed = [":procnet"],
    gotags_sets = [["linux_bpf"]],
    include_default = False,
    deps = [
        "//pkg/network/protocols/http/testutil",
        "@com_github_stretchr_testify//assert",
    ],
)
