load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

go_library(
    name = "containerd",
    srcs = [
        "containerd_util.go",
        "diagnosis.go",
        "hidden_bytes_archive_linux.go",
        "hidden_bytes_linux.go",
        "hidden_bytes_metadata_linux.go",
        "hidden_bytes_state_linux.go",
        "image_layers.go",
        "namespaces.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/pkg/util/containerd",
    visibility = ["//visibility:public"],
    deps = [
        "//comp/core/diagnose/def",
        "//pkg/config/env",
        "//pkg/config/setup",
        "//pkg/errors",
        "//pkg/util/containers/image",
        "//pkg/util/log",
        "//pkg/util/retry",
        "@com_github_containerd_containerd_api//types",
        "@com_github_containerd_containerd_v2//client",
        "@com_github_containerd_containerd_v2//core/containers",
        "@com_github_containerd_containerd_v2//core/leases",
        "@com_github_containerd_containerd_v2//core/mount",
        "@com_github_containerd_containerd_v2//core/snapshots",
        "@com_github_containerd_containerd_v2//defaults",
        "@com_github_containerd_containerd_v2//pkg/namespaces",
        "@com_github_containerd_containerd_v2//pkg/oci",
        "@com_github_containerd_errdefs//:errdefs",
        "@com_github_opencontainers_go_digest//:go-digest",
        "@com_github_opencontainers_image_spec//identity",
        "@com_github_opencontainers_image_spec//specs-go/v1:specs-go",
    ] + select({
        "@rules_go//go/platform:android": [
            "@com_github_containerd_containerd_v2//core/content",
            "@com_github_containerd_containerd_v2//core/images",
            "@com_github_containerd_platforms//:platforms",
            "@com_github_klauspost_compress//zstd",
            "@org_golang_x_sys//unix",
        ],
        "@rules_go//go/platform:linux": [
            "@com_github_containerd_containerd_v2//core/content",
            "@com_github_containerd_containerd_v2//core/images",
            "@com_github_containerd_platforms//:platforms",
            "@com_github_klauspost_compress//zstd",
            "@org_golang_x_sys//unix",
        ],
        "//conditions:default": [],
    }),
)

dd_agent_go_test(
    name = "containerd_test",
    srcs = [
        "containerd_util_test.go",
        "hidden_bytes_archive_linux_test.go",
        "hidden_bytes_linux_test.go",
        "hidden_bytes_metadata_linux_test.go",
        "image_layers_linux_test.go",
        "image_layers_test.go",
        "namespaces_test.go",
    ],
    embed = [":containerd"],
    gotags_sets = [[
        "cel",
        "containerd",
    ]],
    include_default = False,
    deps = [
        "//pkg/config/mock",
        "//pkg/util/containerd/fake",
        "@com_github_containerd_cgroups_v3//cgroup1/stats",
        "@com_github_containerd_containerd_api//types",
        "@com_github_containerd_containerd_v2//client",
        "@com_github_containerd_containerd_v2//core/containers",
        "@com_github_containerd_containerd_v2//core/mount",
        "@com_github_containerd_containerd_v2//core/snapshots",
        "@com_github_containerd_containerd_v2//pkg/cio",
        "@com_github_containerd_containerd_v2//pkg/namespaces",
        "@com_github_containerd_containerd_v2//pkg/oci",
        "@com_github_containerd_errdefs//:errdefs",
        "@com_github_containerd_typeurl_v2//:typeurl",
        "@com_github_gogo_protobuf//types",
        "@com_github_opencontainers_go_digest//:go-digest",
        "@com_github_opencontainers_image_spec//specs-go/v1:specs-go",
        "@com_github_opencontainers_runtime_spec//specs-go",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
        "@org_golang_google_protobuf//types/known/anypb",
    ] + select({
        "@rules_go//go/platform:android": [
            "@com_github_containerd_containerd_v2//core/content",
            "@com_github_containerd_containerd_v2//core/images",
            "@com_github_containerd_platforms//:platforms",
            "@com_github_klauspost_compress//zstd",
            "@com_github_opencontainers_image_spec//specs-go",
            "@org_golang_x_sys//unix",
        ],
        "@rules_go//go/platform:linux": [
            "@com_github_containerd_containerd_v2//core/content",
            "@com_github_containerd_containerd_v2//core/images",
            "@com_github_containerd_platforms//:platforms",
            "@com_github_klauspost_compress//zstd",
            "@com_github_opencontainers_image_spec//specs-go",
            "@org_golang_x_sys//unix",
        ],
        "//conditions:default": [],
    }),
)
