load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "components",
    srcs = [
        "active_directory.go",
        "doc.go",
        "docker_agent.go",
        "ecs_cluster.go",
        "fakeintake.go",
        "kubernetes_agent.go",
        "kubernetes_cluster.go",
        "remotehost.go",
        "remotehost_agent.go",
        "remotehost_docker.go",
        "remotehost_flare.go",
        "remotehost_params.go",
        "remotehost_updater.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/test/e2e-framework/testing/components",
    visibility = ["//visibility:public"],
    deps = [
        "//test/e2e-framework/components/os/types",
        "//test/e2e-framework/components/outputs",
        "//test/e2e-framework/testing/utils/common",
        "//test/e2e-framework/testing/utils/e2e/client",
        "//test/e2e-framework/testing/utils/e2e/client/agentclient",
        "//test/e2e-framework/testing/utils/e2e/client/agentclientparams",
        "//test/e2e-framework/testing/utils/e2e/client/ecs",
        "//test/fakeintake/client",
        "@io_k8s_client_go//kubernetes",
        "@io_k8s_client_go//tools/clientcmd",
    ],
)
