load("@rules_go//go:def.bzl", "go_library")

package(default_package_metadata = ["//pkg/serializer:go_package_metadata"])

go_library(
    name = "mocks",
    srcs = ["metric_serializer.go"],
    importpath = "github.com/DataDog/datadog-agent/pkg/serializer/mocks",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/metrics",
        "//pkg/metrics/event",
        "//pkg/metrics/servicecheck",
        "//pkg/serializer/marshaler",
        "//pkg/serializer/types",
        "@com_github_stretchr_testify//mock",
    ],
)
