load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

package(default_package_metadata = ["//pkg/config/remote:go_package_metadata"])

go_library(
    name = "data",
    srcs = [
        "file.go",
        "product.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/pkg/config/remote/data",
    visibility = ["//visibility:public"],
)

dd_agent_go_test(
    name = "data_test",
    srcs = ["file_test.go"],
    embed = [":data"],
    deps = ["@com_github_stretchr_testify//assert"],
)
