load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

# gazelle:dd_agent_go_test on

go_library(
    name = "dogstatsdcommon",
    srcs = ["check.go"],
    importpath = "github.com/DataDog/datadog-agent/cmd/agent/subcommands/dogstatsdcommon",
    visibility = ["//visibility:public"],
    deps = [
        "//comp/core/config",
        "//comp/dogstatsd/config",
    ],
)

dd_agent_go_test(
    name = "dogstatsdcommon_test",
    srcs = ["check_test.go"],
    embed = [":dogstatsdcommon"],
    deps = [
        "//comp/core/config",
        "//pkg/config/mock",
        "@com_github_stretchr_testify//assert",
    ],
)
