load("@rules_go//go:def.bzl", "go_library")

package(default_package_metadata = ["//test/e2e-framework:go_package_metadata"])

go_library(
    name = "command",
    srcs = [
        "agent.go",
        "doc.go",
        "product.go",
        "registry.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/test/e2e-framework/components/windows/command",
    visibility = ["//visibility:public"],
)
