load("@rules_go//go:def.bzl", "go_library")

package(default_package_metadata = ["//comp/core/configsync:go_package_metadata"])

go_library(
    name = "def",
    srcs = [
        "component.go",
        "params.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/comp/core/configsync/def",
    visibility = ["//visibility:public"],
)
