load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

go_library(
    name = "impl",
    srcs = [
        "connectivity.go",
        "connectivity_endpoint.go",
        "newcomponent.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/comp/networkdevices/impl",
    visibility = ["//visibility:public"],
    deps = [
        "//comp/api/api/def",
        "//comp/core/log/def",
        "//comp/def",
        "//comp/networkdevices/def",
        "//pkg/networkdevice/pinger",
        "//pkg/networkdevices/connectivity",
        "//pkg/snmp/gosnmplib",
        "//pkg/util/http",
        "@com_github_gosnmp_gosnmp//:gosnmp",
        "@org_golang_x_sync//errgroup",
    ],
)

dd_agent_go_test(
    name = "impl_test",
    srcs = [
        "connectivity_endpoint_test.go",
        "connectivity_test.go",
    ],
    embed = [":impl"],
    deps = [
        "//comp/core/log/mock",
        "//pkg/networkdevices/connectivity",
        "@com_github_stretchr_testify//require",
    ],
)
