load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "process",
    srcs = [
        "config.go",
        "info.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/pkg/dyninst/process",
    tags = ["manual"],
    visibility = ["//visibility:public"],
    deps = select({
        "@rules_go//go/platform:android": [
            "//pkg/dyninst/ir",
        ],
        "@rules_go//go/platform:linux": [
            "//pkg/dyninst/ir",
        ],
        "//conditions:default": [],
    }),
)
