load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules:windows_resources.bzl", "win_messagetable", "win_resource")

win_resource(
    name = "rsrc",
    src = "trace-agent.rc",
    visibility = ["//cmd/trace-agent:__subpackages__"],
    deps = [
        "version.h",
        "//tools/windows/DatadogAgentInstaller/WixSetup/assets:project.ico",
    ],
)

win_messagetable(
    name = "messagetable",
    src = "trace-agent-msg.mc",
    target_compatible_with = ["@platforms//os:windows"],  # keep
    visibility = ["//visibility:public"],
)
