load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")
load("//bazel/rules/go_package_metadata:defs.bzl", "go_package_metadata")

package(default_package_metadata = [":go_package_metadata"])

go_package_metadata(
    name = "go_package_metadata",
    module = "github.com/DataDog/datadog-agent/pkg/util/cache",
)

go_library(
    name = "cache",
    srcs = [
        "basic_cache.go",
        "cache.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/pkg/util/cache",
    visibility = ["//visibility:public"],
    deps = ["@com_github_patrickmn_go_cache//:go-cache"],
)

dd_agent_go_test(
    name = "cache_test",
    srcs = ["basic_cache_test.go"],
    embed = [":cache"],
    deps = ["@com_github_stretchr_testify//assert"],
)
