load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

dd_agent_go_test(
    name = "preflight-mode_test",
    srcs = [
        "preflightmode_common_test.go",
        "preflightmode_nix_test.go",
    ],
    deps = [
        "//test/e2e-framework/components/datadog/agentparams",
        "//test/e2e-framework/components/os",
        "//test/e2e-framework/scenarios/aws/ec2",
        "//test/e2e-framework/testing/components",
        "//test/e2e-framework/testing/e2e",
        "//test/e2e-framework/testing/environments",
        "//test/e2e-framework/testing/provisioners/aws/host",
        "//test/fakeintake/aggregator",
        "//test/fakeintake/client",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
