#!/bin/sh
#
# Perform necessary datadog-updater setup steps after package is installed.
#
# .deb: STEP 5 of 5

INSTALL_DIR=/opt/datadog-installer

set -e
case "$1" in
    configure)
        # Create a symlink to the bootstrap binary
        ln -sf $INSTALL_DIR/bin/installer/installer /usr/bin/datadog-bootstrap
    ;;
    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
    ;;
esac

exit 0
