load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

go_library(
    name = "impl",
    srcs = [
        "fx.go",
        "handler.go",
        "iterator.go",
        "origin.go",
        "semaphore.go",
        "server.go",
        "sketch_iterator.go",
        "telemetry.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/comp/dogstatsd/http/impl",
    visibility = ["//visibility:public"],
    deps = [
        "//comp/aggregator/demultiplexer/def",
        "//comp/core/config",
        "//comp/core/hostname/hostnameinterface/def",
        "//comp/core/log/def",
        "//comp/core/tagger/def",
        "//comp/core/tagger/origindetection",
        "//comp/core/tagger/types",
        "//comp/core/telemetry/def",
        "//comp/def",
        "//comp/dogstatsd/http/def",
        "//comp/dogstatsd/http/impl/internal/reader",
        "//comp/filterlist/def",
        "//pkg/metrics",
        "//pkg/proto/pbgo/dogstatsdhttp",
        "//pkg/tagger/types",
        "//pkg/tagset",
        "//pkg/util/metricname",
    ],
)

dd_agent_go_test(
    name = "impl_test",
    srcs = [
        "handler_test.go",
        "iterator_test.go",
        "semaphore_test.go",
        "server_test.go",
        "sketch_iterator_test.go",
    ],
    embed = [":impl"],
    deps = [
        "//comp/core/config",
        "//comp/core/hostname/hostnameinterface/mock",
        "//comp/core/log/mock",
        "//comp/core/tagger/fx-mock",
        "//comp/core/tagger/impl",
        "//comp/core/tagger/mock",
        "//comp/core/tagger/types",
        "//comp/core/telemetry/def",
        "//comp/core/telemetry/mock",
        "//comp/core/workloadmeta/def",
        "//comp/core/workloadmeta/impl",
        "//comp/def",
        "//comp/filterlist/impl",
        "//pkg/metrics",
        "//pkg/proto/pbgo/dogstatsdhttp",
        "//pkg/tagset",
        "//pkg/util/metricname",
        "@com_github_stretchr_testify//require",
    ],
)
