load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

go_library(
    name = "impl",
    srcs = [
        "chunks.go",
        "credentials.go",
        "cursor.go",
        "pingcapability.go",
        "rcconfig.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/comp/ndmdiscovery/impl",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/config/model",
        "//pkg/config/structure",
        "//pkg/networkdevices/connectivity",
        "//pkg/persistentcache",
    ],
)

dd_agent_go_test(
    name = "impl_test",
    srcs = [
        "chunks_test.go",
        "credentials_test.go",
        "cursor_test.go",
        "pingcapability_test.go",
        "rcconfig_test.go",
    ],
    embed = [":impl"],
    deps = [
        "//pkg/config/mock",
        "//pkg/networkdevices/connectivity",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
