[package]
name = "par-control"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "Private Action Runner control-plane"

[lib]
name = "par_control"
path = "src/lib.rs"
doctest = false

[[bin]]
name = "par-control"
path = "src/bins/par-control.rs"

[dependencies]
anyhow.workspace = true
clap = { workspace = true, features = ["derive"] }
datadog-agent-commons.workspace = true
dd-agent-log.workspace = true
dd-procmgr-client.workspace = true
hyper-util.workspace = true
log.workspace = true
prost.workspace = true
rustls-pki-types.workspace = true
saluki-tls.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_yaml.workspace = true
tokio = { workspace = true, features = [
  "macros",
  "net",
  "rt-multi-thread",
  "signal",
] }
tokio-rustls.workspace = true
tokio-stream = { workspace = true, features = ["net"] }
tonic = { workspace = true, features = ["transport"] }
tonic-prost.workspace = true
tower.workspace = true

[target.'cfg(not(windows))'.dependencies]
rustls.workspace = true

[target.'cfg(windows)'.dependencies]
rustls.workspace = true
windows-registry.workspace = true
windows-sys = { workspace = true, features = ["Win32_System_Registry"] }

[dev-dependencies]
tempfile.workspace = true

[build-dependencies]
tonic-prost-build.workspace = true
