load("@rules_go//go:def.bzl", "go_binary", "go_library")
load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")
load(":symbol_uploader_test.bzl", "objcopy_go_fixture")

# gazelle:go_test file

go_library(
    name = "symboluploader",
    srcs = [
        "config.go",
        "symbol_endpoint.go",
        "symbol_querier.go",
        "symbol_query_batching.go",
        "symbol_uploader.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/comp/host-profiler/symboluploader",
    visibility = ["//visibility:public"],
    deps = select({
        "@rules_go//go/platform:android": [
            "//comp/host-profiler/symboluploader/cgroup",
            "//comp/host-profiler/symboluploader/pclntab",
            "//comp/host-profiler/symboluploader/pipeline",
            "//comp/host-profiler/symboluploader/symbol",
            "//comp/host-profiler/symboluploader/symbolcopier",
            "//comp/host-profiler/version",
            "@com_github_datadog_jsonapi//:jsonapi",
            "@com_github_datadog_zstd//:zstd",
            "@com_github_elastic_go_freelru//:go-freelru",
            "@io_opentelemetry_go_ebpf_profiler//libpf",
            "@io_opentelemetry_go_ebpf_profiler//reporter",
            "@org_golang_x_sync//errgroup",
        ],
        "@rules_go//go/platform:linux": [
            "//comp/host-profiler/symboluploader/cgroup",
            "//comp/host-profiler/symboluploader/pclntab",
            "//comp/host-profiler/symboluploader/pipeline",
            "//comp/host-profiler/symboluploader/symbol",
            "//comp/host-profiler/symboluploader/symbolcopier",
            "//comp/host-profiler/version",
            "@com_github_datadog_jsonapi//:jsonapi",
            "@com_github_datadog_zstd//:zstd",
            "@com_github_elastic_go_freelru//:go-freelru",
            "@io_opentelemetry_go_ebpf_profiler//libpf",
            "@io_opentelemetry_go_ebpf_profiler//reporter",
            "@org_golang_x_sync//errgroup",
        ],
        "//conditions:default": [],
    }),
)

dd_agent_go_test(
    name = "symbol_query_batching_test",
    srcs = ["symbol_query_batching_test.go"],
    data = glob(["testdata/**"]),
    embed = [":symboluploader"],
    deps = select({
        "@rules_go//go/platform:android": [
            "//comp/host-profiler/symboluploader/symbol",
            "@com_github_stretchr_testify//require",
            "@io_opentelemetry_go_ebpf_profiler//libpf",
        ],
        "@rules_go//go/platform:linux": [
            "//comp/host-profiler/symboluploader/symbol",
            "@com_github_stretchr_testify//require",
            "@io_opentelemetry_go_ebpf_profiler//libpf",
        ],
        "//conditions:default": [],
    }),
)

go_binary(
    name = "helloworld_no_symbols_raw",
    srcs = ["testdata/helloworld.go"],
    linkmode = "normal",
    pure = "on",
    race = "off",
    target_compatible_with = ["@platforms//os:linux"],
)

objcopy_go_fixture(
    name = "helloworld_no_symbols",
    src = ":helloworld_no_symbols_raw",
    out = "helloworld_no_symbols.out",
    objcopy_args = [
        "-R",
        ".note.gnu.build-id",
        "-S",
    ],
    target_compatible_with = ["@platforms//os:linux"],
)

go_binary(
    name = "helloworld_dynsym_raw",
    srcs = ["testdata/helloworld.go"],
    gc_linkopts = ["-linkmode=external"],
    linkmode = "normal",
    pure = "off",
    race = "off",
    target_compatible_with = ["@platforms//os:linux"],
)

objcopy_go_fixture(
    name = "helloworld_dynsym",
    src = ":helloworld_dynsym_raw",
    out = "helloworld_dynsym.out",
    objcopy_args = [
        "-R",
        ".note.gnu.build-id",
        "-S",
    ],
    target_compatible_with = ["@platforms//os:linux"],
)

go_binary(
    name = "helloworld_symtab_raw",
    srcs = ["testdata/helloworld.go"],
    gc_linkopts = ["-linkmode=external"],
    linkmode = "normal",
    pure = "off",
    race = "off",
    target_compatible_with = ["@platforms//os:linux"],
)

objcopy_go_fixture(
    name = "helloworld_symtab",
    src = ":helloworld_symtab_raw",
    out = "helloworld_symtab.out",
    objcopy_args = [
        "-R",
        ".note.gnu.build-id",
        "-g",
    ],
    target_compatible_with = ["@platforms//os:linux"],
)

go_binary(
    name = "helloworld_debug_infos_raw",
    srcs = ["testdata/helloworld.go"],
    gc_linkopts = ["-linkmode=external"],
    linkmode = "normal",
    pure = "off",
    race = "off",
    target_compatible_with = ["@platforms//os:linux"],
)

objcopy_go_fixture(
    name = "helloworld_debug_infos",
    src = ":helloworld_debug_infos_raw",
    out = "helloworld_debug_infos.out",
    objcopy_args = [
        "-R",
        ".note.gnu.build-id",
    ],
    target_compatible_with = ["@platforms//os:linux"],
)

go_binary(
    name = "helloworld_dynsym_corrupt_gopclntab_raw",
    srcs = ["testdata/helloworld.go"],
    gc_linkopts = ["-linkmode=external"],
    linkmode = "normal",
    pure = "off",
    race = "off",
    target_compatible_with = ["@platforms//os:linux"],
)

objcopy_go_fixture(
    name = "helloworld_dynsym_corrupt_gopclntab",
    src = ":helloworld_dynsym_corrupt_gopclntab_raw",
    out = "helloworld_dynsym_corrupt_gopclntab.out",
    objcopy_args = [
        "-R",
        ".note.gnu.build-id",
        "-S",
        "-R",
        ".gopclntab",
    ],
    target_compatible_with = ["@platforms//os:linux"],
)

go_binary(
    name = "helloworld_debug_infos_corrupt_gopclntab_raw",
    srcs = ["testdata/helloworld.go"],
    gc_linkopts = ["-linkmode=external"],
    linkmode = "normal",
    pure = "off",
    race = "off",
    target_compatible_with = ["@platforms//os:linux"],
)

objcopy_go_fixture(
    name = "helloworld_debug_infos_corrupt_gopclntab",
    src = ":helloworld_debug_infos_corrupt_gopclntab_raw",
    out = "helloworld_debug_infos_corrupt_gopclntab.out",
    objcopy_args = [
        "-R",
        ".note.gnu.build-id",
        "-R",
        ".gopclntab",
    ],
    target_compatible_with = ["@platforms//os:linux"],
)

# Note: these tests are still not hermetic because they rely on system objcopy for the code
# under test itself.
dd_agent_go_test(
    name = "symbol_uploader_test",
    srcs = ["symbol_uploader_test.go"],
    data = glob(["testdata/**"]) + select({
        "@platforms//os:linux": [
            ":helloworld_debug_infos",
            ":helloworld_debug_infos_corrupt_gopclntab",
            ":helloworld_dynsym",
            ":helloworld_dynsym_corrupt_gopclntab",
            ":helloworld_no_symbols",
            ":helloworld_symtab",
        ],
        "//conditions:default": [],
    }),
    embed = [":symboluploader"],
    env = select({
        "@platforms//os:linux": {
            "SYMBOL_UPLOADER_FIXTURE_DEBUG_INFOS": "$(rlocationpath :helloworld_debug_infos)",
            "SYMBOL_UPLOADER_FIXTURE_DEBUG_INFOS_CORRUPT_GOPCLNTAB": "$(rlocationpath :helloworld_debug_infos_corrupt_gopclntab)",
            "SYMBOL_UPLOADER_FIXTURE_DYNSYM": "$(rlocationpath :helloworld_dynsym)",
            "SYMBOL_UPLOADER_FIXTURE_DYNSYM_CORRUPT_GOPCLNTAB": "$(rlocationpath :helloworld_dynsym_corrupt_gopclntab)",
            "SYMBOL_UPLOADER_FIXTURE_NO_SYMBOLS": "$(rlocationpath :helloworld_no_symbols)",
            "SYMBOL_UPLOADER_FIXTURE_SYMTAB": "$(rlocationpath :helloworld_symtab)",
        },
        "//conditions:default": {},
    }),
    deps = select({
        "@rules_go//go/platform:android": [
            "//comp/host-profiler/symboluploader/symbol",
            "//pkg/util/safeelf",
            "@com_github_datadog_jsonapi//:jsonapi",
            "@com_github_datadog_zstd//:zstd",
            "@com_github_jarcoal_httpmock//:httpmock",
            "@com_github_stretchr_testify//assert",
            "@com_github_stretchr_testify//require",
            "@io_opentelemetry_go_ebpf_profiler//libpf",
            "@io_opentelemetry_go_ebpf_profiler//libpf/pfelf",
            "@io_opentelemetry_go_ebpf_profiler//process",
            "@io_opentelemetry_go_ebpf_profiler//remotememory",
            "@io_opentelemetry_go_ebpf_profiler//reporter",
            "@rules_go//go/runfiles",
        ],
        "@rules_go//go/platform:linux": [
            "//comp/host-profiler/symboluploader/symbol",
            "//pkg/util/safeelf",
            "@com_github_datadog_jsonapi//:jsonapi",
            "@com_github_datadog_zstd//:zstd",
            "@com_github_jarcoal_httpmock//:httpmock",
            "@com_github_stretchr_testify//assert",
            "@com_github_stretchr_testify//require",
            "@io_opentelemetry_go_ebpf_profiler//libpf",
            "@io_opentelemetry_go_ebpf_profiler//libpf/pfelf",
            "@io_opentelemetry_go_ebpf_profiler//process",
            "@io_opentelemetry_go_ebpf_profiler//remotememory",
            "@io_opentelemetry_go_ebpf_profiler//reporter",
            "@rules_go//go/runfiles",
        ],
        "//conditions:default": [],
    }),
)
