load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

go_library(
    name = "provisioners",
    srcs = [
        "file_provisioner.go",
        "provisioners.go",
        "pulumi_provisioner.go",
        "static_stack_provisioner.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/test/e2e-framework/testing/provisioners",
    visibility = ["//visibility:public"],
    deps = [
        "//test/e2e-framework/components",
        "//test/e2e-framework/testing/runner",
        "//test/e2e-framework/testing/utils/infra",
        "@com_github_pulumi_pulumi_sdk_v3//go/pulumi",
    ],
)

dd_agent_go_test(
    name = "provisioners_test",
    srcs = ["pulumi_provisioner_test.go"],
    embed = [":provisioners"],
    deps = ["@com_github_stretchr_testify//assert"],
)
