load("@rules_go//go:def.bzl", "go_library")

package(default_package_metadata = ["//pkg/api:go_package_metadata"])

go_library(
    name = "version",
    srcs = ["version.go"],
    importpath = "github.com/DataDog/datadog-agent/pkg/api/version",
    visibility = ["//visibility:public"],
    deps = ["//pkg/version"],
)
