load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")
load("//bazel/rules/go_package_metadata:defs.bzl", "go_package_metadata")

package(default_package_metadata = [":go_package_metadata"])

go_package_metadata(
    name = "go_package_metadata",
    module = "github.com/DataDog/datadog-agent/comp/core/tagger/subscriber",
)

go_library(
    name = "subscriber",
    srcs = [
        "subscriber.go",
        "subscription_manager.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/comp/core/tagger/subscriber",
    visibility = ["//visibility:public"],
    deps = [
        "//comp/core/tagger/telemetry",
        "//comp/core/tagger/types",
        "//pkg/util/log",
    ],
)

dd_agent_go_test(
    name = "subscriber_test",
    srcs = ["subscription_manager_test.go"],
    embed = [":subscriber"],
    deps = [
        "//comp/core/tagger/telemetry",
        "//comp/core/tagger/types",
        "//comp/core/telemetry/def",
        "//comp/core/telemetry/mock",
        "//pkg/util/fxutil",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
