load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

go_library(
    name = "smb",
    srcs = [
        "config_entry.go",
        "launcher.go",
        "launcher_nosmb.go",
        "options.go",
        "scanner.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/pkg/logs/launchers/smb",
    visibility = ["//visibility:public"],
    deps = [
        "//comp/logs-library/pipeline",
        "//comp/logs/agent/config",
        "//comp/logs/auditor/def",
        "//pkg/config/model",
        "//pkg/config/setup",
        "//pkg/fips",
        "//pkg/logs/internal/decoder",
        "//pkg/logs/internal/smb/client",
        "//pkg/logs/launchers",
        "//pkg/logs/sources",
        "//pkg/logs/status/utils",
        "//pkg/logs/tailers",
        "//pkg/logs/tailers/smb",
        "//pkg/util/log",
        "//pkg/util/startstop",
        "@com_github_benbjohnson_clock//:clock",
    ],
)

dd_agent_go_test(
    name = "smb_test",
    srcs = [
        "launcher_nosmb_test.go",
        "launcher_test.go",
        "listing_test.go",
        "logon_test.go",
        "openfiles_test.go",
        "restart_test.go",
        "samba_env_test.go",
        "samba_integration_test.go",
        "scanner_test.go",
    ],
    data = glob(["testdata/**"]),
    embed = [":smb"],
    gotags_sets = [["smb"]],
    deps = [
        "//comp/core/hostname/hostnameinterface/mock",
        "//comp/logs-library/diagnostic",
        "//comp/logs-library/metrics",
        "//comp/logs-library/pipeline",
        "//comp/logs-library/pipeline/mock",
        "//comp/logs-library/processor",
        "//comp/logs/agent/config",
        "//comp/logs/auditor/mock",
        "//pkg/config/mock",
        "//pkg/fips",
        "//pkg/logs/internal/smb/client",
        "//pkg/logs/internal/smb/client/fake",
        "//pkg/logs/internal/smb/thirdparty/gosmb2",
        "//pkg/logs/internal/smb/thirdparty/gosmb2/auth",
        "//pkg/logs/message",
        "//pkg/logs/sources",
        "//pkg/logs/tailers",
        "//pkg/logs/tailers/smb",
        "//pkg/util/log",
        "@com_github_benbjohnson_clock//:clock",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
