load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "outputs",
    srcs = [
        "dockerhost.go",
        "ecs.go",
        "host.go",
        "kubernetes.go",
        "outputs.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/test/e2e-framework/scenarios/outputs",
    visibility = ["//visibility:public"],
    deps = [
        "//test/e2e-framework/components/outputs",
        "//test/e2e-framework/testing/utils/e2e/client/agentclientparams",
    ],
)
