load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "def",
    srcs = [
        "component.go",
        "format.go",
        "types.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/comp/anomalydetection/observer/def",
    visibility = ["//visibility:public"],
    deps = [
        "//comp/anomalydetection/severityevents/def",
        "//pkg/tagset",
    ],
)

go_test(
    name = "def_test",
    srcs = ["format_test.go"],
    embed = [":def"],
)
