load("@rules_go//go:def.bzl", "go_library")

package(default_package_metadata = ["//comp/forwarder/defaultforwarder:go_package_metadata"])

go_library(
    name = "noop-impl",
    srcs = ["noop.go"],
    importpath = "github.com/DataDog/datadog-agent/comp/forwarder/defaultforwarder/noop-impl",
    visibility = ["//visibility:public"],
    deps = [
        "//comp/forwarder/defaultforwarder/def",
        "//comp/forwarder/defaultforwarder/resolver",
        "//comp/forwarder/defaultforwarder/transaction",
        "//pkg/util/fxutil",
    ],
)
