load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "e2ectl-worker_lib",
    srcs = ["main.go"],
    importpath = "github.com/DataDog/datadog-agent/test/e2e-framework/cmd/e2ectl-worker",
    visibility = ["//visibility:private"],
    deps = [
        "//test/e2e-framework/components/os",
        "//test/e2e-framework/scenarios/aws/ec2",
        "//test/e2e-framework/testing/environments",
        "//test/e2e-framework/testing/installers/host/installscript",
        "//test/e2e-framework/testing/installers/kubernetes/helm",
        "//test/e2e-framework/testing/provisioner",
        "//test/e2e-framework/testing/provisioners",
        "//test/e2e-framework/testing/provisioners/aws/host",
        "//test/e2e-framework/testing/standalone",
    ],
)

go_binary(
    name = "e2ectl-worker",
    embed = [":e2ectl-worker_lib"],
    visibility = ["//visibility:public"],
)
