load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

go_library(
    name = "report",
    srcs = [
        "bandwidth_state.go",
        "derived_metrics.go",
        "health.go",
        "metadata.go",
        "metrics.go",
        "snapshot.go",
        "topology.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/pkg/collector/corechecks/network-devices/gnmi/report",
    visibility = ["//visibility:public"],
    deps = [
        "//comp/forwarder/eventplatform/def",
        "//pkg/aggregator/sender",
        "//pkg/collector/corechecks/network-devices/gnmi/client",
        "//pkg/collector/corechecks/network-devices/gnmi/config",
        "//pkg/networkdevice/integrations",
        "//pkg/networkdevice/lldp",
        "//pkg/networkdevice/metadata",
        "//pkg/networkdevice/utils",
        "//pkg/util/log",
        "//pkg/util/sort",
    ],
)

dd_agent_go_test(
    name = "report_test",
    srcs = [
        "derived_metrics_test.go",
        "health_test.go",
        "metadata_test.go",
        "metrics_test.go",
        "snapshot_test.go",
        "topology_test.go",
    ],
    embed = [":report"],
    deps = [
        "//pkg/aggregator/mocksender",
        "//pkg/collector/check/id",
        "//pkg/collector/corechecks/network-devices/gnmi/client",
        "//pkg/collector/corechecks/network-devices/gnmi/config",
        "//pkg/networkdevice/metadata",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//mock",
        "@com_github_stretchr_testify//require",
    ],
)
