load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

go_library(
    name = "uprobes",
    srcs = [
        "attacher.go",
        "doc.go",
        "inspector.go",
        "procfs.go",
        "telemetry.go",
        "testutil.go",
        "testutil_attacher_runner.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/pkg/ebpf/uprobes",
    visibility = ["//visibility:public"],
    deps = select({
        "@rules_go//go/platform:android": [
            "//comp/core/telemetry/def",
            "//comp/core/telemetry/impl/noops",
            "//pkg/ebpf",
            "//pkg/ebpf/bytecode",
            "//pkg/ebpf/uprobes/testutil",
            "//pkg/eventmonitor/consumers/testutil",
            "//pkg/network/go/bininspect",
            "//pkg/network/protocols/http/testutil",
            "//pkg/network/usm/sharedlibraries",
            "//pkg/network/usm/sharedlibraries/testutil",
            "//pkg/network/usm/utils",
            "//pkg/process/monitor",
            "//pkg/security/utils",
            "//pkg/util/common",
            "//pkg/util/kernel",
            "//pkg/util/log",
            "//pkg/util/safeelf",
            "//pkg/util/testutil",
            "//pkg/util/testutil/docker",
            "@com_github_datadog_ebpf_manager//:ebpf-manager",
            "@com_github_stretchr_testify//assert",
            "@com_github_stretchr_testify//mock",
            "@com_github_stretchr_testify//require",
        ],
        "@rules_go//go/platform:linux": [
            "//comp/core/telemetry/def",
            "//comp/core/telemetry/impl/noops",
            "//pkg/ebpf",
            "//pkg/ebpf/bytecode",
            "//pkg/ebpf/uprobes/testutil",
            "//pkg/eventmonitor/consumers/testutil",
            "//pkg/network/go/bininspect",
            "//pkg/network/protocols/http/testutil",
            "//pkg/network/usm/sharedlibraries",
            "//pkg/network/usm/sharedlibraries/testutil",
            "//pkg/network/usm/utils",
            "//pkg/process/monitor",
            "//pkg/security/utils",
            "//pkg/util/common",
            "//pkg/util/kernel",
            "//pkg/util/log",
            "//pkg/util/safeelf",
            "//pkg/util/testutil",
            "//pkg/util/testutil/docker",
            "@com_github_datadog_ebpf_manager//:ebpf-manager",
            "@com_github_stretchr_testify//assert",
            "@com_github_stretchr_testify//mock",
            "@com_github_stretchr_testify//require",
        ],
        "//conditions:default": [],
    }),
)

dd_agent_go_test(
    name = "uprobes_test",
    srcs = [
        "attacher_test.go",
        "inspector_test.go",
    ],
    embed = [":uprobes"],
    gotags_sets = [["bpf"]],
    include_default = False,
    tags = ["requires_ebpf"],
    deps = [
        "//pkg/ebpf",
        "//pkg/ebpf/ebpftest",
        "//pkg/network/go/bininspect",
        "//pkg/network/protocols/http/testutil",
        "//pkg/network/usm/sharedlibraries",
        "//pkg/network/usm/sharedlibraries/testutil",
        "//pkg/network/usm/utils",
        "//pkg/util/kernel",
        "//pkg/util/safeelf",
        "@com_github_datadog_ebpf_manager//:ebpf-manager",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//mock",
        "@com_github_stretchr_testify//require",
        "@com_github_stretchr_testify//suite",
    ],
)

dd_agent_go_test(
    name = "attacher_test",
    srcs = ["attacher_test.go"],
    embed = [":uprobes"],
    gotags_sets = [["bpf"]],
    include_default = False,
    tags = ["requires_ebpf"],
    deps = select({
        "@rules_go//go/platform:android": [
            "//pkg/ebpf",
            "//pkg/ebpf/ebpftest",
            "//pkg/network/go/bininspect",
            "//pkg/network/usm/sharedlibraries",
            "//pkg/network/usm/sharedlibraries/testutil",
            "//pkg/network/usm/utils",
            "//pkg/util/kernel",
            "//pkg/util/safeelf",
            "@com_github_datadog_ebpf_manager//:ebpf-manager",
            "@com_github_stretchr_testify//assert",
            "@com_github_stretchr_testify//mock",
            "@com_github_stretchr_testify//require",
            "@com_github_stretchr_testify//suite",
        ],
        "@rules_go//go/platform:linux": [
            "//pkg/ebpf",
            "//pkg/ebpf/ebpftest",
            "//pkg/network/go/bininspect",
            "//pkg/network/usm/sharedlibraries",
            "//pkg/network/usm/sharedlibraries/testutil",
            "//pkg/network/usm/utils",
            "//pkg/util/kernel",
            "//pkg/util/safeelf",
            "@com_github_datadog_ebpf_manager//:ebpf-manager",
            "@com_github_stretchr_testify//assert",
            "@com_github_stretchr_testify//mock",
            "@com_github_stretchr_testify//require",
            "@com_github_stretchr_testify//suite",
        ],
        "//conditions:default": [],
    }),
)

dd_agent_go_test(
    name = "inspector_test",
    srcs = ["inspector_test.go"],
    embed = [":uprobes"],
    gotags_sets = [["bpf"]],
    include_default = False,
    tags = ["requires_ebpf"],
    deps = select({
        "@rules_go//go/platform:android": [
            "//pkg/network/protocols/http/testutil",
            "//pkg/network/usm/utils",
            "@com_github_stretchr_testify//require",
        ],
        "@rules_go//go/platform:linux": [
            "//pkg/network/protocols/http/testutil",
            "//pkg/network/usm/utils",
            "@com_github_stretchr_testify//require",
        ],
        "//conditions:default": [],
    }),
)
