load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

go_library(
    name = "process",
    srcs = [
        "go_labels.go",
        "go_labels_tls_amd64.go",
        "go_labels_tls_arm64.go",
        "go_labels_tls_unsupported.go",
        "opts_linux.go",
        "opts_windows.go",
        "otel_tls.go",
        "otel_tls_upstream_access.go",
        "otel_tls_upstream_pfelf.go",
        "resolver_ebpf.go",
        "resolver_ebpf_test_helpers.go",
        "resolver_ebpfless.go",
        "resolver_linux.go",
        "resolver_windows.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/pkg/security/resolvers/process",
    visibility = ["//visibility:public"],
    deps = select({
        "@rules_go//go/platform:android": [
            "//pkg/discovery/tracermetadata",
            "//pkg/discovery/tracermetadata/model",
            "//pkg/security/ebpf",
            "//pkg/security/metrics",
            "//pkg/security/otelprocessctx",
            "//pkg/security/probe/config",
            "//pkg/security/probe/managerhelper",
            "//pkg/security/probe/procfs",
            "//pkg/security/resolvers/cgroup",
            "//pkg/security/resolvers/envvars",
            "//pkg/security/resolvers/mount",
            "//pkg/security/resolvers/path",
            "//pkg/security/resolvers/usergroup",
            "//pkg/security/resolvers/usersessions",
            "//pkg/security/secl/containerutils",
            "//pkg/security/secl/model",
            "//pkg/security/secl/model/sharedconsts",
            "//pkg/security/seclog",
            "//pkg/security/utils",
            "//pkg/util/kernel",
            "//pkg/util/ktime",
            "//pkg/util/safeelf",
            "@com_github_cilium_ebpf//:ebpf",
            "@com_github_datadog_datadog_go_v5//statsd",
            "@com_github_datadog_ebpf_manager//:ebpf-manager",
            "@com_github_hashicorp_golang_lru_v2//simplelru",
            "@com_github_shirou_gopsutil_v4//process",
            "@io_opentelemetry_go_ebpf_profiler//libc",
            "@io_opentelemetry_go_ebpf_profiler//libpf/pfbufio",
            "@io_opentelemetry_go_ebpf_profiler//libpf/pfunsafe",
            "@org_uber_go_atomic//:atomic",
        ],
        "@rules_go//go/platform:linux": [
            "//pkg/discovery/tracermetadata",
            "//pkg/discovery/tracermetadata/model",
            "//pkg/security/ebpf",
            "//pkg/security/metrics",
            "//pkg/security/otelprocessctx",
            "//pkg/security/probe/config",
            "//pkg/security/probe/managerhelper",
            "//pkg/security/probe/procfs",
            "//pkg/security/resolvers/cgroup",
            "//pkg/security/resolvers/envvars",
            "//pkg/security/resolvers/mount",
            "//pkg/security/resolvers/path",
            "//pkg/security/resolvers/usergroup",
            "//pkg/security/resolvers/usersessions",
            "//pkg/security/secl/containerutils",
            "//pkg/security/secl/model",
            "//pkg/security/secl/model/sharedconsts",
            "//pkg/security/seclog",
            "//pkg/security/utils",
            "//pkg/util/kernel",
            "//pkg/util/ktime",
            "//pkg/util/safeelf",
            "@com_github_cilium_ebpf//:ebpf",
            "@com_github_datadog_datadog_go_v5//statsd",
            "@com_github_datadog_ebpf_manager//:ebpf-manager",
            "@com_github_hashicorp_golang_lru_v2//simplelru",
            "@com_github_shirou_gopsutil_v4//process",
            "@io_opentelemetry_go_ebpf_profiler//libc",
            "@io_opentelemetry_go_ebpf_profiler//libpf/pfbufio",
            "@io_opentelemetry_go_ebpf_profiler//libpf/pfunsafe",
            "@org_uber_go_atomic//:atomic",
        ],
        "@rules_go//go/platform:windows": [
            "//pkg/process/procutil",
            "//pkg/security/config",
            "//pkg/security/metrics",
            "//pkg/security/secl/model",
            "//pkg/security/utils",
            "//pkg/security/utils/pathutils",
            "//pkg/util/log",
            "@com_github_datadog_datadog_go_v5//statsd",
        ],
        "//conditions:default": [],
    }) + select({
        "@rules_go//go/platform:android_386": [
            "@io_opentelemetry_go_ebpf_profiler//libpf",
            "@io_opentelemetry_go_ebpf_profiler//libpf/pfelf",
        ],
        "@rules_go//go/platform:android_amd64": [
            "@io_opentelemetry_go_ebpf_profiler//asm/amd",
            "@io_opentelemetry_go_ebpf_profiler//libpf",
            "@io_opentelemetry_go_ebpf_profiler//libpf/pfelf",
            "@io_opentelemetry_go_ebpf_profiler//nativeunwind/elfunwindinfo",
        ],
        "@rules_go//go/platform:android_arm": [
            "@io_opentelemetry_go_ebpf_profiler//libpf",
            "@io_opentelemetry_go_ebpf_profiler//libpf/pfelf",
        ],
        "@rules_go//go/platform:android_arm64": [
            "@io_opentelemetry_go_ebpf_profiler//asm/arm",
            "@io_opentelemetry_go_ebpf_profiler//libpf",
            "@io_opentelemetry_go_ebpf_profiler//libpf/pfelf",
            "@io_opentelemetry_go_ebpf_profiler//nativeunwind/elfunwindinfo",
            "@org_golang_x_arch//arm64/arm64asm",
        ],
        "@rules_go//go/platform:linux_386": [
            "@io_opentelemetry_go_ebpf_profiler//libpf",
            "@io_opentelemetry_go_ebpf_profiler//libpf/pfelf",
        ],
        "@rules_go//go/platform:linux_amd64": [
            "@io_opentelemetry_go_ebpf_profiler//asm/amd",
            "@io_opentelemetry_go_ebpf_profiler//libpf",
            "@io_opentelemetry_go_ebpf_profiler//libpf/pfelf",
            "@io_opentelemetry_go_ebpf_profiler//nativeunwind/elfunwindinfo",
        ],
        "@rules_go//go/platform:linux_arm": [
            "@io_opentelemetry_go_ebpf_profiler//libpf",
            "@io_opentelemetry_go_ebpf_profiler//libpf/pfelf",
        ],
        "@rules_go//go/platform:linux_arm64": [
            "@io_opentelemetry_go_ebpf_profiler//asm/arm",
            "@io_opentelemetry_go_ebpf_profiler//libpf",
            "@io_opentelemetry_go_ebpf_profiler//libpf/pfelf",
            "@io_opentelemetry_go_ebpf_profiler//nativeunwind/elfunwindinfo",
            "@org_golang_x_arch//arm64/arm64asm",
        ],
        "@rules_go//go/platform:linux_mips": [
            "@io_opentelemetry_go_ebpf_profiler//libpf",
            "@io_opentelemetry_go_ebpf_profiler//libpf/pfelf",
        ],
        "@rules_go//go/platform:linux_mips64": [
            "@io_opentelemetry_go_ebpf_profiler//libpf",
            "@io_opentelemetry_go_ebpf_profiler//libpf/pfelf",
        ],
        "@rules_go//go/platform:linux_mips64le": [
            "@io_opentelemetry_go_ebpf_profiler//libpf",
            "@io_opentelemetry_go_ebpf_profiler//libpf/pfelf",
        ],
        "@rules_go//go/platform:linux_mipsle": [
            "@io_opentelemetry_go_ebpf_profiler//libpf",
            "@io_opentelemetry_go_ebpf_profiler//libpf/pfelf",
        ],
        "@rules_go//go/platform:linux_ppc64": [
            "@io_opentelemetry_go_ebpf_profiler//libpf",
            "@io_opentelemetry_go_ebpf_profiler//libpf/pfelf",
        ],
        "@rules_go//go/platform:linux_ppc64le": [
            "@io_opentelemetry_go_ebpf_profiler//libpf",
            "@io_opentelemetry_go_ebpf_profiler//libpf/pfelf",
        ],
        "@rules_go//go/platform:linux_riscv64": [
            "@io_opentelemetry_go_ebpf_profiler//libpf",
            "@io_opentelemetry_go_ebpf_profiler//libpf/pfelf",
        ],
        "@rules_go//go/platform:linux_s390x": [
            "@io_opentelemetry_go_ebpf_profiler//libpf",
            "@io_opentelemetry_go_ebpf_profiler//libpf/pfelf",
        ],
        "//conditions:default": [],
    }),
)

dd_agent_go_test(
    name = "process_test",
    srcs = [
        "go_labels_test.go",
        "otel_tls_test.go",
        "resolver_test.go",
    ],
    embed = [":process"],
    deps = select({
        "@rules_go//go/platform:android": [
            "//pkg/security/probe/config",
            "//pkg/security/probe/procfs",
            "//pkg/security/resolvers/cgroup",
            "//pkg/security/resolvers/path",
            "//pkg/security/resolvers/usergroup",
            "//pkg/security/secl/model",
            "//pkg/util/ktime",
            "//pkg/util/safeelf",
            "@com_github_datadog_datadog_go_v5//statsd",
            "@com_github_stretchr_testify//assert",
            "@com_github_stretchr_testify//require",
            "@io_opentelemetry_go_ebpf_profiler//libpf",
            "@io_opentelemetry_go_ebpf_profiler//libpf/pfelf",
        ],
        "@rules_go//go/platform:linux": [
            "//pkg/security/probe/config",
            "//pkg/security/probe/procfs",
            "//pkg/security/resolvers/cgroup",
            "//pkg/security/resolvers/path",
            "//pkg/security/resolvers/usergroup",
            "//pkg/security/secl/model",
            "//pkg/util/ktime",
            "//pkg/util/safeelf",
            "@com_github_datadog_datadog_go_v5//statsd",
            "@com_github_stretchr_testify//assert",
            "@com_github_stretchr_testify//require",
            "@io_opentelemetry_go_ebpf_profiler//libpf",
            "@io_opentelemetry_go_ebpf_profiler//libpf/pfelf",
        ],
        "//conditions:default": [],
    }),
)
