load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "mock",
    srcs = ["mock.go"],
    importpath = "github.com/DataDog/datadog-agent/comp/trace/config/mock",
    visibility = ["//visibility:public"],
    deps = [
        "//comp/core/config",
        "//comp/core/ipc/mock",
        "//comp/core/log/mock",
        "//comp/core/tagger/impl",
        "//comp/core/telemetry/mock",
        "//comp/core/workloadmeta/def",
        "//comp/core/workloadmeta/impl",
        "//comp/def",
        "//comp/trace/config/def",
        "//comp/trace/config/impl",
        "@com_github_stretchr_testify//require",
    ],
)
