load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "workloads",
    srcs = ["workloads.go"],
    importpath = "github.com/DataDog/datadog-agent/test/e2e-framework/cmd/e2ectl/internal/workloads",
    visibility = ["//test/e2e-framework/cmd/e2ectl:__subpackages__"],
    deps = [
        "//test/e2e-framework/cmd/e2ectl/internal/config",
        "//test/e2e-framework/cmd/e2ectl/internal/envstore",
        "//test/e2e-framework/cmd/e2ectl/internal/localinfra",
        "//test/e2e-framework/cmd/internal/envconfig/workloads",
        "//test/e2e-framework/testing/runner",
        "//test/e2e-framework/testing/runner/parameters",
        "//test/e2e-framework/testing/workloads/catalog",
    ],
)
