load("@rules_go//go:def.bzl", "go_library")

package(default_package_metadata = ["//pkg/trace:go_package_metadata"])

go_library(
    name = "teststatsd",
    srcs = ["statsd.go"],
    importpath = "github.com/DataDog/datadog-agent/pkg/trace/teststatsd",
    visibility = ["//visibility:public"],
    deps = ["@com_github_datadog_datadog_go_v5//statsd"],
)
