load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "fx",
    srcs = ["fx.go"],
    importpath = "github.com/DataDog/datadog-agent/comp/networkdevices/gnmistatus/fx",
    visibility = ["//visibility:public"],
    deps = [
        "//comp/networkdevices/gnmistatus/impl",
        "//pkg/util/fxutil",
    ],
)
