load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

go_library(
    name = "helm",
    srcs = ["config.go"],
    importpath = "github.com/DataDog/datadog-agent/test/e2e-framework/cmd/internal/envconfig/helm",
    visibility = ["//test/e2e-framework/cmd:__subpackages__"],
    deps = ["//test/e2e-framework/cmd/internal/configschema"],
)

dd_agent_go_test(
    name = "helm_test",
    srcs = ["config_test.go"],
    embed = [":helm"],
    deps = ["//test/e2e-framework/cmd/internal/configschema"],
)
