#!/usr/bin/env bash
set -euo pipefail

"Running entrypoint.d/agent"
exec /root/go/bin/dlv --listen=:2345 --headless=true --log=true --log-output=debugger,debuglineerr,gdbwire,lldbout,rpc --accept-multiclient --api-version=2 exec  /opt/datadog-agent/bin/agent/agent -- run
#/opt/datadog-agent/bin/agent run
