#!/usr/bin/env bash
set -euo pipefail

if [[ -x /opt/datadog-agent/embedded/bin/agent-check-runner/agent-check-runner ]]; then
exec /opt/datadog-agent/embedded/bin/agent-check-runner/agent-check-runner --config /etc/datadog-agent/datadog.yaml run
fi
