#!/usr/bin/env bash
set -euo pipefail

if [[ -x /opt/datadog-agent/embedded/bin/privateactionrunner ]]; then
exec /opt/datadog-agent/embedded/bin/privateactionrunner run --cfgpath=/etc/datadog-agent/datadog.yaml
fi
