load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "authoredscripts",
    srcs = [
        "catalog.go",
        "command.go",
        "environment.go",
        "execution.go",
        "global_environment.go",
        "manifest.go",
        "package.go",
        "process_linux.go",
        "process_other.go",
        "session.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/pkg/privateactionrunner/bundle-support/authoredscripts",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/privateactionrunner/adapters/tmpl",
        "//pkg/privateactionrunner/adapters/workflowjsonschema",
        "//pkg/privateactionrunner/artifacts",
        "//pkg/privateactionrunner/bundle-support/command",
        "@com_github_cyphar_filepath_securejoin//:filepath-securejoin",
        "@in_yaml_go_yaml_v3//:yaml",
    ],
)
