load("@rules_go//go:def.bzl", "go_library")

package(default_package_metadata = ["//pkg/opentelemetry-mapping-go/otlp/attributes:go_package_metadata"])

go_library(
    name = "source",
    srcs = ["source_provider.go"],
    importpath = "github.com/DataDog/datadog-agent/pkg/opentelemetry-mapping-go/otlp/attributes/source",
    visibility = ["//visibility:public"],
)
