source 'https://supermarket.chef.io'

# Pinning a commit on the 4.0 branch for now
# TODO: use the released 4.0 once it's out
cookbook 'datadog', git: "https://github.com/DataDog/chef-datadog", ref: "608378de1e221229f3eab7531054e3616833d4b9"

# We pin an old version of the apt cookbook because this cookbook triggers an "apt update" by default
# and in newer versions this update is not allowed to fail, while in 3.X it is. For some reason
# apt update fails a lot in our debian instances.
# This can be removed if the datadog cookbook no longer depends on apt, since it's only used there
# (ie: when the datadog cookbook requires chef >= 13.3, which already bundles everything we use from apt).
cookbook 'apt', '< 4.0'

cookbook 'dd-agent-install', path: './site-cookbooks/dd-agent-install'
cookbook 'dd-agent-upgrade', path: './site-cookbooks/dd-agent-upgrade'
cookbook 'dd-agent-install-script', path: './site-cookbooks/dd-agent-install-script'
cookbook 'dd-agent-step-by-step', path: './site-cookbooks/dd-agent-step-by-step'
cookbook 'dd-agent-import-conf', path: './site-cookbooks/dd-agent-import-conf'
cookbook 'dd-agent-5', path: './site-cookbooks/dd-agent-5'
