source 'https://supermarket.chef.io'
# TODO: pin to a release once https://github.com/DataDog/chef-datadog/pull/520 & https://github.com/DataDog/chef-datadog/pull/505 are released
cookbook 'datadog', git: "https://github.com/datadog/chef-datadog.git", branch: "arbll/kitchen"
# cookbook 'datadog', '~> 2.13.0'
cookbook 'apt', '~> 3.0'
cookbook 'yum', '< 5.0'
cookbook 'windows', '~> 3.4.3'
cookbook 'dd-agent-install', path: './site-cookbooks/dd-agent-install'
cookbook 'dd-agent-upgrade', path: './site-cookbooks/dd-agent-upgrade'
cookbook 'dd-agent-install-script', path: './site-cookbooks/dd-agent-install-script'
cookbook 'dd-agent-step-by-step', path: './site-cookbooks/dd-agent-step-by-step'
