load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

go_library(
    name = "healthcheck",
    srcs = [
        "allowlist.go",
        "dispatcher.go",
        "observer.go",
        "par_dispatcher.go",
        "par_dispatcher_unsupported.go",
        "registry.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/pkg/collector/healthcheck",
    visibility = ["//visibility:public"],
    deps = [
        "//comp/core/autodiscovery/integration",
        "//pkg/collector/check/id",
        "//pkg/metrics/event",
        "//pkg/metrics/servicecheck",
        "//pkg/proto/pbgo/privateactionrunner/executor",
        "//pkg/util/log",
        "@cc_mvdan_sh_v3//syntax",
    ] + select({
        "@rules_go//go/platform:aix": [
            "//pkg/config/model",
        ],
        "@rules_go//go/platform:android": [
            "//comp/privateactionrunner/def",
            "//pkg/api/security/cert",
            "//pkg/config/model",
            "//pkg/privateactionrunner/executor",
            "@org_golang_google_grpc//:grpc",
            "@org_golang_google_grpc//codes",
            "@org_golang_google_grpc//credentials",
            "@org_golang_google_grpc//status",
        ],
        "@rules_go//go/platform:darwin": [
            "//comp/privateactionrunner/def",
            "//pkg/api/security/cert",
            "//pkg/config/model",
            "//pkg/privateactionrunner/executor",
            "@org_golang_google_grpc//:grpc",
            "@org_golang_google_grpc//codes",
            "@org_golang_google_grpc//credentials",
            "@org_golang_google_grpc//status",
        ],
        "@rules_go//go/platform:dragonfly": [
            "//pkg/config/model",
        ],
        "@rules_go//go/platform:freebsd": [
            "//pkg/config/model",
        ],
        "@rules_go//go/platform:illumos": [
            "//pkg/config/model",
        ],
        "@rules_go//go/platform:ios": [
            "//comp/privateactionrunner/def",
            "//pkg/api/security/cert",
            "//pkg/config/model",
            "//pkg/privateactionrunner/executor",
            "@org_golang_google_grpc//:grpc",
            "@org_golang_google_grpc//codes",
            "@org_golang_google_grpc//credentials",
            "@org_golang_google_grpc//status",
        ],
        "@rules_go//go/platform:js": [
            "//pkg/config/model",
        ],
        "@rules_go//go/platform:linux": [
            "//comp/privateactionrunner/def",
            "//pkg/api/security/cert",
            "//pkg/config/model",
            "//pkg/privateactionrunner/executor",
            "@org_golang_google_grpc//:grpc",
            "@org_golang_google_grpc//codes",
            "@org_golang_google_grpc//credentials",
            "@org_golang_google_grpc//status",
        ],
        "@rules_go//go/platform:netbsd": [
            "//pkg/config/model",
        ],
        "@rules_go//go/platform:openbsd": [
            "//pkg/config/model",
        ],
        "@rules_go//go/platform:osx": [
            "//pkg/config/model",
        ],
        "@rules_go//go/platform:plan9": [
            "//pkg/config/model",
        ],
        "@rules_go//go/platform:qnx": [
            "//pkg/config/model",
        ],
        "@rules_go//go/platform:solaris": [
            "//pkg/config/model",
        ],
        "@rules_go//go/platform:windows": [
            "//comp/privateactionrunner/def",
            "//pkg/api/security/cert",
            "//pkg/config/model",
            "//pkg/privateactionrunner/executor",
            "@org_golang_google_grpc//:grpc",
            "@org_golang_google_grpc//codes",
            "@org_golang_google_grpc//credentials",
            "@org_golang_google_grpc//status",
        ],
        "//conditions:default": [],
    }),
)

dd_agent_go_test(
    name = "healthcheck_test",
    srcs = [
        "allowlist_test.go",
        "healthcheck_test.go",
        "par_dispatcher_test.go",
    ],
    embed = [":healthcheck"],
    embedsrcs = [
        "dispatcher.go",
        "healthcheck_test.go",
        "observer.go",
        "registry.go",
    ],
    deps = [
        "//comp/core/autodiscovery/integration",
        "//pkg/collector/check/id",
        "//pkg/metrics/event",
        "//pkg/metrics/servicecheck",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ] + select({
        "@rules_go//go/platform:android": [
            "//pkg/api/security/cert",
            "//pkg/config/mock",
            "//pkg/privateactionrunner/executor",
            "//pkg/proto/pbgo/privateactionrunner/executor",
            "@org_golang_google_grpc//:grpc",
            "@org_golang_google_grpc//codes",
            "@org_golang_google_grpc//credentials",
            "@org_golang_google_grpc//status",
        ],
        "@rules_go//go/platform:darwin": [
            "//pkg/api/security/cert",
            "//pkg/config/mock",
            "//pkg/privateactionrunner/executor",
            "//pkg/proto/pbgo/privateactionrunner/executor",
            "@org_golang_google_grpc//:grpc",
            "@org_golang_google_grpc//codes",
            "@org_golang_google_grpc//credentials",
            "@org_golang_google_grpc//status",
        ],
        "@rules_go//go/platform:ios": [
            "//pkg/api/security/cert",
            "//pkg/config/mock",
            "//pkg/privateactionrunner/executor",
            "//pkg/proto/pbgo/privateactionrunner/executor",
            "@org_golang_google_grpc//:grpc",
            "@org_golang_google_grpc//codes",
            "@org_golang_google_grpc//credentials",
            "@org_golang_google_grpc//status",
        ],
        "@rules_go//go/platform:linux": [
            "//pkg/api/security/cert",
            "//pkg/config/mock",
            "//pkg/privateactionrunner/executor",
            "//pkg/proto/pbgo/privateactionrunner/executor",
            "@org_golang_google_grpc//:grpc",
            "@org_golang_google_grpc//codes",
            "@org_golang_google_grpc//credentials",
            "@org_golang_google_grpc//status",
        ],
        "@rules_go//go/platform:windows": [
            "//pkg/api/security/cert",
            "//pkg/config/mock",
            "//pkg/privateactionrunner/executor",
            "//pkg/proto/pbgo/privateactionrunner/executor",
            "@org_golang_google_grpc//:grpc",
            "@org_golang_google_grpc//codes",
            "@org_golang_google_grpc//credentials",
            "@org_golang_google_grpc//status",
        ],
        "//conditions:default": [],
    }),
)
