package rum

const (

	// =========================
	// COMMON ATTRIBUTE PREFIXES
	// =========================

	Datadog = "datadog"
	Device  = "device"
	Display = "display"
	Error   = "error"
	Os      = "os"
	Service = "service"
	Session = "session"
	Usr     = "usr"
	User    = "user"
	View    = "view"

	// =================
	// COMMON ATTRIBUTES
	// =================

	Date                    = "date"
	Application             = "application"
	Id                      = "id"
	Identifier              = "identifier"
	CurrentLocale           = "current_locale"
	Name                    = "name"
	Version                 = "version"
	BuildVersion            = "build_version"
	BuildId                 = "build_id"
	Type                    = "type"
	HasReplay               = "has_replay"
	Source                  = "source"
	Referrer                = "referrer"
	Url                     = "url"
	FullName                = "full_name"
	Email                   = "email"
	Hash                    = "hash"
	Account                 = "account"
	AnonymousId             = "anonymous_id"
	Connectivity            = "connectivity"
	Status                  = "status"
	Interfaces              = "interfaces"
	EffectiveType           = "effective_type"
	Cellular                = "cellular"
	Technology              = "technology"
	CarrierName             = "carrier_name"
	Viewport                = "viewport"
	Width                   = "width"
	Height                  = "height"
	Synthetics              = "synthetics"
	TestId                  = "test_id"
	ResultId                = "result_id"
	Injected                = "injected"
	CITest                  = "ci_test"
	TestExecutionId         = "test_execution_id"
	VersionMajor            = "version_major"
	Model                   = "model"
	Brand                   = "brand"
	Manufacturer            = "manufacturer"
	Architecture            = "architecture"
	Locale                  = "locale"
	Locales                 = "locales"
	TimeZone                = "time_zone"
	BatteryLevel            = "battery_level"
	PowerSavingMode         = "power_saving_mode"
	BrightnessLevel         = "brightness_level"
	DD                      = "_dd"
	FormatVersion           = "format_version"
	Plan                    = "plan"
	SessionPrecondition     = "session_precondition"
	Configuration           = "configuration"
	SessionSampleRate       = "session_sample_rate"
	SessionReplaySampleRate = "session_replay_sample_rate"
	ProfilingSampleRate     = "profiling_sample_rate"
	BrowserSDKVersion       = "browser_sdk_version"
	SDKName                 = "sdk_name"
	Context                 = "context"
	Container               = "container"

	// =================
	// ACTION ATTRIBUTES
	// =================

	Action      = "action"
	LoadingTime = "loading_time"
	Target      = "target"
	Frustration = "frustration"
	Count       = "count"
	Position    = "position"
	Selector    = "selector"
	NameSource  = "name_source"

	// ================
	// ERROR ATTRIBUTES
	// ================
	Message            = "message"
	Stack              = "stack"
	Causes             = "causes"
	IsCrash            = "is_crash"
	Fingerprint        = "fingerprint"
	Category           = "category"
	Handling           = "handling"
	HandlingStack      = "handling_stack"
	SourceType         = "source_type"
	Resource           = "resource"
	Method             = "method"
	StatusCode         = "status_code"
	Provider           = "provider"
	Domain             = "domain"
	Threads            = "threads"
	Crashed            = "crashed"
	State              = "state"
	BinaryImages       = "binary_images"
	UUID               = "uuid"
	IsSystem           = "is_system"
	LoadAddress        = "load_address"
	MaxAddress         = "max_address"
	Arch               = "arch"
	WasTruncated       = "was_truncated"
	Meta               = "meta"
	CodeType           = "code_type"
	ParentProcess      = "parent_process"
	IncidentIdentifier = "incident_identifier"
	Process            = "process"
	ExceptionType      = "exception_type"
	ExceptionCodes     = "exception_codes"
	Path               = "path"
	CSP                = "csp"
	Disposition        = "disposition"
	TimeSinceAppStart  = "time_since_app_start"
	Freeze             = "freeze"
	Duration           = "duration"
	FeatureFlags       = "feature_flags"

	// =================
	// LONG TASK ATTRIBUTES
	// =================

	LongTask                     = "long_task"
	StartTime                    = "start_time"
	EntryType                    = "entry_type"
	BlockingDuration             = "blocking_duration"
	RenderStart                  = "render_start"
	StyleAndLayoutStart          = "style_and_layout_start"
	FirstUIEventTimestamp        = "first_ui_event_timestamp"
	IsFrozenFrame                = "is_frozen_frame"
	Scripts                      = "scripts"
	PauseDuration                = "pause_duration"
	ForcedStyleAndLayoutDuration = "forced_style_and_layout_duration"
	ExecutionStart               = "execution_start"
	SouceUrl                     = "souce_url"
	SourceFunctionName           = "source_function_name"
	SourceCharPosition           = "source_char_position"
	Invoker                      = "invoker"
	InvokerType                  = "invoker_type"
	WindowAttribution            = "window_attribution"
	Discarded                    = "discarded"
	Profiling                    = "profiling"

	// ===================
	// RESOURCE ATTRIBUTES
	// ===================

	Size                 = "size"
	EncodedBodySize      = "encoded_body_size"
	DecodedBodySize      = "decoded_body_size"
	TransferSize         = "transfer_size"
	RenderBlockingStatus = "render_blocking_status"
	Worker               = "worker"
	Redirect             = "redirect"
	DNS                  = "dns"
	Connect              = "connect"
	SSL                  = "ssl"
	FirstByte            = "first_byte"
	Download             = "download"
	Protocol             = "protocol"
	DeliveryType         = "delivery_type"
	GraphQL              = "graphql"
	OperationType        = "operationType"
	OperationName        = "operationName"
	Payload              = "payload"
	Variables            = "variables"
	SpanId               = "span_id"
	ParentSpanId         = "parent_span_id"
	TraceId              = "trace_id"
	RulePSR              = "rule_psr"
	ErrorReason          = "error_reason"

	// ===============
	// VIEW ATTRIBUTES
	// ===============

	NetworkSettledTime                   = "network_settled_time"
	InteractionToNextViewTime            = "interaction_to_next_view_time"
	LoadingType                          = "loading_type"
	TimeSpent                            = "time_spent"
	FirstContentfulPaint                 = "first_contentful_paint"
	LargestContentfulPaint               = "largest_contentful_paint"
	LargestContentfulPaintTargetSelector = "largest_contentful_paint_target_selector"
	FirstInputDelay                      = "first_input_delay"
	FirstInputTime                       = "first_input_time"
	FirstInputTargetSelector             = "first_input_target_selector"
	InteractionToNextPaint               = "interaction_to_next_paint"
	InteractionToNextPaintTime           = "interaction_to_next_paint_time"
	InteractionToNextPaintTargetSelector = "interaction_to_next_paint_target_selector"
	CumulativeLayoutShift                = "cumulative_layout_shift"
	CumulativeLayoutShiftTime            = "cumulative_layout_shift_time"
	CumulativeLayoutShiftTargetSelector  = "cumulative_layout_shift_target_selector"
	DOMComplete                          = "dom_complete"
	DOMContentLoaded                     = "dom_content_loaded"
	DOMInteractive                       = "dom_interactive"
	LoadEvent                            = "load_event"
	CustomTimings                        = "custom_timings"
	IsActive                             = "is_active"
	IsSlowRendered                       = "is_slow_rendered"
	SlowFrames                           = "slow_frames"
	FrozenFrame                          = "frozen_frame"
	InForegroundPeriods                  = "in_foreground_periods"
	MemoryAverage                        = "memory_average"
	MemoryMax                            = "memory_max"
	CPUTicksCount                        = "cpu_ticks_count"
	CPUTicksPerSecond                    = "cpu_ticks_per_second"
	RefreshRateAverage                   = "refresh_rate_average"
	RefreshRateMin                       = "refresh_rate_min"
	SlowFramesRate                       = "slow_frames_rate"
	FreezeRate                           = "freeze_rate"
	FlutterBuildTime                     = "flutter_build_time"
	FlutterRasterTime                    = "flutter_raster_time"
	JSRefreshRate                        = "js_refresh_rate"
	Performance                          = "performance"
	CLS                                  = "cls"
	Score                                = "score"
	Timestamp                            = "timestamp"
	TargetSelector                       = "target_selector"
	PreviousRect                         = "previous_rect"
	CurrentRect                          = "current_rect"
	X                                    = "x"
	Y                                    = "y"
	FCP                                  = "fcp"
	FID                                  = "fid"
	INP                                  = "inp"
	LCP                                  = "lcp"
	ResourceUrl                          = "resource_url"
	FBC                                  = "fbc"
	SampledForReplay                     = "sampled_for_replay"
	Privacy                              = "privacy"
	ReplayLevel                          = "replay_level"
	DocumentVersion                      = "document_version"
	PageStates                           = "page_states"
	ReplayStats                          = "replay_stats"
	RecordsCount                         = "records_count"
	SegmentsCount                        = "segments_count"
	SegmentsTotalRawSize                 = "segments_total_raw_size"
	CLSDevicePixelRatio                  = "cls.device_pixel_ratio"
	StartSessionReplayRecordingManually  = "start_session_replay_recording_manually"
	Scroll                               = "scroll"
	MaxDepth                             = "max_depth"
	MaxDepthScrollTop                    = "max_depth_scroll_top"
	MaxScrollHeight                      = "max_scroll_height"
	MaxScrollHeightTime                  = "max_scroll_height_time"
	MetricMax                            = "metric_max"
	InForeground                         = "in_foreground"
	Crash                                = "crash"
	Min                                  = "min"
	Max                                  = "max"
	Average                              = "average"

	// ================
	// VITAL ATTRIBUTES
	// ================
	Vital         = "vital"
	Description   = "description"
	Custom        = "custom"
	ComputedValue = "computed_value"
)
