#!/usr/bin/env bash
set -euo pipefail

# Check `bazelisk` properly bootstraps `bazel` or fail with instructions
if [ -z "${BAZEL_REAL:-}" ] || [ "${BAZELISK_SKIP_WRAPPER:-}" != true ]; then
  >&2 cat "$(dirname "$0")/bazelisk.md"
  exit 2
fi

# Ensure `XDG_CACHE_HOME` denotes a directory
if [ ! -d "${XDG_CACHE_HOME:-}" ]; then
  if [ -n "${CI:-}" ]; then
    >&2 echo "🔴 XDG_CACHE_HOME (${XDG_CACHE_HOME:-}) must denote a directory in CI!"
    exit 2
  fi
  if [[ -e /.dockerenv || -e /run/.containerenv ]]; then
    >&2 echo "💡 To persist caches across restarts, please set XDG_CACHE_HOME pointing to a mounted directory, e.g.:"
    # shellcheck disable=SC2016
    >&2 echo '    docker run --env=XDG_CACHE_HOME=/cache --volume=~/.cache:/cache ...'
  fi
fi

# Ensure `bazel` & managed toolchains honor `XDG_CACHE_HOME`
extra_args=()
if [ -n "${XDG_CACHE_HOME:-}" ]; then
  if [[ "$XDG_CACHE_HOME" != /* ]]; then
    >&2 echo "🔴 XDG_CACHE_HOME ($XDG_CACHE_HOME) must denote an absolute path!"
    exit 2
  fi
  export GOCACHE="$XDG_CACHE_HOME/go-build"
  export GOMODCACHE="$XDG_CACHE_HOME/go/mod"
  extra_args+=(--disk_cache="$XDG_CACHE_HOME/bazel/disk-cache")
  # https://github.com/bazelbuild/bazel/issues/26384
  [ "$XDG_CACHE_HOME" = "$(dirname "$(dirname "$0")")/.cache" ] && extra_args+=(--repo_contents_cache=)
  [ -n "${CI:-}" ] && [ -z "${GITHUB_ACTIONS:-}" ] && extra_args+=(--config=ci)
else
  # Without `XDG_CACHE_HOME`, fall back Go caches to official defaults so Go repo rules work under strict repo_env
  [ -z "${GOCACHE:-}" ] && export GOCACHE=~/.cache/go-build
  [ -n "${GOPATH:-}" ] && gp="${GOPATH%%:*}" || gp=~/go
  export GOMODCACHE="${GOMODCACHE:-$gp/pkg/mod}"
  unset gp
fi

# "--startup cmd ..." -> "--startup cmd --config=ci ..."
if [[ $# -gt 0 && ${#extra_args[@]} -gt 0 ]]; then
  args=()
  cmd=
  for arg in "$@"; do
    args+=("$arg")
    if [[ -z "$cmd" && "$arg" != -* ]]; then
      cmd=$arg
      args+=("${extra_args[@]}")
    fi
  done
  set -- "${args[@]}"
fi

exec "$BAZEL_REAL" "$@"
