load("@rules_go//go:def.bzl", "go_library")

package(default_package_metadata = ["//pkg/api:go_package_metadata"])

go_library(
    name = "coverage",
    srcs = [
        "coverage.go",
        "no_coverage.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/pkg/api/coverage",
    visibility = ["//visibility:public"],
)
