load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "protectedfile",
    srcs = ["protected_file.go"],
    importpath = "github.com/DataDog/datadog-agent/pkg/ebpf/protectedfile",
    visibility = ["//visibility:public"],
    deps = select({
        "@rules_go//go/platform:android": [
            "//pkg/util/log",
            "@com_github_justincormack_go_memfd//:go-memfd",
        ],
        "@rules_go//go/platform:linux": [
            "//pkg/util/log",
            "@com_github_justincormack_go_memfd//:go-memfd",
        ],
        "//conditions:default": [],
    }),
)
