load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "mock",
    srcs = ["mock.go"],
    importpath = "github.com/DataDog/datadog-agent/comp/process/containercheck/mock",
    visibility = ["//visibility:public"],
    deps = [
        "//comp/process/containercheck/def",
        "//pkg/process/checks",
        "//pkg/process/checks/mocks",
        "@com_github_stretchr_testify//mock",
    ],
)
