load("@protobuf//bazel:proto_library.bzl", "proto_library")
load("@rules_go//proto:def.bzl", "go_proto_library")

proto_library(
    name = "remotequeries_proto",
    srcs = ["remotequeries.proto"],
    strip_import_prefix = "/pkg/proto",
    visibility = ["//visibility:public"],
)

go_proto_library(
    name = "remotequeries_go_proto",
    importpath = "pkg/proto/pbgo/core",
    proto = ":remotequeries_proto",
    visibility = ["//visibility:public"],
)
