load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

go_library(
    name = "resolver",
    srcs = [
        "credential_catalog.go",
        "credentials_resolver.go",
        "integration_credentials.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/pkg/privateactionrunner/credentials/resolver",
    visibility = ["//visibility:public"],
    deps = [
        "//comp/core/autodiscovery/integration",
        "//comp/core/ipc/def",
        "//comp/core/ipc/httphelpers",
        "//pkg/privateactionrunner/adapters/logging",
        "//pkg/privateactionrunner/libs/connection",
        "//pkg/privateactionrunner/libs/privateconnection",
        "//pkg/proto/pbgo/privateactionrunner/privateactions",
        "@com_github_google_uuid//:uuid",
        "@in_yaml_go_yaml_v3//:yaml",
    ],
)

dd_agent_go_test(
    name = "resolver_test",
    srcs = [
        "credential_catalog_test.go",
        "integration_credentials_test.go",
    ],
    embed = [":resolver"],
    deps = [
        "//comp/core/autodiscovery/integration",
        "//pkg/proto/pbgo/privateactionrunner/privateactions",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
