load("@bazel_lib//lib:write_source_files.bzl", "write_source_files")
load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go_package_metadata:defs.bzl", "go_package_metadata")
load("//bazel/rules/go_sdk_overrides:defs.bzl", "go_sdk_overrides")

package(default_package_metadata = [":go_package_metadata"])

go_package_metadata(
    name = "go_package_metadata",
    module = "github.com/DataDog/datadog-agent/pkg/template",
)

write_source_files(
    name = "generate",
    files = go_sdk_overrides(),
)

go_library(
    name = "template",
    srcs = ["docs.go"],
    importpath = "github.com/DataDog/datadog-agent/pkg/template",
    visibility = ["//visibility:public"],
)
