#!/bin/sh
#
# Perform necessary datadog-agent removal steps
# after package is uninstalled.
#

KNOWN_DISTRIBUTION="(Debian|Ubuntu|RedHat|CentOS|openSUSE|Amazon|Arista|SUSE)"
DISTRIBUTION=$(lsb_release -d 2>/dev/null | grep -Eo $KNOWN_DISTRIBUTION  || grep -Eo $KNOWN_DISTRIBUTION /etc/issue 2>/dev/null || grep -Eo $KNOWN_DISTRIBUTION /etc/Eos-release 2>/dev/null || uname -s)

INSTALL_DIR=/opt/datadog-agent6
LOG_DIR=/var/log/datadog
CONFIG_DIR=/etc/dd-agent

if [ -f "/etc/debian_version" ] || [ "$DISTRIBUTION" = "Debian" ] || [ "$DISTRIBUTION" = "Ubuntu" ]; then
    set -e

    case "$1" in
        purge)
            # FIXME: when the package is renamed `datadog-agent`, uncomment all the purge-related commands
            # that remove users/directories currently set up by the `datadog-agent` (agent5) package
            echo "Leaving dd-agent user and group in place"
            # echo "Deleting dd-agent user"
            # deluser dd-agent --quiet
            # echo "Deleting dd-agent group"
            # getent group dd-agent >/dev/null && delgroup dd-agent --quiet || true
            echo "Force-deleting $INSTALL_DIR"
            rm -rf $INSTALL_DIR
            # rm -rf $LOG_DIR
            # rm -rf $CONFIG_DIR
        ;;
        *)
        ;;
    esac
elif [ -f "/etc/redhat-release" ] || [ -f "/etc/system-release" ] || [ -f "/etc/SuSE-release" ] || [ "$DISTRIBUTION" = "RedHat" ] || [ "$DISTRIBUTION" = "CentOS" ] || [ "$DISTRIBUTION" = "openSUSE" ] || [ "$DISTRIBUTION" = "Amazon" ] || [ "$DISTRIBUTION" = "SUSE" ] || [ "$DISTRIBUTION" = "Arista" ]; then
    case "$*" in
        0)
            # We're uninstalling.
            # We don't delete the dd-agent user/group (see https://fedoraproject.org/wiki/Packaging:UsersAndGroups#Allocation_Strategies)
        ;;
        1)
            # We're upgrading.
        ;;
        *)
        ;;
    esac
else
    echo "[ ${Red}FAILED ${RCol}]\tYour system is currently not supported by this script.";
    exit 1;
fi

exit 0
