#! /bin/sh

# This script is RPM-specific
# It is run at the very end of an install/upgrade of the package
# It is NOT run on removal of the package

SERVICE_NAME=datadog-agent6

# Restart the agent
echo "(Re)starting $SERVICE_NAME now..."
if command -v systemctl >/dev/null 2>&1; then
    systemctl restart $SERVICE_NAME || true
elif command -v initctl >/dev/null 2>&1; then
    initctl start $SERVICE_NAME || initctl restart $SERVICE_NAME || true
else
    echo "[ ${Red}FAILED ${RCol}]\tUnsupported init system."
    exit 1
fi

exit 0
