load("@rules_go//go:def.bzl", "go_library")

package(default_package_metadata = ["//pkg/process/util/api:go_package_metadata"])

go_library(
    name = "headers",
    srcs = ["headers.go"],
    importpath = "github.com/DataDog/datadog-agent/pkg/process/util/api/headers",
    visibility = ["//visibility:public"],
)
