load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

go_library(
    name = "baselineselector",
    srcs = ["baseline_selector.go"],
    importpath = "github.com/DataDog/datadog-agent/comp/networkpath/npcollector/impl/baselineselector",
    visibility = ["//visibility:public"],
    deps = [
        "//comp/networkpath/npcollector/impl/common",
        "//comp/networkpath/npcollector/model",
    ],
)

dd_agent_go_test(
    name = "baselineselector_test",
    srcs = ["baseline_selector_test.go"],
    embed = [":baselineselector"],
    deps = [
        "//comp/networkpath/npcollector/impl/common",
        "//comp/networkpath/npcollector/model",
        "//pkg/networkpath/payload",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
