load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")
load("//bazel/rules/go_package_metadata:defs.bzl", "go_package_metadata")

package(default_package_metadata = [":go_package_metadata"])

go_package_metadata(
    name = "go_package_metadata",
    module = "github.com/DataDog/datadog-agent/pkg/zstd",
)

go_library(
    name = "zstd",
    srcs = [
        "zstd.go",
        "zstd_cgo.go",
        "zstd_nocgo.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/pkg/zstd",
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_datadog_zstd//:zstd",
        "@com_github_klauspost_compress//zstd",
    ],
)

dd_agent_go_test(
    name = "zstd_test",
    srcs = ["zstd_cross_test.go"],
    embed = [":zstd"],
    deps = [
        "@com_github_klauspost_compress//zstd",
    ],
)
