MODEL = "/issue_auto_assign_model"
BASE_MODEL = "distilbert-base-uncased-finetuned-sst-2-english"
## THIS LIST SHOULD NOT BE UPDATED UNLESS THE MODEL IS RE-TRAINED. THE ONLY ALLOWED CHANGE IS THE RENAME OF AN EXISTING TEAM.
TEAMS = (
    'container-ecosystems',
    'windows-agent',
    'remote-config',
    'container-platform',
    'documentation',
    'agent-security',
    'container-app',
    'agent-all',
    'processes',
    'agent-devx',
    'agent-delivery',
    'networks',
    'ebpf-platform',
    'agent-apm',
    'single-machine-performance',
    'agent-e2e-testing',
    'agent-devx',
    'triage',
    'windows-agent',
    'container-integrations',
    'software-integrity-and-trust',
    'opentelemetry',
    'universal-service-monitoring',
    'agent-build',
    'agent-runtimes',
    'agent-integrations',
    'agent-metrics-pipelines',
    'platform-integrations',
    'agent-devx',
    'asm-go',
    'agent-cspm',
    'debugger',
    'database-monitoring',
    'network-device-monitoring',
    'serverless',
    'apm-onboarding',
    'fleet',
    'agent-logs-pipelines',
)
