"""The trace loader."""

load("@rules_go//go:def.bzl", "go_library")
load(
    "@rules_pkg//pkg:mappings.bzl",
    "pkg_attributes",
    "pkg_files",
)
load("//bazel/rules/dd_strip:dd_strip.bzl", "dd_strip_debug")
load("//bazel/rules/go:go_binary.bzl", "dd_agent_go_binary")
load("//tasks:build_tags.bzl", "LOADER_TAGS")

package(default_visibility = ["//packages:__subpackages__"])

pkg_files(
    name = "trace_loader_all_files",
    # Temporary: Point to prebuilt trace_loader. When we can stamp module deps
    # in the file, swap to :loader and rename that as trace-loader.
    srcs = select({
        "//packages/agent:linux_default": [
            "@trace_loader_binary//:trace_loader",
        ],
        "//packages/agent:linux_fips": [
            "@trace_loader_binary//:trace_loader",
        ],
        # This shouldn't be needed in practice, but it is used by the systemd
        # service, which is used when installing the deb manually.
        "//packages/agent:linux_heroku": [
            "main_noop.sh",
        ],
        "@platforms//os:macos": [
            "@trace_loader_binary//:trace_loader",
        ],
        "//conditions:default": [],
    }),
    attributes = pkg_attributes(mode = "755"),
    prefix = "embedded/bin",
    renames = select({
        "//packages/agent:linux_heroku": {":main_noop.sh": "trace-loader"},
        "//conditions:default": {},
    }),
)

go_library(
    name = "loader_lib",
    srcs = [
        "docs.go",
        "main_nix.go",
        "memory_darwin.go",
        "memory_linux.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/cmd/loader",
    deps = select({
        "@rules_go//go/platform:android": [
            "//comp/core/delegatedauth/noop-impl/types",
            "//comp/core/log/def",
            "//comp/core/secrets/noop-impl/types",
            "//comp/otelcol/otlp/configcheck",
            "//pkg/config/env",
            "//pkg/config/model",
            "//pkg/config/setup",
            "//pkg/config/utils",
            "//pkg/trace/api/loader",
            "//pkg/util/defaultpaths",
            "//pkg/util/log",
            "//pkg/util/log/setup",
            "@org_golang_x_sys//unix",
        ],
        "@rules_go//go/platform:darwin": [
            "//comp/core/delegatedauth/noop-impl/types",
            "//comp/core/log/def",
            "//comp/core/secrets/noop-impl/types",
            "//comp/otelcol/otlp/configcheck",
            "//pkg/config/env",
            "//pkg/config/model",
            "//pkg/config/setup",
            "//pkg/config/utils",
            "//pkg/trace/api/loader",
            "//pkg/util/defaultpaths",
            "//pkg/util/log",
            "//pkg/util/log/setup",
            "@org_golang_x_sys//unix",
        ],
        "@rules_go//go/platform:ios": [
            "//comp/core/delegatedauth/noop-impl/types",
            "//comp/core/log/def",
            "//comp/core/secrets/noop-impl/types",
            "//comp/otelcol/otlp/configcheck",
            "//pkg/config/env",
            "//pkg/config/model",
            "//pkg/config/setup",
            "//pkg/config/utils",
            "//pkg/trace/api/loader",
            "//pkg/util/defaultpaths",
            "//pkg/util/log",
            "//pkg/util/log/setup",
            "@org_golang_x_sys//unix",
        ],
        "@rules_go//go/platform:linux": [
            "//comp/core/delegatedauth/noop-impl/types",
            "//comp/core/log/def",
            "//comp/core/secrets/noop-impl/types",
            "//comp/otelcol/otlp/configcheck",
            "//pkg/config/env",
            "//pkg/config/model",
            "//pkg/config/setup",
            "//pkg/config/utils",
            "//pkg/trace/api/loader",
            "//pkg/util/defaultpaths",
            "//pkg/util/log",
            "//pkg/util/log/setup",
            "@org_golang_x_sys//unix",
        ],
        "//conditions:default": [],
    }),
)

# TODO(ABLD-294): Rename to trace-loader and use this instead of @trace_loader_binary//:trace_loader
dd_agent_go_binary(
    name = "loader_unstripped",
    embed = [":loader_lib"],
    # LOADER_TAGS is actually empty. We're including it to keep a consistent style.
    exact_gotags = list(LOADER_TAGS) + select({
        "@platforms//os:linux": ["bpf"],
        "//conditions:default": [],
    }),
    tags = ["manual"],
    target_compatible_with = select({
        "@platforms//os:windows": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    visibility = ["//visibility:private"],
)

dd_strip_debug(
    name = "loader",
    input = ":loader_unstripped",
)
