load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "impl",
    srcs = ["forwarder.go"],
    importpath = "github.com/DataDog/datadog-agent/comp/healthplatform/forwarder/impl",
    visibility = ["//visibility:public"],
    deps = [
        "//comp/core/config",
        "//comp/healthplatform/forwarder/client",
        "//comp/healthplatform/forwarder/def",
    ],
)
