load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

go_library(
    name = "nodefilter",
    srcs = [
        "nodefilter.go",
        "nodefilter_nop.go",
        "pod_parser.go",
        "pod_store.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/comp/core/workloadmeta/collectors/internal/nodefilter",
    visibility = ["//comp/core/workloadmeta/collectors:__subpackages__"],
    deps = [
        "//comp/core/config",
        "//comp/core/workloadmeta/def",
        "//internal/third_party/golang/expansion",
        "//pkg/config/env",
        "//pkg/errors",
        "//pkg/util/containers",
        "//pkg/util/containers/image",
        "//pkg/util/flavor",
        "//pkg/util/gpu",
        "//pkg/util/kubernetes",
        "//pkg/util/log",
        "//pkg/version",
        "@io_k8s_api//core/v1:core",
        "@io_k8s_apimachinery//pkg/apis/meta/v1:meta",
        "@io_k8s_apimachinery//pkg/fields",
        "@io_k8s_apimachinery//pkg/runtime",
        "@io_k8s_apimachinery//pkg/runtime/schema",
        "@io_k8s_apimachinery//pkg/types",
        "@io_k8s_apimachinery//pkg/watch",
        "@io_k8s_client_go//kubernetes",
        "@io_k8s_client_go//rest",
        "@io_k8s_client_go//tools/cache",
        "@io_k8s_client_go//tools/clientcmd",
        "@org_uber_go_fx//:fx",
    ],
)

dd_agent_go_test(
    name = "nodefilter_test",
    srcs = [
        "nodefilter_test.go",
        "pod_parser_test.go",
        "pod_store_test.go",
    ],
    embed = [":nodefilter"],
    gotags_sets = [["nodefilter"]],
    include_default = False,
    tags = ["manual"],
    deps = [
        "//comp/core",
        "//comp/core/config",
        "//comp/core/workloadmeta/def",
        "//comp/core/workloadmeta/fx-mock",
        "//comp/core/workloadmeta/mock",
        "//pkg/config/env",
        "//pkg/errors",
        "//pkg/util/fxutil",
        "//pkg/util/kubernetes",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
        "@io_k8s_api//core/v1:core",
        "@io_k8s_apimachinery//pkg/api/resource",
        "@io_k8s_apimachinery//pkg/apis/meta/v1:meta",
        "@io_k8s_apimachinery//pkg/types",
        "@org_uber_go_fx//:fx",
    ],
)
