load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

dd_agent_go_test(
    name = "discovery_test",
    srcs = [
        "config_discovery_linux_test.go",
        "configfilesdiscovery_docker_test.go",
        "docker_test.go",
        "k8s_test.go",
        "linux_test.go",
        "process_autodiscovery_test.go",
    ],
    data = [
        "config/helm-values.tmpl",
        "testdata/config/agent_config.yaml",
        "testdata/config/agent_process_autodiscovery.yaml",
        "testdata/config/agent_process_config.yaml",
        "testdata/config/agent_process_disabled_config.yaml",
        "testdata/config/nginx_process_autodiscovery.yaml",
        "testdata/config/redisdb_process_autodiscovery.yaml",
        "testdata/config/system_probe_config.yaml",
        "testdata/config/system_probe_config_fallback.yaml",
        "testdata/config/system_probe_config_privileged_logs.yaml",
        "testdata/compose/docker-compose.configfilesdiscovery-kafka.yaml",
        "testdata/compose/docker-compose.configfilesdiscovery-postgres.yaml",
        "testdata/compose/docker-compose.configfilesdiscovery-redis.yaml",
        "testdata/compose/docker-compose.configfilesdiscovery-spark-master.yaml",
    ] + select({
        "@rules_go//go/platform:android": [
            "testdata/compose/docker-compose.fake-krakend.yaml",
        ],
        "@rules_go//go/platform:linux": [
            "testdata/compose/docker-compose.fake-krakend.yaml",
        ],
        "//conditions:default": [],
    }),
    embedsrcs = [
        "config/helm-values.tmpl",
        "testdata/config/agent_config.yaml",
        "testdata/config/agent_process_autodiscovery.yaml",
        "testdata/config/agent_process_config.yaml",
        "testdata/config/agent_process_disabled_config.yaml",
        "testdata/config/nginx_process_autodiscovery.yaml",
        "testdata/config/redisdb_process_autodiscovery.yaml",
        "testdata/config/system_probe_config.yaml",
        "testdata/config/system_probe_config_fallback.yaml",
        "testdata/config/system_probe_config_privileged_logs.yaml",
        "testdata/compose/docker-compose.configfilesdiscovery-kafka.yaml",
        "testdata/compose/docker-compose.configfilesdiscovery-postgres.yaml",
        "testdata/compose/docker-compose.configfilesdiscovery-redis.yaml",
        "testdata/compose/docker-compose.configfilesdiscovery-spark-master.yaml",
    ] + select({
        "@rules_go//go/platform:android": [
            "testdata/compose/docker-compose.fake-krakend.yaml",
        ],
        "@rules_go//go/platform:linux": [
            "testdata/compose/docker-compose.fake-krakend.yaml",
        ],
        "//conditions:default": [],
    }),
    deps = [
        "//test/e2e-framework/common/config",
        "//test/e2e-framework/common/utils",
        "//test/e2e-framework/components/datadog/agentparams",
        "//test/e2e-framework/components/datadog/apps",
        "//test/e2e-framework/components/datadog/apps/nginx",
        "//test/e2e-framework/components/datadog/dockeragentparams",
        "//test/e2e-framework/components/datadog/kubernetesagentparams",
        "//test/e2e-framework/components/kubernetes",
        "//test/e2e-framework/components/remote",
        "//test/e2e-framework/resources/aws",
        "//test/e2e-framework/scenarios/aws/ec2",
        "//test/e2e-framework/scenarios/aws/ec2docker",
        "//test/e2e-framework/scenarios/aws/kindvm",
        "//test/e2e-framework/testing/components",
        "//test/e2e-framework/testing/e2e",
        "//test/e2e-framework/testing/environments",
        "//test/e2e-framework/testing/provisioners",
        "//test/e2e-framework/testing/provisioners/aws/docker",
        "//test/e2e-framework/testing/provisioners/aws/host",
        "//test/e2e-framework/testing/provisioners/aws/kubernetes/kindvm",
        "//test/fakeintake/aggregator",
        "//test/new-e2e/tests/process",
        "@com_github_datadog_agent_payload_v5//agentdiscovery",
        "@com_github_datadog_agent_payload_v5//process",
        "@com_github_google_go_cmp//cmp",
        "@com_github_google_go_cmp//cmp/cmpopts",
        "@com_github_pulumi_pulumi_kubernetes_sdk_v4//go/kubernetes",
        "@com_github_pulumi_pulumi_sdk_v3//go/pulumi",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
        "@io_k8s_api//core/v1:core",
        "@io_k8s_apimachinery//pkg/apis/meta/v1:meta",
    ] + select({
        "@rules_go//go/platform:android": [
            "//test/fakeintake/client",
        ],
        "@rules_go//go/platform:linux": [
            "//test/fakeintake/client",
        ],
        "//conditions:default": [],
    }),
)
