load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

go_library(
    name = "handler",
    srcs = ["handler.go"],
    importpath = "github.com/DataDog/datadog-agent/comp/core/autodiscovery/providers/ndm/handler",
    visibility = ["//visibility:public"],
    deps = ["//comp/core/autodiscovery/integration"],
)

dd_agent_go_test(
    name = "handler_test",
    srcs = ["handler_test.go"],
    embed = [":handler"],
    deps = [
        "//comp/core/autodiscovery/integration",
        "@com_github_stretchr_testify//assert",
    ],
)
