load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

go_library(
    name = "jsonprune",
    srcs = [
        "doc.go",
        "prune.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/pkg/dyninst/jsonprune",
    tags = ["manual"],
    visibility = ["//visibility:public"],
    deps = select({
        "@rules_go//go/platform:android": [
            "@com_github_go_json_experiment_json//jsontext",
        ],
        "@rules_go//go/platform:linux": [
            "@com_github_go_json_experiment_json//jsontext",
        ],
        "//conditions:default": [],
    }),
)

dd_agent_go_test(
    name = "jsonprune_test",
    srcs = [
        "prune_bench_test.go",
        "prune_property_test.go",
        "prune_test.go",
    ],
    embed = [":jsonprune"],
    gotags_sets = [["bpf"]],
    include_default = False,
    tags = ["requires_ebpf"],
    deps = select({
        "@rules_go//go/platform:android": [
            "@com_github_stretchr_testify//assert",
            "@com_github_stretchr_testify//require",
        ],
        "@rules_go//go/platform:linux": [
            "@com_github_stretchr_testify//assert",
            "@com_github_stretchr_testify//require",
        ],
        "//conditions:default": [],
    }),
)
