load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "catalog",
    srcs = ["catalog.go"],
    importpath = "github.com/DataDog/datadog-agent/pkg/fleet/installer/catalog",
    visibility = ["//visibility:public"],
    deps = ["@com_github_google_go_containerregistry//pkg/name"],
)

go_test(
    name = "catalog_test",
    srcs = ["catalog_test.go"],
    embed = [":catalog"],
)
