load("@rules_go//go:def.bzl", "go_library")

package(default_package_metadata = ["//pkg/opentelemetry-mapping-go/inframetadata:go_package_metadata"])

go_library(
    name = "testutils",
    srcs = ["resource.go"],
    importpath = "github.com/DataDog/datadog-agent/pkg/opentelemetry-mapping-go/inframetadata/internal/testutils",
    visibility = [
        "//pkg/opentelemetry-mapping-go/inframetadata:__subpackages__",
        "@com_github_datadog_datadog_agent_pkg_opentelemetry_mapping_go_inframetadata//:__subpackages__",
    ],
    deps = [
        "@com_github_stretchr_testify//require",
        "@io_opentelemetry_go_collector_pdata//pcommon",
    ],
)
