load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/go:dd_agent_go_test.bzl", "dd_agent_go_test")

go_library(
    name = "catalog",
    srcs = ["catalog.go"],
    importpath = "github.com/DataDog/datadog-agent/pkg/fleet/catalog",
    visibility = ["//visibility:public"],
    deps = ["@com_github_google_go_containerregistry//pkg/name"],
)

dd_agent_go_test(
    name = "catalog_test",
    srcs = ["catalog_test.go"],
    embed = [":catalog"],
    deps = ["@com_github_stretchr_testify//require"],
)
