load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "yaml",
    srcs = ["yaml.go"],
    importpath = "github.com/DataDog/datadog-agent/test/e2e-framework/resources/yaml",
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_pulumi_pulumi_kubernetes_sdk_v4//go/kubernetes/utilities",
        "@com_github_pulumi_pulumi_sdk_v3//go/pulumi",
        "@com_github_pulumi_pulumi_sdk_v3//go/pulumi/internals",
    ],
)
