load("@rules_go//go:def.bzl", "go_library")

package(default_package_metadata = ["//pkg/template:go_package_metadata"])

go_library(
    name = "fmtsort",
    srcs = ["sort.go"],
    importpath = "github.com/DataDog/datadog-agent/pkg/template/internal/fmtsort",
    visibility = ["//pkg/template:__subpackages__"],
)
