load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "windows",
    srcs = [
        "agent_package.go",
        "apm_inject_base_suite.go",
        "base_suite.go",
        "doc.go",
        "dotnet_base_suite.go",
        "iis_helper.go",
        "install_script.go",
        "installer.go",
        "installer_base_suite.go",
        "java_helper.go",
        "package_version.go",
        "params.go",
    ],
    embedsrcs = [
        "fixtures/sample_config_disabled",
        "fixtures/sample_config_enabled",
    ],
    importpath = "github.com/DataDog/datadog-agent/test/new-e2e/tests/installer/windows",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/version",
        "//test/e2e-framework/components/os",
        "//test/e2e-framework/testing/components",
        "//test/e2e-framework/testing/e2e",
        "//test/e2e-framework/testing/environments",
        "//test/e2e-framework/testing/runner",
        "//test/e2e-framework/testing/runner/parameters",
        "//test/e2e-framework/testing/utils/common",
        "//test/e2e-framework/testing/utils/e2e/client",
        "//test/e2e-framework/testing/utils/optional",
        "//test/new-e2e/tests/installer/unix",
        "//test/new-e2e/tests/installer/windows/consts",
        "//test/new-e2e/tests/installer/windows/suite-assertions",
        "//test/new-e2e/tests/windows",
        "//test/new-e2e/tests/windows/common",
        "//test/new-e2e/tests/windows/common/agent",
        "//test/new-e2e/tests/windows/common/pipeline",
        "@com_github_cenkalti_backoff_v7//:backoff",
        "@com_github_stretchr_testify//suite",
    ],
)

go_test(
    name = "windows_test",
    srcs = [
        "agent_config_test.go",
        "agent_domain_test.go",
        "agent_gmsa_test.go",
        "agent_install_test.go",
        "agent_upgrade_test.go",
        "apm_inject_injector_stats_test.go",
        "apm_inject_install_script_test.go",
        "apm_inject_install_test.go",
        "apm_inject_msi_install_test.go",
        "apm_inject_system_probe_config_test.go",
        "ddot_install_test.go",
        "ddot_msi_install_test.go",
        "dotnet_install_no_iis_test.go",
        "dotnet_install_script_test.go",
        "dotnet_install_test.go",
        "dotnet_msi_install_test.go",
        "eudm_msi_install_test.go",
        "install_exe_test.go",
        "install_script_agent_user_test.go",
        "install_script_domain_test.go",
        "install_script_test.go",
        "installer_install_test.go",
        "installer_rollback_test.go",
        "installer_test.go",
        "persisting_extensions_test.go",
    ],
    embed = [":windows"],
    embedsrcs = [
        "resources/apm-inject/DummyApp.java",
        "resources/apm-inject/index.aspx",
        "resources/apm-inject/web.config",
        "resources/dotnet/index.aspx",
        "resources/dotnet/web.config",
    ],
    gotags = ["test"],
    deps = [
        "//pkg/util/testutil/flake",
        "//test/e2e-framework/components/activedirectory",
        "//test/e2e-framework/components/os",
        "//test/e2e-framework/resources/aws",
        "//test/e2e-framework/scenarios/aws/ec2",
        "//test/e2e-framework/scenarios/aws/ec2/windows",
        "//test/e2e-framework/testing/components",
        "//test/e2e-framework/testing/e2e",
        "//test/e2e-framework/testing/environments",
        "//test/e2e-framework/testing/provisioners",
        "//test/e2e-framework/testing/provisioners/aws/host/windows",
        "//test/new-e2e/tests/ddot",
        "//test/new-e2e/tests/installer/host",
        "//test/new-e2e/tests/installer/unix",
        "//test/new-e2e/tests/installer/windows/consts",
        "//test/new-e2e/tests/installer/windows/suite-assertions",
        "//test/new-e2e/tests/windows/common",
        "//test/new-e2e/tests/windows/common/agent",
        "@com_github_cenkalti_backoff_v7//:backoff",
        "@com_github_google_uuid//:uuid",
        "@com_github_pulumi_pulumi_sdk_v3//go/pulumi",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
        "@in_gopkg_yaml_v3//:yaml_v3",
        "@in_yaml_go_yaml_v2//:yaml",
        "@in_yaml_go_yaml_v3//:yaml",
    ],
)
