// Package com_datadoghq_gitlab_custom_attributes
// DO NOT EDIT THIS FILE MANUALLY!
//
// This file was autogenerated by the golang gitlab generator.
// You can regenerate it by running `bzl run //domains/workflow/actionplatform/apps/tools/golang_action_generator:generate -- -g gitlab`.
package com_datadoghq_gitlab_custom_attributes

import (
	"context"

	"github.com/DataDog/dd-source/domains/actionplatform/apps/private-runner/src/private-bundles/com/datadoghq/gitlab/lib"
	"github.com/DataDog/dd-source/domains/actionplatform/apps/private-runner/src/types"
	runtimepb "github.com/DataDog/dd-source/domains/actionplatform/proto/runtime"
)

type DeleteCustomUserAttributeHandler struct{}

func NewDeleteCustomUserAttributeHandler() *DeleteCustomUserAttributeHandler {
	return &DeleteCustomUserAttributeHandler{}
}

type DeleteCustomUserAttributeInputs struct {
	UserId int    `json:"user_id,omitempty"`
	Key    string `json:"key,omitempty"`
}

type DeleteCustomUserAttributeOutputs struct{}

func (h *DeleteCustomUserAttributeHandler) Run(
	ctx context.Context,
	task *types.Task,
	credential *runtimepb.Credential,
) (any, error) {
	inputs, err := types.ExtractInputs[DeleteCustomUserAttributeInputs](task)
	if err != nil {
		return nil, err
	}
	git, err := lib.NewGitlabClient(credential)
	if err != nil {
		return nil, err
	}

	_, err = git.CustomAttribute.DeleteCustomUserAttribute(inputs.UserId, inputs.Key)
	if err != nil {
		return nil, err
	}
	return &DeleteCustomUserAttributeOutputs{}, nil
}
