// Package com_datadoghq_gitlab_custom_attributes
// DO NOT EDIT THIS FILE MANUALLY!
//
// This file was autogenerated by the golang gitlab generator.
// You can regenerate it by running `bzl run //domains/workflow/actionplatform/apps/tools/golang_action_generator:generate -- -g gitlab`.
package com_datadoghq_gitlab_custom_attributes

import (
	"context"

	"github.com/DataDog/dd-source/domains/actionplatform/apps/private-runner/src/private-bundles/com/datadoghq/gitlab/lib"
	"github.com/DataDog/dd-source/domains/actionplatform/apps/private-runner/src/types"
	runtimepb "github.com/DataDog/dd-source/domains/actionplatform/proto/runtime"

	"gitlab.com/gitlab-org/api/client-go"
)

type GetCustomProjectAttributeHandler struct{}

func NewGetCustomProjectAttributeHandler() *GetCustomProjectAttributeHandler {
	return &GetCustomProjectAttributeHandler{}
}

type GetCustomProjectAttributeInputs struct {
	ProjectId int    `json:"project_id,omitempty"`
	Key       string `json:"key,omitempty"`
}

type GetCustomProjectAttributeOutputs struct {
	CustomAttribute *gitlab.CustomAttribute `json:"custom_attribute"`
}

func (h *GetCustomProjectAttributeHandler) Run(
	ctx context.Context,
	task *types.Task,
	credential *runtimepb.Credential,
) (any, error) {
	inputs, err := types.ExtractInputs[GetCustomProjectAttributeInputs](task)
	if err != nil {
		return nil, err
	}
	git, err := lib.NewGitlabClient(credential)
	if err != nil {
		return nil, err
	}

	customAttribute, _, err := git.CustomAttribute.GetCustomProjectAttribute(inputs.ProjectId, inputs.Key)
	if err != nil {
		return nil, err
	}
	return &GetCustomProjectAttributeOutputs{CustomAttribute: customAttribute}, nil
}
