load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "installer",
    srcs = ["installer.go"],
    importpath = "github.com/DataDog/datadog-agent/test/e2e-framework/cmd/e2ectl/internal/installer",
    visibility = ["//test/e2e-framework/cmd/e2ectl:__subpackages__"],
    deps = [
        "//test/e2e-framework/cmd/e2ectl/internal/config",
        "//test/e2e-framework/cmd/e2ectl/internal/envstore",
        "//test/e2e-framework/testing/environments",
        "//test/e2e-framework/testing/installers/host/installscript",
        "//test/e2e-framework/testing/installers/kubernetes/helm",
        "//test/e2e-framework/testing/provisioner",
        "//test/e2e-framework/testing/standalone",
    ],
)
