---
name: "Assign issue to a team"

on:
  issues:
    types: [opened, reopened]
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Issue number to triage'
        required: true
        type: number

jobs:
  triage:
    permissions:
      contents: read
      issues: write
      actions: write
    uses: DataDog/issue-triage-action/.github/workflows/issue-triage.yml@b39f0bc12abc52fe8aa70dc9b9353bf307a13219 # v1.0.1
    with:
      slack_map_path: tasks/libs/pipeline/github_slack_map.yaml
      environment_name: main
      issue_number: ${{ github.event_name == 'workflow_dispatch' && fromJSON(github.event.inputs.issue_number) || 0 }}
    secrets: inherit
