name: Update OTel Collector Dependencies and Generate OTel Agent

on:
  schedule:
    - cron: '0 12 * * 3'
  workflow_dispatch:

jobs:
  update-and-generate:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for getting the required OIDC token from GitHub
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: .go-version

      - name: Install dda
        uses: ./.github/actions/install-dda
        with:
          features: legacy-tasks

      - uses: DataDog/dd-octo-sts-action@96a25462dbcb10ebf0bfd6e2ccc917d2ab235b9a # v1.0.4
        id: octo-sts
        with:
          scope: DataDog/datadog-agent
          policy: self.collector-generate-and-update.create-pr

      - name: Run Collector Update Script
        id: collector-update
        env:
          GITHUB_TOKEN: ${{ steps.octo-sts.outputs.token }}
        run: |
          dda inv -- -e install-tools
          dda inv -- -e collector.update
          echo "OCB_VERSION=$OCB_VERSION" >> $GITHUB_OUTPUT
          dda inv -- -e collector.generate
          dda inv -- -e generate-licenses

      - uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        name: Create pull request
        with:
          token: ${{ steps.octo-sts.outputs.token }}
          commit-message: Update OTel Collector dependencies to ${{ steps.collector-update.outputs.OCB_VERSION}} and generate OTel Agent
          branch: update-otel-collector-dependencies-${{ steps.collector-update.outputs.OCB_VERSION}}
          sign-commits: true
          title: Update OTel Collector dependencies to v${{ steps.collector-update.outputs.OCB_VERSION}}
          body: This PR updates the dependencies of the OTel Collector to v{OCB_VERSION} and generates the OTel Agent code.
          draft: true
