name: Check Markdown links

on:
  pull_request:

permissions: {}

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - uses: tcort/github-action-markdown-link-check@e047c5b37f24ab722bbef1a27b6fab7f96bc4068 # v1.1.3
      with:
        use-quiet-mode: yes
        config-file: .markdown-link-check
        check-modified-files-only: yes
        base-branch: ${{ github.base_ref }}
