load("@bazel_skylib//rules:copy_file.bzl", "copy_file")
load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/ebpf:ebpf.bzl", "ebpf_prog")

go_library(
    name = "kernelbugs",
    srcs = [
        "kernel_bugs.go",
        "kernel_bugs_amd64.go",
        "kernel_bugs_arm64.go",
        "kernel_bugs_nobpf.go",
    ],
    embedsrcs = select({
        "@rules_go//go/platform:android_amd64": [
            "c/uprobe-trigger.o",
            "c/detect-seccomp-bug",
        ],
        "@rules_go//go/platform:linux_amd64": [
            "c/uprobe-trigger.o",
            "c/detect-seccomp-bug",
        ],
        "//conditions:default": [],
    }),
    importpath = "github.com/DataDog/datadog-agent/pkg/ebpf/kernelbugs",
    visibility = ["//visibility:public"],
    deps = select({
        "@rules_go//go/platform:android_386": [
            "//pkg/ebpf",
        ],
        "@rules_go//go/platform:android_amd64": [
            "//pkg/ebpf",
            "//pkg/ebpf/bytecode/runtime",
            "//pkg/util/funcs",
            "@com_github_datadog_ebpf_manager//:ebpf-manager",
        ],
        "@rules_go//go/platform:android_arm": [
            "//pkg/ebpf",
        ],
        "@rules_go//go/platform:android_arm64": [
            "//pkg/ebpf",
        ],
        "@rules_go//go/platform:linux_386": [
            "//pkg/ebpf",
        ],
        "@rules_go//go/platform:linux_amd64": [
            "//pkg/ebpf",
            "//pkg/ebpf/bytecode/runtime",
            "//pkg/util/funcs",
            "@com_github_datadog_ebpf_manager//:ebpf-manager",
        ],
        "@rules_go//go/platform:linux_arm": [
            "//pkg/ebpf",
        ],
        "@rules_go//go/platform:linux_arm64": [
            "//pkg/ebpf",
        ],
        "@rules_go//go/platform:linux_mips": [
            "//pkg/ebpf",
        ],
        "@rules_go//go/platform:linux_mips64": [
            "//pkg/ebpf",
        ],
        "@rules_go//go/platform:linux_mips64le": [
            "//pkg/ebpf",
        ],
        "@rules_go//go/platform:linux_mipsle": [
            "//pkg/ebpf",
        ],
        "@rules_go//go/platform:linux_ppc64": [
            "//pkg/ebpf",
        ],
        "@rules_go//go/platform:linux_ppc64le": [
            "//pkg/ebpf",
        ],
        "@rules_go//go/platform:linux_riscv64": [
            "//pkg/ebpf",
        ],
        "@rules_go//go/platform:linux_s390x": [
            "//pkg/ebpf",
        ],
        "//conditions:default": [],
    }),
)

# CO-RE program
ebpf_prog(
    name = "uprobe-trigger",
    src = "c/uprobe-trigger.c",
    core = True,
    visibility = ["//visibility:public"],
    deps = ["//pkg/ebpf/c:ebpf_c_headers"],
)

# detect-seccomp-bug is a native binary (not eBPF), x86 only.
cc_binary(
    name = "detect-seccomp-bug",
    srcs = ["c/detect-seccomp-bug.c"],
    linkopts = [
        "-static",
        "-Wl,--gc-sections",
    ],
    target_compatible_with = [
        "@platforms//cpu:x86_64",
        "@platforms//os:linux",
    ],
    visibility = ["//visibility:public"],
    deps = ["@libseccomp"],
)

# gazelle relies on scanning `out / outs` attributes to infer generated files.
# `copy_file` is a convenient way to adhere to that convention, preventing
# gazelle from issuing warnings for unfound files that go sources want to embed
# as well as the need for manual editing of the generated rules (with `# keep`)
copy_file(
    name = "c/uprobe-trigger",
    src = "uprobe-trigger",
    out = "c/uprobe-trigger.o",
)

copy_file(
    name = "c/detect-seccomp-bug",
    src = "detect-seccomp-bug",
    out = "c/detect-seccomp-bug",
)
